Repository spatialos/UnrealGDK, pull requests merged in 2018-11, with the labels that each got.

#488 Only update position and rotation if we have authority
  SpatialGDK/Source/Private/EngineClasses/SpatialActorChannel.cpp
Labels: size/XS

#405 Server Travel!
  SpatialGDK/Extras/schema/global_state_manager.schema
  SpatialGDK/Extras/unreal-engine.version
  SpatialGDK/Source/Private/EngineClasses/SpatialGameInstance.cpp
  SpatialGDK/Source/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/Private/Interop/Connection/SpatialWorkerConnection.cpp
  SpatialGDK/Source/Private/Interop/GlobalStateManager.cpp
  SpatialGDK/Source/Private/Interop/SnapshotManager.cpp
  SpatialGDK/Source/Private/Interop/SpatialDispatcher.cpp
  SpatialGDK/Source/Private/Interop/SpatialPlayerSpawner.cpp
  SpatialGDK/Source/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/Public/EngineClasses/SpatialGameInstance.h
  SpatialGDK/Source/Public/EngineClasses/SpatialNetDriver.h
  SpatialGDK/Source/Public/Interop/Connection/SpatialWorkerConnection.h
  SpatialGDK/Source/Public/Interop/GlobalStateManager.h
  SpatialGDK/Source/Public/Interop/SnapshotManager.h
  SpatialGDK/Source/Public/Interop/SpatialReceiver.h
  SpatialGDK/Source/Public/SpatialConstants.h
  SpatialGDK/Source/Public/Utils/SchemaUtils.h
  SpatialGDKEditorToolbar/Source/Private/SpatialGDKEditorGenerateSnapshot.cpp
Labels: size/XXL

#489 Removed callout in Map Travel doc
  SpatialGDK/Documentation/content/map-travel.md
Labels: size/XS

#490 Whoops
  SpatialGDK/Source/Private/EngineClasses/SpatialActorChannel.cpp
Labels: size/S

#495 Added check for SpatialGameInstance and also updated docs
  SpatialGDK/Documentation/content/get-started/porting-unreal-project-to-gdk.md
  SpatialGDK/Source/Private/EngineClasses/SpatialNetDriver.cpp
Labels: size/XS

#493 Change schema database to use class paths
  SpatialGDK/Source/Private/Interop/SpatialTypebindingManager.cpp
  SpatialGDK/Source/Public/Utils/SchemaDatabase.h
  SpatialGDKEditorToolbar/Source/Private/SchemaGenerator/SchemaGenerator.cpp
  SpatialGDKEditorToolbar/Source/Private/SchemaGenerator/SchemaGenerator.h
  SpatialGDKEditorToolbar/Source/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp
Labels: size/M

#494 Better entity names for the inspector
  SpatialGDK/Extras/schema/unreal_metadata.schema
  SpatialGDK/Source/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/Public/Schema/StandardLibrary.h
  SpatialGDK/Source/Public/Schema/UnrealMetadata.h
  SpatialGDKEditorToolbar/Source/Private/SpatialGDKEditorGenerateSnapshot.cpp
Labels: size/S

#496 Upgrade to 13.3.1
  SpatialGDK/Extras/core-sdk.version
Labels: size/XS

#497 Datatracklink that was missed out
  SpatialGDK/Documentation/content/get-started/dependencies.md
Labels: size/XS

#498 Fix typo
  SpatialGDK/Documentation/content/get-started/dependencies.md
Labels: size/XS

#499 Only trigger REPNOTIFY_Always if not applying initial data
  SpatialGDK/Source/Private/Utils/ComponentReader.cpp
Labels: size/S

#502 Removed the .clang-format
  .clang-format
Labels: size/M

#503 Update file paths, clean up script output a bit
  .gitignore
  SpatialGDK/Extras/fastbuild/README.md
  SpatialGDK/Extras/fastbuild/install.ps1
  SpatialGDK/Extras/fastbuild/uninstall.ps1
Labels: size/M

#505 Revert the revert of #493 and fix the crash due to not loading classes
  SpatialGDK/Source/Private/Interop/SpatialTypebindingManager.cpp
  SpatialGDK/Source/Public/Utils/SchemaDatabase.h
  SpatialGDKEditorToolbar/Source/Private/SchemaGenerator/SchemaGenerator.cpp
  SpatialGDKEditorToolbar/Source/Private/SchemaGenerator/SchemaGenerator.h
  SpatialGDKEditorToolbar/Source/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp
Labels: size/M

#501 UNR-704: Remove actor log spam, clean up deletion flow
  SpatialGDK/Source/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/Private/Utils/EntityRegistry.cpp
Labels: size/S

#506 Removed object ref code
  SpatialGDK/Source/Private/Utils/ComponentFactory.cpp
  SpatialGDK/Source/Private/Utils/ComponentReader.cpp
  SpatialGDK/Source/Public/Utils/ComponentFactory.h
Labels: size/S

#507 Fix order when ProcessQueuedResolvedObjects is called
  SpatialGDK/Source/Private/Interop/SpatialDispatcher.cpp
  SpatialGDK/Source/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/Public/Interop/SpatialReceiver.h
Labels: size/XS

#500 Support authority callbacks
  SpatialGDK/Documentation/assets/screen-grabs/on-authority-gained.jpg
  SpatialGDK/Documentation/assets/screen-grabs/on-authority-lost.jpg
  SpatialGDK/Documentation/content/authority.md
  SpatialGDK/Documentation/toc.md
  SpatialGDK/Source/Private/Interop/SpatialReceiver.cpp
Labels: size/M

#508 Allow static subobjects to be deleted in constructors
  SpatialGDK/Source/Private/EngineClasses/SpatialPackageMapClient.cpp
  SpatialGDK/Source/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/Public/Schema/UnrealMetadata.h
  SpatialGDKEditorToolbar/Source/Private/SpatialGDKEditorGenerateSnapshot.cpp
Labels: size/M

#510 Updated engine version for CI to 959c05465e4
  SpatialGDK/Extras/unreal-engine.version
Labels: size/XS

#512 Support paths with spaces
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/Build/Build.csproj
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/Common/Common.csproj
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/Linter/Linter.csproj
Labels: size/XS

#513 Clean error message
  SpatialGDK/Source/Private/Interop/SpatialReceiver.cpp
Labels: size/XS

#511 Check against unresolved objects before sending rpcs
  SpatialGDK/Source/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/Private/Interop/SpatialTypebindingManager.cpp
Labels: size/XS

#514 Prevent delegates from causing runtime check failures
  SpatialGDK/Source/Private/Utils/ComponentFactory.cpp
  SpatialGDKEditorToolbar/Source/Private/SchemaGenerator/TypeStructure.cpp
Labels: size/XS

#516 Search for actor in existing singletons
  SpatialGDK/Source/Private/Interop/GlobalStateManager.cpp
Labels: size/S

#515 Feature/server only singleton
  SpatialGDK/Extras/schema/singleton.schema
  SpatialGDK/Source/Private/Interop/GlobalStateManager.cpp
  SpatialGDK/Source/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/Public/Schema/Singleton.h
  SpatialGDK/Source/Public/SpatialConstants.h
  SpatialGDKEditorToolbar/Source/Private/SpatialGDKEditorGenerateSnapshot.cpp
Labels: size/M

#518 Properly build windows server
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/Build/Build.cs
Labels: size/S

#520 Change queuing to be verbose
  SpatialGDK/Source/Private/Interop/SpatialSender.cpp
Labels: size/XS

#517 Capitailize component name
  SpatialGDKEditorToolbar/Source/Private/SchemaGenerator/SchemaGenerator.cpp
  SpatialGDKEditorToolbar/Source/Private/SchemaGenerator/Utils/DataTypeUtilities.cpp
  SpatialGDKEditorToolbar/Source/Private/SchemaGenerator/Utils/DataTypeUtilities.h
Labels: size/S

#521 Schema fixes
  SpatialGDKEditorToolbar/Source/Private/SchemaGenerator/SchemaGenerator.cpp
  SpatialGDKEditorToolbar/Source/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp
  SpatialGDKEditorToolbar/Source/Private/SchemaGenerator/Utils/DataTypeUtilities.cpp
  SpatialGDKEditorToolbar/Source/Private/SchemaGenerator/Utils/DataTypeUtilities.h
Labels: size/M

#523 Use correct class to create type structure
  SpatialGDKEditorToolbar/Source/Private/SchemaGenerator/TypeStructure.cpp
Labels: size/XS

#522 Use deployment map URL which enables lobby travel
  SpatialGDK/Source/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/Private/Interop/GlobalStateManager.cpp
  SpatialGDK/Source/Public/Interop/GlobalStateManager.h
Labels: size/M

#528 ServerTravel - Auto snapshot selection
  SpatialGDK/Source/Private/EngineClasses/SpatialNetDriver.cpp
Labels: size/S

#529 Removed PIE prefixes from map checking when connecting to a server.
  SpatialGDK/Source/Private/EngineClasses/SpatialNetDriver.cpp
Labels: size/XS

#519 Rename component to SingletonManager
  SpatialGDK/Extras/schema/global_state_manager.schema
  SpatialGDK/Source/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/Private/Interop/GlobalStateManager.cpp
  SpatialGDK/Source/Private/Interop/SnapshotManager.cpp
  SpatialGDK/Source/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/Public/SpatialConstants.h
  SpatialGDKEditorToolbar/Source/Private/SpatialGDKEditorGenerateSnapshot.cpp
Labels: size/M

#530 Prevent singleton crash
  SpatialGDK/Source/Private/Interop/GlobalStateManager.cpp
Labels: size/XS

#532 Check for duplicate RPCs and field names in schema
  SpatialGDKEditorToolbar/Source/Private/SchemaGenerator/SchemaGenerator.cpp
  SpatialGDKEditorToolbar/Source/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp
  SpatialGDKEditorToolbar/Source/Private/SchemaGenerator/Utils/DataTypeUtilities.cpp
  SpatialGDKEditorToolbar/Source/Private/SchemaGenerator/Utils/DataTypeUtilities.h
Labels: size/M
