Repository spatialos/UnrealGDK, pull requests merged in 2018-12, with the labels that each got.

#533 Update welcome and index page
  SpatialGDK/Documentation/index.md
  SpatialGDK/Documentation/welcome.md
Labels: size/M

#536 No need to pass game name in worker config
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/Build/Build.cs
Labels: size/XS

#537 Feature/drive by fixes
  SpatialGDKEditorToolbar/Source/Private/SchemaGenerator/SchemaGenerator.cpp
  SpatialGDKEditorToolbar/Source/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp
  SpatialGDKEditorToolbar/Source/Private/SchemaGenerator/Utils/DataTypeUtilities.cpp
  SpatialGDKEditorToolbar/Source/Private/SchemaGenerator/Utils/DataTypeUtilities.h
Labels: size/M

#535 Changed SpatialPosition to be rebased from zero origin
  SpatialGDK/Source/Private/EngineClasses/SpatialActorChannel.cpp
Labels: size/XS

#542 Small update to welcome and index page
  SpatialGDK/Documentation/index.md
  SpatialGDK/Documentation/welcome.md
Labels: size/M

#540 Improve error messages around name collision for schema types
  SpatialGDKEditorToolbar/Source/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp
Labels: size/XS

#547 Git hooks for running Setup.bat, don't re-download same version CoreSDK
  Setup.bat
Labels: size/M

#546 Added function to get worker flags in blueprints
  SpatialGDK/Source/Private/Interop/SpatialDispatcher.cpp
  SpatialGDK/Source/Private/Interop/SpatialWorkerFlags.cpp
  SpatialGDK/Source/Public/Interop/SpatialWorkerFlags.h
Labels: size/M

#538 Create SpawnData to imitate native Unreal new actor serialization
  SpatialGDK/Extras/schema/rotation.schema
  SpatialGDK/Extras/schema/spawndata.schema
  SpatialGDK/Source/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/Private/Interop/SpatialStaticComponentView.cpp
  SpatialGDK/Source/Public/EngineClasses/SpatialActorChannel.h
  SpatialGDK/Source/Public/Interop/SpatialReceiver.h
  SpatialGDK/Source/Public/Interop/SpatialSender.h
  SpatialGDK/Source/Public/Schema/Rotation.h
  SpatialGDK/Source/Public/Schema/SpawnData.h
  SpatialGDK/Source/Public/SpatialConstants.h
  SpatialGDK/Source/Public/Utils/SchemaUtils.h
  SpatialGDKEditorToolbar/Source/Private/SpatialGDKEditorGenerateSnapshot.cpp
Labels: size/XL

#545 Add enableProtocolLogging command line flag
  SpatialGDK/Source/Private/Interop/Connection/SpatialWorkerConnection.cpp
  SpatialGDK/Source/Public/Interop/Connection/ConnectionConfig.h
Labels: size/S

#548 Docs tidy-up
  SpatialGDK/Documentation/content/authority.md
  SpatialGDK/Documentation/content/cross-server-rpcs.md
  SpatialGDK/Documentation/content/directory-structure.md
  SpatialGDK/Documentation/content/dynamic-typebindings.md
  SpatialGDK/Documentation/content/glossary.md
  SpatialGDK/Documentation/content/handover-between-server-workers.md
  SpatialGDK/Documentation/content/map-travel.md
  SpatialGDK/Documentation/content/spatial-type.md
  SpatialGDK/Documentation/content/toolbars.md
  SpatialGDK/Documentation/content/troubleshooting.md
  SpatialGDK/Documentation/toc.md
Labels: size/L

#550 Fixed issues with URL traveling
  SpatialGDK/Source/Private/EngineClasses/SpatialNetDriver.cpp
Labels: size/S

#552 [UNR-670] Report write access failures when generating snapshot or schema
  SpatialGDKEditorToolbar/Source/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp
  SpatialGDKEditorToolbar/Source/Private/SpatialGDKEditorGenerateSnapshot.cpp
Labels: size/M

#553 NoLogToSpatial Param to stop logging to Spatial
  SpatialGDK/Source/Private/Interop/SpatialOutputDevice.cpp
  SpatialGDK/Source/Public/Interop/SpatialOutputDevice.h
Labels: size/XS

#561 Remove cached worker SDK
  Setup.bat
Labels: size/S

#539 Support for AlwaysRelevent object references.
  SpatialGDK/Extras/unreal-engine.version
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetBitWriter.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialStaticComponentView.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialTypebindingManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentFactory.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/SchemaUtils.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetBitReader.h
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetBitWriter.h
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialPackageMapClient.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialTypebindingManager.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/Interest.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/StandardLibrary.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/UnrealObjectRef.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/ComponentFactory.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/RepDataUtils.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/SchemaOption.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/SchemaUtils.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SnapshotGenerator/SpatialGDKEditorSnapshotGenerator.cpp
Labels: size/XXL

#557 Use TWeakObjectPtr for UnrealObjectRefs and add IsValid checks upon use.
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialPackageMapClient.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SnapshotGenerator/SpatialGDKEditorSnapshotGenerator.cpp
Labels: size/M

#560 Improve git hooks!
  RequireSetup
  Setup.bat
Labels: size/S

#562 Add callout
  SpatialGDK/Documentation/content/get-started/porting-unreal-project-to-gdk.md
Labels: size/XS

#559 Add -nocompile to Improbable.Unreal.Scripts/Build.
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/Build/Build.cs
Labels: size/M

#563 Fix not being able to build on Linux
  SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentFactory.cpp
Labels: size/XS

#554 Use TWeakObjectPtr for unresolved objects
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetBitWriter.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentFactory.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetBitWriter.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialSender.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/ComponentFactory.h
Labels: size/M

#565 UNR-824: Quick fix for aggressive ROLE_AutonomousProxy assignment
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
Labels: size/XS
