Repository spatialos/UnrealGDK, pull requests merged in 2018-08, with the labels that each got.

#258 Update setup-and-installing.md
  docs/setup-and-installing.md
Labels: size/XS

#251 UNR-481: Pending Replicated Property Updates Resolve Correctly to Owning Object
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/InteropCodeGenerator/TypeBindingGenerator.cpp
  Source/SpatialGDK/Private/SpatialInterop.cpp
  Source/SpatialGDK/Public/SpatialInterop.h
Labels: size/M

#260 UNR-464 - common plugin utils
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/InteropCodeGenerator/SpatialGDKEditorInteropCodeGenerator.cpp
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorGenerateSnapshot.cpp
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorUtils.cpp
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorUtils.h
Labels: size/M

#262 Add troubleshooting link to main page
  README.md
Labels: size/XS

#265 Added support for RPCs with spaces
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/InteropCodeGenerator/TypeBindingGenerator.cpp
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/InteropCodeGenerator/Utils/DataTypeUtilities.cpp
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/InteropCodeGenerator/Utils/DataTypeUtilities.h
  Source/SpatialGDK/Private/SpatialNetDriver.cpp
Labels: size/M

#266 Update setup-and-installing.md
  docs/setup-and-installing.md
Labels: size/M

#267 Docs/post release patch 2
  README.md
  docs/content/glossary.md
  docs/setup-and-installing.md
Labels: size/XS

#264 Link to a definition of modules.
  README.md
Labels: size/XS

#269 UNR-422: Fixed stalling interop codegen when recieving error output
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/InteropCodeGenerator/SpatialGDKEditorInteropCodeGenerator.cpp
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/InteropCodeGenerator/TypeBindingGenerator.cpp
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/InteropCodeGenerator/TypeBindingGenerator.h
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/InteropCodeGenerator/TypeStructure.cpp
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/InteropCodeGenerator/TypeStructure.h
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorInteropCodeGenerator.h
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorToolbar.h
  docs/known-issues.md
Labels: size/L

#273 Fixed compilation error
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorInteropCodeGenerator.h
Labels: size/XS

#268 Added blogpost link.
  README.md
  docs/readme.md
Labels: size/XS

#274 Set target .NETFramework to 4.5
  Source/Programs/Improbable.Unreal.CodeGeneration.Test/Improbable.Unreal.CodeGeneration.Test.csproj
  Source/Programs/Improbable.Unreal.CodeGeneration/Improbable.Unreal.CodeGeneration.csproj
  Source/Programs/Improbable.Unreal.Scripts/Build/Build.csproj
  Source/Programs/Improbable.Unreal.Scripts/Codegen/Codegen.csproj
  Source/Programs/Improbable.Unreal.Scripts/Common/Common.csproj
  Source/Programs/Improbable.Unreal.Scripts/DiffCopy/DiffCopy.csproj
  Source/Programs/Improbable.Unreal.Scripts/Linter/Linter.csproj
  docs/setup-and-installing.md
Labels: size/S

#276 Fix TypeStructure ComponentClasses
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/InteropCodeGenerator/TypeStructure.cpp
Labels: size/XS

#275 UNR-478 Fixed Byte Alignment Issues with Handover Data
  Source/SpatialGDK/Private/SpatialActorChannel.cpp
Labels: size/XS

#261 Add singleton class instructions to porting guide
  docs/content/porting-unreal-project-to-gdk.md
Labels: size/M

#277 Clarify ICG
  docs/content/interop.md
Labels: size/XS

#279 Use path instead of class name in GSM update
  Source/SpatialGDK/Private/SpatialActorChannel.cpp
Labels: size/XS

#257 UNR-432 snapshot path config
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorGenerateSnapshot.cpp
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbarSettings.cpp
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorGenerateSnapshot.h
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorToolbarSettings.h
  docs/assets/screen_grabs/toolbar/toolbar_settings.png
  docs/content/toolbar.md
Labels: size/M

#278 UNR-282: Added support for static arrays in handover data
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/InteropCodeGenerator/TypeBindingGenerator.cpp
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/InteropCodeGenerator/TypeBindingGenerator.h
  Source/SpatialGDK/Public/SpatialTypeBinding.h
Labels: size/M

#180 Boilerplate to support CrossServer RPCs
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/InteropCodeGenerator/TypeStructure.cpp
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/InteropCodeGenerator/TypeStructure.h
  Source/SpatialGDK/Private/SpatialNetDriver.cpp
  Source/SpatialGDK/Public/SpatialNetDriver.h
Labels: size/M

#270 Feature/unr 466
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/InteropCodeGenerator/SpatialGDKEditorInteropCodeGenerator.cpp
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/InteropCodeGenerator/TypeBindingGenerator.cpp
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/InteropCodeGenerator/TypeStructure.cpp
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorGenerateSnapshot.cpp
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbarSettings.cpp
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorUtils.cpp
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorInteropCodeGenerator.h
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorToolbarSettings.h
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorUtils.h
  docs/assets/screen_grabs/toolbar/ICGSettings.png
  docs/content/interop.md
  docs/content/toolbar.md
Labels: size/XL

#282 Docs/image updates
  docs/assets/screen_grabs/codegen.png
  docs/assets/screen_grabs/snapshot.png
  docs/assets/screen_grabs/toolbar/toolbar_buttons.png
  docs/assets/screen_grabs/toolbar/toolbar_settings.png
  docs/content/toolbar.md
Labels: size/XS

#281 UNR-493 - Move SpatialActorChannel callbacks to interop
  Source/SpatialGDK/Private/SpatialActorChannel.cpp
  Source/SpatialGDK/Private/SpatialInterop.cpp
  Source/SpatialGDK/Public/SpatialActorChannel.h
  Source/SpatialGDK/Public/SpatialInterop.h
Labels: size/L

#284 Added proper component to entity
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/InteropCodeGenerator/TypeBindingGenerator.cpp
  Source/SpatialGDK/Private/SpatialNetDriver.cpp
Labels: size/XS

#285 Update setup-and-installing.md
  docs/setup-and-installing.md
Labels: size/XS

#286 Add callback for classes with typebindings
  Source/SpatialGDK/Private/SpatialInterop.cpp
Labels: size/XS

#288 Adjust porting guide for UNR-466
  docs/content/porting-unreal-project-to-gdk.md
Labels: size/M

#290 Fix default snapshot path
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorGenerateSnapshot.cpp
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbarSettings.cpp
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorToolbarSettings.h
Labels: size/M

#292 Made one warning for all reliable multicasts
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/InteropCodeGenerator/SchemaGenerator.cpp
Labels: size/S

#289 Support Blueprint Defined Rep Structs
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/InteropCodeGenerator/SpatialGDKEditorInteropCodeGenerator.cpp
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/InteropCodeGenerator/TypeBindingGenerator.cpp
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/InteropCodeGenerator/TypeBindingGenerator.h
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/InteropCodeGenerator/TypeStructure.h
Labels: size/M

#291 Fix multicast rpcs so they can be issued without an owner on servers
  Source/SpatialGDK/Private/SpatialNetDriver.cpp
Labels: size/XS

#255 UNR-397 & UNR-398: Fix preplaced replicated actors and spawn them once
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorGenerateSnapshot.cpp
  Source/SpatialGDK/Private/SpatialActorChannel.cpp
  Source/SpatialGDK/Private/SpatialInterop.cpp
  Source/SpatialGDK/Private/SpatialInteropPipelineBlock.cpp
  Source/SpatialGDK/Private/SpatialPackageMapClient.cpp
  Source/SpatialGDK/Public/SpatialActorChannel.h
  Source/SpatialGDK/Public/SpatialConstants.h
  Source/SpatialGDK/Public/SpatialInterop.h
  Source/SpatialGDK/Public/SpatialPackageMapClient.h
  docs/known-issues.md
  schema/improbable/unreal/gdk/global_state_manager.schema
Labels: size/XL

#296 Updated engine version
  Source/SpatialGDK/Public/SpatialInterop.h
  unreal-engine.version
Labels: size/XS

#297 Remove unused Actor reference
  Source/SpatialGDK/Private/SpatialPackageMapClient.cpp
Labels: size/XS

#280 shim notifier
  Source/SpatialGDK/Private/SpatialInteropPipelineBlock.cpp
  Source/SpatialGDK/Public/SpatialInteropPipelineBlock.h
Labels: size/S

#295 Fix processing ops before entity pipeline is initialized
  Source/Programs/Improbable.Unreal.CodeGeneration/Templates/UnrealEntityPipelineHeaderGenerator.tt
  Source/SpatialGDK/Private/SpatialNetDriver.cpp
Labels: size/XS

#287 Feature/unr 456 create spatial tagging
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/InteropCodeGenerator/SpatialGDKEditorInteropCodeGenerator.cpp
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/InteropCodeGenerator/TypeBindingGenerator.cpp
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/InteropCodeGenerator/TypeBindingGenerator.h
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/InteropCodeGenerator/TypeStructure.cpp
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/InteropCodeGenerator/TypeStructure.h
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorGenerateSnapshot.cpp
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorInteropCodeGenerator.h
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorToolbar.h
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorToolbarSettings.h
  Source/SpatialGDK/Private/SpatialInterop.cpp
  Source/SpatialGDK/Private/SpatialTypeBinding.cpp
  Source/SpatialGDK/Public/SpatialTypeBinding.h
  docs/assets/screen_grabs/toolbar/ICGSettings.png
  docs/assets/screen_grabs/toolbar/spatial_interop_tagging.png
  docs/content/interop.md
  docs/content/porting-unreal-project-to-gdk.md
  docs/content/toolbar.md
  docs/content/troubleshooting.md
  unreal-engine.version
Labels: size/XL

#300 Updated doc
  docs/content/interop.md
  docs/content/singleton-actors.md
  docs/content/troubleshooting.md
Labels: size/M

#299 Furthered blueprint typebinding support
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/InteropCodeGenerator/SpatialGDKEditorInteropCodeGenerator.cpp
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/InteropCodeGenerator/TypeBindingGenerator.cpp
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/InteropCodeGenerator/TypeBindingGenerator.h
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/InteropCodeGenerator/TypeStructure.h
Labels: size/XL

#301 UNR-526 Fixed RPCTypeOwners overwriting correct Schema Types file
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/InteropCodeGenerator/TypeStructure.cpp
Labels: size/XS

#303 UNR-529: Increased scope of type binding includes.
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/InteropCodeGenerator/TypeBindingGenerator.cpp
  Source/SpatialGDK/Private/SpatialMemoryWriter.cpp
Labels: size/S

#307 UNR-543 Fix default map loading
  Source/SpatialGDK/Private/SpatialGameInstance.cpp
Labels: size/XS

#305 fix relative paths
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbarSettings.cpp
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorToolbarSettings.h
Labels: size/XS

#308 unr-351: Replace use of UStruct::SerializeBin() with custom SerializeStruct
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/InteropCodeGenerator/TypeBindingGenerator.cpp
  Source/SpatialGDK/Private/SpatialTypeBinding.cpp
  Source/SpatialGDK/Public/SpatialTypeBinding.h
Labels: size/M
