Repository spatialos/UnrealGDK, pull requests merged in 2018-10, with the labels that each got.

#388 Ensure spatial networking is on for schema gen
  SpatialGDK/Source/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDKEditorToolbar/Source/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp
  SpatialGDKEditorToolbar/Source/Private/SpatialGDKEditorToolbar.cpp
  SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar.Build.cs
Labels: size/S

#387 Fixed error message around unknown components
  SpatialGDK/Source/Private/Interop/SpatialReceiver.cpp
Labels: size/XS

#394 Include blueprint inherited components in a Class's subobjects
  SpatialGDK/Source/Private/Interop/SpatialTypebindingManager.cpp
Labels: size/XS

#393 Resolve actors as soon as possible
  SpatialGDK/Source/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/Private/Interop/SpatialReceiver.cpp
Labels: size/XS

#390 Early-out of connection attempt if getting deployment list fails.
  SpatialGDK/Source/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/Private/Interop/Connection/SpatialWorkerConnection.cpp
  SpatialGDK/Source/Public/EngineClasses/SpatialNetDriver.h
  SpatialGDK/Source/Public/Interop/Connection/SpatialWorkerConnection.h
Labels: size/M

#395 Add missing snapshot gen step to docs.
  SpatialGDK/Documentation/setup-and-installing.md
Labels: size/XS

#389 Feature/unr 628 fix for commit 360
  SpatialGDK/Source/Private/EngineClasses/SpatialActorChannel.cpp
Labels: size/S

#369 UNR-407: Adding FUnrealObjectRef assignment when sending/receiving updates
  SpatialGDK/Source/Private/EngineClasses/SpatialNetBitReader.cpp
  SpatialGDK/Source/Private/EngineClasses/SpatialNetBitWriter.cpp
  SpatialGDK/Source/Private/EngineClasses/SpatialPackageMapClient.cpp
  SpatialGDK/Source/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/Private/Utils/ComponentFactory.cpp
  SpatialGDK/Source/Private/Utils/ComponentReader.cpp
  SpatialGDK/Source/Public/EngineClasses/SpatialNetBitReader.h
  SpatialGDK/Source/Public/EngineClasses/SpatialNetBitWriter.h
  SpatialGDK/Source/Public/EngineClasses/SpatialPackageMapClient.h
  SpatialGDK/Source/Public/Interop/SpatialReceiver.h
  SpatialGDK/Source/Public/Schema/UnrealObjectRef.h
  SpatialGDK/Source/Public/SpatialConstants.h
  SpatialGDK/Source/Public/Utils/ComponentFactory.h
  SpatialGDK/Source/Public/Utils/ComponentReader.h
  SpatialGDK/Source/Public/Utils/SchemaOption.h
  SpatialGDK/Source/Public/Utils/SchemaUtils.h
Labels: size/XL

#397 Throttle spatial rotation updates
  SpatialGDK/Source/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/Public/EngineClasses/SpatialActorChannel.h
Labels: size/S

#364 Use spatial fast array serialize
  SpatialGDK/Source/Private/Utils/ComponentReader.cpp
Labels: size/S

#391 Overlapping boundaries
  SpatialGDK/Extras/schema/unreal_metadata.schema
  SpatialGDK/Source/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/Private/Interop/GlobalStateManager.cpp
  SpatialGDK/Source/Private/Interop/SpatialPlayerSpawner.cpp
  SpatialGDK/Source/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/Private/Interop/SpatialView.cpp
  SpatialGDK/Source/Private/Utils/ComponentFactory.cpp
  SpatialGDK/Source/Private/Utils/ComponentReader.cpp
  SpatialGDK/Source/Public/EngineClasses/SpatialActorChannel.h
  SpatialGDK/Source/Public/Interop/SpatialPlayerSpawner.h
  SpatialGDK/Source/Public/Interop/SpatialReceiver.h
  SpatialGDK/Source/Public/Interop/SpatialSender.h
  SpatialGDK/Source/Public/Interop/SpatialView.h
  SpatialGDK/Source/Public/Schema/UnrealMetadata.h
Labels: size/XL

#399 Generate schema for UObjects automatically
  SpatialGDKEditorToolbar/Source/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp
Labels: size/S

#398 Working UnrealObjRefs for Startup Actors
  SpatialGDK/Source/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/Private/EngineClasses/SpatialPackageMapClient.cpp
  SpatialGDK/Source/Private/Utils/ComponentFactory.cpp
  SpatialGDK/Source/Public/EngineClasses/SpatialNetDriver.h
  SpatialGDKEditorToolbar/Source/Private/SpatialGDKEditorGenerateSnapshot.cpp
Labels: size/M

#401 Only include core_types.schema if it's needed
  SpatialGDK/Source/Private/EngineClasses/SpatialPackageMapClient.cpp
  SpatialGDKEditorToolbar/Source/Private/SchemaGenerator/SchemaGenerator.cpp
Labels: size/M

#403 Point to the new FASTBuild storage share Cleaned up script outputs, made them nicer
  SpatialGDK/Extras/fastbuild/install.ps1
  SpatialGDK/Extras/fastbuild/uninstall.ps1
Labels: size/S

#404 Fixed IWYU issues in SpatialSender.cpp and SpatialPlayerSpawner.h
  SpatialGDK/Source/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/Public/Interop/SpatialPlayerSpawner.h
Labels: size/XS

#408 Fix corruption caused by replication of obj references in arrays
  SpatialGDK/Source/Private/Utils/ComponentReader.cpp
  SpatialGDK/Source/Public/Utils/ComponentReader.h
Labels: size/M

#407 Be able to spawn on workers which don't have authority over the spawner
  SpatialGDK/Source/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/Private/Interop/SpatialSender.cpp
Labels: size/S

#410 fixed incorrect gdk starter project link
  README.md
Labels: size/XS

#411 fixed numbering of list in singleton actors doc page
  SpatialGDK/Documentation/content/singleton-actors.md
Labels: size/XS

#396 UNR-561 view refactor
  SpatialGDK/Source/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/Private/EngineClasses/SpatialPackageMapClient.cpp
  SpatialGDK/Source/Private/Interop/GlobalStateManager.cpp
  SpatialGDK/Source/Private/Interop/SpatialDispatcher.cpp
  SpatialGDK/Source/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/Private/Interop/SpatialStaticComponentView.cpp
  SpatialGDK/Source/Public/EngineClasses/SpatialActorChannel.h
  SpatialGDK/Source/Public/EngineClasses/SpatialNetDriver.h
  SpatialGDK/Source/Public/Interop/GlobalStateManager.h
  SpatialGDK/Source/Public/Interop/SpatialDispatcher.h
  SpatialGDK/Source/Public/Interop/SpatialReceiver.h
  SpatialGDK/Source/Public/Interop/SpatialSender.h
  SpatialGDK/Source/Public/Interop/SpatialStaticComponentView.h
  SpatialGDK/Source/Public/Schema/Component.h
  SpatialGDK/Source/Public/Schema/Rotation.h
  SpatialGDK/Source/Public/Schema/StandardLibrary.h
  SpatialGDK/Source/Public/SpatialConstants.h
Labels: size/XL

#409 Prevent crash when running snapshot and schema at the same time
  SpatialGDKEditorToolbar/Source/Private/SpatialGDKEditorToolbar.cpp
  SpatialGDKEditorToolbar/Source/Private/SpatialGDKEditorToolbarCommands.cpp
  SpatialGDKEditorToolbar/Source/Private/SpatialGDKEditorToolbarStyle.cpp
  SpatialGDKEditorToolbar/Source/Public/SpatialGDKEditorToolbar.h
  SpatialGDKEditorToolbar/Source/Public/SpatialGDKEditorToolbarCommands.h
Labels: size/S

#402 Updated engine version to fix CI
  SpatialGDK/Extras/unreal-engine.version
Labels: size/XS

#412 Fix broken stuff
  SpatialGDK/Source/Public/EngineClasses/SpatialNetDriver.h
  SpatialGDK/Source/Public/Schema/Component.h
Labels: size/XS

#415 Fix linux build support - Removed uneeded typename identifiers
  SpatialGDK/Source/Private/Interop/SpatialStaticComponentView.cpp
  SpatialGDK/Source/Public/Interop/SpatialStaticComponentView.h
  SpatialGDK/Source/Public/Schema/Component.h
Labels: size/XS

#416 UNR-659 Clean up actor channels
  SpatialGDK/Source/Private/Interop/GlobalStateManager.cpp
  SpatialGDK/Source/Private/Interop/SpatialReceiver.cpp
Labels: size/S

#418 Fix crash for when subobject doesn't exist
  SpatialGDK/Source/Private/Interop/SpatialReceiver.cpp
Labels: size/XS

#406 Made generating schema for all supported classes opt out
  SpatialGDKEditorToolbar/Source/Private/SpatialGDKEditorToolbarSettings.cpp
Labels: size/XS

#419 Only call MergeChangeList if something has changed
  SpatialGDK/Source/Private/EngineClasses/SpatialActorChannel.cpp
Labels: size/S

#417 UNR-658: Switch checkfs to early-outs on failed statically-named actor resolution
  SpatialGDK/Source/Private/EngineClasses/SpatialNetBitReader.cpp
  SpatialGDK/Source/Private/Utils/ComponentReader.cpp
  SpatialGDK/Source/Private/Utils/SchemaUtils.cpp
  SpatialGDK/Source/Public/EngineClasses/SpatialNetBitReader.h
  SpatialGDK/Source/Public/Utils/ComponentReader.h
  SpatialGDK/Source/Public/Utils/SchemaUtils.h
Labels: size/M

#420 Upgrade to 4.20
  README.md
  SpatialGDK/Documentation/content/glossary.md
  SpatialGDK/Documentation/index.md
  SpatialGDK/Documentation/setup-and-installing.md
  SpatialGDK/Source/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/Private/EngineClasses/SpatialPackageMapClient.cpp
  SpatialGDK/Source/Private/Interop/SpatialDispatcher.cpp
  SpatialGDK/Source/Private/Utils/ComponentFactory.cpp
  SpatialGDK/Source/Private/Utils/ComponentReader.cpp
  SpatialGDK/Source/Public/EngineClasses/SpatialActorChannel.h
  SpatialGDK/Source/Public/EngineClasses/SpatialNetDriver.h
  SpatialGDK/Source/Public/EngineClasses/SpatialPackageMapClient.h
  SpatialGDK/Source/Public/Utils/RepLayoutUtils.h
  SpatialGDK/Source/SpatialGDK.Build.cs
  SpatialGDKEditorToolbar/Source/Private/SchemaGenerator/SchemaGenerator.cpp
  SpatialGDKEditorToolbar/Source/Private/SchemaGenerator/TypeStructure.cpp
  SpatialGDKEditorToolbar/Source/Private/SchemaGenerator/Utils/CodeWriter.h
  SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar.Build.cs
Labels: size/M

#424 Resolve singletons on non-authoritative servers
  SpatialGDK/Source/Private/Interop/GlobalStateManager.cpp
  SpatialGDK/Source/Public/Interop/SpatialStaticComponentView.h
Labels: size/XS

#429 Docs/docs refactor initial pass
  README.md
  SpatialGDK/Documentation/features.md
  SpatialGDK/Documentation/index.md
  SpatialGDK/Documentation/known-issues.md
Labels: size/L

#430 Update to latest GDK
  SpatialGDK/Extras/unreal-engine.version
  SpatialGDK/Source/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/Private/EngineClasses/SpatialGameInstance.cpp
  SpatialGDK/Source/Private/EngineClasses/SpatialNetBitReader.cpp
  SpatialGDK/Source/Private/EngineClasses/SpatialNetBitWriter.cpp
  SpatialGDK/Source/Private/EngineClasses/SpatialNetConnection.cpp
  SpatialGDK/Source/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/Private/EngineClasses/SpatialPackageMapClient.cpp
  SpatialGDK/Source/Private/Interop/Connection/SpatialWorkerConnection.cpp
  SpatialGDK/Source/Private/Interop/GlobalStateManager.cpp
  SpatialGDK/Source/Private/Interop/SpatialDispatcher.cpp
  SpatialGDK/Source/Private/Interop/SpatialOutputDevice.cpp
  SpatialGDK/Source/Private/Interop/SpatialPlayerSpawner.cpp
  SpatialGDK/Source/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/Private/Interop/SpatialStaticComponentView.cpp
  SpatialGDK/Source/Private/Interop/SpatialTypebindingManager.cpp
  SpatialGDK/Source/Private/SpatialGDKModule.cpp
  SpatialGDK/Source/Private/Utils/ComponentFactory.cpp
  SpatialGDK/Source/Private/Utils/ComponentReader.cpp
  SpatialGDK/Source/Private/Utils/EntityRegistry.cpp
  SpatialGDK/Source/Private/Utils/SchemaUtils.cpp
  SpatialGDK/Source/Public/EngineClasses/SpatialActorChannel.h
  SpatialGDK/Source/Public/EngineClasses/SpatialNetBitReader.h
  SpatialGDK/Source/Public/EngineClasses/SpatialNetBitWriter.h
  SpatialGDK/Source/Public/EngineClasses/SpatialNetDriver.h
  SpatialGDK/Source/Public/EngineClasses/SpatialPackageMapClient.h
  SpatialGDK/Source/Public/Interop/Connection/ConnectionConfig.h
  SpatialGDK/Source/Public/Interop/Connection/SpatialWorkerConnection.h
  SpatialGDK/Source/Public/Interop/GlobalStateManager.h
  SpatialGDK/Source/Public/Interop/SpatialDispatcher.h
  SpatialGDK/Source/Public/Interop/SpatialOutputDevice.h
  SpatialGDK/Source/Public/Interop/SpatialPlayerSpawner.h
  SpatialGDK/Source/Public/Interop/SpatialReceiver.h
  SpatialGDK/Source/Public/Interop/SpatialSender.h
  SpatialGDK/Source/Public/Interop/SpatialStaticComponentView.h
  SpatialGDK/Source/Public/Interop/SpatialTypebindingManager.h
  SpatialGDK/Source/Public/Schema/Component.h
  SpatialGDK/Source/Public/Schema/DynamicComponent.h
  SpatialGDK/Source/Public/Schema/Rotation.h
  SpatialGDK/Source/Public/Schema/StandardLibrary.h
  SpatialGDK/Source/Public/Schema/UnrealMetadata.h
  SpatialGDK/Source/Public/SpatialConstants.h
  SpatialGDK/Source/Public/SpatialGDKLoader.h
  SpatialGDK/Source/Public/SpatialGDKModule.h
  SpatialGDK/Source/Public/Utils/ComponentFactory.h
  SpatialGDK/Source/Public/Utils/EntityRegistry.h
  SpatialGDK/Source/Public/Utils/SchemaUtils.h
  SpatialGDKEditorToolbar/Source/Private/SchemaGenerator/SchemaGenerator.h
  SpatialGDKEditorToolbar/Source/Private/SpatialGDKEditorGenerateSnapshot.cpp
Labels: size/L

#434 Made any controller match its pawn's position.
  SpatialGDK/Source/Private/EngineClasses/SpatialActorChannel.cpp
Labels: size/XS

#438 Removed tag
  SpatialGDK/Documentation/content/generating-a-snapshot.md
Labels: size/XS

#436 Updated directory structure docs
  SpatialGDK/Documentation/content/directory-structure.md
Labels: size/XS

#439 Make schema better
  SpatialGDK/Extras/schema/global_state_manager.schema
  SpatialGDK/Extras/schema/player.schema
  SpatialGDK/Extras/schema/rotation.schema
  SpatialGDK/Extras/schema/spawner.schema
  SpatialGDK/Extras/schema/unreal_metadata.schema
  SpatialGDK/Source/Public/SpatialConstants.h
Labels: size/S

#433 Update known issues doc
  SpatialGDK/Documentation/known-issues.md
Labels: size/XS

#440 Add a singleton component to simplify streaming queries
  SpatialGDK/Extras/schema/singleton.schema
  SpatialGDK/Source/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/Private/Interop/SpatialStaticComponentView.cpp
  SpatialGDK/Source/Public/Schema/Singleton.h
  SpatialGDK/Source/Public/SpatialConstants.h
Labels: size/M

#441 UNR-621: Call `CallPreReplication` before saving out actor's in the snapshot
  SpatialGDK/Source/Private/Interop/SpatialReceiver.cpp
  SpatialGDKEditorToolbar/Source/Private/SpatialGDKEditorGenerateSnapshot.cpp
Labels: size/XS

#437 Updated the helper-scripts.md
  SpatialGDK/Documentation/content/helper-scripts.md
Labels: size/XS

#432 Created cross server RPC stub doc
  SpatialGDK/Documentation/assets/screen-grabs/crossserver-blueprint.png
  SpatialGDK/Documentation/assets/shooting-workflow-simple.png
  SpatialGDK/Documentation/content/cross-server-rpcs.md
  SpatialGDK/Documentation/features.md
Labels: size/M

#446 Docs/alpha onboarding
  SpatialGDK/Documentation/content/concepts.md
  SpatialGDK/Documentation/content/get-started/0-get-started.md
  SpatialGDK/Documentation/content/get-started/1-dependencies.md
  SpatialGDK/Documentation/content/get-started/2-build-unreal.md
  SpatialGDK/Documentation/content/get-started/3-gdk-and-starter-project.md
  SpatialGDK/Documentation/content/get-started/4-tutorial.md
  SpatialGDK/Documentation/content/getting-started.md
  SpatialGDK/Documentation/content/troubleshooting.md
  SpatialGDK/Documentation/contributions/unreal-gdk-coding-standards.md
  SpatialGDK/Documentation/index.md
  SpatialGDK/Documentation/known-issues.md
  SpatialGDK/Documentation/recommended-use.md
  SpatialGDK/Documentation/setup-and-installing.md
Labels: size/XL

#443 Update singleton doc
  SpatialGDK/Documentation/assets/screen-grabs/blueprint_singleton.png
  SpatialGDK/Documentation/content/singleton-actors.md
Labels: size/M

#425 Replication of multiple subobjects
  Setup.bat
  SpatialGDK/Extras/schema/core_types.schema
  SpatialGDK/Extras/schema/global_state_manager.schema
  SpatialGDK/Extras/schema/rotation.schema
  SpatialGDK/Extras/schema/spawner.schema
  SpatialGDK/Extras/schema/unreal_metadata.schema
  SpatialGDK/Source/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/Private/EngineClasses/SpatialPackageMapClient.cpp
  SpatialGDK/Source/Private/Interop/GlobalStateManager.cpp
  SpatialGDK/Source/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/Private/Interop/SpatialTypebindingManager.cpp
  SpatialGDK/Source/Private/Utils/ComponentFactory.cpp
  SpatialGDK/Source/Public/EngineClasses/SpatialActorChannel.h
  SpatialGDK/Source/Public/EngineClasses/SpatialPackageMapClient.h
  SpatialGDK/Source/Public/Interop/SpatialReceiver.h
  SpatialGDK/Source/Public/Interop/SpatialSender.h
  SpatialGDK/Source/Public/Interop/SpatialTypebindingManager.h
  SpatialGDK/Source/Public/Schema/StandardLibrary.h
  SpatialGDK/Source/Public/Schema/UnrealMetadata.h
  SpatialGDK/Source/Public/SpatialConstants.h
  SpatialGDK/Source/Public/Utils/ComponentFactory.h
  SpatialGDK/Source/Public/Utils/SchemaDatabase.h
  SpatialGDKEditorToolbar/Source/Private/SchemaGenerator/SchemaGenerator.cpp
  SpatialGDKEditorToolbar/Source/Private/SchemaGenerator/SchemaGenerator.h
  SpatialGDKEditorToolbar/Source/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp
  SpatialGDKEditorToolbar/Source/Private/SchemaGenerator/TypeStructure.cpp
  SpatialGDKEditorToolbar/Source/Private/SchemaGenerator/TypeStructure.h
  SpatialGDKEditorToolbar/Source/Private/SchemaGenerator/Utils/ComponentIdGenerator.h
  SpatialGDKEditorToolbar/Source/Private/SchemaGenerator/Utils/DataTypeUtilities.cpp
  SpatialGDKEditorToolbar/Source/Private/SpatialGDKEditorGenerateSnapshot.cpp
  SpatialGDKEditorToolbar/Source/Public/SpatialGDKEditorToolbarSettings.h
Labels: size/XXL

#448 Fix Singleton component schema package
  SpatialGDK/Extras/schema/singleton.schema
Labels: size/XS

#450 Renamed toolbar.md to toolbars.md
  SpatialGDK/Documentation/README.md
  SpatialGDK/Documentation/content/directory-structure.md
  SpatialGDK/Documentation/content/toolbars.md
Labels: size/XS

#451 MD'd snapshot docs
  SpatialGDK/Documentation/content/generating-a-snapshot.md
Labels: size/M

#456 Don't include non-supported schema
  SpatialGDKEditorToolbar/Source/Private/SchemaGenerator/SchemaGenerator.cpp
Labels: size/XS

#457 Cleanup contributions folder
  .github/CONTRIBUTING.md
  .github/issue-template.md
  pull_request_template.md
Labels: size/S

#455 Readme fixes
  README.md
Labels: size/XS

#458 Clean ClassToSchema before generating schema
  SpatialGDKEditorToolbar/Source/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp
Labels: size/XS

#460 Disable schema for SceneComponent since it causes a failed ensure
  SpatialGDKEditorToolbar/Source/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp
Labels: size/XS

#459 Refactored the plugin naming and image
  SpatialGDK/Documentation/assets/screen-grabs/toolbar/enable-toolbar.png
  SpatialGDK/Documentation/assets/screen-grabs/toolbar/toolbar-settings.png
  SpatialGDK/Documentation/content/toolbars.md
  SpatialGDK/Resources/Icon128.png
  SpatialGDK/SpatialGDK.uplugin
  SpatialGDKEditorToolbar/Resources/Icon128.png
  SpatialGDKEditorToolbar/Source/Private/SpatialGDKEditorToolbar.cpp
  SpatialGDKEditorToolbar/SpatialGDKEditorToolbar.uplugin
Labels: size/M

#461 Add missing include
  SpatialGDKEditorToolbar/Source/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp
Labels: size/XS

#427 Updated the porting guide
  SpatialGDK/Documentation/content/porting-unreal-project-to-gdk.md
Labels: size/L

#464 Add default initialization
  SpatialGDK/Source/Private/Interop/SpatialTypebindingManager.cpp
Labels: size/XS

#449 Update handover doc
  SpatialGDK/Documentation/assets/screen-grabs/handover-blueprint.png
  SpatialGDK/Documentation/content/handover-between-server-workers.md
Labels: size/S

#454 Update known issues
  SpatialGDK/Documentation/known-issues.md
Labels: size/XS

#463 Added spatial type doc
  SpatialGDK/Documentation/assets/screen-grabs/blueprint-singleton.png
  SpatialGDK/Documentation/content/spatial-type.md
Labels: size/M

#462 Added mentions of load balancing v2
  SpatialGDK/Documentation/content/toolbars.md
Labels: size/S

#465 Switched off unity build
  SpatialGDK/Source/Private/Interop/GlobalStateManager.cpp
  SpatialGDK/Source/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/Private/Interop/SpatialStaticComponentView.cpp
  SpatialGDK/Source/Private/Interop/SpatialTypebindingManager.cpp
  SpatialGDK/Source/Private/Utils/ComponentFactory.cpp
  SpatialGDK/Source/Private/Utils/ComponentReader.cpp
  SpatialGDK/Source/Public/Interop/SpatialSender.h
  SpatialGDK/Source/Public/Interop/SpatialStaticComponentView.h
  SpatialGDK/Source/Public/Schema/StandardLibrary.h
  SpatialGDK/Source/Public/Schema/UnrealMetadata.h
  SpatialGDK/Source/SpatialGDK.Build.cs
Labels: size/M

#470 Make Setup.bat clean the schema folder
  Setup.bat
Labels: size/XS

#453 Updated glossary
  SpatialGDK/Documentation/content/cross-server-rpcs.md
  SpatialGDK/Documentation/content/generating-a-snapshot.md
  SpatialGDK/Documentation/content/get-started/gdk-and-starter-project.md
  SpatialGDK/Documentation/content/get-started/porting-unreal-project-to-gdk.md
  SpatialGDK/Documentation/content/glossary.md
  SpatialGDK/Documentation/content/handover-between-server-workers.md
  SpatialGDK/Documentation/content/singleton-actors.md
  SpatialGDK/Documentation/index.md
  SpatialGDK/Documentation/welcome.md
Labels: size/XL

#472 Local deploy pauses if there's an error
  SpatialGDKEditorToolbar/Source/Private/SpatialGDKEditorToolbar.cpp
Labels: size/XS

#466 Map travel initial doc
  SpatialGDK/Documentation/content/map-travel.md
Labels: size/M

#469 Docs/girays launchday docs pass
  README.md
  SpatialGDK/Documentation/content/get-started/gdk-and-starter-project.md
  SpatialGDK/Documentation/content/get-started/introduction.md
  SpatialGDK/Documentation/content/get-started/porting-unreal-project-to-gdk.md
  SpatialGDK/Documentation/content/troubleshooting.md
  SpatialGDK/Documentation/features.md
  SpatialGDK/Documentation/index.md
  SpatialGDK/Documentation/known-issues.md
  SpatialGDK/Documentation/toc.md
  SpatialGDK/Documentation/welcome.md
Labels: size/M

#473 Authority doc
  SpatialGDK/Documentation/content/authority.md
  SpatialGDK/Documentation/content/generating-a-snapshot.md
  SpatialGDK/Documentation/content/handover-between-server-workers.md
Labels: size/M

#474 Updated feature list
  SpatialGDK/Documentation/features.md
Labels: size/XS

#479 Tutorial
  SpatialGDK/Documentation/content/get-started/tutorial.md
Labels: size/L

#480 format fix
  SpatialGDK/Documentation/content/get-started/gdk-and-starter-project.md
Labels: size/XS

#478 Updated spatial type doc
  SpatialGDK/Documentation/content/spatial-type.md
Labels: size/XS

#477 What's new initial
  SpatialGDK/Documentation/content/whatsnew.md
  SpatialGDK/Documentation/toc.md
Labels: size/S

#481 Added images and fixed markdown for improbadoc
  SpatialGDK/Documentation/assets/screen-grabs/blueprint-gamemode-singleton-serveronly.png
  SpatialGDK/Documentation/assets/screen-grabs/blueprint-gamestate-singleton.png
  SpatialGDK/Documentation/assets/screen-grabs/spatial-game-instance-reparent.png
  SpatialGDK/Documentation/assets/screen-grabs/toolbar/toolbar-checkboxes.png
  SpatialGDK/Documentation/assets/screen-grabs/toolbar/toolbars-basic.png
  SpatialGDK/Documentation/content/get-started/porting-unreal-project-to-gdk.md
Labels: size/S

#476 Added imges and updated ToC for map-travel doc
  SpatialGDK/Documentation/assets/screen-grabs/cooking-maps.png
  SpatialGDK/Documentation/assets/screen-grabs/snapshot-asset-cooking.png
  SpatialGDK/Documentation/content/map-travel.md
  SpatialGDK/Documentation/toc.md
Labels: size/XS

#483 ToC Updates and linting fixes
  SpatialGDK/Documentation/content/get-started/gdk-and-starter-project.md
  SpatialGDK/Documentation/content/get-started/introduction.md
  SpatialGDK/Documentation/content/whatsnew.md
  SpatialGDK/Documentation/toc.md
Labels: size/XS

#482 Mention that you need to update your load balancing strategy.
  SpatialGDK/Documentation/content/get-started/tutorial.md
Labels: size/XS

#485 Getting started feedback
  SpatialGDK/Documentation/assets/screen-grabs/toolbar/schema-button.png
  SpatialGDK/Documentation/assets/screen-grabs/toolbar/snapshot-button.png
  SpatialGDK/Documentation/content/get-started/gdk-and-starter-project.md
Labels: size/S

#484 Updated tutorial
  SpatialGDK/Documentation/content/get-started/tutorial.md
Labels: size/M

#487 Tidied up
  SpatialGDK/Documentation/content/cross-server-rpcs.md
  SpatialGDK/Documentation/content/handover-between-server-workers.md
  SpatialGDK/Documentation/content/map-travel.md
  SpatialGDK/Documentation/content/whatsnew.md
Labels: size/M

#486 Add images, fix typos
  SpatialGDK/Documentation/assets/tutorial/console.png
  SpatialGDK/Documentation/assets/tutorial/cross-server.gif
  SpatialGDK/Documentation/assets/tutorial/inspector.png
  SpatialGDK/Documentation/assets/tutorial/launch.png
  SpatialGDK/Documentation/assets/tutorial/project-name.png
  SpatialGDK/Documentation/content/get-started/tutorial.md
Labels: size/L
