Repository spatialos/UnrealGDK, pull requests merged in 2018-07, with the labels that each got.

#232 UNR-443: Troublshooting docs ++
  docs/content/porting-unreal-project-to-gdk.md
  docs/content/troubleshooting.md
  docs/known-issues.md
Labels: size/L

#230 UNR-453 - add toolbar doc
  docs/assets/screen_grabs/toolbar/enable_toolbar.png
  docs/assets/screen_grabs/toolbar/toolbar_buttons.png
  docs/assets/screen_grabs/toolbar/toolbar_settings.png
  docs/assets/screen_grabs/toolbar/window_access.png
  docs/content/directory-structure.md
  docs/content/toolbar.md
Labels: size/M

#233 Create singleton-actors.md
  docs/content/singleton-actors.md
Labels: size/M

#229 UNR-188 - RPC ownership fix
  Source/SpatialGDK/Private/SpatialNetDriver.cpp
Labels: size/XS

#235 Snapshot docs
  docs/assets/screen_grabs/snapshot.png
  docs/content/snapshots.md
Labels: size/S

#234 Docs/update some links
  README.md
  docs/assets/screen_grabs/codegen.png
  docs/assets/screen_grabs/interop_codegen.png
  docs/content/adding-a-replicated-property.md
  docs/content/directory-structure.md
  docs/content/glossary.md
  docs/content/interop.md
  docs/content/porting-unreal-project-to-gdk.md
  docs/content/setting-up-a-blank-project.md
  docs/content/singleton-actors.md
  docs/readme.md
  docs/setup-and-installing.md
Labels: size/M

#236 Adjust the porting doc
  docs/content/porting-unreal-project-to-gdk.md
Labels: size/S

#239 UNR-479: Fix UE4 fork path
  docs/setup-and-installing.md
Labels: size/XS

#237 Add recommended use and warnings
  README.md
  docs/content/directory-structure.md
  docs/content/generating-a-snapshot.md
  docs/content/glossary.md
  docs/content/helper-scripts.md
  docs/content/interop.md
  docs/content/porting-unreal-project-to-gdk.md
  docs/content/singleton-actors.md
  docs/content/snapshots.md
  docs/content/supported-replicated-types.md
  docs/content/toolbar.md
  docs/content/troubleshooting.md
  docs/known-issues.md
  docs/readme.md
  docs/setup-and-installing.md
Labels: size/M

#241 First pass feature list
  docs/features.md
Labels: size/M

#244 Update setup-and-installing.md
  docs/setup-and-installing.md
Labels: size/XS

#243 Update the features page
  docs/features.md
  docs/readme.md
Labels: size/XS

#247 Small docs edits
  README.md
  docs/content/directory-structure.md
  docs/content/interop.md
  docs/readme.md
  docs/setup-and-installing.md
Labels: size/S

#249 rename
  .github/CONTRIBUTING.md
Labels: size/XS

#245 Added stably-named replicated actor details to docs
  docs/content/troubleshooting.md
  docs/known-issues.md
Labels: size/XS

#246 UNR-469: Docs/link fixes
  README.md
  docs/content/directory-structure.md
  docs/content/generating-a-snapshot.md
  docs/content/glossary.md
  docs/content/handover-between-server-workers.md
  docs/content/helper-scripts.md
  docs/content/interop.md
  docs/content/porting-unreal-project-to-gdk.md
  docs/content/singleton-actors.md
  docs/content/supported-replicated-types.md
  docs/content/toolbar.md
  docs/content/troubleshooting.md
  docs/contributions/unreal-gdk-coding-standards.md
  docs/features.md
  docs/known-issues.md
  docs/readme.md
  docs/setup-and-installing.md
Labels: size/M

#252 Update setup-and-installing.md to cite BuildWorker.bat
  docs/setup-and-installing.md
Labels: size/XS

#250 Added feature list link in the readme.
  README.md
Labels: size/XS

#253 Update setup-and-installing.md
  docs/setup-and-installing.md
Labels: size/XS

#254 Added new toolbar icons
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Resources/BrowserIcon_40x.png
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Resources/Codegen.png
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Resources/Codegen@0.5x.png
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Resources/CodegenIcon.png
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Resources/CreateSnapshotIcon.png
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Resources/Icon128.png
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Resources/ImprobableIconStop_40x.png
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Resources/ImprobableIcon_40x.png
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Resources/Inspector.png
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Resources/Inspector@0.5x.png
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Resources/Launch.png
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Resources/Launch@0.5x.png
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Resources/Snapshot.png
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Resources/Snapshot@0.5x.png
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Resources/Stop.png
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Resources/Stop@0.5x.png
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbarStyle.cpp
Labels: size/S

#256 Update supported-replicated-types.md
  docs/content/supported-replicated-types.md
Labels: size/XS
