Repository spatialos/UnrealGDK, pull requests merged in 2018-09, with the labels that each got.

#311 Revert UNR-518 to unblock CI
  Source/SpatialGDK/Private/SpatialNetDriver.cpp
  Source/SpatialGDK/Public/SpatialNetDriver.h
Labels: size/M

#315 Added back troubleshooting to the toc
  docs/toc.md
Labels: size/XS

#316 New engine version
  unreal-engine.version
Labels: size/XS

#320 Add missing include
  Source/SpatialGDK/Public/Utils/SchemaDatabase.h
Labels: size/XS

#321 Style adjustments and fixes
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/InteropCodeGenerator/SchemaGenerator.cpp
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/InteropCodeGenerator/SpatialGDKEditorInteropCodeGenerator.cpp
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/InteropCodeGenerator/TypeBindingGenerator.cpp
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/InteropCodeGenerator/TypeStructure.cpp
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
  Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp
  Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  Source/SpatialGDK/Private/Interop/SpatialTypebindingManager.cpp
  Source/SpatialGDK/Public/Interop/Connection/ConnectionConfig.h
  Source/SpatialGDK/Public/Interop/Connection/SpatialWorkerConnection.h
  Source/SpatialGDK/Public/Schema/UnrealMetadata.h
  Source/SpatialGDK/Public/SpatialGDKLoader.h
  Source/SpatialGDK/Public/Utils/SchemaDatabase.h
Labels: size/L

#322 Port subobject changes to dynamic typebindings
  Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  Source/SpatialGDK/Private/Interop/SpatialTypebindingManager.cpp
  Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h
  Source/SpatialGDK/Public/Interop/SpatialTypebindingManager.h
Labels: size/M

#323 PR fixes for Dynamic Typebindings
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorGenerateSnapshot.cpp
  Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp
  Source/SpatialGDK/Public/EngineClasses/SpatialPackageMapClient.h
  Source/SpatialGDK/Public/Interop/SpatialConditionMapFilter.h
Labels: size/S

#324 Add UPROPERTY
  Source/SpatialGDK/Public/Interop/SpatialTypebindingManager.h
Labels: size/XS

#326 Fixed order of component ids
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/InteropCodeGenerator/SpatialGDKEditorInteropCodeGenerator.cpp
Labels: size/XS

#313 Readd UNR-518
  Source/SpatialGDK/Private/SpatialNetDriver.cpp
  Source/SpatialGDK/Public/SpatialNetDriver.h
Labels: size/M

#325 Fixed lingering Subobject GUIDs when an Actor is deleted
  Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp
  Source/SpatialGDK/Private/Interop/SpatialView.cpp
  Source/SpatialGDK/Public/Interop/SpatialView.h
Labels: size/S

#318 Handover
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/InteropCodeGenerator/TypeStructure.cpp
  Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  Source/SpatialGDK/Private/Interop/SpatialTypebindingManager.cpp
  Source/SpatialGDK/Private/Utils/ComponentFactory.cpp
  Source/SpatialGDK/Private/Utils/ComponentReader.cpp
  Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h
  Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
  Source/SpatialGDK/Public/Interop/SpatialReceiver.h
  Source/SpatialGDK/Public/Interop/SpatialSender.h
  Source/SpatialGDK/Public/Interop/SpatialTypebindingManager.h
  Source/SpatialGDK/Public/Utils/ComponentFactory.h
  Source/SpatialGDK/Public/Utils/ComponentReader.h
  Source/SpatialGDK/Public/Utils/RepDataUtils.h
Labels: size/XXL

#334 Remove actor channel from EntityToActorChannel map on cleanup
  Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
Labels: size/S

#331 Incorrect removal of subobjectrefs
  Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp
Labels: size/XS

#337 Fixed SpatialActorChannel::Cleanup from crashing in editor
  Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
Labels: size/XS

#336 PR for Level Snapshots
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorGenerateSnapshot.cpp
  Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h
  Source/SpatialGDK/Public/Interop/SpatialReceiver.h
  Source/SpatialGDK/Public/Interop/SpatialSender.h
  Source/SpatialGDK/Public/Schema/Rotation.h
  Source/SpatialGDK/Public/Schema/SnapshotEntity.h
  schema/improbable/unreal/gdk/global_state_manager.schema
  schema/improbable/unreal/gdk/rotation.schema
  schema/improbable/unreal/gdk/snapshot_entity.schema
Labels: size/XL

#338 UNR-559: Fix warnings and enable Linux compilation (WIP)
  BuildGDK.bat
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
  Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  Source/SpatialGDK/Private/Interop/Connection/ConnectionConfig.cpp
  Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp
  Source/SpatialGDK/Private/Interop/SpatialPlayerSpawner.cpp
  Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  Source/SpatialGDK/Private/Interop/SpatialTypebindingManager.cpp
  Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h
  Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
  Source/SpatialGDK/Public/Interop/Connection/ConnectionConfig.h
  Source/SpatialGDK/Public/Interop/Connection/SpatialWorkerConnection.h
  Source/SpatialGDK/Public/Interop/SpatialView.h
  Source/SpatialGDK/Public/Schema/UnrealObjectRef.h
  Source/SpatialGDK/Public/SpatialConstants.h
  Source/SpatialGDK/Public/Utils/EntityRegistry.h
Labels: size/L

#341 Remove subobject NetGUIDs during RemoveComponent
  Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp
  Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  Source/SpatialGDK/Private/Interop/SpatialView.cpp
  Source/SpatialGDK/Public/EngineClasses/SpatialPackageMapClient.h
  Source/SpatialGDK/Public/Interop/SpatialReceiver.h
  Source/SpatialGDK/Public/Interop/SpatialView.h
Labels: size/M

#342 Schema for a specific class has to be generated for it to replicate
  Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  Source/SpatialGDK/Private/Interop/SpatialTypebindingManager.cpp
Labels: size/S

#344 Save Startup Actors to snapshot :clap:
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorGenerateSnapshot.cpp
  Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  Source/SpatialGDK/Private/Utils/ComponentFactory.cpp
  Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h
  Source/SpatialGDK/Public/Interop/SpatialReceiver.h
  Source/SpatialGDK/Public/Interop/SpatialSender.h
  Source/SpatialGDK/Public/Schema/Rotation.h
  Source/SpatialGDK/Public/Utils/ComponentFactory.h
  schema/improbable/unreal/gdk/global_state_manager.schema
  schema/improbable/unreal/gdk/level_data.schema
  schema/improbable/unreal/gdk/rotation.schema
Labels: size/XL

#347 TSchemaOption Implementation :eyes:
  BuildGDK.bat
  Source/SpatialGDK/Private/EngineClasses/SpatialNetBitWriter.cpp
  Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp
  Source/SpatialGDK/Private/Interop/SpatialPlayerSpawner.cpp
  Source/SpatialGDK/Private/Utils/ComponentFactory.cpp
  Source/SpatialGDK/Private/Utils/ComponentReader.cpp
  Source/SpatialGDK/Public/Schema/UnrealObjectRef.h
  Source/SpatialGDK/Public/Utils/ComponentReader.h
  Source/SpatialGDK/Public/Utils/SchemaOption.h
  Source/SpatialGDK/Public/Utils/SchemaUtils.h
Labels: size/L

#343 Prefixed "Spatial" to all hand written components
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorGenerateSnapshot.cpp
  Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  Source/SpatialGDK/Private/Interop/GlobalStateManager.cpp
  Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  Source/SpatialGDK/Private/Interop/SpatialView.cpp
  Source/SpatialGDK/Public/Interop/SpatialReceiver.h
  Source/SpatialGDK/Public/Interop/SpatialSender.h
  Source/SpatialGDK/Public/Interop/SpatialView.h
  Source/SpatialGDK/Public/Schema/Component.h
  Source/SpatialGDK/Public/Schema/DynamicComponent.h
  Source/SpatialGDK/Public/Schema/Rotation.h
  Source/SpatialGDK/Public/Schema/StandardLibrary.h
  Source/SpatialGDK/Public/Schema/UnrealMetadata.h
Labels: size/L

#346 DTB - PR Feedback Round 2
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/InteropCodeGenerator/SpatialGDKEditorInteropCodeGenerator.cpp
  Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorGenerateSnapshot.cpp
  Source/SpatialGDK/Private/Interop/GlobalStateManager.cpp
  Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  Source/SpatialGDK/Private/Interop/SpatialView.cpp
  Source/SpatialGDK/Private/Utils/ComponentFactory.cpp
  Source/SpatialGDK/Private/Utils/ComponentReader.cpp
  Source/SpatialGDK/Public/Interop/SpatialView.h
  Source/SpatialGDK/Public/SpatialConstants.h
  Source/SpatialGDK/Public/Utils/ComponentFactory.h
  Source/SpatialGDK/Public/Utils/ComponentReader.h
Labels: size/L

#348 Replaced ICG with GDoc WIP link. Tidied up content...
  .github/CONTRIBUTING.md
  LICENSE.md
  README.md
  docs/README.md
  docs/content/concepts.md
  docs/content/directory-structure.md
  docs/content/generating-a-snapshot.md
  docs/content/getting-started.md
  docs/content/glossary.md
  docs/content/handover-between-server-workers.md
  docs/content/helper-scripts.md
  docs/content/interop.md
  docs/content/porting-unreal-project-to-gdk.md
  docs/content/singleton-actors.md
  docs/content/troubleshooting.md
  docs/contributing.md
  docs/contributions/unreal-gdk-coding-standards.md
  docs/index.md
  docs/known-issues.md
  docs/license.md
  docs/toc.md
Labels: size/XL

#349 Fix style, add template GetTypeHash
  SpatialGDK/Source/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/Private/Interop/SpatialTypebindingManager.cpp
  SpatialGDK/Source/Public/Schema/UnrealObjectRef.h
  SpatialGDK/Source/Public/Utils/SchemaOption.h
  SpatialGDKEditorToolbar/Source/Private/InteropCodeGenerator/SpatialGDKEditorInteropCodeGenerator.cpp
  SpatialGDKEditorToolbar/Source/Private/InteropCodeGenerator/TypeStructure.cpp
Labels: size/S

#350 Fix crash on missing UnrealMetadata when closing PIE instance
  SpatialGDK/Source/Private/EngineClasses/SpatialActorChannel.cpp
Labels: size/XS

#351 Cleanup of Setup.bat
  Setup.bat
Labels: size/XS

#354 Add Worker ID to SpatialWorkerConnection.
  SpatialGDK/Source/Private/Interop/Connection/SpatialWorkerConnection.cpp
  SpatialGDK/Source/Public/Interop/Connection/SpatialWorkerConnection.h
Labels: size/S

#353 Added namespaces and update to our coding guidelines.
  SpatialGDK/Documentation/contributions/unreal-gdk-coding-standards.md
  SpatialGDK/Source/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/Private/EngineClasses/SpatialNetBitReader.cpp
  SpatialGDK/Source/Private/EngineClasses/SpatialNetBitWriter.cpp
  SpatialGDK/Source/Private/EngineClasses/SpatialPackageMapClient.cpp
  SpatialGDK/Source/Private/Interop/GlobalStateManager.cpp
  SpatialGDK/Source/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/Private/Interop/SpatialView.cpp
  SpatialGDK/Source/Private/Utils/ComponentFactory.cpp
  SpatialGDK/Source/Private/Utils/ComponentReader.cpp
  SpatialGDK/Source/Public/EngineClasses/SpatialNetBitReader.h
  SpatialGDK/Source/Public/EngineClasses/SpatialNetBitWriter.h
  SpatialGDK/Source/Public/EngineClasses/SpatialPackageMapClient.h
  SpatialGDK/Source/Public/Interop/SpatialReceiver.h
  SpatialGDK/Source/Public/Interop/SpatialView.h
  SpatialGDK/Source/Public/Schema/Component.h
  SpatialGDK/Source/Public/Schema/DynamicComponent.h
  SpatialGDK/Source/Public/Schema/Rotation.h
  SpatialGDK/Source/Public/Schema/StandardLibrary.h
  SpatialGDK/Source/Public/Schema/UnrealMetadata.h
  SpatialGDK/Source/Public/Schema/UnrealObjectRef.h
  SpatialGDK/Source/Public/SpatialConstants.h
  SpatialGDK/Source/Public/Utils/ComponentReader.h
  SpatialGDK/Source/Public/Utils/SchemaOption.h
  SpatialGDK/Source/Public/Utils/SchemaUtils.h
  SpatialGDKEditorToolbar/Source/Private/SpatialGDKEditorGenerateSnapshot.cpp
Labels: size/XL

#357 Error log if SpatialNetDriver not set up correctly
  SpatialGDK/Source/Private/EngineClasses/SpatialGameInstance.cpp
Labels: size/XS

#359 Get SpatialNetworking flag from settings
  SpatialGDK/Source/Private/EngineClasses/SpatialGameInstance.cpp
  SpatialGDK/Source/SpatialGDK.Build.cs
Labels: size/XS

#360 Added a retry for reserving an entity
  SpatialGDK/Source/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/Public/EngineClasses/SpatialActorChannel.h
Labels: size/M

#365 Fix Linux build support by removing improbable namespace around UnrealObjectRef
  SpatialGDK/Source/Private/EngineClasses/SpatialNetBitReader.cpp
  SpatialGDK/Source/Private/EngineClasses/SpatialNetBitWriter.cpp
  SpatialGDK/Source/Private/EngineClasses/SpatialPackageMapClient.cpp
  SpatialGDK/Source/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/Private/Utils/ComponentFactory.cpp
  SpatialGDK/Source/Private/Utils/ComponentReader.cpp
  SpatialGDK/Source/Public/EngineClasses/SpatialNetBitReader.h
  SpatialGDK/Source/Public/EngineClasses/SpatialNetBitWriter.h
  SpatialGDK/Source/Public/EngineClasses/SpatialPackageMapClient.h
  SpatialGDK/Source/Public/Interop/SpatialReceiver.h
  SpatialGDK/Source/Public/Schema/UnrealObjectRef.h
  SpatialGDK/Source/Public/SpatialConstants.h
  SpatialGDK/Source/Public/Utils/ComponentReader.h
  SpatialGDK/Source/Public/Utils/SchemaUtils.h
Labels: size/L

#358 UNR-573: Directory structure docs
  SpatialGDK/Documentation/content/directory-structure.md
Labels: size/S

#368 Don't crash when actor is null
  SpatialGDK/Source/Private/EngineClasses/SpatialActorChannel.cpp
Labels: size/XS

#339 Dynamic component interest
  SpatialGDK/Source/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/Private/Interop/Connection/SpatialWorkerConnection.cpp
  SpatialGDK/Source/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/Private/Interop/SpatialView.cpp
  SpatialGDK/Source/Public/EngineClasses/SpatialActorChannel.h
  SpatialGDK/Source/Public/Interop/Connection/SpatialWorkerConnection.h
  SpatialGDK/Source/Public/Interop/SpatialSender.h
  SpatialGDK/Source/Public/Interop/SpatialView.h
  SpatialGDK/Source/Public/Schema/StandardLibrary.h
Labels: size/L

#366 Client Travel
  SpatialGDK/Source/Private/EngineClasses/SpatialGameInstance.cpp
  SpatialGDK/Source/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/Private/EngineClasses/SpatialPackageMapClient.cpp
  SpatialGDK/Source/Private/Interop/Connection/SpatialWorkerConnection.cpp
  SpatialGDK/Source/Public/EngineClasses/SpatialPackageMapClient.h
  SpatialGDK/Source/Public/Interop/Connection/ConnectionConfig.h
  SpatialGDK/Source/Public/Interop/Connection/SpatialWorkerConnection.h
  SpatialGDK/Source/Public/SpatialConstants.h
Labels: size/M

#371 Use Owner for Spatial Position
  SpatialGDK/Source/Private/EngineClasses/SpatialActorChannel.cpp
Labels: size/S

#370 Made switch for generating all classes
  SpatialGDKEditorToolbar/Source/Private/InteropCodeGenerator/SpatialGDKEditorInteropCodeGenerator.cpp
  SpatialGDKEditorToolbar/Source/Private/SpatialGDKEditorToolbarSettings.cpp
  SpatialGDKEditorToolbar/Source/Public/SpatialGDKEditorToolbarSettings.h
Labels: size/S

#374 Fix native networking not working after running with Spatial networking once
  SpatialGDK/Source/Private/EngineClasses/SpatialGameInstance.cpp
Labels: size/XS

#373 DTB- Feedback round 4
  SpatialGDK/Source/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/Private/EngineClasses/SpatialPackageMapClient.cpp
  SpatialGDK/Source/Private/Interop/Connection/SpatialWorkerConnection.cpp
  SpatialGDK/Source/Private/Interop/GlobalStateManager.cpp
  SpatialGDK/Source/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/Private/Interop/SpatialTypebindingManager.cpp
  SpatialGDK/Source/Public/EngineClasses/SpatialNetDriver.h
  SpatialGDK/Source/Public/EngineClasses/SpatialPackageMapClient.h
  SpatialGDK/Source/Public/Interop/Connection/SpatialWorkerConnection.h
  SpatialGDK/Source/Public/Interop/GlobalStateManager.h
  SpatialGDK/Source/Public/Interop/SpatialPlayerSpawner.h
  SpatialGDK/Source/Public/Interop/SpatialReceiver.h
  SpatialGDK/Source/Public/Interop/SpatialSender.h
  SpatialGDK/Source/Public/Interop/SpatialTypebindingManager.h
  SpatialGDK/Source/Public/Interop/SpatialView.h
  SpatialGDK/Source/Public/Schema/GlobalStateManager.h
  SpatialGDK/Source/Public/Schema/Rotation.h
  SpatialGDK/Source/Public/Schema/StandardLibrary.h
  SpatialGDK/Source/Public/Schema/UnrealMetadata.h
  SpatialGDK/Source/Public/SpatialConstants.h
  SpatialGDK/Source/Public/SpatialGDKLoader.h
  SpatialGDK/Source/Public/Utils/EntityBuilder.h
  SpatialGDK/Source/Public/Utils/RepLayoutUtils.h
  SpatialGDKEditorToolbar/Source/Private/SpatialGDKEditorGenerateSnapshot.cpp
Labels: size/XL

#376 Fix deployment list error printing garbage text
  SpatialGDK/Source/Private/Interop/Connection/SpatialWorkerConnection.cpp
Labels: size/XS

#377 Fixed check for subobject
  SpatialGDK/Source/Private/Interop/SpatialTypebindingManager.cpp
Labels: size/XS

#372 UNR-577: CI scripts for the DTB branches
  SpatialGDK/Extras/unreal-engine.version
  ci/build_linux.bat
  ci/build_linux.sh
  ci/build_windows.bat
  ci/build_windows.sh
  ci/pinned-tools.sh
  ci/profiling.sh
Labels: size/M

#378 Revert "[UNR-556] Resend reliable RPCs (#367)"
  SpatialGDK/Source/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/Public/Interop/SpatialSender.h
Labels: size/L

#375 Initial docs pass
  SpatialGDK/Documentation/README.md
  SpatialGDK/Documentation/content/directory-structure.md
  SpatialGDK/Documentation/content/generating-a-snapshot.md
  SpatialGDK/Documentation/content/getting-started.md
  SpatialGDK/Documentation/content/glossary.md
  SpatialGDK/Documentation/content/handover-between-server-workers.md
  SpatialGDK/Documentation/content/helper-scripts.md
  SpatialGDK/Documentation/content/interop.md
  SpatialGDK/Documentation/content/porting-unreal-project-to-gdk.md
  SpatialGDK/Documentation/content/singleton-actors.md
  SpatialGDK/Documentation/content/toolbar.md
  SpatialGDK/Documentation/content/troubleshooting.md
  SpatialGDK/Documentation/features.md
  SpatialGDK/Documentation/index.md
  SpatialGDK/Documentation/known-issues.md
  SpatialGDK/Documentation/setup-and-installing.md
  SpatialGDK/Documentation/toc.md
  SpatialGDK/Source/Private/EngineClasses/SpatialPackageMapClient.cpp
  SpatialGDKEditorToolbar/Resources/Schema.png
  SpatialGDKEditorToolbar/Resources/Schema@0.5x.png
  SpatialGDKEditorToolbar/Source/Private/SchemaGenerator/SchemaGenerator.cpp
  SpatialGDKEditorToolbar/Source/Private/SchemaGenerator/SchemaGenerator.h
  SpatialGDKEditorToolbar/Source/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp
  SpatialGDKEditorToolbar/Source/Private/SchemaGenerator/TypeStructure.cpp
  SpatialGDKEditorToolbar/Source/Private/SchemaGenerator/TypeStructure.h
  SpatialGDKEditorToolbar/Source/Private/SchemaGenerator/Utils/CodeWriter.cpp
  SpatialGDKEditorToolbar/Source/Private/SchemaGenerator/Utils/CodeWriter.h
  SpatialGDKEditorToolbar/Source/Private/SchemaGenerator/Utils/ComponentIdGenerator.h
  SpatialGDKEditorToolbar/Source/Private/SchemaGenerator/Utils/DataTypeUtilities.cpp
  SpatialGDKEditorToolbar/Source/Private/SchemaGenerator/Utils/DataTypeUtilities.h
  SpatialGDKEditorToolbar/Source/Private/SpatialGDKEditorToolbar.cpp
  SpatialGDKEditorToolbar/Source/Private/SpatialGDKEditorToolbarCommands.cpp
  SpatialGDKEditorToolbar/Source/Private/SpatialGDKEditorToolbarStyle.cpp
  SpatialGDKEditorToolbar/Source/Public/SpatialGDKEditorInteropCodeGenerator.h
  SpatialGDKEditorToolbar/Source/Public/SpatialGDKEditorSchemaGenerator.h
  SpatialGDKEditorToolbar/Source/Public/SpatialGDKEditorToolbar.h
  SpatialGDKEditorToolbar/Source/Public/SpatialGDKEditorToolbarCommands.h
  SpatialGDKEditorToolbar/Source/Public/SpatialGDKEditorToolbarSettings.h
  SpatialGDKEditorToolbar/SpatialGDKEditorToolbar.uplugin
Labels: size/XL

#379 Fix missing includes
  SpatialGDK/Source/Public/Interop/Connection/ConnectionConfig.h
  SpatialGDK/Source/Public/Schema/UnrealMetadata.h
Labels: size/XS

#380 Update the setup.bat to include a pause
  Setup.bat
Labels: size/XS

#381 Docs/toc divider formatting
  SpatialGDK/Documentation/assets/screen-grabs/codegen.png
  SpatialGDK/Documentation/content/handover-between-server-workers.md
  SpatialGDK/Documentation/index.md
  SpatialGDK/Documentation/setup-and-installing.md
  SpatialGDK/Documentation/toc.md
Labels: size/S

#382 Updated sdk to 13.3.0
  SpatialGDK/Extras/core-sdk.version
Labels: size/XS

#384 Removed unused schema references
  SpatialGDK/Extras/schema/spawner.schema
  SpatialGDK/Extras/schema/unreal_metadata.schema
Labels: size/XS

#383 [UNR-556] Re-add resending reliable RPCs
  SpatialGDK/Source/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/Private/EngineClasses/SpatialPackageMapClient.cpp
  SpatialGDK/Source/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/Public/Interop/SpatialReceiver.h
  SpatialGDK/Source/Public/Interop/SpatialSender.h
  SpatialGDK/Source/Public/Schema/StandardLibrary.h
Labels: size/L

#385 Fix README.md
  README.md
Labels: size/S

#386 Fix crash in snapshot generator
  SpatialGDK/Source/Private/Utils/ComponentFactory.cpp
Labels: size/XS
