Repository spatialos/UnrealGDK, pull requests merged in 2019-11, with the labels that each got.

#1354 Better create entity response handling
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h
Labels: jira/UNR, size/M

#1466 Docs - UNR-2325 - Add missing simplayer clients build step
  SpatialGDK/Documentation/content/cloud-deployment-workflow.md
  SpatialGDK/Documentation/content/get-started/example-project/exampleproject-cloud-deployment.md
  SpatialGDK/Documentation/content/get-started/starter-template/get-started-template-cloud.md
Labels: jira/UNR, size/M

#1421 Feature/unr 2034 spatial debugger
  CHANGELOG.md
  SpatialGDK/Content/SpatialDebugger/BP_SpatialDebugger.uasset
  SpatialGDK/Content/SpatialDebugger/Textures/Auth.uasset
  SpatialGDK/Content/SpatialDebugger/Textures/AuthIntent.uasset
  SpatialGDK/Content/SpatialDebugger/Textures/Box.uasset
  SpatialGDK/Content/SpatialDebugger/Textures/LockClosed.uasset
  SpatialGDK/Content/SpatialDebugger/Textures/LockOpen.uasset
  SpatialGDK/Raw/SpatialDebugger/Textures/Auth.png
  SpatialGDK/Raw/SpatialDebugger/Textures/AuthIntent.png
  SpatialGDK/Raw/SpatialDebugger/Textures/Box.png
  SpatialGDK/Raw/SpatialDebugger/Textures/LockClosed.png
  SpatialGDK/Raw/SpatialDebugger/Textures/LockOpen.png
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialGameInstance.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialDebugger.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialStaticComponentView.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialDebugger.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditor.cpp
  SpatialGDK/SpatialGDK.uplugin
Labels: do-not-merge/work-in-progress, jira/UNR, size/XL

#1470 Revert "Feature/unr 2034 spatial debugger"
  CHANGELOG.md
  SpatialGDK/Content/SpatialDebugger/BP_SpatialDebugger.uasset
  SpatialGDK/Content/SpatialDebugger/Textures/Auth.uasset
  SpatialGDK/Content/SpatialDebugger/Textures/AuthIntent.uasset
  SpatialGDK/Content/SpatialDebugger/Textures/Box.uasset
  SpatialGDK/Content/SpatialDebugger/Textures/LockClosed.uasset
  SpatialGDK/Content/SpatialDebugger/Textures/LockOpen.uasset
  SpatialGDK/Raw/SpatialDebugger/Textures/Auth.png
  SpatialGDK/Raw/SpatialDebugger/Textures/AuthIntent.png
  SpatialGDK/Raw/SpatialDebugger/Textures/Box.png
  SpatialGDK/Raw/SpatialDebugger/Textures/LockClosed.png
  SpatialGDK/Raw/SpatialDebugger/Textures/LockOpen.png
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialGameInstance.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialDebugger.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialStaticComponentView.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialDebugger.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditor.cpp
  SpatialGDK/SpatialGDK.uplugin
Labels: jira/no-ticket, size/XL

#1469 Update buildkite queue
  .buildkite/premerge.steps.yaml
Labels: jira/UNR, size/XS

#1445 [UNR-2214] Abstract + GridBasedLBStrategy
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/AbstractLBStrategy.cpp
  SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/GridBasedLBStrategy.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h
  SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/AbstractLBStrategy.h
  SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/GridBasedLBStrategy.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialActorUtils.h
  SpatialGDK/Source/SpatialGDKTests/SpatialGDK/LoadBalancing/GridBasedLBStrategy/GridBasedLBStrategyTest.cpp
  SpatialGDK/Source/SpatialGDKTests/SpatialGDK/LoadBalancing/GridBasedLBStrategy/TestGridBasedLBStrategy.cpp
  SpatialGDK/Source/SpatialGDKTests/SpatialGDK/LoadBalancing/GridBasedLBStrategy/TestGridBasedLBStrategy.h
Labels: jira/UNR, size/XXL

#1473 Bugfix: Add Category to UPROPERTY
  SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/GridBasedLBStrategy.h
Labels: jira/no-ticket, size/XS

#1477 Fix garbage collection during schema generation
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditor.cpp
Labels: jira/no-ticket, size/XS

#1476 fixing up Setup.sh
  Setup.sh
  SpatialGDK/Extras/git/post-merge
Labels: jira/no-ticket, size/L

#1479 Bugfix: EntityPool fails if call times out
  SpatialGDK/Source/SpatialGDK/Private/Utils/EntityPool.cpp
Labels: jira/no-ticket, size/XS

#1480 Feature/GV-98 Unreal GDK multiple engine version CI
  .buildkite/premerge.steps.yaml
  ci/check-version-file.sh
  ci/gdk_build_template.steps.yaml
  ci/generate_and_upload_build_steps.sh
  ci/get-engine.ps1
Labels: jira/GV, size/L

#1483 Feature/gv 98 fix version file parsing
  ci/get-engine.ps1
Labels: jira/GV, size/XS

#1438 Feature/UNR-2244 Extend UHT to add spatial function flags
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Public/Utils/EngineVersionCheck.h
Labels: jira/UNR, size/XS

#1472 Docs - added docs about AllowUnresolvedParameters
  SpatialGDK/Documentation/content/cross-server-rpcs.md
Labels: docs, jira/UNR, size/S

#1454 [UNR-1997] 4.23.1 Upgrade
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/GlobalStateManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentFactory.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentReader.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialFastArrayNetSerialize.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialConditionMapFilter.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/EngineVersionCheck.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/RepLayoutUtils.h
  SpatialGDK/Source/SpatialGDK/SpatialGDK.Build.cs
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/TypeStructure.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditor.cpp
  SpatialGDK/Source/SpatialGDKEditorCommandlet/Private/Commandlets/CookAndGenerateSchemaCommandlet.cpp
  ci/unreal-engine.version
Labels: jira/UNR, size/XL

#1478 Adding a Worker SDK upgrade doc
  SpatialGDK/Extras/worker-sdk-upgrade.md
Labels: jira/no-ticket, size/XS

#1484 Update release-process.md
  SpatialGDK/Extras/internal-documentation/release-process.md
Labels: jira/no-ticket, size/XS

#1481 UNR-2317 Fix crash when starting PIE with missing schema
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialClassInfoManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialClassInfoManager.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialSender.h
Labels: jira/UNR, size/M

#1487 Fix editor crash when running with outdated schema (no schema for subobject)
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
Labels: jira/no-ticket, size/XS

#1475 Update the translator to query for connection entities
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialVirtualWorkerTranslator.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialVirtualWorkerTranslator.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
  SpatialGDK/Source/SpatialGDKTests/SpatialGDK/EngineClasses/SpatialVirtualWorkerTranslator/SpatialVirtualWorkerTranslatorTest.cpp
Labels: jira/UNR, size/XL

#1471 [UNR-2203] Spatial virtual worker translator refactor
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialLoadBalanceEnforcer.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialVirtualWorkerTranslator.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/GridBasedLBStrategy.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialLoadBalanceEnforcer.h
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialVirtualWorkerTranslator.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialSender.h
  SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/AbstractLBStrategy.h
  SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/GridBasedLBStrategy.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/AuthorityIntent.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialCommonTypes.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h
Labels: jira/UNR, size/XL

#1489 Fix a typo that Jo found
  SpatialGDK/Documentation/content/tutorials/dbsync/tutorial-dbsync-intro.md
Labels: jira/no-ticket, size/XS

#1491 UNR-2364 Crash in ProcessRPCs
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/Utils/RPCContainer.cpp
  SpatialGDK/Source/SpatialGDK/Public/Utils/RPCContainer.h
Labels: jira/UNR, size/XS

#1492 Reduce log severity when deleting an actor with no channel
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
Labels: jira/no-ticket, size/XS

#1430 Bugfix/unr 1698 fix host url override
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialGameInstance.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialGDKConsoleCommands.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialGameInstance.h
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/ConnectionConfig.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/SpatialWorkerConnection.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialGDKConsoleCommands.h
Labels: jira/UNR, size/XL

#1488 UNR-2363 Use accessors to get Spatial Networking flag from settings
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialGameInstance.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialStatics.cpp
  SpatialGDK/Source/SpatialGDK/Public/Utils/EngineVersionCheck.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditor.cpp
  SpatialGDK/Source/SpatialGDKEditorCommandlet/Private/Commandlets/CookAndGenerateSchemaCommandlet.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
  SpatialGDK/Source/SpatialGDKServices/Private/LocalDeploymentManager.cpp
  SpatialGDK/Source/SpatialGDKTests/Private/SpatialGDKTestsModule.cpp
  SpatialGDK/Source/SpatialGDKTests/SpatialGDK/Utils/Misc/SpatialActivationFlags.cpp
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/SpatialGDKEditorSchemaGeneratorTest.cpp
  SpatialGDK/SpatialGDK.uplugin
  ci/gdk_build_template.steps.yaml
Labels: jira/UNR, size/L

#1497 Fix up copyright headers, move UnrealObjectRef.cpp to the right place
  SpatialGDK/Source/SpatialGDK/Private/Schema/UnrealObjectRef.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/ActorGroupManager.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/OutgoingMessages.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/SpatialWorkerConnection.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/UnrealObjectRef.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/ActorGroupManager.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/SchemaDatabase.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/SchemaOption.h
  SpatialGDK/Source/SpatialGDKEditor/Private/WorkerTypeCustomization.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h
  SpatialGDK/Source/SpatialGDKEditor/Public/WorkerTypeCustomization.h
  SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorToolbar.h
  SpatialGDK/Source/SpatialGDKServices/Private/Interop/Connection/EditorWorkerController.cpp
  SpatialGDK/Source/SpatialGDKServices/Public/Interop/Connection/EditorWorkerController.h
  SpatialGDK/Source/SpatialGDKServices/Public/LocalDeploymentManager.h
  SpatialGDK/Source/SpatialGDKServices/Public/SpatialGDKServicesModule.h
  SpatialGDK/Source/SpatialGDKTests/Public/SpatialGDKTestsModule.h
Labels: jira/no-ticket, size/S

#1495 Bugfix/servers retain interest in always relevant actors
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/InterestFactory.cpp
  SpatialGDK/Source/SpatialGDK/Public/Utils/InterestFactory.h
Labels: jira/no-ticket, size/S

#1463 Feature/unr 2302 unreal gdk ci testing with spatial
  .buildkite/premerge.steps.yaml
  SpatialGDK/Source/SpatialGDKServices/Private/SpatialGDKServicesModule.cpp
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKServices/LocalDeploymentManager/LocalDeploymentManagerTest.cpp
  ci/cleanup.ps1
  ci/gdk_build.template.steps.yaml
  ci/generate-and-upload-build-steps.sh
  ci/get-engine.ps1
  ci/report-tests.ps1
  ci/run-tests.ps1
  ci/setup-build-test-gdk.ps1
  ci/setup-gdk.ps1
  ci/setup-tests.ps1
Labels: jira/UNR, size/L

#1494 Update CHANGELOG.md
  CHANGELOG.md
Labels: jira/no-ticket, size/S

#1490 Clear queued RPCs on entity/actor deletion
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/RPCContainer.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialSender.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/RPCContainer.h
Labels: jira/no-ticket, size/S

#1467 UNR-1945 SpatialGDK Example Tests
  SpatialGDK/Source/SpatialGDKTests/Examples/SpatialGDKExampleTest.cpp
  SpatialGDK/Source/SpatialGDKTests/Examples/SpatialGDKTestGuidelines.h
  SpatialGDK/Source/SpatialGDKTests/Public/TestDefinitions.h
Labels: jira/UNR, size/L

#1496 UNR 2363 Fix LocalDeploymentManager to stop using bSpatialNetworking to disable himself.
  SpatialGDK/Source/SpatialGDKServices/Private/LocalDeploymentManager.cpp
  SpatialGDK/Source/SpatialGDKServices/Public/LocalDeploymentManager.h
  SpatialGDK/Source/SpatialGDKTests/SpatialGDK/Utils/Misc/SpatialActivationFlags.cpp
Labels: jira/UNR, size/L

#1498 Updated the Keep your GDK up to date guide
  SpatialGDK/Documentation/content/get-started/build-unreal-fork.md
  SpatialGDK/Documentation/content/get-started/dependencies.md
  SpatialGDK/Documentation/content/pricing-and-support/versioning-scheme.md
  SpatialGDK/Documentation/content/upgrading.md
  SpatialGDK/Documentation/unreal-features-support.md
Labels: jira/UNR, size/M

#1503 UNR-2419: make gdk setup self-contained
  ci/setup-gdk.ps1
Labels: jira/UNR, size/XS

#1453 GCS-1500 - Add support to DeploymentLauncher to parse a .pb.json launch config.
  CHANGELOG.md
  RequireSetup
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/DeploymentLauncher/DeploymentLauncher.cs
Labels: jira/GCS, jira/UNR, size/M

#1506 Update unreal-engine.version file to preview
  ci/unreal-engine.version
Labels: jira/no-ticket, size/XS

#1502 Bugfix/unr 2408 ui crash fix
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorCloudLauncher.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorCloudLauncher.h
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKSimulatedPlayerDeployment.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorToolbar.h
Labels: jira/UNR, size/L

#1444 UNR-2189 - Bugfix cloud launch config default
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditor.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorCloudLauncher.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorSettings.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKSimulatedPlayerDeployment.cpp
Labels: jira/UNR, size/M

#1485 [UNR-2378] Add UE4 4.23 support to Features Support page
  SpatialGDK/Documentation/content/get-started/dependencies.md
  SpatialGDK/Documentation/unreal-features-support.md
Labels: docs, jira/UNR, size/S

#1510 Fixed an error in the feature support table
  SpatialGDK/Documentation/unreal-features-support.md
Labels: jira/no-ticket, size/XS

#1508 Reload class by component id if it has been unloaded (WIP)
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialClassInfoManager.cpp
Labels: jira/GCS, size/S

#1500 Docs - Simplayer fixes based on Teri's feedback (docs-preview PR)
  SpatialGDK/Documentation/content/cloud-deployment-workflow.md
  SpatialGDK/Documentation/content/get-started/example-project/exampleproject-cloud-deployment.md
  SpatialGDK/Documentation/content/get-started/starter-template/get-started-template-cloud.md
  SpatialGDK/Documentation/content/simulated-players.md
Labels: docs, jira/no-ticket, size/M

#1486 Docs - Simplayer fixes based on Teri's feedback
  SpatialGDK/Documentation/content/cloud-deployment-workflow.md
  SpatialGDK/Documentation/content/get-started/example-project/exampleproject-cloud-deployment.md
  SpatialGDK/Documentation/content/get-started/starter-template/get-started-template-cloud.md
  SpatialGDK/Documentation/content/simulated-players.md
Labels: docs, jira/no-ticket, size/M

#1431 [UNR-1698][MS] Updating docs regarding receptionistHost command line …
  SpatialGDK/Documentation/content/map-travel.md
Labels: jira/UNR, size/XS

#1424 Feature/unr 1998 adding network profiler calls
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentFactory.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialSender.h
Labels: jira/UNR, size/M

#1452 UNR-2181 - Add option to DeploymentLauncher to deploy only sim player deployment
  CHANGELOG.md
  RequireSetup
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/DeploymentLauncher/DeploymentLauncher.cs
Labels: jira/UNR, size/M

#1514 Added 'and zoning' to 'workers and zoning' URL
  SpatialGDK/Documentation/content/spatialos-concepts/authority-and-interest.md
Labels: jira/no-ticket, size/XS

#1515 Move RPC types into separate enum, remove old reliable RPC checking
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialClassInfoManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/RPCContainer.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialMetrics.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialClassInfoManager.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialSender.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/RPCContainer.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialMetrics.h
  SpatialGDK/Source/SpatialGDKTests/SpatialGDK/Utils/RPCContainer/ObjectSpy.cpp
  SpatialGDK/Source/SpatialGDKTests/SpatialGDK/Utils/RPCContainer/ObjectSpy.h
  SpatialGDK/Source/SpatialGDKTests/SpatialGDK/Utils/RPCContainer/RPCContainerTest.cpp
Labels: jira/no-ticket, size/XL

#1512 Bugfix: Fixed up regex to handle log categories without imporbable prefix
  SpatialGDK/Source/SpatialGDKServices/Private/SSpatialOutputLog.cpp
Labels: jira/no-ticket, size/XS

#1518 Cherry picked update from docs-preview
  SpatialGDK/Documentation/content/spatialos-concepts/authority-and-interest.md
Labels: jira/no-ticket, size/XS

#1509 UNR 1132 Correct handling of unresolved reference in structs
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetBitReader.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentReader.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetBitReader.h
Labels: jira/UNR, size/S

#1519 Remove unnecessary ConfigRestartRequired = false from settings
  SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h
Labels: jira/no-ticket, size/M

#1522 Update fastbuild readme
  SpatialGDK/Extras/fastbuild/README.md
Labels: jira/no-ticket, size/S

#1505 Feature/unr 2034 spatial debugger
  CHANGELOG.md
  SpatialGDK/Content/SpatialDebugger/BP_SpatialDebugger.uasset
  SpatialGDK/Content/SpatialDebugger/Textures/Auth.uasset
  SpatialGDK/Content/SpatialDebugger/Textures/AuthIntent.uasset
  SpatialGDK/Content/SpatialDebugger/Textures/Box.uasset
  SpatialGDK/Content/SpatialDebugger/Textures/LockClosed.uasset
  SpatialGDK/Content/SpatialDebugger/Textures/LockOpen.uasset
  SpatialGDK/Raw/SpatialDebugger/Textures/Auth.png
  SpatialGDK/Raw/SpatialDebugger/Textures/AuthIntent.png
  SpatialGDK/Raw/SpatialDebugger/Textures/Box.png
  SpatialGDK/Raw/SpatialDebugger/Textures/LockClosed.png
  SpatialGDK/Raw/SpatialDebugger/Textures/LockOpen.png
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialGameInstance.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialDebugger.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialStaticComponentView.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialDebugger.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditor.cpp
  SpatialGDK/SpatialGDK.uplugin
Labels: jira/UNR, size/XL

#1523 Add overrides for handover, server interest, and load balancing
  SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp
  SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h
Labels: jira/no-ticket, size/M

#1530 Feature/sim player scripts changelog
  CHANGELOG.md
Labels: jira/no-ticket, size/XS

#1455 UNR-2287 Server travel
  CHANGELOG.md
  SpatialGDK/Extras/schema/global_state_manager.schema
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/GlobalStateManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SnapshotManager.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialGameInstance.h
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/SpatialWorkerConnection.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/GlobalStateManager.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SnapshotGenerator/SpatialGDKEditorSnapshotGenerator.cpp
Labels: jira/UNR, size/XL

#1501 Task/unr 1905 improve slack hooks
  .buildkite/premerge.steps.yaml
  ci/build-and-send-slack-notification.ps1
  ci/gdk_build.template.steps.yaml
  ci/generate-and-upload-build-steps.sh
  ci/report-tests.ps1
  ci/setup-tests.ps1
Labels: jira/UNR, size/L

#1536 Bugfix: Fixed up regex to handle log categories without imporba… (#1512)
  SpatialGDK/Source/SpatialGDKServices/Private/SSpatialOutputLog.cpp
Labels: jira/no-ticket, size/XS

#1511 [UNR-2445][MS] Doc changes for server travel.
  SpatialGDK/Documentation/content/map-travel.md
  SpatialGDK/Documentation/unreal-features-support.md
Labels: docs, jira/UNR, size/S

#1513 Zoning glue: This uses the Strategy, Translator, and Enforcer to move authority across worker boundaries.
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialLoadBalanceEnforcer.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetConnection.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialVirtualWorkerTranslator.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/AbstractLBStrategy.cpp
  SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/GridBasedLBStrategy.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialVirtualWorkerTranslator.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h
  SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/AbstractLBStrategy.h
  SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/GridBasedLBStrategy.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SnapshotGenerator/SpatialGDKEditorSnapshotGenerator.cpp
  SpatialGDK/Source/SpatialGDKTests/SpatialGDK/EngineClasses/SpatialVirtualWorkerTranslator/SpatialVirtualWorkerTranslatorTest.cpp
Labels: jira/no-ticket, size/XL

#1537 implement tracking and fix slack message
  .buildkite/premerge.steps.yaml
  ci/report-tests.ps1
  ci/setup-build-test-gdk.ps1
  ci/upload-test-metrics.sh
Labels: jira/GV, size/M
