Repository spatialos/UnrealGDK, pull requests merged in 2019-04, with the labels that each got.

#789 Use the EntityToChannel map the netdriver already has in the dispatcher
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialDispatcher.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
Labels: size/XS

#791 Fix the command line override of using QBI
  SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp
  SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h
Labels: size/XS

#794 docs/DOC-1024-Bugfixes
  SpatialGDK/Documentation/content/get-started/dependencies.md
  SpatialGDK/Documentation/content/get-started/gdk-template.md
Labels: size/XS

#795 change variable type to ensure linux builds work
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
Labels: size/XS

#696 Bug fix - ensure Begin play occurs after GSM is ready (GDK-side)
  SpatialGDK/Source/SpatialGDK/Private/Interop/GlobalStateManager.cpp
  ci/unreal-engine.version
Labels: size/S

#796 Added a local state record for which players have been spawned
  SpatialGDK/Extras/schema/spawner.schema
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialPlayerSpawner.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/SpatialWorkerConnection.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialPlayerSpawner.h
Labels: size/M

#797 Switch default to network protocol to TCP
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/ConnectionConfig.h
Labels: size/XS

#799 Changed default multiplex level.
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/ConnectionConfig.h
Labels: size/XS

#790 Add deployment region options
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/DeploymentLauncher/DeploymentLauncher.cs
  SpatialGDK/Build/Scripts/DeploymentLauncher.bat
Labels: size/M

#771 UNR-1076: Disconnection handling
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialGameInstance.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialGameInstance.h
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/ErrorCodeRemapping.h
Labels: size/M

#801 [UNR-442] Don't send log messages to Spatial if PIE index doesn't match
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialOutputDevice.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialOutputDevice.h
Labels: size/S

#803 [UNR-1239] - Fix String Deserialization from Schema
  SpatialGDK/Source/SpatialGDK/Public/Utils/SchemaUtils.h
Labels: size/XS

#807 Update known-issues.md
  SpatialGDK/Documentation/known-issues.md
Labels: size/XS

#805 Added a warning for when replicated abilities are detected in schema generation
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp
  SpatialGDK/Source/SpatialGDKEditor/SpatialGDKEditor.Build.cs
  SpatialGDK/SpatialGDK.uplugin
Labels: size/S

#810 Fix Visual Studio 2017 download link
  SpatialGDK/Documentation/content/get-started/dependencies.md
Labels: size/XS

#811 Add Direct X to dependencies
  SpatialGDK/Documentation/content/get-started/dependencies.md
Labels: size/XS

#809 Bugfix - get subobject if not default
  SpatialGDK/Source/SpatialGDK/Public/Schema/UnrealMetadata.h
Labels: size/XS

#814 Fix numbering and styling in setup docs.
  SpatialGDK/Documentation/content/get-started/build-unreal-fork.md
  SpatialGDK/Documentation/content/get-started/gdk-template.md
Labels: size/S

#816 Specify the correct version of the DirectX dependency.
  SpatialGDK/Documentation/content/get-started/dependencies.md
Labels: size/XS

#815 Fix missing SchemaDatabase
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialClassInfoManager.cpp
Labels: size/XS

#812 Add pragma once directive to header
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialWorkerFlags.h
Labels: size/XS

#818 Upgrade to worker SDK 13.6.2
  RequireSetup
  SpatialGDK/Extras/core-sdk.version
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/ConnectionConfig.h
Labels: size/XS

#817 Fixed schema generation for subobjects
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/TypeStructure.cpp
Labels: size/XS

#823 Update dependencies.md
  SpatialGDK/Documentation/content/get-started/dependencies.md
Labels: size/XS

#819 Rate limit position updates
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h
Labels: size/M

#782 UNR-948: add support for passing in command line flags for local launch
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorSettings.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
Labels: size/S

#826 Update gdk-template.md
  SpatialGDK/Documentation/content/get-started/gdk-template.md
Labels: size/XS

#808 Run both Windows and Linux builds, side by side
  .buildkite/premerge.steps.yaml
  ci/build-gdk.ps1
  ci/common.ps1
  ci/get-engine.ps1
  ci/setup-and-build-gdk.ps1
  ci/setup-gdk.ps1
Labels: size/M

#830 Remove mention of 13.2
  SpatialGDK/Documentation/content/get-started/dependencies.md
Labels: size/XS

#831 DOC-862 Change 'layers' to 'server-worker types'
  SpatialGDK/Documentation/content/glossary.md
  SpatialGDK/Documentation/content/non-unreal-server-worker-types.md
  SpatialGDK/Documentation/toc.md
Labels: size/S

#824 Internal docs
  .github/pull-request-template.md
  CHANGELOG.md
  SpatialGDK/Extras/internal-documentation/how-to-write-good-release-notes.md
  SpatialGDK/Extras/internal-documentation/release-process.md
Labels: size/XL

#832 Update CHANGELOG.md
  CHANGELOG.md
Labels: size/XS

#833 Fix editor crash when making LogSpatialSender Verbose
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
Labels: size/XS

#822 [UNR-963] Fix updating component interest and ACLs on possessing a different pawn
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialDispatcher.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialSender.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/Component.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/DynamicComponent.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialActorUtils.h
Labels: size/L

#828 UNR-1036: Fixing temperamental TSubclassOf<> property replication
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp
Labels: size/XS

#837 Doc: upgrade guide
  SpatialGDK/Documentation/content/upgrading.md
  SpatialGDK/Documentation/toc.md
Labels: docs, size/M

#839 Revert "Doc: upgrade guide"
  SpatialGDK/Documentation/content/upgrading.md
  SpatialGDK/Documentation/toc.md
Labels: size/M

#829 Docs - Template Cloud Deployment - Default to Single Worker Config
  SpatialGDK/Documentation/content/get-started/gdk-template.md
Labels: docs, size/XS

#840 Specify that you must use a fresh setup when testing a release.
  SpatialGDK/Extras/internal-documentation/release-process.md
Labels: size/S

#835 Feature/unr 1018 reconnect to deployment
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/EditorWorkerController.h
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h
  SpatialGDK/Source/SpatialGDK/SpatialGDK.Build.cs
Labels: size/M

#838 Docs - Adds Local and Cloud dev workflows docs, create Workflow section of TOC
  SpatialGDK/Documentation/content/cloud-dev-workflow.md
  SpatialGDK/Documentation/content/local-dev-workflow.md
  SpatialGDK/Documentation/toc.md
Labels: docs, size/M

#836 Docs - Add ShooterGame as a Reference in the Porting Guide
  SpatialGDK/Documentation/content/get-started/porting-unreal-project-to-gdk.md
Labels: docs, size/S

#834 Multithreaded SpatialWorkerConnection
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/OutgoingMessages.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SnapshotManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialOutputDevice.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/ConnectionConfig.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/OutgoingMessages.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/SpatialWorkerConnection.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialOutputDevice.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h
Labels: size/XXL

#844 Added known issue to known-issues doc
  SpatialGDK/Documentation/known-issues.md
Labels: size/XS

#845 Changed include and added destructor
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/OutgoingMessages.h
Labels: size/XS

#846 Add listen for spatial end event
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/EditorWorkerController.h
  SpatialGDK/Source/SpatialGDK/SpatialGDK.Build.cs
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorToolbar.h
Labels: size/S

#792 Rewrite multi-layer stage 1 (C API) as net driver dispatcher
  SpatialGDK/Documentation/content/non-unreal-server-worker-types.md
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialGameInstance.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialDispatcher.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialGameInstance.h
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/SpatialWorkerConnection.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialDispatcher.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/OpCallbackTemplate.h
Labels: size/XL

#825 Entity creation not affected by actor throttling
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h
Labels: size/M

#843 Bugfix/commandlet exit codes
  SpatialGDK/Source/SpatialGDKEditorCommandlet/Private/Commandlets/GenerateSchemaAndSnapshotsCommandlet.cpp
  SpatialGDK/Source/SpatialGDKEditorCommandlet/Private/Commandlets/GenerateSchemaAndSnapshotsCommandlet.h
  SpatialGDK/Source/SpatialGDKEditorCommandlet/Private/Commandlets/GenerateSchemaCommandlet.cpp
  SpatialGDK/Source/SpatialGDKEditorCommandlet/Private/Commandlets/GenerateSnapshotCommandlet.cpp
  SpatialGDK/Source/SpatialGDKEditorCommandlet/Private/Commandlets/GenerateSnapshotCommandlet.h
Labels: size/M

#800 Fully configurable auto-generated launch config for local deployments.
  SpatialGDK/Documentation/assets/screen-grabs/toolbar/multi-player-options.png
  SpatialGDK/Documentation/content/toolbars.md
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorSettings.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorToolbar.h
Labels: size/XL

#852 Made the server interest result type full snapshot result
  SpatialGDK/Source/SpatialGDK/Private/Utils/InterestFactory.cpp
Labels: size/XS

#851 Upgrade Guide
  SpatialGDK/Documentation/content/upgrading.md
  SpatialGDK/Documentation/toc.md
Labels: docs, size/M

#802 UNR-1218 New Incremental & Full Schema Generation
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialClassInfoManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/InterestFactory.cpp
  SpatialGDK/Source/SpatialGDK/Public/Utils/InterestFactory.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/SchemaDatabase.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SchemaGenerator.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SchemaGenerator.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/Utils/ComponentIdGenerator.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditor.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditor.h
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSchemaGenerator.h
  SpatialGDK/Source/SpatialGDKEditorCommandlet/Private/Commandlets/GenerateSchemaAndSnapshotsCommandlet.cpp
  SpatialGDK/Source/SpatialGDKEditorCommandlet/Private/Commandlets/GenerateSchemaCommandlet.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbarCommands.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorToolbar.h
  SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorToolbarCommands.h
Labels: size/XXL

#841 [UNR-795] Engine Versioning
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Public/Utils/EngineVersionCheck.h
  ci/unreal-engine.version
Labels: size/S

#849 Added Metrics: DynamicFPS and Load
  RequireSetup
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/Build/Build.cs
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialMetrics.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/OutgoingMessages.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/SpatialWorkerConnection.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialMetrics.h
Labels: size/L

#847 Update Visual Studio workloads installation details
  SpatialGDK/Documentation/content/get-started/dependencies.md
Labels: size/S

#854 fix links to markdown anchors
  SpatialGDK/Documentation/content/cloud-dev-workflow.md
  SpatialGDK/Documentation/content/get-started/gdk-template.md
Labels: size/XS

#856 Docs - Update roadmap links
  README.md
  SpatialGDK/Documentation/content/get-started/introduction.md
  SpatialGDK/Documentation/index.md
  SpatialGDK/Documentation/recommended-use.md
  SpatialGDK/Documentation/toc.md
Labels: docs, size/XS

#870 Update roadmap links
  README.md
  SpatialGDK/Documentation/content/cloud-dev-workflow.md
  SpatialGDK/Documentation/content/get-started/gdk-template.md
  SpatialGDK/Documentation/content/get-started/introduction.md
  SpatialGDK/Documentation/index.md
  SpatialGDK/Documentation/recommended-use.md
  SpatialGDK/Documentation/toc.md
Labels: size/XS

#869 Small multiserver tutorial fixes from DOC-913
  SpatialGDK/Documentation/content/get-started/tutorial.md
Labels: docs, size/S

#842 Docs/doc 850 get started info updates
  README.md
  SpatialGDK/Documentation/assets/set-up-template/template-two-client-inspector.png
  SpatialGDK/Documentation/assets/set-up-template/template-two-clients.png
  SpatialGDK/Documentation/content/dynamic-typebindings.md
  SpatialGDK/Documentation/content/get-started/build-unreal-fork.md
  SpatialGDK/Documentation/content/get-started/dependencies.md
  SpatialGDK/Documentation/content/get-started/gdk-template.md
  SpatialGDK/Documentation/content/get-started/tutorial.md
  SpatialGDK/Documentation/content/glossary.md
  SpatialGDK/Documentation/content/map-travel.md
  SpatialGDK/Documentation/content/non-unreal-server-worker-types.md
  SpatialGDK/Documentation/content/singleton-actors.md
  SpatialGDK/Documentation/content/spatialos-concepts/concepts.md
  SpatialGDK/Documentation/content/spatialos-concepts/generating-a-snapshot.md
  SpatialGDK/Documentation/content/spatialos-concepts/schema.md
  SpatialGDK/Documentation/content/toolbars.md
  SpatialGDK/Documentation/content/tutorials/multiserver-shooter/tutorial-multiserver-cloudtest.md
  SpatialGDK/Documentation/content/tutorials/multiserver-shooter/tutorial-multiserver-healthchanges.md
  SpatialGDK/Documentation/content/tutorials/multiserver-shooter/tutorial-multiserver-intro.md
  SpatialGDK/Documentation/content/tutorials/multiserver-shooter/tutorial-multiserver-localtest.md
  SpatialGDK/Documentation/content/tutorials/multiserver-shooter/tutorial-multiserver-setup.md
  SpatialGDK/Documentation/content/tutorials/tutorial-porting-guide.md
  SpatialGDK/Documentation/toc.md
Labels: docs, size/XXL

#857 Update known-issues.md
  SpatialGDK/Documentation/known-issues.md
Labels: size/XS

#872 Fix crash when loading SchemaDatabase with async loading suspended
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
Labels: size/XS

#858 Don't set authority on initial entity checkout
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
Labels: size/S

#871 Added log message for if the schema generation failed/succeed
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditor.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
Labels: size/M

#874 Merge 0.4.0-rc into master
  CHANGELOG.md
  README.md
  SpatialGDK/Documentation/assets/set-up-template/template-two-client-inspector.png
  SpatialGDK/Documentation/assets/set-up-template/template-two-clients.png
  SpatialGDK/Documentation/content/dynamic-typebindings.md
  SpatialGDK/Documentation/content/get-started/build-unreal-fork.md
  SpatialGDK/Documentation/content/get-started/dependencies.md
  SpatialGDK/Documentation/content/get-started/gdk-template.md
  SpatialGDK/Documentation/content/get-started/tutorial.md
  SpatialGDK/Documentation/content/glossary.md
  SpatialGDK/Documentation/content/map-travel.md
  SpatialGDK/Documentation/content/non-unreal-server-worker-types.md
  SpatialGDK/Documentation/content/singleton-actors.md
  SpatialGDK/Documentation/content/spatialos-concepts/concepts.md
  SpatialGDK/Documentation/content/spatialos-concepts/generating-a-snapshot.md
  SpatialGDK/Documentation/content/spatialos-concepts/schema.md
  SpatialGDK/Documentation/content/toolbars.md
  SpatialGDK/Documentation/content/tutorials/multiserver-shooter/tutorial-multiserver-cloudtest.md
  SpatialGDK/Documentation/content/tutorials/multiserver-shooter/tutorial-multiserver-healthchanges.md
  SpatialGDK/Documentation/content/tutorials/multiserver-shooter/tutorial-multiserver-intro.md
  SpatialGDK/Documentation/content/tutorials/multiserver-shooter/tutorial-multiserver-localtest.md
  SpatialGDK/Documentation/content/tutorials/multiserver-shooter/tutorial-multiserver-setup.md
  SpatialGDK/Documentation/content/tutorials/tutorial-porting-guide.md
  SpatialGDK/Documentation/toc.md
  SpatialGDK/Extras/internal-documentation/release-process.md
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
Labels: size/XXL

#878 Docs - Add back schema and snapshot generation to shooter tutorial
  SpatialGDK/Documentation/content/tutorials/multiserver-shooter/tutorial-multiserver-setup.md
Labels: docs, size/XS

#868 New Unreal features support and known issues pages
  SpatialGDK/Documentation/content/whatsnew.md
  SpatialGDK/Documentation/features.md
  SpatialGDK/Documentation/known-issues.md
  SpatialGDK/Documentation/toc.md
  SpatialGDK/Documentation/unreal-features-support.md
Labels: docs, size/XL

#882 Call OnConnectedToSpatialOS directly rather than binding to a delegate
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
Labels: size/XS

#881 UNR-1312 Fix schema commandlet crash
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditor.cpp
Labels: size/S

#883 Upgraded to version 13.7.1
  SpatialGDK/Extras/core-sdk.version
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp
Labels: size/XS

#886 Merge 0.4.0 rc into master
  SpatialGDK/Documentation/content/tutorials/multiserver-shooter/tutorial-multiserver-setup.md
  SpatialGDK/Documentation/content/whatsnew.md
  SpatialGDK/Documentation/features.md
  SpatialGDK/Documentation/known-issues.md
  SpatialGDK/Documentation/toc.md
  SpatialGDK/Documentation/unreal-features-support.md
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditor.cpp
Labels: size/XL

#887 Stopped trying to resolve dirty blueprints when running from a comman…
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditor.cpp
Labels: size/XS

#853 Docs - new "Technical overview" section
  SpatialGDK/Documentation/assets/screen-grabs/game-architecture.png
  SpatialGDK/Documentation/assets/screen-grabs/moving-across-boundaries.gif
  SpatialGDK/Documentation/assets/screen-grabs/networking-switch.png
  SpatialGDK/Documentation/assets/screen-grabs/shooting-across-boundaries.png
  SpatialGDK/Documentation/content/technical-overview/gdk-concepts.md
  SpatialGDK/Documentation/content/technical-overview/gdk-principles.md
  SpatialGDK/Documentation/content/technical-overview/how-the-gdk-fits-in.md
  SpatialGDK/Documentation/toc.md
Labels: docs, size/L

#889 Update multi layer stage 1 rewrite docs
  SpatialGDK/Documentation/content/non-unreal-server-worker-types.md
Labels: size/S

#876 [UNR-1303] Rename namespace improbable to SpatialGDK
  SpatialGDK/Documentation/content/non-unreal-server-worker-types.md
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialFastArrayNetSerialize.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetBitReader.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/EditorWorkerController.h
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/OutgoingMessages.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/GlobalStateManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SnapshotManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialClassInfoManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialPlayerSpawner.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialStaticComponentView.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentFactory.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentReader.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/EntityPool.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/InterestFactory.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/SchemaUtils.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialMetrics.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialFastArrayNetSerialize.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/OutgoingMessages.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/SpatialWorkerConnection.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialStaticComponentView.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/Component.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/DynamicComponent.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/Heartbeat.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/Interest.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/Singleton.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/SpawnData.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/StandardLibrary.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/UnrealMetadata.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/UnrealObjectRef.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/ComponentFactory.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/ComponentReader.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/InterestFactory.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/RepLayoutUtils.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/SchemaOption.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/SchemaUtils.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialActorUtils.h
  SpatialGDK/Source/SpatialGDK/SpatialGDK.Build.cs
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/TypeStructure.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/Utils/DataTypeUtilities.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/Utils/DataTypeUtilities.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SnapshotGenerator/SpatialGDKEditorSnapshotGenerator.cpp
Labels: size/XL

#893 Remove iterate from worker build
  RequireSetup
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/Build/Build.cs
Labels: size/XS

#896 Merge 0.4.0-rc into master
  CHANGELOG.md
  RequireSetup
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/Build/Build.cs
  SpatialGDK/Documentation/assets/screen-grabs/game-architecture.png
  SpatialGDK/Documentation/assets/screen-grabs/moving-across-boundaries.gif
  SpatialGDK/Documentation/assets/screen-grabs/networking-switch.png
  SpatialGDK/Documentation/assets/screen-grabs/shooting-across-boundaries.png
  SpatialGDK/Documentation/content/technical-overview/gdk-concepts.md
  SpatialGDK/Documentation/content/technical-overview/gdk-principles.md
  SpatialGDK/Documentation/content/technical-overview/how-the-gdk-fits-in.md
  SpatialGDK/Documentation/toc.md
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditor.cpp
Labels: size/L

#892 Update release-process.md
  SpatialGDK/Extras/internal-documentation/release-process.md
Labels: size/XS
