Repository spatialos/UnrealGDK, pull requests merged in 2019-07, with the labels that each got.

#1001 Bugfix missing engine association in registry
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/Build/Build.cs
Labels: size/XS

#994 Docs - Add info about how to disable timeouts when debugging
  SpatialGDK/Documentation/content/get-started/example-project/exampleproject-local-deployment.md
  SpatialGDK/Documentation/content/get-started/gdk-template.md
  SpatialGDK/Documentation/content/troubleshooting.md
Labels: docs

#992 Docs - Update the schema generation docs
  SpatialGDK/Documentation/content/glossary.md
  SpatialGDK/Documentation/content/how-to-use-schema.md
Labels: docs, size/M

#879 Non-unreal server worker types [stage 2]
  CHANGELOG.md
  Setup.bat
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/CodeGenerator/Base/Bundle.cs
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/CodeGenerator/Base/ICodeGenerator.cs
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/CodeGenerator/Base/Model.cs
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/CodeGenerator/Base/SchemaBundleLoader.cs
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/CodeGenerator/Base/Text.cs
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/CodeGenerator/Base/TypeDescription.cs
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/CodeGenerator/CodeGenerator.csproj
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/CodeGenerator/Program.cs
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/CodeGenerator/README.md
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/CodeGenerator/Unreal/EnumGenerator.cs
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/CodeGenerator/Unreal/HeaderGenerator.cs
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/CodeGenerator/Unreal/HelperFunctions.cs
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/CodeGenerator/Unreal/InterfaceGenerator.cs
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/CodeGenerator/Unreal/MapEquals.cs
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/CodeGenerator/Unreal/Serialization.cs
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/CodeGenerator/Unreal/SourceGenerator.cs
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/CodeGenerator/Unreal/Types.cs
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/CodeGenerator/Unreal/UnrealGenerator.cs
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/Improbable.Unreal.Scripts.sln
  SpatialGDK/Build/Scripts/ExternalSchemaCodegen.bat
  ci/setup-and-build-gdk.ps1
  ci/setup-gdk.ps1
Labels: size/XXL

#932 Scale Testing with Simulated Players
  Setup.bat
  Setup.sh
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/Build/Build.cs
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/Common/LinuxScripts.cs
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/DeploymentLauncher/DeploymentLauncher.cs
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/DeploymentLauncher/DeploymentLauncher.csproj
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/Improbable.Unreal.Scripts.sln
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/WorkerCoordinator/Authentication.cs
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/WorkerCoordinator/BuildTargets.targets
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/WorkerCoordinator/CoordinatorConnection.cs
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/WorkerCoordinator/Logger.cs
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/WorkerCoordinator/SpatialConfig/cloud_launch_sim_player_deployment.json
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/WorkerCoordinator/SpatialConfig/spatialos.SimulatedPlayerCoordinator.worker.json
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/WorkerCoordinator/WorkerCoordinator.cs
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/WorkerCoordinator/WorkerCoordinator.csproj
  SpatialGDK/Build/Scripts/DeploymentLauncher.bat
  SpatialGDK/Extras/schema/spawner.schema
  SpatialGDK/Resources/Cloud.png
  SpatialGDK/Resources/Cloud@0.5x.png
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialPlayerSpawner.cpp
  SpatialGDK/Source/SpatialGDK/Private/SimulatedPlayers/SimPlayerBPFunctionLibrary.cpp
  SpatialGDK/Source/SpatialGDK/Public/SimulatedPlayers/SimPlayerBPFunctionLibrary.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/EngineVersionCheck.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditor.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorCloudLauncher.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorSettings.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditor.h
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorCloudLauncher.h
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorModule.h
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h
  SpatialGDK/Source/SpatialGDKEditor/SpatialGDKEditor.Build.cs
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbarCommands.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbarStyle.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKSimulatedPlayerDeployment.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorToolbar.h
  SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorToolbarCommands.h
  SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKSimulatedPlayerDeployment.h
  SpatialGDK/Source/SpatialGDKEditorToolbar/SpatialGDKEditorToolbar.Build.cs
  SpatialGDK/SpatialGDK.uplugin
  ci/setup-gdk.ps1
  ci/unreal-engine.version
Labels: simplayers, size/XXL

#988 Feature/unr 1454 config receptionist
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/ConnectionConfig.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h
Labels: size/XS

#1139 Bugfix - Fix up Fast Local Restart issues
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorToolbar.h
  SpatialGDK/Source/SpatialGDKServices/Private/LocalDeploymentManager.cpp
Labels: jira/no-ticket, size/L

#1147 [UNR-1688] - Update broken link for the building workers
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKSimulatedPlayerDeployment.cpp
Labels: jira/UNR, size/XS

#1146 UNR-1692 Cross-server RPCs should now be properly handled.
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
Labels: jira/UNR, size/S

#1151 Bugfix: [UNR-1693] Do not Pack RPCs that are destined for a different worker type
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/ActorGroupManager.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialSender.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/ActorGroupManager.h
Labels: jira/UNR, size/M

#1153 UNR-1710 Fixed a crash that may happen if rpcs are sent to tornoff actor
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
Labels: jira/UNR, size/XS

#1150 UNR-1677 : Preserve URL options on ClientTravel
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialPlayerSpawner.cpp
Labels: jira/UNR, size/S

#1155 Don't kick off processes in commandlets
  SpatialGDK/Source/SpatialGDKServices/Private/LocalDeploymentManager.cpp
Labels: jira/no-ticket, size/M

#1154 UNR-1718 Only send client and multicast RPCs on entity creation
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
Labels: jira/UNR, size/S

#1159 UNR-1705 / UNR-1666 - Correctly determine if we have created a new replicator in 4.20
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp
Labels: jira/UNR, size/XS

#1158 Bugfix/unr 1694 cleanup packing references
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialSender.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h
Labels: jira/no-ticket, size/M

#1162 Revert "UNR-1710 Fixed a crash that may happen if rpcs are sent to tornoff actor"
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
Labels: jira/UNR, size/XS

#1160 Clean up UPROPERTY categories for the ActorInterestComponent
  SpatialGDK/Source/SpatialGDK/Private/Utils/InterestFactory.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/Components/ActorInterestComponent.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialInterestConstraints.h
Labels: jira/no-ticket, size/M

#1163 Docs - revert clang install to wiki page
  SpatialGDK/Documentation/content/get-started/build-unreal-fork.md
Labels: jira/no-ticket, size/XS

#1165 Docs/DOC-1126 porting guide update
  SpatialGDK/Documentation/assets/porting-guide/porting-solution-config.png
  SpatialGDK/Documentation/assets/porting-guide/spatial-game-instance-reparent.png
  SpatialGDK/Documentation/content/tutorials/porting-guide/tutorial-portingguide-build.md
  SpatialGDK/Documentation/content/tutorials/porting-guide/tutorial-portingguide-deployment.md
  SpatialGDK/Documentation/content/tutorials/porting-guide/tutorial-portingguide-logs.md
  SpatialGDK/Documentation/content/tutorials/porting-guide/tutorial-portingguide-setup.md
  SpatialGDK/Documentation/content/tutorials/tutorial-porting-guide.md
  SpatialGDK/Documentation/toc.md
Labels: jira/DOC, size/XL

#1167 Docs/DOC-1126 porting guide update (#1165)
  SpatialGDK/Documentation/assets/porting-guide/porting-solution-config.png
  SpatialGDK/Documentation/assets/porting-guide/spatial-game-instance-reparent.png
  SpatialGDK/Documentation/content/tutorials/porting-guide/tutorial-portingguide-build.md
  SpatialGDK/Documentation/content/tutorials/porting-guide/tutorial-portingguide-deployment.md
  SpatialGDK/Documentation/content/tutorials/porting-guide/tutorial-portingguide-logs.md
  SpatialGDK/Documentation/content/tutorials/porting-guide/tutorial-portingguide-setup.md
  SpatialGDK/Documentation/content/tutorials/tutorial-porting-guide.md
  SpatialGDK/Documentation/toc.md
Labels: jira/DOC, size/XL

#1169 Docs/DOC-1128 template guide update
  SpatialGDK/Documentation/content/cloud-deployment-workflow.md
  SpatialGDK/Documentation/content/get-started/build-unreal-fork.md
  SpatialGDK/Documentation/content/get-started/example-project/exampleproject-intro.md
  SpatialGDK/Documentation/content/get-started/example-project/exampleproject-local-deployment.md
  SpatialGDK/Documentation/content/get-started/example-project/exampleproject-play.md
  SpatialGDK/Documentation/content/get-started/gdk-template.md
  SpatialGDK/Documentation/content/get-started/starter-template/get-started-template-cloud.md
  SpatialGDK/Documentation/content/get-started/starter-template/get-started-template-intro.md
  SpatialGDK/Documentation/content/get-started/starter-template/get-started-template-local.md
  SpatialGDK/Documentation/content/get-started/starter-template/get-started-template-play.md
  SpatialGDK/Documentation/content/get-started/starter-template/get-started-template-setup.md
  SpatialGDK/Documentation/content/local-deployment-workflow.md
  SpatialGDK/Documentation/content/project-setup.md
  SpatialGDK/Documentation/content/toolbars.md
  SpatialGDK/Documentation/content/troubleshooting.md
  SpatialGDK/Documentation/content/tutorials/multiserver-shooter/tutorial-multiserver-cloudtest.md
  SpatialGDK/Documentation/content/tutorials/porting-guide/tutorial-portingguide-deployment.md
  SpatialGDK/Documentation/content/tutorials/tutorial-porting-guide.md
  SpatialGDK/Documentation/toc.md
Labels: jira/DOC, size/XXL

#1114 added external schema codegen tool documentation
  SpatialGDK/Documentation/content/get-started/example-project/exampleproject-local-deployment.md
  SpatialGDK/Documentation/content/helper-scripts.md
  SpatialGDK/Documentation/content/non-unreal-server-worker-types.md
Labels: docs, jira/no-ticket, size/L

#1171 SpatialOS typo
  SpatialGDK/Documentation/content/get-started/example-project/exampleproject-cloud-deployment.md
Labels: jira/no-ticket, size/XS

#1166 Add max net cull distance
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/InterestFactory.cpp
  SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h
Labels: jira/no-ticket, size/S

#1164 Add IsReplayConnection func
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetConnection.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetConnection.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/EngineVersionCheck.h
  ci/unreal-engine.version
Labels: jira/no-ticket, size/S

#1174 UNR-1710 Disabled replication for tornoff Actor
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
Labels: jira/UNR, size/XS

#1178 UNR-1747: fix build script for local launch
  CHANGELOG.md
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/Build/Build.cs
Labels: jira/UNR, size/XS

#1179 UNR-1757 Skip actor itself when iterating ReplicationMap when creating entity
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
Labels: jira/UNR, size/XS

#1172 UNR-1754 Auto deploy config
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorSettings.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
Labels: jira/UNR, size/S

#1170 Fixing missing error message when SchemaDatabase missing
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
Labels: jira/no-ticket, size/XS

#1181 Pin SpatialD
  SpatialGDK/Source/SpatialGDKServices/Private/LocalDeploymentManager.cpp
Labels: jira/no-ticket, size/XS

#1173 Bugfix/unr 1705 crash on dynamic component re-add
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
Labels: jira/no-ticket, size/S

#1175 DOC-1160 Add Actor readiness doc
  SpatialGDK/Documentation/content/actor-readiness.md
  SpatialGDK/Documentation/toc.md
Labels: jira/DOC, size/M

#1182 UNR-1606 Added tracking of the RPCs on entity creation
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
Labels: jira/UNR, size/XS

#1183 Update pull-request-template.md
  .github/pull-request-template.md
Labels: jira/no-ticket, size/XS

#1184 UNR-1606 Added tracking of the RPCs on entity creation (#1182)
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
Labels: jira/UNR, size/XS

#1186 Add Actor readiness docs to docs-next
  SpatialGDK/Documentation/content/actor-readiness.md
  SpatialGDK/Documentation/toc.md
Labels: jira/no-ticket, size/M

#1187 Resolve stably named subobjects correctly
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp
Labels: jira/no-ticket, size/XS

#1194 Fix native server launch script
  RequireSetup
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/Common/LinuxScripts.cs
Labels: jira/no-ticket, size/XS

#1177 UNR-1735
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/CodeGenerator/Unreal/HeaderGenerator.cs
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/CodeGenerator/Unreal/InterfaceGenerator.cs
Labels: jira/UNR, size/XS

#1196 UNR-1772 - Bugfix: Log errored blueprints before running GC
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditor.cpp
Labels: jira/UNR, size/S

#1190 DOC-1172 Versioning scheme page
  SpatialGDK/Documentation/content/pricing-and-support/versioning-scheme.md
  SpatialGDK/Documentation/content/upgrading.md
  SpatialGDK/Documentation/toc.md
Labels: docs, jira/DOC, size/M

#1197 DOC-1230 Suggested GDK & Example project docs changes
  SpatialGDK/Documentation/content/get-started/dependencies.md
  SpatialGDK/Documentation/content/get-started/example-project/exampleproject-cloud-deployment.md
  SpatialGDK/Documentation/content/get-started/example-project/exampleproject-intro.md
  SpatialGDK/Documentation/content/get-started/example-project/exampleproject-local-deployment.md
  SpatialGDK/Documentation/content/get-started/example-project/exampleproject-setup.md
  SpatialGDK/Documentation/content/get-started/introduction.md
Labels: jira/DOC, size/M

#1192 UNR-1673 - Update workflow diagrams
  SpatialGDK/Documentation/assets/toolbar/deploy.png
  SpatialGDK/Documentation/content/cloud-deployment-workflow.md
  SpatialGDK/Documentation/content/local-deployment-workflow.md
Labels: docs, jira/UNR, size/S

#1193 DOC-1127 - Setup Automation Docs
  SpatialGDK/Documentation/content/cloud-deployment-workflow.md
  SpatialGDK/Documentation/content/directory-structure.md
  SpatialGDK/Documentation/content/get-started/build-unreal-fork.md
  SpatialGDK/Documentation/content/get-started/dependencies.md
  SpatialGDK/Documentation/content/get-started/example-project/exampleproject-cloud-deployment.md
  SpatialGDK/Documentation/content/get-started/example-project/exampleproject-intro.md
  SpatialGDK/Documentation/content/get-started/example-project/exampleproject-local-deployment.md
  SpatialGDK/Documentation/content/get-started/example-project/exampleproject-manual-setup.md
  SpatialGDK/Documentation/content/get-started/example-project/exampleproject-play.md
  SpatialGDK/Documentation/content/get-started/example-project/exampleproject-setup.md
  SpatialGDK/Documentation/content/get-started/gdk-template.md
  SpatialGDK/Documentation/content/get-started/introduction.md
  SpatialGDK/Documentation/content/get-started/starter-template/get-started-template-cloud.md
  SpatialGDK/Documentation/content/get-started/starter-template/get-started-template-intro.md
  SpatialGDK/Documentation/content/get-started/starter-template/get-started-template-local.md
  SpatialGDK/Documentation/content/get-started/starter-template/get-started-template-play.md
  SpatialGDK/Documentation/content/get-started/starter-template/get-started-template-setup.md
  SpatialGDK/Documentation/content/local-deployment-workflow.md
  SpatialGDK/Documentation/content/manual-engine-build.md
  SpatialGDK/Documentation/content/project-setup.md
  SpatialGDK/Documentation/content/toolbars.md
  SpatialGDK/Documentation/content/troubleshooting.md
  SpatialGDK/Documentation/content/tutorials/multiserver-shooter/tutorial-multiserver-cloudtest.md
  SpatialGDK/Documentation/content/tutorials/multiserver-shooter/tutorial-multiserver-setup.md
  SpatialGDK/Documentation/content/tutorials/porting-guide/tutorial-portingguide-deployment.md
  SpatialGDK/Documentation/content/tutorials/tutorial-porting-guide.md
  SpatialGDK/Documentation/index.md
  SpatialGDK/Documentation/toc.md
Labels: docs, jira/DOC, size/XXL

#1185 Schema gen with no changes should no longer generate new ComponentIds
  SpatialGDK/Source/SpatialGDK/Public/Utils/SchemaDatabase.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SchemaGenerator.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SchemaGenerator.h
Labels: jira/no-ticket, size/M

#1200 Editor settings typo
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h
Labels: jira/no-ticket, size/XS

#1195 UNR-1773 - Bugfix: Don't always wait for deployment
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorToolbar.h
  SpatialGDK/Source/SpatialGDKServices/Private/LocalDeploymentManager.cpp
  SpatialGDK/Source/SpatialGDKServices/Public/LocalDeploymentManager.h
Labels: jira/UNR, size/M

#1198 Add reconnect a worker known issue
  CHANGELOG.md
Labels: jira/no-ticket, size/XS

#1205 Working link for docs assembly upload instruction in Deploy window
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKSimulatedPlayerDeployment.cpp
Labels: jira/no-ticket, size/XS

#1204 DOC-1226 - Explain how to use Buildproject.bat for Shipping builds in Example Project guide
  SpatialGDK/Documentation/content/cloud-deployment-workflow.md
  SpatialGDK/Documentation/content/get-started/example-project/exampleproject-cloud-deployment.md
  SpatialGDK/Documentation/content/get-started/starter-template/get-started-template-cloud.md
  SpatialGDK/Documentation/content/helper-scripts.md
Labels: jira/DOC, size/M

#1191 Docs - Use new lightbox macro for expandable images
  SpatialGDK/Documentation/content/get-started/example-project/exampleproject-cloud-deployment.md
  SpatialGDK/Documentation/content/get-started/example-project/exampleproject-setup.md
  SpatialGDK/Documentation/content/get-started/gdk-template.md
  SpatialGDK/Documentation/content/technical-overview/gdk-concepts.md
  SpatialGDK/Documentation/content/technical-overview/how-the-gdk-fits-in.md
  SpatialGDK/Documentation/content/tutorials/deployment-manager/tutorial-deploymentmgr-authentication.md
  SpatialGDK/Documentation/content/tutorials/deployment-manager/tutorial-deploymentmgr-intro.md
  SpatialGDK/Documentation/content/tutorials/deployment-manager/tutorial-deploymentmgr-launch.md
  SpatialGDK/Documentation/content/tutorials/deployment-manager/tutorial-deploymentmgr-play.md
Labels: docs, jira/no-ticket, size/XL

#1203 Docs - update local & cloud guides to reflect new workflows (fast local restart, deploy button)
  SpatialGDK/Documentation/assets/example-project/first-client-launch.png
  SpatialGDK/Documentation/assets/toolbar/deploy-settings.png
  SpatialGDK/Documentation/assets/toolbar/stop-button-native.png
  SpatialGDK/Documentation/content/get-started/example-project/exampleproject-cloud-deployment.md
  SpatialGDK/Documentation/content/get-started/example-project/exampleproject-local-deployment.md
  SpatialGDK/Documentation/content/get-started/starter-template/get-started-template-cloud.md
  SpatialGDK/Documentation/content/get-started/starter-template/get-started-template-local.md
  SpatialGDK/Documentation/content/get-started/starter-template/get-started-template-setup.md
Labels: docs, jira/no-ticket, size/L

#1201 DOC-1157 Docs: game client interest management
  SpatialGDK/Documentation/assets/screen-grabs/authority-areas.png
  SpatialGDK/Documentation/assets/screen-grabs/game-client-interest-management/add-component.png
  SpatialGDK/Documentation/assets/screen-grabs/game-client-interest-management/net-cull-distance-diagram.png
  SpatialGDK/Documentation/assets/screen-grabs/game-client-interest-management/replication-section.png
  SpatialGDK/Documentation/assets/screen-grabs/game-client-interest-management/set-up-interest.png
  SpatialGDK/Documentation/assets/screen-grabs/interest-areas.gif
  SpatialGDK/Documentation/content/actor-handover.md
  SpatialGDK/Documentation/content/actor-readiness.md
  SpatialGDK/Documentation/content/authority.md
  SpatialGDK/Documentation/content/cross-server-rpcs.md
  SpatialGDK/Documentation/content/game-client-interest-management.md
  SpatialGDK/Documentation/content/get-started/example-project/exampleproject-cloud-deployment.md
  SpatialGDK/Documentation/content/get-started/gdk-template.md
  SpatialGDK/Documentation/content/glossary.md
  SpatialGDK/Documentation/content/helper-scripts.md
  SpatialGDK/Documentation/content/how-to-use-snapshots.md
  SpatialGDK/Documentation/content/singleton-actors.md
  SpatialGDK/Documentation/content/spatial-type.md
  SpatialGDK/Documentation/content/spatialos-concepts/authority-and-interest.md
  SpatialGDK/Documentation/content/spatialos-concepts/schema-and-snapshots.md
  SpatialGDK/Documentation/content/spatialos-concepts/what-is-spatialos.md
  SpatialGDK/Documentation/content/spatialos-concepts/workers-and-zoning.md
  SpatialGDK/Documentation/content/technical-overview/gdk-concepts.md
  SpatialGDK/Documentation/content/tutorials/multiserver-shooter/tutorial-multiserver-setup.md
  SpatialGDK/Documentation/toc.md
Labels: jira/DOC, size/XXL

#1206 UNR-1672 - Docs - Update features support page & remove GAS workarounds
  SpatialGDK/Documentation/content/ability-system.md
  SpatialGDK/Documentation/toc.md
  SpatialGDK/Documentation/unreal-features-support.md
Labels: docs, jira/UNR, size/M

#1207 UNR-1758 Removed SnapshotPath setting to prevent it being checked in
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorSettings.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h
Labels: jira/UNR, size/XS

#1209 Lots of minor fixes
  CHANGELOG.md
  SpatialGDK/Documentation/content/game-client-interest-management.md
  SpatialGDK/Documentation/content/get-started/example-project/exampleproject-local-deployment.md
  SpatialGDK/Documentation/content/get-started/gdk-template.md
  SpatialGDK/Documentation/content/get-started/starter-template/get-started-template-local.md
  SpatialGDK/Documentation/content/glossary.md
  SpatialGDK/Documentation/content/map-travel.md
  SpatialGDK/Documentation/content/spatialos-concepts/schema-and-snapshots.md
  SpatialGDK/Documentation/content/spatialos-concepts/world-entities-components.md
  SpatialGDK/Documentation/content/technical-overview/gdk-concepts.md
  SpatialGDK/Documentation/content/troubleshooting.md
  SpatialGDK/Documentation/content/tutorials/porting-guide/tutorial-portingguide-deployment.md
Labels: jira/no-ticket, size/M

#1211 Removes an incorrect statement that we support VS2019
  SpatialGDK/Documentation/content/get-started/dependencies.md
Labels: jira/no-ticket, size/XS

#1210 Docs - Fully remove clone step from GDK template setup
  SpatialGDK/Documentation/content/get-started/starter-template/get-started-template-setup.md
Labels: jira/no-ticket, size/XS

#1212 Fixes for various netguid resolution issues
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialDispatcher.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h
Labels: jira/no-ticket, size/S

#1213 Update CHANGELOG.md
  CHANGELOG.md
Labels: jira/no-ticket, size/XS

#1216 Remove check
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp
Labels: jira/no-ticket, size/XS

#1208 UNR-1792 Prevent crash on dynamic components
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
Labels: jira/UNR, size/XS

#1214 Docs - Explain local workflow better
  SpatialGDK/Documentation/content/cloud-deployment-workflow.md
  SpatialGDK/Documentation/content/get-started/example-project/exampleproject-local-deployment.md
  SpatialGDK/Documentation/content/get-started/starter-template/get-started-template-local.md
  SpatialGDK/Documentation/content/local-deployment-workflow.md
Labels: docs, jira/no-ticket, size/M

#1219 Add offloading content across Unreal docs
  SpatialGDK/Documentation/assets/configure-actor-groups.png
  SpatialGDK/Documentation/assets/offloading-apis/get-actor-group-for-actor.png
  SpatialGDK/Documentation/assets/offloading-apis/get-actor-group-for-class.png
  SpatialGDK/Documentation/assets/offloading-apis/is-actor-group-owner-for-actor.png
  SpatialGDK/Documentation/assets/offloading-apis/is-actor-group-owner-for-class.png
  SpatialGDK/Documentation/assets/offloading-apis/is-actor-group-owner.png
  SpatialGDK/Documentation/assets/offloading-diagram.png
  SpatialGDK/Documentation/assets/offloading-project/actor-groups.png
  SpatialGDK/Documentation/assets/offloading-project/enable-offloading.png
  SpatialGDK/Documentation/assets/offloading-project/launch-configuration.png
  SpatialGDK/Documentation/assets/offloading-project/turrets.png
  SpatialGDK/Documentation/assets/snapshot-validation.png
  SpatialGDK/Documentation/assets/specify-launch-configuration.png
  SpatialGDK/Documentation/content/apis-and-helper-scripts/actor-group-ownership-helpers.md
  SpatialGDK/Documentation/content/apis-and-helper-scripts/helper-scripts.md
  SpatialGDK/Documentation/content/cloud-deployment-workflow.md
  SpatialGDK/Documentation/content/get-started/example-project/exampleproject-cloud-deployment.md
  SpatialGDK/Documentation/content/get-started/starter-template/get-started-template-cloud.md
  SpatialGDK/Documentation/content/glossary.md
  SpatialGDK/Documentation/content/technical-overview/gdk-concepts.md
  SpatialGDK/Documentation/content/tutorials/offloading-tutorial/offloading-gameplay-changes.md
  SpatialGDK/Documentation/content/tutorials/offloading-tutorial/offloading-intro.md
  SpatialGDK/Documentation/content/tutorials/offloading-tutorial/offloading-setup.md
  SpatialGDK/Documentation/content/workers/non-unreal-server-worker-types.md
  SpatialGDK/Documentation/content/workers/offloading-concept.md
  SpatialGDK/Documentation/content/workers/set-up-offloading.md
  SpatialGDK/Documentation/toc.md
Labels: jira/no-ticket, size/XL

#1217 Any object that can be replicated by the GDK needs to have an Actor somewhere in the outer chain.
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialClassInfoManager.cpp
Labels: jira/no-ticket, size/XS

#1202 MacOS fixes
  Setup.sh
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/Build/Build.csproj
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/CodeGenerator/CodeGenerator.csproj
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/Common/Common.csproj
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/DeploymentLauncher/DeploymentLauncher.csproj
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/Linter/Linter.csproj
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/Mac/Build/Build.csproj
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/Mac/Common/Common.csproj
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/Mac/Improbable.Unreal.Scripts.sln
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/Mac/Linter/Linter.csproj
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/WorkerCoordinator/WorkerCoordinator.csproj
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/WriteLinuxScript/WriteLinuxScript.csproj
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/ConnectionConfig.h
  SpatialGDK/Source/SpatialGDKServices/Private/LocalDeploymentManager.cpp
Labels: jira/no-ticket, size/L

#1221 Editor settings UI tooltips
  SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKSimulatedPlayerDeployment.cpp
Labels: jira/no-ticket, size/M

#1220 Update to latest 422 engine rc
  ci/unreal-engine.version
Labels: jira/no-ticket, size/XS

#1168 DOC-1161 Editor settings docs
  SpatialGDK/Documentation/assets/editor-settings/runtime-settings.png
  SpatialGDK/Documentation/assets/editor-settings/spatialos-settings.png
  SpatialGDK/Documentation/assets/screen-grabs/toolbar/toolbar-settings.png
  SpatialGDK/Documentation/content/actor-handover.md
  SpatialGDK/Documentation/content/directory-structure.md
  SpatialGDK/Documentation/content/get-started/example-project/exampleproject-cloud-deployment.md
  SpatialGDK/Documentation/content/get-started/example-project/exampleproject-local-deployment.md
  SpatialGDK/Documentation/content/get-started/gdk-template.md
  SpatialGDK/Documentation/content/glossary.md
  SpatialGDK/Documentation/content/how-to-use-schema.md
  SpatialGDK/Documentation/content/how-to-use-snapshots.md
  SpatialGDK/Documentation/content/tutorials/porting-guide/tutorial-portingguide-deployment.md
  SpatialGDK/Documentation/content/unreal-editor-interface/editor-settings.md
  SpatialGDK/Documentation/content/unreal-editor-interface/runtime-settings.md
  SpatialGDK/Documentation/content/unreal-editor-interface/toolbars.md
  SpatialGDK/Documentation/toc.md
Labels: docs, jira/DOC, size/L

#1223 DOC-1092 and DOC-1089
  SpatialGDK/Documentation/assets/workflows/vs-command-arguments.png
  SpatialGDK/Documentation/content/glossary.md
  SpatialGDK/Documentation/content/workflows/autostart-server-workers.md
  SpatialGDK/Documentation/content/workflows/debug-from-vs-overview.md
  SpatialGDK/Documentation/content/workflows/set-up-vs.md
  SpatialGDK/Documentation/toc.md
Labels: jira/DOC, size/L

#1222 Bugfix/unr 1806 fix subobject schema name clash
  SpatialGDK/Source/SpatialGDK/Public/Utils/SchemaDatabase.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SchemaGenerator.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp
Labels: jira/no-ticket, size/M

#1229 Add null check for channel
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp
Labels: jira/no-ticket, size/XS

#1225 UNR-1781: add documentation to how to exclude directories from schema generation.
  SpatialGDK/Documentation/content/get-started/example-project/exampleproject-local-deployment.md
  SpatialGDK/Documentation/content/get-started/gdk-template.md
  SpatialGDK/Documentation/content/get-started/starter-template/get-started-template-local.md
  SpatialGDK/Documentation/content/how-to-use-schema.md
  SpatialGDK/Documentation/content/tutorials/porting-guide/tutorial-portingguide-deployment.md
Labels: jira/UNR, size/S

#1232 Docs - Database Sync Worker Tutorial
  SpatialGDK/Documentation/assets/dbsync/dbsync-kd-exampleproject.gif
  SpatialGDK/Documentation/assets/dbsync/editor-settings-generate-launch-config.png
  SpatialGDK/Documentation/assets/dbsync/kd-counts-0-0.png
  SpatialGDK/Documentation/assets/dbsync/kd-counts-2-0.png
  SpatialGDK/Documentation/assets/dbsync/kd-populated.png
  SpatialGDK/Documentation/content/get-started/build-unreal-fork.md
  SpatialGDK/Documentation/content/get-started/dependencies.md
  SpatialGDK/Documentation/content/get-started/example-project/exampleproject-cloud-deployment.md
  SpatialGDK/Documentation/content/get-started/example-project/exampleproject-intro.md
  SpatialGDK/Documentation/content/get-started/example-project/exampleproject-local-deployment.md
  SpatialGDK/Documentation/content/get-started/example-project/exampleproject-manual-setup.md
  SpatialGDK/Documentation/content/get-started/example-project/exampleproject-setup.md
  SpatialGDK/Documentation/content/get-started/starter-template/get-started-template-cloud.md
  SpatialGDK/Documentation/content/get-started/starter-template/get-started-template-intro.md
  SpatialGDK/Documentation/content/get-started/starter-template/get-started-template-local.md
  SpatialGDK/Documentation/content/get-started/starter-template/get-started-template-setup-manual.md
  SpatialGDK/Documentation/content/get-started/starter-template/get-started-template-setup.md
  SpatialGDK/Documentation/content/tutorials/dbsync/tutorial-dbsync-communicating.md
  SpatialGDK/Documentation/content/tutorials/dbsync/tutorial-dbsync-intro.md
  SpatialGDK/Documentation/content/tutorials/dbsync/tutorial-dbsync-setup.md
  SpatialGDK/Documentation/content/tutorials/dbsync/tutorial-dbsync-syncing.md
  SpatialGDK/Documentation/content/tutorials/dbsync/tutorial-dbsync-testing.md
  SpatialGDK/Documentation/content/tutorials/deployment-manager/tutorial-deploymentmgr-intro.md
  SpatialGDK/Documentation/content/tutorials/multiserver-shooter/tutorial-multiserver-healthchanges.md
  SpatialGDK/Documentation/content/tutorials/multiserver-shooter/tutorial-multiserver-intro.md
  SpatialGDK/Documentation/content/tutorials/multiserver-shooter/tutorial-multiserver-localtest.md
  SpatialGDK/Documentation/content/tutorials/multiserver-shooter/tutorial-multiserver-setup.md
  SpatialGDK/Documentation/content/tutorials/porting-guide/tutorial-portingguide-build.md
  SpatialGDK/Documentation/content/tutorials/porting-guide/tutorial-portingguide-deployment.md
  SpatialGDK/Documentation/content/tutorials/porting-guide/tutorial-portingguide-setup.md
  SpatialGDK/Documentation/content/tutorials/tutorial-porting-guide.md
  SpatialGDK/Documentation/toc.md
Labels: jira/no-ticket, size/XXL

#1234 Docs - dbsync fixes
  SpatialGDK/Documentation/content/tutorials/dbsync/tutorial-dbsync-communicating.md
  SpatialGDK/Documentation/content/tutorials/dbsync/tutorial-dbsync-intro.md
  SpatialGDK/Documentation/content/tutorials/dbsync/tutorial-dbsync-setup.md
  SpatialGDK/Documentation/content/tutorials/dbsync/tutorial-dbsync-syncing.md
  SpatialGDK/Documentation/content/tutorials/dbsync/tutorial-dbsync-testing.md
Labels: jira/no-ticket

#1235 Fix player movement when on zoned servers
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
Labels: jira/no-ticket, size/M

#1231 Bugfix/unr 1798 prevent loading stale classes
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Public/Schema/UnrealMetadata.h
Labels: jira/no-ticket, size/M

#1238 UNR-1814 - Fixing event fields to clear deserialization
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/CodeGenerator/Unreal/SourceGenerator.cs
  SpatialGDK/Build/Scripts/ExternalSchemaCodegen.bat
Labels: jira/UNR, size/XS

#1230 UNR-1738 Initial AlwaysRelevant support
  RequireSetup
  SpatialGDK/Extras/schema/relevant.schema
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/InterestFactory.cpp
  SpatialGDK/Source/SpatialGDK/Public/Schema/AlwaysRelevant.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/InterestFactory.h
Labels: jira/UNR, size/M

#1248 UNR-1817 DB-Worker tutorial small doc change for all time deaths
  SpatialGDK/Documentation/content/tutorials/dbsync/tutorial-dbsync-testing.md
Labels: jira/UNR, size/XS

#1249 We forgot to increment Version in SpatialGDK.uplugin
  SpatialGDK/SpatialGDK.uplugin
Labels: jira/no-ticket, size/XS

#1250 UNR-1819 Docs fix incorrect branch
  SpatialGDK/Documentation/content/tutorials/dbsync/tutorial-dbsync-setup.md
Labels: jira/UNR, size/XS

#1247 Misc tweaks
  SpatialGDK/Documentation/content/tutorials/dbsync/tutorial-dbsync-communicating.md
  SpatialGDK/Documentation/content/tutorials/dbsync/tutorial-dbsync-intro.md
  SpatialGDK/Documentation/content/tutorials/dbsync/tutorial-dbsync-setup.md
  SpatialGDK/Documentation/content/tutorials/dbsync/tutorial-dbsync-syncing.md
  SpatialGDK/Documentation/content/tutorials/dbsync/tutorial-dbsync-testing.md
Labels: jira/no-ticket, size/L

#1233 Readme 0.6.0 update
  README.md
  SpatialGDK/Documentation/spatialos-gdkforunreal-header.png
Labels: jira/no-ticket, size/S

#1228 Docs - provide clang upgrade guide
  SpatialGDK/Documentation/content/get-started/dependencies.md
  SpatialGDK/Documentation/content/upgrading.md
Labels: jira/no-ticket, size/S

#1239 UNR-1811 - Docs improvement for known issue of relative paths
  SpatialGDK/Documentation/content/get-started/example-project/exampleproject-cloud-deployment.md
  SpatialGDK/Documentation/content/get-started/starter-template/get-started-template-cloud.md
Labels: jira/UNR, size/XS

#1258 Docs/fixes
  SpatialGDK/Documentation/content/tutorials/dbsync/tutorial-dbsync-setup.md
Labels: jira/no-ticket, size/XS

#1256 Bronze review for offloading topics
  SpatialGDK/Documentation/content/apis-and-helper-scripts/actor-group-ownership-helpers.md
  SpatialGDK/Documentation/content/glossary.md
  SpatialGDK/Documentation/content/tutorials/offloading-tutorial/offloading-gameplay-changes.md
  SpatialGDK/Documentation/content/tutorials/offloading-tutorial/offloading-intro.md
  SpatialGDK/Documentation/content/tutorials/offloading-tutorial/offloading-setup.md
  SpatialGDK/Documentation/content/workers/offloading-concept.md
  SpatialGDK/Documentation/content/workers/set-up-offloading.md
Labels: jira/no-ticket, size/M

#1252 more misc docs fixes
  SpatialGDK/Documentation/content/tutorials/dbsync/tutorial-dbsync-communicating.md
  SpatialGDK/Documentation/content/tutorials/dbsync/tutorial-dbsync-setup.md
  SpatialGDK/Documentation/content/tutorials/dbsync/tutorial-dbsync-syncing.md
  SpatialGDK/Documentation/content/tutorials/dbsync/tutorial-dbsync-testing.md
Labels: jira/no-ticket, size/S

#1255 Doc 1250 debugging workflow
  SpatialGDK/Documentation/content/workflows/autostart-server-workers.md
  SpatialGDK/Documentation/content/workflows/set-up-vs.md
Labels: jira/no-ticket, size/M

#1245 Updated external worker codegen docs to match script change
  SpatialGDK/Documentation/content/apis-and-helper-scripts/helper-scripts.md
  SpatialGDK/Documentation/content/workers/non-unreal-server-worker-types.md
Labels: jira/no-ticket, size/XS

#1244 Updated ExternalSchemaCodegen.bat to take a project path argument
  SpatialGDK/Build/Scripts/ExternalSchemaCodegen.bat
Labels: jira/no-ticket, size/M

#1257 UNR-1674 Docs update map travel
  SpatialGDK/Documentation/content/map-travel.md
  SpatialGDK/Documentation/content/technical-overview/gdk-concepts.md
Labels: jira/UNR, size/M

#1260 Example Project Missing step to build project
  SpatialGDK/Documentation/content/get-started/example-project/exampleproject-setup.md
Labels: jira/no-ticket, size/XS

#1261 Updated multiplayer options screenshot
  SpatialGDK/Documentation/assets/set-up-template/template-multiplayer-options.png
Labels: jira/no-ticket, size/XS

#1262 Fix cloud deployment text overflow
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKSimulatedPlayerDeployment.cpp
Labels: jira/no-ticket, size/S

#1218 Audit the CHANGELOG
  CHANGELOG.md
Labels: jira/no-ticket, size/M

#1264 Simulated player nits
  SpatialGDK/Documentation/content/get-started/example-project/exampleproject-cloud-deployment.md
  SpatialGDK/Documentation/content/get-started/starter-template/get-started-template-cloud.md
  SpatialGDK/Documentation/content/simulated-players.md
Labels: jira/no-ticket, size/S

#1267 Miscellaneous setup/onboarding changes
  SpatialGDK/Documentation/content/get-started/build-unreal-fork.md
  SpatialGDK/Documentation/content/get-started/dependencies.md
  SpatialGDK/Documentation/content/manual-engine-build.md
Labels: jira/no-ticket, size/M

#1263 Added note about which name field to edit
  SpatialGDK/Documentation/content/get-started/example-project/exampleproject-cloud-deployment.md
  SpatialGDK/Documentation/content/get-started/starter-template/get-started-template-cloud.md
Labels: jira/no-ticket, size/XS

#1268 Merge 0.6.0 release into master
  CHANGELOG.md
  README.md
  RequireSetup
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/Build/Build.cs
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/CodeGenerator/Unreal/HeaderGenerator.cs
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/CodeGenerator/Unreal/InterfaceGenerator.cs
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/CodeGenerator/Unreal/SourceGenerator.cs
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/Common/LinuxScripts.cs
  SpatialGDK/Build/Scripts/ExternalSchemaCodegen.bat
  SpatialGDK/Documentation/spatialos-gdkforunreal-header.png
  SpatialGDK/Extras/schema/global_state_manager.schema
  SpatialGDK/Extras/schema/relevant.schema
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetConnection.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/GlobalStateManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialClassInfoManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialDispatcher.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialPlayerSpawner.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/ActorGroupManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/InterestFactory.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/Components/ActorInterestComponent.h
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetConnection.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/ConnectionConfig.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/GlobalStateManager.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialInterestConstraints.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialSender.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/AlwaysRelevant.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/UnrealMetadata.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialGDKModule.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/ActorGroupManager.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/EngineVersionCheck.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/InterestFactory.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/SchemaDatabase.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SchemaGenerator.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SchemaGenerator.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SnapshotGenerator/SpatialGDKEditorSnapshotGenerator.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditor.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorSettings.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKSimulatedPlayerDeployment.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorToolbar.h
  SpatialGDK/Source/SpatialGDKServices/Private/LocalDeploymentManager.cpp
  SpatialGDK/Source/SpatialGDKServices/Public/LocalDeploymentManager.h
  SpatialGDK/SpatialGDK.uplugin
  ci/unreal-engine.version
Labels: jira/no-ticket, size/XXL

#1246 IsListening and ownership fix
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialStaticComponentView.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/ClientRPCEndpoint.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/ServerRPCEndpoint.h
Labels: jira/no-ticket, size/M

#1270 UNR-1856: Updated docs
  SpatialGDK/Documentation/content/get-started/example-project/exampleproject-local-deployment.md
  SpatialGDK/Documentation/content/get-started/starter-template/get-started-template-local.md
Labels: jira/UNR, size/M
