Repository spatialos/UnrealGDK, pull requests merged in 2019-05, with the labels that each got.

#899 Updated tutorial text for SpatialOS settings, formatting updates
  SpatialGDK/Documentation/content/get-started/gdk-template.md
  SpatialGDK/Documentation/content/technical-overview/gdk-concepts.md
  SpatialGDK/Documentation/content/technical-overview/gdk-principles.md
  SpatialGDK/Documentation/content/technical-overview/how-the-gdk-fits-in.md
  SpatialGDK/Documentation/content/tutorials/multiserver-shooter/tutorial-multiserver-healthchanges.md
  SpatialGDK/Documentation/content/tutorials/multiserver-shooter/tutorial-multiserver-intro.md
  SpatialGDK/Documentation/content/tutorials/multiserver-shooter/tutorial-multiserver-localtest.md
  SpatialGDK/Documentation/content/tutorials/multiserver-shooter/tutorial-multiserver-setup.md
  SpatialGDK/Documentation/content/tutorials/tutorial-porting-guide.md
Labels: size/M

#904 0.4.1 rc
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SchemaGenerator.cpp
Labels: size/M

#905 Wrap launch config path with quotes in order to properly launch
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
Labels: size/XS

#901 Replacing diagrams
  SpatialGDK/Documentation/assets/screen-grabs/game-architecture.png
  SpatialGDK/Documentation/assets/screen-grabs/networking-switch.png
Labels: size/XS

#908 Fix BuildWorker.bat command in docs
  SpatialGDK/Documentation/content/get-started/gdk-template.md
Labels: size/XS

#910 Update unreal-features-support.md
  SpatialGDK/Documentation/content/unreal-features-support.md
Labels: size/XS

#902 Add "update the roadmap" to release-process.md
  SpatialGDK/Extras/internal-documentation/release-process.md
Labels: size/XS

#911 Merge 0.4.1-rc into master
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SchemaGenerator.cpp
Labels: size/M

#913 Docs/doc 1068 branding update
  SpatialGDK/Documentation/assets/spatialos-gdkforunreal-header.png
  SpatialGDK/Documentation/index.md
Labels: docs, size/XS

#914 Bugfix/increase ops tick rate
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp
Labels: size/XS

#912 Docs/DOC-1068 Schema updates
  SpatialGDK/Documentation/assets/screen-grabs/toolbar/inspector-button.png
  SpatialGDK/Documentation/assets/screen-grabs/toolbar/play-button.png
  SpatialGDK/Documentation/assets/screen-grabs/toolbar/schema-button-full-scan.png
  SpatialGDK/Documentation/assets/screen-grabs/toolbar/schema-button.png
  SpatialGDK/Documentation/assets/screen-grabs/toolbar/snapshot-button.png
  SpatialGDK/Documentation/assets/screen-grabs/toolbar/start-button.png
  SpatialGDK/Documentation/assets/screen-grabs/toolbar/stop-button.png
  SpatialGDK/Documentation/assets/screen-grabs/toolbar/toolbar-buttons.png
  SpatialGDK/Documentation/assets/screen-grabs/toolbar/toolbars-basic.png
  SpatialGDK/Documentation/content/get-started/gdk-template.md
  SpatialGDK/Documentation/content/spatialos-concepts/schema.md
  SpatialGDK/Documentation/content/tutorials/multiserver-shooter/tutorial-multiserver-setup.md
  SpatialGDK/Documentation/content/tutorials/tutorial-porting-guide.md
Labels: docs, size/M

#918 Spatial Type doc: remove mention of Advanced section
  SpatialGDK/Documentation/content/get-started/gdk-template.md
  SpatialGDK/Documentation/content/spatial-type.md
Labels: size/XS

#921 Add reliable RPC order checking to settings
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialSender.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h
Labels: size/M

#922 Add release note for UNR-1368
  CHANGELOG.md
Labels: size/XS

#909 DOC-850 SpatialOS concepts for the GDK
  SpatialGDK/Documentation/assets/screen-grabs/authority-areas.png
  SpatialGDK/Documentation/assets/screen-grabs/client-workers.png
  SpatialGDK/Documentation/assets/screen-grabs/component-details.png
  SpatialGDK/Documentation/assets/screen-grabs/deployment.png
  SpatialGDK/Documentation/assets/screen-grabs/interest-areas.gif
  SpatialGDK/Documentation/assets/screen-grabs/trad-client-server.png
  SpatialGDK/Documentation/assets/screen-grabs/workers-machines.png
  SpatialGDK/Documentation/content/actor-handover.md
  SpatialGDK/Documentation/content/authority.md
  SpatialGDK/Documentation/content/dynamic-typebindings.md
  SpatialGDK/Documentation/content/get-started/build-unreal-fork.md
  SpatialGDK/Documentation/content/get-started/gdk-template.md
  SpatialGDK/Documentation/content/get-started/introduction.md
  SpatialGDK/Documentation/content/glossary.md
  SpatialGDK/Documentation/content/how-to-use-schema.md
  SpatialGDK/Documentation/content/how-to-use-snapshots.md
  SpatialGDK/Documentation/content/map-travel.md
  SpatialGDK/Documentation/content/singleton-actors.md
  SpatialGDK/Documentation/content/spatialos-concepts/authority-and-interest.md
  SpatialGDK/Documentation/content/spatialos-concepts/concepts.md
  SpatialGDK/Documentation/content/spatialos-concepts/generating-a-snapshot.md
  SpatialGDK/Documentation/content/spatialos-concepts/schema-and-snapshots.md
  SpatialGDK/Documentation/content/spatialos-concepts/what-is-spatialos.md
  SpatialGDK/Documentation/content/spatialos-concepts/workers-and-load-balancing.md
  SpatialGDK/Documentation/content/spatialos-concepts/world-entities-components.md
  SpatialGDK/Documentation/content/technical-overview/gdk-concepts.md
  SpatialGDK/Documentation/content/toolbars.md
  SpatialGDK/Documentation/content/tutorials/tutorial-porting-guide.md
  SpatialGDK/Documentation/toc.md
Labels: docs, size/XL

#923 Reduced MulticastRPC authority warning to verbose
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
Labels: size/XS

#926 [UNR-1350] Bugfix: GenerateSchemaAndSnapshots: Run full schema gen once, then generate snapshots
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDKEditorCommandlet/Private/Commandlets/GenerateSchemaAndSnapshotsCommandlet.cpp
  SpatialGDK/Source/SpatialGDKEditorCommandlet/Private/Commandlets/GenerateSchemaAndSnapshotsCommandlet.h
Labels: size/S

#906 Upgrade to 4.22 with backwards comparability for 4.20
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/GlobalStateManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialClassInfoManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentReader.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/ComponentReader.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SnapshotGenerator/SpatialGDKEditorSnapshotGenerator.cpp
Labels: size/XL

#930 Ignore UInterfaceProperty replication
  SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentFactory.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/TypeStructure.cpp
Labels: size/XS

#928 Update RPC Status
  SpatialGDK/Documentation/unreal-features-support.md
Labels: size/XS

#919 UNR-1375: Save deduplicated schema names in schema db
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Public/Utils/SchemaDatabase.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SchemaGenerator.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SchemaGenerator.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/Utils/DataTypeUtilities.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/Utils/DataTypeUtilities.h
Labels: size/M

#897 Updated release process
  SpatialGDK/Extras/internal-documentation/release-process.md
Labels: size/M

#891 Update release-process.md
  SpatialGDK/Extras/internal-documentation/release-process.md
Labels: size/XS

#934 [UNR-1371] Bugfix: Do not generate schema for assets in 'Directories to Never Cook'
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditor.cpp
Labels: size/M

#907 UNR-1255: Kill hanging AutomationToolLauncher processes
  .buildkite/hooks/post-command
  ci/purge.ps1
Labels: size/M

#898 Feature/server metrics on client
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialMetricsDisplay.cpp
  SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialMetrics.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialMetricsDisplay.h
Labels: size/L

#924 Remove hardcoding of AIWorker
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SnapshotGenerator/SpatialGDKEditorSnapshotGenerator.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorSettings.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h
Labels: size/M

#942 [UNR 1415] Bugfix: Readonly Schema Database crashes editor during generation
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditor.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSchemaGenerator.h
Labels: size/M

#916 UNR-1375: Delete existing generated schema files when doing a full scan.
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditor.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSchemaGenerator.h
Labels: size/XS

#945 [DOC-1086] - add "Server" to Linux server worker build
  SpatialGDK/Documentation/content/get-started/gdk-template.md
Labels: size/XS

#948 Simplify the LAN testing process in release-process.md
  SpatialGDK/Extras/internal-documentation/release-process.md
Labels: size/S

#949 [UNR-1427] Schema database must be deleted upon upgrading.
  SpatialGDK/Documentation/content/upgrading.md
Labels: size/XS

#935 get review on release notes
  SpatialGDK/Extras/internal-documentation/release-process.md
Labels: size/XS

#950 Add Listen Server & Network lag commands to features support page
  SpatialGDK/Documentation/unreal-features-support.md
Labels: docs, size/S

#927 Release 0.4.2 RC
  CHANGELOG.md
  SpatialGDK/Documentation/content/non-unreal-server-worker-types.md
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialFastArrayNetSerialize.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetBitReader.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/EditorWorkerController.h
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/OutgoingMessages.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/GlobalStateManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SnapshotManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialClassInfoManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialPlayerSpawner.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialStaticComponentView.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentFactory.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentReader.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/EntityPool.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/InterestFactory.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/SchemaUtils.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialMetrics.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialFastArrayNetSerialize.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/OutgoingMessages.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/SpatialWorkerConnection.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialStaticComponentView.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/Component.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/DynamicComponent.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/Heartbeat.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/Interest.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/Singleton.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/SpawnData.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/StandardLibrary.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/UnrealMetadata.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/UnrealObjectRef.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/ComponentFactory.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/ComponentReader.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/InterestFactory.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/RepLayoutUtils.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/SchemaDatabase.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/SchemaOption.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/SchemaUtils.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialActorUtils.h
  SpatialGDK/Source/SpatialGDK/SpatialGDK.Build.cs
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SchemaGenerator.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SchemaGenerator.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/TypeStructure.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/Utils/DataTypeUtilities.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/Utils/DataTypeUtilities.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SnapshotGenerator/SpatialGDKEditorSnapshotGenerator.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditor.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSchemaGenerator.h
  SpatialGDK/Source/SpatialGDKEditorCommandlet/Private/Commandlets/GenerateSchemaAndSnapshotsCommandlet.cpp
  SpatialGDK/Source/SpatialGDKEditorCommandlet/Private/Commandlets/GenerateSchemaAndSnapshotsCommandlet.h
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
Labels: size/XXL

#933 Added toggle for offloading
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/EditorWorkerController.h
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp
  SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SnapshotGenerator/SpatialGDKEditorSnapshotGenerator.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
  ci/unreal-engine.version
Labels: size/M

#929 Added generation of entities to ensure offloaded workers receive updates for the GSM
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SnapshotGenerator/SpatialGDKEditorSnapshotGenerator.cpp
Labels: size/M

#954 Merge 0.4.2 release into master
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditor.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSchemaGenerator.h
Labels: size/M

#938 Fix crash when resolving subobject class in ClassInfoManager
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialClassInfoManager.cpp
Labels: size/XS

#956 Docs/doc 1023 Deployment Manager guide
  SpatialGDK/Documentation/assets/deployment-manager/deploymentmgr-consoledeployments.png
  SpatialGDK/Documentation/assets/deployment-manager/deploymentmgr-consoleoverview.png
  SpatialGDK/Documentation/assets/deployment-manager/deploymentmgr-deployments.png
  SpatialGDK/Documentation/assets/deployment-manager/deploymentmgr-directory.png
  SpatialGDK/Documentation/assets/deployment-manager/deploymentmgr-launch.png
  SpatialGDK/Documentation/assets/deployment-manager/deploymentmgr-share.png
  SpatialGDK/Documentation/assets/deployment-manager/deploymentmgr-share2.png
  SpatialGDK/Documentation/assets/deployment-manager/deploymentmgr-startscreen.png
  SpatialGDK/Documentation/assets/deployment-manager/deploymentmgr-token.png
  SpatialGDK/Documentation/assets/tutorial/project-name.png
  SpatialGDK/Documentation/content/get-started/build-unreal-fork.md
  SpatialGDK/Documentation/content/get-started/example-project/exampleproject-cloud-deployment.md
  SpatialGDK/Documentation/content/get-started/example-project/exampleproject-setup.md
  SpatialGDK/Documentation/content/tutorials/deployment-manager/tutorial-deploymentmgr-authentication.md
  SpatialGDK/Documentation/content/tutorials/deployment-manager/tutorial-deploymentmgr-clone.md
  SpatialGDK/Documentation/content/tutorials/deployment-manager/tutorial-deploymentmgr-configure.md
  SpatialGDK/Documentation/content/tutorials/deployment-manager/tutorial-deploymentmgr-intro.md
  SpatialGDK/Documentation/content/tutorials/deployment-manager/tutorial-deploymentmgr-launch.md
  SpatialGDK/Documentation/content/tutorials/deployment-manager/tutorial-deploymentmgr-play.md
  SpatialGDK/Documentation/content/tutorials/deployment-manager/tutorial-deploymentmgr-workers.md
  SpatialGDK/Documentation/toc.md
Labels: size/XL

#958 docs/formatting fix for build-unreal-fork
  SpatialGDK/Documentation/content/get-started/build-unreal-fork.md
Labels: size/XS

#959 docs/Updated index page - Added publishing data to both tutorials
  SpatialGDK/Documentation/content/get-started/build-unreal-fork.md
  SpatialGDK/Documentation/content/get-started/example-project/exampleproject-cloud-deployment.md
  SpatialGDK/Documentation/content/get-started/example-project/exampleproject-intro.md
  SpatialGDK/Documentation/content/get-started/example-project/exampleproject-local-deployment.md
  SpatialGDK/Documentation/content/get-started/example-project/exampleproject-play.md
  SpatialGDK/Documentation/content/get-started/example-project/exampleproject-setup.md
  SpatialGDK/Documentation/content/tutorials/deployment-manager/tutorial-deploymentmgr-authentication.md
  SpatialGDK/Documentation/content/tutorials/deployment-manager/tutorial-deploymentmgr-clone.md
  SpatialGDK/Documentation/content/tutorials/deployment-manager/tutorial-deploymentmgr-configure.md
  SpatialGDK/Documentation/content/tutorials/deployment-manager/tutorial-deploymentmgr-intro.md
  SpatialGDK/Documentation/content/tutorials/deployment-manager/tutorial-deploymentmgr-launch.md
  SpatialGDK/Documentation/content/tutorials/deployment-manager/tutorial-deploymentmgr-play.md
  SpatialGDK/Documentation/content/tutorials/deployment-manager/tutorial-deploymentmgr-workers.md
  SpatialGDK/Documentation/index.md
  SpatialGDK/Documentation/toc.md
Labels: size/M

#960 docs/DOC-1066 Update README.md
  README.md
Labels: size/M

#961 docs/Update tutorial-deploymentmgr-launch.md
  SpatialGDK/Documentation/content/tutorials/deployment-manager/tutorial-deploymentmgr-launch.md
Labels: size/XS

#962 Formatting fixes - Slight text edits
  SpatialGDK/Documentation/content/tutorials/deployment-manager/tutorial-deploymentmgr-launch.md
  SpatialGDK/Documentation/content/tutorials/deployment-manager/tutorial-deploymentmgr-play.md
  SpatialGDK/Documentation/toc.md
Labels: size/S

#965 Remove duplicate paragraph
  SpatialGDK/Documentation/content/technical-overview/how-the-gdk-fits-in.md
Labels: size/XS

#964 Make toggle blueprint callable
  SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialMetricsDisplay.h
Labels: size/XS

#969 UX updates
  SpatialGDK/Documentation/content/get-started/build-unreal-fork.md
  SpatialGDK/Documentation/content/get-started/dependencies.md
  SpatialGDK/Documentation/content/get-started/example-project/exampleproject-cloud-deployment.md
  SpatialGDK/Documentation/content/get-started/example-project/exampleproject-intro.md
  SpatialGDK/Documentation/content/get-started/example-project/exampleproject-local-deployment.md
  SpatialGDK/Documentation/content/get-started/example-project/exampleproject-play.md
  SpatialGDK/Documentation/content/get-started/example-project/exampleproject-setup.md
  SpatialGDK/Documentation/content/get-started/gdk-template.md
  SpatialGDK/Documentation/content/get-started/introduction.md
  SpatialGDK/Documentation/index.md
  SpatialGDK/Documentation/toc.md
Labels: size/M

#967 Bugfix/singleton resumption quickfix
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/Interop/GlobalStateManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/GlobalStateManager.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h
Labels: size/M

#920 Bugfix/unr 1033 rpcpayload
  SpatialGDK/Extras/schema/rpc_components.schema
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/GlobalStateManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialStaticComponentView.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/EntityPool.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/GlobalStateManager.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialSender.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/RPCPayload.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/SchemaUtils.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SnapshotGenerator/SpatialGDKEditorSnapshotGenerator.cpp
Labels: size/XL

#970 Feature/unr 1376 add handover disable option
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialClassInfoManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp
  SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
Labels: size/M

#972 [UNR-1010] Fix crash when retrying reliable RPCs with destroyed argument
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialSender.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialCommonTypes.h
Labels: size/M

#971 Formatting updates
  SpatialGDK/Documentation/content/get-started/build-unreal-fork.md
  SpatialGDK/Documentation/content/get-started/dependencies.md
  SpatialGDK/Documentation/content/get-started/example-project/exampleproject-cloud-deployment.md
  SpatialGDK/Documentation/content/get-started/example-project/exampleproject-intro.md
  SpatialGDK/Documentation/content/get-started/example-project/exampleproject-local-deployment.md
  SpatialGDK/Documentation/content/get-started/example-project/exampleproject-play.md
  SpatialGDK/Documentation/content/get-started/example-project/exampleproject-setup.md
  SpatialGDK/Documentation/content/get-started/gdk-template.md
  SpatialGDK/Documentation/content/get-started/introduction.md
  SpatialGDK/Documentation/content/pricing-and-support/pricing.md
  SpatialGDK/Documentation/content/pricing-and-support/support.md
  SpatialGDK/Documentation/content/spatialos-concepts/authority-and-interest.md
  SpatialGDK/Documentation/content/spatialos-concepts/schema-and-snapshots.md
  SpatialGDK/Documentation/content/spatialos-concepts/what-is-spatialos.md
  SpatialGDK/Documentation/content/spatialos-concepts/workers-and-load-balancing.md
  SpatialGDK/Documentation/content/spatialos-concepts/world-entities-components.md
  SpatialGDK/Documentation/content/technical-overview/gdk-concepts.md
  SpatialGDK/Documentation/content/technical-overview/gdk-principles.md
  SpatialGDK/Documentation/content/technical-overview/how-the-gdk-fits-in.md
  SpatialGDK/Documentation/content/tutorials/deployment-manager/tutorial-deploymentmgr-authentication.md
  SpatialGDK/Documentation/content/tutorials/deployment-manager/tutorial-deploymentmgr-clone.md
  SpatialGDK/Documentation/content/tutorials/deployment-manager/tutorial-deploymentmgr-configure.md
  SpatialGDK/Documentation/content/tutorials/deployment-manager/tutorial-deploymentmgr-intro.md
  SpatialGDK/Documentation/content/tutorials/deployment-manager/tutorial-deploymentmgr-launch.md
  SpatialGDK/Documentation/content/tutorials/deployment-manager/tutorial-deploymentmgr-play.md
  SpatialGDK/Documentation/content/tutorials/deployment-manager/tutorial-deploymentmgr-workers.md
  SpatialGDK/Documentation/content/tutorials/multiserver-shooter/tutorial-multiserver-cloudtest.md
  SpatialGDK/Documentation/content/tutorials/multiserver-shooter/tutorial-multiserver-healthchanges.md
  SpatialGDK/Documentation/content/tutorials/multiserver-shooter/tutorial-multiserver-intro.md
  SpatialGDK/Documentation/content/tutorials/multiserver-shooter/tutorial-multiserver-localtest.md
  SpatialGDK/Documentation/content/tutorials/multiserver-shooter/tutorial-multiserver-setup.md
  SpatialGDK/Documentation/content/tutorials/tutorial-porting-guide.md
  SpatialGDK/Documentation/index.md
  SpatialGDK/Documentation/known-issues.md
  SpatialGDK/Documentation/toc.md
Labels: size/XL

#975 Docs/ux standardisation
  SpatialGDK/Documentation/content/get-started/build-unreal-fork.md
  SpatialGDK/Documentation/content/get-started/dependencies.md
  SpatialGDK/Documentation/content/get-started/example-project/exampleproject-cloud-deployment.md
  SpatialGDK/Documentation/content/get-started/example-project/exampleproject-intro.md
  SpatialGDK/Documentation/content/get-started/example-project/exampleproject-local-deployment.md
  SpatialGDK/Documentation/content/get-started/example-project/exampleproject-play.md
  SpatialGDK/Documentation/content/get-started/example-project/exampleproject-setup.md
  SpatialGDK/Documentation/content/get-started/gdk-template.md
  SpatialGDK/Documentation/content/get-started/introduction.md
  SpatialGDK/Documentation/content/tutorials/deployment-manager/tutorial-deploymentmgr-authentication.md
  SpatialGDK/Documentation/content/tutorials/deployment-manager/tutorial-deploymentmgr-clone.md
  SpatialGDK/Documentation/content/tutorials/deployment-manager/tutorial-deploymentmgr-configure.md
  SpatialGDK/Documentation/content/tutorials/deployment-manager/tutorial-deploymentmgr-intro.md
  SpatialGDK/Documentation/content/tutorials/deployment-manager/tutorial-deploymentmgr-launch.md
  SpatialGDK/Documentation/content/tutorials/deployment-manager/tutorial-deploymentmgr-play.md
  SpatialGDK/Documentation/content/tutorials/deployment-manager/tutorial-deploymentmgr-workers.md
  SpatialGDK/Documentation/content/tutorials/multiserver-shooter/tutorial-multiserver-cloudtest.md
  SpatialGDK/Documentation/content/tutorials/multiserver-shooter/tutorial-multiserver-healthchanges.md
  SpatialGDK/Documentation/content/tutorials/multiserver-shooter/tutorial-multiserver-intro.md
  SpatialGDK/Documentation/content/tutorials/multiserver-shooter/tutorial-multiserver-localtest.md
  SpatialGDK/Documentation/content/tutorials/multiserver-shooter/tutorial-multiserver-setup.md
  SpatialGDK/Documentation/content/tutorials/tutorial-porting-guide.md
Labels: size/XL

#978 Setup.sh fixes
  CHANGELOG.md
  Setup.sh
Labels: size/S

#977 Link, typo, small format
  SpatialGDK/Documentation/content/get-started/dependencies.md
  SpatialGDK/Documentation/content/get-started/example-project/exampleproject-local-deployment.md
  SpatialGDK/Documentation/content/tutorials/tutorial-porting-guide.md
  SpatialGDK/Documentation/index.md
Labels: size/S

#976 Extend BuildKite cleanup
  ci/purge.ps1
Labels: size/XS

#877 Docs/unr 1133 singleton guidelines
  SpatialGDK/Documentation/assets/screen-grabs/blueprint-singleton.png
  SpatialGDK/Documentation/content/singleton-actors.md
Labels: size/M

#980 Feature/switch metrics to frame time
  SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialMetricsDisplay.cpp
  SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialMetricsDisplay.h
  SpatialGDK/Source/SpatialGDK/SpatialGDK.Build.cs
Labels: size/M

#985 Add SpatialOS concepts intro page
  SpatialGDK/Documentation/content/glossary.md
  SpatialGDK/Documentation/content/spatialos-concepts/authority-and-interest.md
  SpatialGDK/Documentation/content/spatialos-concepts/introduction.md
  SpatialGDK/Documentation/content/spatialos-concepts/schema-and-snapshots.md
  SpatialGDK/Documentation/content/spatialos-concepts/what-is-spatialos.md
  SpatialGDK/Documentation/content/spatialos-concepts/workers-and-load-balancing.md
  SpatialGDK/Documentation/content/spatialos-concepts/world-entities-components.md
  SpatialGDK/Documentation/content/technical-overview/how-the-gdk-fits-in.md
  SpatialGDK/Documentation/toc.md
Labels: size/S

#984 Non-content update to environment variables steps & a small tweak
  SpatialGDK/Documentation/content/get-started/build-unreal-fork.md
Labels: size/M

#946 Removing temporary schema database auto update check
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp
Labels: size/XS

#983 Feature/unr 1480 batch spatial position updates
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialSender.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h
Labels: size/M

#986 Add auto spawn option to spatial metrics display
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialMetricsDisplay.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialMetricsDisplay.h
Labels: size/S

#989 Hide Unreal GDK from content browser
  CHANGELOG.md
  SpatialGDK/SpatialGDK.uplugin
Labels: size/XS
