Repository spatialos/UnrealGDK, pull requests merged in 2019-03, with the labels that each got.

#713 Still generate schema even if some blueprints haven't compiled
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditor.cpp
Labels: size/S

#709 Bugfix/faster tearoff
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
Labels: size/S

#718 Merge master into hydra
  CONTRIBUTING.md
  RequireSetup
  SpatialGDK/Documentation/assets/screen-grabs/snapshot.png
  SpatialGDK/Documentation/assets/screen-grabs/toolbar/schema-button.png
  SpatialGDK/Documentation/assets/screen-grabs/toolbar/snapshot-button.png
  SpatialGDK/Documentation/assets/screen-grabs/toolbar/toolbar-buttons.png
  SpatialGDK/Documentation/assets/screen-grabs/toolbar/toolbars-basic.png
  SpatialGDK/Documentation/assets/screen-grabs/toolbar/toolbars.png
  SpatialGDK/Documentation/assets/screen-grabs/toolbar/window-access.png
  SpatialGDK/Documentation/assets/set-up-template/template-start.png
  SpatialGDK/Documentation/assets/set-up-template/template-stop.png
  SpatialGDK/Documentation/known-issues.md
  SpatialGDK/Extras/schema/core_types.schema
  SpatialGDK/Extras/schema/rpc_components.schema
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialClassInfoManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/ConnectionConfig.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialClassInfoManager.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialSender.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SchemaGenerator.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SnapshotGenerator/SpatialGDKEditorSnapshotGenerator.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditor.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
Labels: size/XL

#720 Remove duplicate local variable for unreal metadata
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
Labels: size/XS

#712 Prevent loading levels when resolving UnrealObjectRefs
  RequireSetup
  SpatialGDK/Extras/schema/core_types.schema
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialPackageMapClient.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/UnrealObjectRef.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/SchemaUtils.h
Labels: size/M

#714 Fix order of initialization
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
Labels: size/XS

#724 Explain how to upgrade the GDK
  SpatialGDK/Documentation/content/get-started/gdk-template.md
  SpatialGDK/Documentation/content/get-started/tutorial.md
Labels: size/XS

#722 Don't try to replicate actors not supported by Spatial
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
Labels: size/XS

#725 docs/New UX changes
  SpatialGDK/Documentation/content/ability-system.md
  SpatialGDK/Documentation/content/authority.md
  SpatialGDK/Documentation/content/concepts.md
  SpatialGDK/Documentation/content/cross-server-rpcs.md
  SpatialGDK/Documentation/content/directory-structure.md
  SpatialGDK/Documentation/content/dynamic-typebindings.md
  SpatialGDK/Documentation/content/generating-a-snapshot.md
  SpatialGDK/Documentation/content/get-started/build-unreal-fork.md
  SpatialGDK/Documentation/content/get-started/dependencies.md
  SpatialGDK/Documentation/content/get-started/introduction.md
  SpatialGDK/Documentation/content/get-started/porting-unreal-project-to-gdk.md
  SpatialGDK/Documentation/content/get-started/tutorial.md
  SpatialGDK/Documentation/content/glossary.md
  SpatialGDK/Documentation/content/handover-between-server-workers.md
  SpatialGDK/Documentation/content/helper-scripts.md
  SpatialGDK/Documentation/content/map-travel.md
  SpatialGDK/Documentation/content/schema.md
  SpatialGDK/Documentation/content/singleton-actors.md
  SpatialGDK/Documentation/content/spatial-type.md
  SpatialGDK/Documentation/content/toolbars.md
  SpatialGDK/Documentation/content/troubleshooting.md
  SpatialGDK/Documentation/content/whatsnew.md
  SpatialGDK/Documentation/contributions/unreal-gdk-coding-standards.md
  SpatialGDK/Documentation/features.md
  SpatialGDK/Documentation/index.md
  SpatialGDK/Documentation/known-issues.md
  SpatialGDK/Documentation/recommended-use.md
  SpatialGDK/Documentation/toc.md
  SpatialGDK/Documentation/welcome.md
Labels: size/L

#727 Default bNoLoadOnClient to false
  SpatialGDK/Source/SpatialGDK/Public/Schema/UnrealObjectRef.h
Labels: size/XS

#723 Bugfix/add underscore
  RequireSetup
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/Build/Build.cs
  SpatialGDK/Documentation/known-issues.md
Labels: size/S

#729 Upgrading BuildKite agents to new CLI version
  .buildkite/premerge.steps.yaml
Labels: size/XS

#726 Update build script to use SimulatedPlayer instead of FakeClient
  RequireSetup
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/Build/Build.cs
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/Common/Common.cs
Labels: size/S

#721 Fixed duplicate creation of startup actors on reconnection
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/GlobalStateManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialPackageMapClient.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h
Labels: size/L

#692 Feature/unr 992 fast array serialization
  SpatialGDK/Documentation/known-issues.md
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialFastArrayNetSerialize.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentFactory.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentReader.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialFastArrayNetSerialize.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/ComponentFactory.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/RepLayoutUtils.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/TypeStructure.cpp
  ci/unreal-engine.version
Labels: size/L

#730 Make 'Delete dynamic actors' work with servers as a separate process
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
Labels: size/XS

#735 Removed unused unreal-engine.version file
  SpatialGDK/Extras/unreal-engine.version
  ci/build_linux.sh
  ci/build_windows.sh
  ci/pinned-tools.sh
  ci/profiling.sh
Labels: size/M

#732 WorkerType stored in GameInstance
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/ConnectionConfig.h
  ci/unreal-engine.version
Labels: size/XS

#738 Latest master into the hydra branch
  .buildkite/premerge.steps.yaml
  RequireSetup
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/Build/Build.cs
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/Common/Common.cs
  SpatialGDK/Documentation/content/ability-system.md
  SpatialGDK/Documentation/content/authority.md
  SpatialGDK/Documentation/content/concepts.md
  SpatialGDK/Documentation/content/cross-server-rpcs.md
  SpatialGDK/Documentation/content/directory-structure.md
  SpatialGDK/Documentation/content/dynamic-typebindings.md
  SpatialGDK/Documentation/content/generating-a-snapshot.md
  SpatialGDK/Documentation/content/get-started/build-unreal-fork.md
  SpatialGDK/Documentation/content/get-started/dependencies.md
  SpatialGDK/Documentation/content/get-started/gdk-template.md
  SpatialGDK/Documentation/content/get-started/introduction.md
  SpatialGDK/Documentation/content/get-started/porting-unreal-project-to-gdk.md
  SpatialGDK/Documentation/content/get-started/tutorial.md
  SpatialGDK/Documentation/content/glossary.md
  SpatialGDK/Documentation/content/handover-between-server-workers.md
  SpatialGDK/Documentation/content/helper-scripts.md
  SpatialGDK/Documentation/content/map-travel.md
  SpatialGDK/Documentation/content/schema.md
  SpatialGDK/Documentation/content/singleton-actors.md
  SpatialGDK/Documentation/content/spatial-type.md
  SpatialGDK/Documentation/content/toolbars.md
  SpatialGDK/Documentation/content/troubleshooting.md
  SpatialGDK/Documentation/content/whatsnew.md
  SpatialGDK/Documentation/contributions/unreal-gdk-coding-standards.md
  SpatialGDK/Documentation/features.md
  SpatialGDK/Documentation/index.md
  SpatialGDK/Documentation/known-issues.md
  SpatialGDK/Documentation/recommended-use.md
  SpatialGDK/Documentation/toc.md
  SpatialGDK/Documentation/welcome.md
  SpatialGDK/Extras/schema/core_types.schema
  SpatialGDK/Extras/unreal-engine.version
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialFastArrayNetSerialize.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/GlobalStateManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentFactory.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentReader.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialFastArrayNetSerialize.h
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialPackageMapClient.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/ConnectionConfig.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/UnrealObjectRef.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/ComponentFactory.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/RepLayoutUtils.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/SchemaUtils.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/TypeStructure.cpp
  ci/build_linux.sh
  ci/build_windows.sh
  ci/pinned-tools.sh
  ci/profiling.sh
  ci/unreal-engine.version
Labels: size/XXL

#739 Removed any mentions of the Starter Project from the docs
  README.md
  SpatialGDK/Documentation/content/get-started/introduction.md
  SpatialGDK/Documentation/content/get-started/porting-unreal-project-to-gdk.md
  SpatialGDK/Documentation/content/glossary.md
  SpatialGDK/Documentation/content/toolbars.md
  SpatialGDK/Documentation/content/troubleshooting.md
  SpatialGDK/Documentation/index.md
Labels: size/S

#733 Properly serialize parameters in RPCs passed by ref
  SpatialGDK/Documentation/known-issues.md
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp
Labels: size/M

#731 Read GSM as client to figure out what map to load.
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialGameInstance.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetConnection.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialGameInstance.h
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
Labels: size/XL

#710 Level streaming support
  RequireSetup
  SpatialGDK/Extras/schema/not_streamed.schema
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetBitReader.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetConnection.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/GlobalStateManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialClassInfoManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentFactory.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentReader.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/EntityRegistry.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/InterestFactory.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetConnection.h
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialPackageMapClient.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialClassInfoManager.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialSender.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/Interest.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/UnrealMetadata.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/ComponentFactory.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/EntityRegistry.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/InterestFactory.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/SchemaDatabase.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SchemaGenerator.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/Utils/ComponentIdGenerator.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SnapshotGenerator/SpatialGDKEditorSnapshotGenerator.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
  ci/unreal-engine.version
Labels: size/XXL

#736 Fix autogenerated launch config for prime number of servers
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
Labels: size/XS

#749 Scope to Windows
  .buildkite/premerge.steps.yaml
Labels: size/XS

#743 docs/Updates to Porting guide and Template docs.
  SpatialGDK/Documentation/assets/screen-grabs/porting-solution-config.png
  SpatialGDK/Documentation/assets/screen-grabs/toolbar/inspector-button.png
  SpatialGDK/Documentation/assets/screen-grabs/toolbar/play-button.png
  SpatialGDK/Documentation/assets/screen-grabs/toolbar/schema-button.png
  SpatialGDK/Documentation/assets/screen-grabs/toolbar/snapshot-button.png
  SpatialGDK/Documentation/assets/screen-grabs/toolbar/start-button.png
  SpatialGDK/Documentation/assets/screen-grabs/toolbar/stop-button.png
  SpatialGDK/Documentation/assets/screen-grabs/toolbar/toolbar-buttons.png
  SpatialGDK/Documentation/assets/screen-grabs/toolbar/toolbar-checkboxes.png
  SpatialGDK/Documentation/assets/set-up-template/template-multiplayer-options.png
  SpatialGDK/Documentation/assets/set-up-template/template-start.png
  SpatialGDK/Documentation/assets/set-up-template/template-stop.png
  SpatialGDK/Documentation/content/get-started/gdk-template.md
  SpatialGDK/Documentation/content/get-started/porting-unreal-project-to-gdk.md
  SpatialGDK/Documentation/content/get-started/tutorial.md
  SpatialGDK/Documentation/toc.md
Labels: size/L

#750 Fix Linux compiler error - Move inline function to header
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialGameInstance.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialGameInstance.h
Labels: size/XS

#746 Add 4.21 interface support
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetConnection.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetConnection.h
Labels: size/XS

#708 [UNR-673] Bulk Entity ID Reservation
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetBitWriter.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetConnection.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/GlobalStateManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialDispatcher.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentFactory.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/EntityPool.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialPackageMapClient.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/SpatialWorkerConnection.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialSender.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/EntityPool.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SnapshotGenerator/SpatialGDKEditorSnapshotGenerator.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorModule.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorSettings.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorModule.h
Labels: size/XXL

#752 [UNR-1083] Handle unreliable RPCs only if worker has authority (#717)
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
Labels: size/XS

#753 Remove inline
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialClassInfoManager.cpp
Labels: size/XS

#754 Add missing replicated timelines to known issues
  SpatialGDK/Documentation/known-issues.md
Labels: size/XS

#755 Remove unnecessary branching
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SchemaGenerator.cpp
Labels: size/XS

#756 Fix level blueprints for both schema generation and object look up.
  SpatialGDK/Extras/schema/unreal_metadata.schema
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/UnrealMetadata.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SnapshotGenerator/SpatialGDKEditorSnapshotGenerator.cpp
Labels: size/L

#757 Invalid sublevel names for sublevels without using World Composition
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp
Labels: size/XS

#758 Make map name schema compliant before putting it in the package name
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp
Labels: size/XS

#748 Docs/UNR-856 NetMulticast RPCs known issue update
  SpatialGDK/Documentation/known-issues.md
Labels: size/XS

#761 Fix bad merge
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
Labels: size/XS

#763 Fix multicast RPCs not being called
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
Labels: size/S

#759 Check against bNetStartup to see if path should be in UnrealMetadata
  SpatialGDK/Extras/schema/unreal_metadata.schema
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Public/Schema/UnrealMetadata.h
Labels: size/S

#751 Bug fix - Short lifecycle objects
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SchemaGenerator.cpp
Labels: size/M

#760 Remove TeamCity ifs from Setup.bat
  Setup.bat
Labels: size/S

#762 Sort RPCs by name since multiple EventGraphs can produce different order
  SpatialGDK/Source/SpatialGDK/Public/Utils/RepLayoutUtils.h
Labels: size/XS

#745 [UNR-964] Added support for starting multiple servers as separate processes
  RequireSetup
  SpatialGDK/Extras/schema/global_state_manager.schema
  SpatialGDK/Source/SpatialGDK/Private/Interop/GlobalStateManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/GlobalStateManager.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
Labels: size/M

#742 MultiServer Shooter Tutorial - Docs Fixes
  SpatialGDK/Documentation/assets/tutorial/inspector-two-workers.png
  SpatialGDK/Documentation/assets/tutorial/inspector.png
  SpatialGDK/Documentation/assets/tutorial/shooting-across-boundaries.gif
  SpatialGDK/Documentation/content/get-started/gdk-template.md
  SpatialGDK/Documentation/content/get-started/tutorial.md
Labels: size/M

#744 Simulated Player Deployment Launcher script
  Setup.bat
  Setup.sh
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/DeploymentLauncher/DeploymentLauncher.cs
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/DeploymentLauncher/DeploymentLauncher.csproj
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/Improbable.Unreal.Scripts.sln
  ci/setup-and-build-gdk.ps1
  ci/setup-gdk.ps1
Labels: size/XL

#768 Docs/tutorial small fixes
  SpatialGDK/Documentation/content/get-started/introduction.md
  SpatialGDK/Documentation/content/get-started/tutorial.md
Labels: size/M

#707 [UNR-990] Multi-layer C layer (stage 1)
  SpatialGDK/Documentation/content/glossary.md
  SpatialGDK/Documentation/content/non-unreal-layers.md
  SpatialGDK/Documentation/toc.md
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialDispatcher.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialDispatcher.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/StandardLibrary.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialCommonTypes.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/OpCallbackTemplate.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/SchemaUtils.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/SnapshotGenerationTemplate.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SnapshotGenerator/SpatialGDKEditorSnapshotGenerator.cpp
Labels: size/XL

#772 Fix: Make GetWorkerFlag public
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialWorkerFlags.h
Labels: size/XS

#775 Add soft reference schema not supported to docs
  SpatialGDK/Documentation/known-issues.md
Labels: size/XS

#780 Docs/warning update and friends
  SpatialGDK/Documentation/content/get-started/build-unreal-fork.md
  SpatialGDK/Documentation/content/get-started/introduction.md
  SpatialGDK/Documentation/content/get-started/porting-unreal-project-to-gdk.md
  SpatialGDK/Documentation/content/get-started/tutorial.md
  SpatialGDK/Documentation/index.md
Labels: size/M

#671 Bugfix/commandlet support mapname
  SpatialGDK/Source/SpatialGDKEditorCommandlet/Private/Commandlets/GenerateSchemaAndSnapshotsCommandlet.cpp
Labels: size/S

#784 Docs/Get started quick link fix
  SpatialGDK/Documentation/content/get-started/build-unreal-fork.md
Labels: size/XS

#764 Update logging on rpc sending and receiving
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp
Labels: size/S

#779 [UNR-1179] Use a separate TimerManager in SpatialNetDriver that ticks on real time
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
Labels: size/S

#734 Offloading spike
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/Build/Build.cs
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SnapshotGenerator/SpatialGDKEditorSnapshotGenerator.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorSettings.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorToolbar.h
  ci/unreal-engine.version
Labels: size/XL

#787 Fix ordering of args for help text
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/Build/Build.cs
Labels: size/XS

#781 Add toggle for using QBI to spatial settings
  SpatialGDK/Documentation/known-issues.md
  SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/InterestFactory.cpp
  SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
Labels: size/M
