Repository spatialos/UnrealGDK, pull requests merged in 2019-06, with the labels that each got.

#993 Add safety checks for position batching
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
Labels: size/S

#966 docs/DOC-1066-Added "hidden" setup page for TPS and Test suite
  SpatialGDK/Documentation/content/get-started/example-project/exampleproject-local-deployment.md
  SpatialGDK/Documentation/content/project-setup.md
  SpatialGDK/Documentation/content/tutorials/deployment-manager/tutorial-deploymentmgr-authentication.md
Labels: size/M

#917 Setup automation
  CHANGELOG.md
  Setup.bat
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/Build/Build.cs
  SpatialGDK/Source/SpatialGDK/Public/Utils/SchemaDatabase.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialMetricsDisplay.h
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h
  ci/get-engine.ps1
Labels: size/L

#996 Increment RequireSetup
  RequireSetup
Labels: size/XS

#979 Bugfix/fix snapshot reloading crash
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialMetricsDisplay.cpp
  SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialMetricsDisplay.h
Labels: size/S

#999 Bugfix: Fixed build issues related to new setup flow
  Setup.bat
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/Build/Build.cs
Labels: size/S

#998 Fix Singleton Interest
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/Utils/InterestFactory.cpp
  SpatialGDK/Source/SpatialGDK/Public/Utils/InterestFactory.h
Labels: size/S

#1004 [UNR-1494] Docs: Server Travel is not currently supported.
  SpatialGDK/Documentation/content/map-travel.md
  SpatialGDK/Documentation/unreal-features-support.md
Labels: size/XS

#1005 Update cross server documentation
  SpatialGDK/Documentation/content/cross-server-rpcs.md
Labels: size/S

#947 Docs/command line arguments doc 361
  SpatialGDK/Documentation/content/command-line-arguments.md
  SpatialGDK/Documentation/content/map-travel.md
  SpatialGDK/Documentation/toc.md
Labels: docs, size/L

#1013 [UNR-1515] Replace toolbar images, in line with new branding guidelines.
  SpatialGDK/Resources/Icon128.png
  SpatialGDK/Resources/Inspector.png
  SpatialGDK/Resources/Inspector@0.5x.png
  SpatialGDK/Resources/Launch.png
  SpatialGDK/Resources/Launch@0.5x.png
  SpatialGDK/Resources/Schema.png
  SpatialGDK/Resources/Schema@0.5x.png
  SpatialGDK/Resources/Snapshot.png
  SpatialGDK/Resources/Snapshot@0.5x.png
  SpatialGDK/Resources/Stop.png
  SpatialGDK/Resources/Stop@0.5x.png
Labels: do-not-merge/work-in-progress

#987 Bugfix/unr 1467 windows dependency ios
  Setup.bat
Labels: size/XS

#991 * Integrated the Development Authentication Flow
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/ConnectionConfig.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/SpatialWorkerConnection.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h
Labels: size/M

#1067 docs/Update exampleproject-cloud-deployment.md
  SpatialGDK/Documentation/content/get-started/example-project/exampleproject-cloud-deployment.md
Labels: docs

#1000 Use SchemaCompiler
  CHANGELOG.md
  Setup.bat
  SpatialGDK/Build/Scripts/BuildWorker.bat
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditor.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSchemaGenerator.h
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
Labels: size/M

#1066 Docs - clearer callout on fork step 1
  SpatialGDK/Documentation/content/get-started/build-unreal-fork.md
Labels: docs

#974 Quick Fixes (DOC-1088)
  SpatialGDK/Documentation/content/dynamic-typebindings.md
  SpatialGDK/Documentation/content/get-started/example-project/exampleproject-cloud-deployment.md
  SpatialGDK/Documentation/content/get-started/example-project/exampleproject-local-deployment.md
  SpatialGDK/Documentation/content/get-started/gdk-template.md
  SpatialGDK/Documentation/content/spatialos-concepts/schema-and-snapshots.md
  SpatialGDK/Documentation/content/toolbars.md
  SpatialGDK/Documentation/content/tutorials/multiserver-shooter/tutorial-multiserver-cloudtest.md
  SpatialGDK/Documentation/content/tutorials/tutorial-porting-guide.md
Labels: size/M
