Repository spatialos/UnrealGDK, pull requests merged in 2019-12, with the labels that each got.

#1534 DOC-1279: Explain branching and auto/manual install
  SpatialGDK/Documentation/content/get-started/build-unreal-fork.md
Labels: jira/DOC, size/S

#1542 fix environment variable
  ci/build-and-send-slack-notification.ps1
Labels: jira/GV, size/XS

#1539 Bugfix Skip forcing spatial networking if -pak argument is present
  RequireSetup
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/Build/Build.cs
Labels: jira/UNR, size/S

#1541 Added %s token to debug strings in GlobalStateManager to display actor class name in log
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/Interop/GlobalStateManager.cpp
Labels: jira/no-ticket, size/XS

#1533 [DOC-1354] Specify SpatialOS unreal engine fork repo release branch
  SpatialGDK/Documentation/assets/screen-grabs/unreal-fork-repo-branch.png
  SpatialGDK/Documentation/content/get-started/build-unreal-fork.md
Labels: jira/DOC, size/XS

#1535 Fixes DOC-1358 Work to tidy up welcome page
  SpatialGDK/Documentation/index.md
Labels: jira/DOC, size/M

#1543 Added netdriver check in SpatialActorChannel::Cleanup
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
Labels: jira/no-ticket, size/S

#1544 Cherry-pick from docs-release
  SpatialGDK/Documentation/assets/screen-grabs/unreal-fork-repo-branch.png
  SpatialGDK/Documentation/content/get-started/build-unreal-fork.md
Labels: jira/no-ticket, size/XS

#1538 [DOC-1434]Update Page Changelog
  SpatialGDK/Documentation/content/simulated-players.md
Labels: do-not-merge/invalid-owners-file, jira/DOC, size/XS

#1545 Fix tracking of number of tests
  ci/report-tests.ps1
Labels: jira/GV, size/XS

#1531 Feature/UNR-2132 additional endpoint support patch 4.20
  CHANGELOG.md
  Setup.bat
  Setup.sh
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/DeploymentLauncher/DeploymentLauncher.cs
  SpatialGDK/Extras/spot.version
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorCloudLauncher.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorSettings.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
  SpatialGDK/Source/SpatialGDKServices/Private/LocalDeploymentManager.cpp
  SpatialGDK/Source/SpatialGDKServices/Public/LocalDeploymentManager.h
Labels: jira/UNR, size/L

#1524 Mark DBSync and Zoning tutorials as experimental
  SpatialGDK/Documentation/content/tutorials/dbsync/tutorial-dbsync-communicating.md
  SpatialGDK/Documentation/content/tutorials/dbsync/tutorial-dbsync-intro.md
  SpatialGDK/Documentation/content/tutorials/dbsync/tutorial-dbsync-syncing.md
  SpatialGDK/Documentation/content/tutorials/dbsync/tutorial-dbsync-testing.md
  SpatialGDK/Documentation/content/tutorials/multiserver-shooter/tutorial-multiserver-cloudtest.md
  SpatialGDK/Documentation/content/tutorials/multiserver-shooter/tutorial-multiserver-healthchanges.md
  SpatialGDK/Documentation/content/tutorials/multiserver-shooter/tutorial-multiserver-intro.md
  SpatialGDK/Documentation/content/tutorials/multiserver-shooter/tutorial-multiserver-localtest.md
  SpatialGDK/Documentation/toc.md
Labels: jira/no-ticket, size/M

#1548 Bugfix/unr 2501 tombstone check to log
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
Labels: jira/UNR, size/XS

#1550 Add spec for linking SpatialMetrics API
  SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialMetrics.h
Labels: jira/no-ticket, size/XS

#1549 Update worker SDK ports
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
Labels: jira/no-ticket, size/XS

#1553 Feature/update platform endpoint
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/DeploymentLauncher/DeploymentLauncher.cs
Labels: jira/no-ticket, size/XS

#1552 Adjust formatting and namespace scope for SpatialConstants
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialMetrics.cpp
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
Labels: jira/no-ticket, size/XL

#1560 Update CHANGELOG.md
  CHANGELOG.md
Labels: jira/no-ticket, size/XS

#1563 Fix the third StopDeployments argument
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/DeploymentLauncher/DeploymentLauncher.cs
Labels: jira/no-ticket, size/XS

#1562 Update Version and VersionName in SpatialGDK.uplugin
  SpatialGDK/SpatialGDK.uplugin
Labels: jira/no-ticket, size/XS

#1561 0.6.3
  CHANGELOG.md
  Setup.bat
  Setup.sh
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/DeploymentLauncher/DeploymentLauncher.cs
  SpatialGDK/Extras/spot.version
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorCloudLauncher.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorSettings.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
  SpatialGDK/Source/SpatialGDKServices/Private/LocalDeploymentManager.cpp
  SpatialGDK/Source/SpatialGDKServices/Public/LocalDeploymentManager.h
  SpatialGDK/SpatialGDK.uplugin
Labels: jira/no-ticket, size/L

#1528 Feature/unr 2396 add trace lib measurements
  RequireSetup
  Setup.bat
  SetupIncTraceLibs.bat
  SpatialGDK/Extras/schema/rpc_components.schema
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialGameInstance.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialLatencyTracer.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialGameInstance.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/OutgoingMessages.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/SpatialWorkerConnection.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/RPCPayload.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialGDKLoader.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialLatencyTracer.h
  SpatialGDK/Source/SpatialGDK/SpatialGDK.Build.cs
Labels: jira/UNR, size/XXL

#1546 UNR-2129 Reduce code coupling
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialLoadBalanceEnforcer.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialVirtualWorkerTranslator.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialClassInfoManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialDispatcher.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSnapshotManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialActorGroupManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialStatics.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialLoadBalanceEnforcer.h
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialVirtualWorkerTranslator.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SnapshotManager.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialClassInfoManager.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialDispatcher.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialSender.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialSnapshotManager.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialWorkerFlags.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialActorGroupManager.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialStatics.h
  SpatialGDK/Source/SpatialGDKEditor/Public/WorkerTypeCustomization.h
Labels: jira/UNR, size/XL

#1568 Removed Validity check for LoadBalancer
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
Labels: jira/UNR, size/XS

#1565 Update CHANGELOG.md (#1458)
  CHANGELOG.md
Labels: jira/no-ticket, size/S

#1566 Merged 0.6.3 into 0.7.1-rc and manually resolved conflicts
  CHANGELOG.md
  Setup.bat
  Setup.sh
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/DeploymentLauncher/DeploymentLauncher.cs
  SpatialGDK/Extras/spot.version
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorCloudLauncher.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorSettings.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
  SpatialGDK/Source/SpatialGDKServices/Private/LocalDeploymentManager.cpp
  SpatialGDK/Source/SpatialGDKServices/Public/LocalDeploymentManager.h
  SpatialGDK/SpatialGDK.uplugin
Labels: jira/no-ticket, size/L

#1507 Enabling SpatialOS toolbar on Mac
  CHANGELOG.md
  Setup.sh
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKDefaultWorkerJsonGenerator.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditor.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorSettings.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKSimulatedPlayerDeployment.cpp
  SpatialGDK/Source/SpatialGDKServices/Private/Interop/Connection/EditorWorkerController.cpp
  SpatialGDK/Source/SpatialGDKServices/Private/LocalDeploymentManager.cpp
  SpatialGDK/Source/SpatialGDKServices/Private/SSpatialOutputLog.cpp
  SpatialGDK/Source/SpatialGDKServices/Private/SpatialGDKServicesModule.cpp
  SpatialGDK/Source/SpatialGDKServices/Public/SpatialGDKServicesConstants.h
  SpatialGDK/Source/SpatialGDKServices/Public/SpatialGDKServicesModule.h
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/SpatialGDKEditorSchemaGeneratorTest.cpp
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKServices/LocalDeploymentManager/LocalDeploymentManagerTest.cpp
  SpatialGDK/SpatialGDK.uplugin
Labels: jira/no-ticket, size/L

#1576 Update CHANGELOG.md
  CHANGELOG.md
Labels: jira/no-ticket, size/XS

#1574 Provide help for rebuilding engine artifacts if download failed
  ci/get-engine.ps1
Labels: jira/no-ticket, size/XS

#1577 Update CHANGELOG.md
  CHANGELOG.md
Labels: jira/no-ticket, size/XS

#1575 0.7.1
  CHANGELOG.md
  Setup.bat
  Setup.sh
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/DeploymentLauncher/DeploymentLauncher.cs
  SpatialGDK/Extras/spot.version
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorCloudLauncher.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorSettings.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
  SpatialGDK/Source/SpatialGDKServices/Private/LocalDeploymentManager.cpp
  SpatialGDK/Source/SpatialGDKServices/Public/LocalDeploymentManager.h
  SpatialGDK/SpatialGDK.uplugin
Labels: jira/no-ticket, size/L

#1440 Allows RunSchemaCompiler to output any format
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp
Labels: jira/no-ticket, size/M

#1521 Enabling pushing iOS command line arguments to builds
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorSettings.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbarCommands.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorToolbar.h
  SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorToolbarCommands.h
  SpatialGDK/Source/SpatialGDKEditorToolbar/SpatialGDKEditorToolbar.Build.cs
Labels: jira/no-ticket, size/M

#1579 Feature/0.7.1 preview merge to master
  CHANGELOG.md
  Setup.bat
  Setup.sh
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/DeploymentLauncher/DeploymentLauncher.cs
  SpatialGDK/Extras/spot.version
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorCloudLauncher.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorSettings.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
  SpatialGDK/Source/SpatialGDKServices/Private/LocalDeploymentManager.cpp
  SpatialGDK/Source/SpatialGDKServices/Public/LocalDeploymentManager.h
  SpatialGDK/SpatialGDK.uplugin
Labels: jira/no-ticket, size/L

#1567 Feature/unr 2494 expose additional connection config settings
  CHANGELOG.md
  RequireSetup
  SpatialGDK/Extras/core-sdk.version
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/ConnectionConfig.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/SpatialWorkerConnection.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h
Labels: jira/UNR, size/L

#1582 Port 443 and China endpoints for 0.8.0
  CHANGELOG.md
  Setup.bat
  Setup.sh
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/DeploymentLauncher/DeploymentLauncher.cs
  SpatialGDK/Extras/spot.version
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorCloudLauncher.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorSettings.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
  SpatialGDK/Source/SpatialGDKServices/Private/LocalDeploymentManager.cpp
  SpatialGDK/Source/SpatialGDKServices/Public/LocalDeploymentManager.h
Labels: jira/PORT, size/L

#1583 Add domain env var to setup.sh
  Setup.sh
Labels: jira/no-ticket, size/XS

#1571 UNR-2507 - LoadObjects when bNetLoadOnClient is false and object is deleted.
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Public/Schema/UnrealMetadata.h
Labels: jira/UNR, size/XS

#1580 UNR-2129 Removed NetDriver from WorkerConnection
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/SpatialWorkerConnection.h
Labels: jira/UNR, size/M

#1584 Added a missing #if WITH_EDITOR to fix the build
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
Labels: jira/UNR, size/XS

#1586 Cherry pick commits from recent tickets to docs-preview from docs-release
  SpatialGDK/Documentation/content/get-started/build-unreal-fork.md
  SpatialGDK/Documentation/index.md
Labels: jira/no-ticket, size/M

#1573 UNR-2318 stop spatial service which runs in different project
  SpatialGDK/Source/SpatialGDKServices/Private/LocalDeploymentManager.cpp
Labels: jira/UNR, size/XS

#1593 Bugfix/log spelling fix
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialGameInstance.cpp
Labels: jira/no-ticket, size/XS

#1594 Default to 4.23 version
  ci/unreal-engine.version
Labels: jira/no-ticket, size/XS

#1597 [UNR-2553][MS] Fix for droppped URL options.
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
Labels: jira/UNR, size/XS

#1517 UNR-1995 Workflow improvement for local deployments where a schema build previously failed
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorToolbar.h
Labels: jira/UNR, size/S

#1598 Before sorting actors based on distance to the player, remove any wea…
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialDebugger.cpp
Labels: jira/UNR, size/XS

#1600 UNR-2318: Use text which was provided by tech editors
  SpatialGDK/Source/SpatialGDKServices/Private/LocalDeploymentManager.cpp
Labels: jira/UNR, size/XS

#1596 UNR-2129 Removing unused code
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
Labels: jira/UNR, size/XS

#1590 [UNR-2129] Decouple net driver and Spatial metrics
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialMetrics.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialMetrics.h
Labels: jira/UNR, size/M

#1601 Don't initialize worker translator if load balancer disabled
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialVirtualWorkerTranslator.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp
Labels: jira/no-ticket, size/S

#1559 GV-101 - Expand CI build configurations (GDK)
  .buildkite/premerge.steps.yaml
  ci/README.md
  ci/build-gdk.ps1
  ci/build-project.ps1
  ci/check-version-file.sh
  ci/cleanup.ps1
  ci/gdk_build.template.steps.yaml
  ci/generate-and-upload-build-steps.sh
  ci/get-engine.ps1
  ci/report-tests.ps1
  ci/run-tests.ps1
  ci/setup-build-test-gdk.ps1
  ci/setup-gdk.ps1
  ci/setup-tests.ps1
  ci/unreal-engine.version
  ci/upload-test-metrics.sh
Labels: jira/GV, size/XL

#1603 Release note for 0.6.4
  CHANGELOG.md
Labels: jira/UNR, size/XS

#1607 Update SpatialGDK.uplugin
  SpatialGDK/SpatialGDK.uplugin
Labels: jira/no-ticket, size/XS

#1606 Update VersionName and release date
  CHANGELOG.md
Labels: jira/no-ticket, size/XS

#1588 Refactored an overzealous warning message and a drive by fix.
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialLoadBalanceEnforcer.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialSender.h
Labels: jira/UNR, size/S

#1604 0.6.4
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
  SpatialGDK/SpatialGDK.uplugin
Labels: jira/no-ticket, size/XS

#1520 [WIP] Add ring buffer settings
  SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp
  SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h
Labels: jira/no-ticket, size/S

#1527 Generate RPC endpoint schema
  RequireSetup
  SpatialGDK/Extras/schema/rpc_components.schema
  SpatialGDK/Extras/schema/rpc_payload.schema
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialStaticComponentView.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/InterestFactory.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/ClientRPCEndpointLegacy.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/ServerRPCEndpointLegacy.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SchemaGenerator.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SchemaGenerator.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSchemaGenerator.h
  SpatialGDK/Source/SpatialGDKEditorCommandlet/Private/Commandlets/CookAndGenerateSchemaCommandlet.cpp
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/ExpectedGeneratedSchemaFileContents.h
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/ExpectedSchema/NonSpatialTypeActor.schema
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/ExpectedSchema/SpatialTypeActor.schema
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/ExpectedSchema/SpatialTypeActorComponent.schema
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/ExpectedSchema/SpatialTypeActorWithActorComponent.schema
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/ExpectedSchema/SpatialTypeActorWithMultipleActorComponents.schema
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/ExpectedSchema/SpatialTypeActorWithMultipleObjectComponents.schema
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/ExpectedSchema/rpc_endpoints.schema
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/SpatialGDKEditorSchemaGeneratorTest.cpp
Labels: WIP-do-not-merge, jira/no-ticket, size/XXL

#1569 ServerTravel cleaning: Fix race condition and removing log.
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/GlobalStateManager.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/GlobalStateManager.h
Labels: jira/UNR, size/S

#1602 Tests for RPCService
  SpatialGDK/Source/SpatialGDK/Private/Tests/RPCServiceTest.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/RPCRingBuffer.cpp
  SpatialGDK/Source/SpatialGDK/Public/Tests/TestDefinitions.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/RPCRingBuffer.h
  SpatialGDK/Source/SpatialGDKTests/Examples/SpatialGDKExampleTest.cpp
  SpatialGDK/Source/SpatialGDKTests/SpatialGDK/EngineClasses/SpatialVirtualWorkerTranslator/SpatialVirtualWorkerTranslatorTest.cpp
  SpatialGDK/Source/SpatialGDKTests/SpatialGDK/LoadBalancing/GridBasedLBStrategy/GridBasedLBStrategyTest.cpp
  SpatialGDK/Source/SpatialGDKTests/SpatialGDK/Utils/Misc/SpatialActivationFlags.cpp
  SpatialGDK/Source/SpatialGDKTests/SpatialGDK/Utils/RPCContainer/RPCContainerTest.cpp
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/SpatialGDKEditorSchemaGeneratorTest.cpp
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKServices/LocalDeploymentManager/LocalDeploymentManagerTest.cpp
Labels: jira/no-ticket, size/XL

#1581 UNR-2503 SpatialDebugger colourings
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialLoadBalanceEnforcer.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialVirtualWorkerTranslator.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/GlobalStateManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialDebugger.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialLoadBalanceEnforcer.h
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialVirtualWorkerTranslator.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/GlobalStateManager.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialCommonTypes.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/InspectionColors.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialDebugger.h
Labels: jira/UNR, size/L

#1605 Review: Worker translator typedefs
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialLoadBalanceEnforcer.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialVirtualWorkerTranslator.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialLoadBalanceEnforcer.h
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialVirtualWorkerTranslator.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/SpatialWorkerConnection.h
  SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/AbstractLBStrategy.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/AuthorityIntent.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialCommonTypes.h
Labels: jira/no-ticket, size/S

#1595 Update release process email list
  SpatialGDK/Extras/internal-documentation/release-process.md
Labels: jira/no-ticket, size/XS

#1599 UNR-2352 Pop & locking actors
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/ReferenceCountedLockingPolicy.cpp
  SpatialGDK/Source/SpatialGDK/Private/Schema/UnrealObjectRef.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
  SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/AbstractLBStrategy.h
  SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/AbstractLockingPolicy.h
  SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/ReferenceCountedLockingPolicy.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialCommonTypes.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h
  SpatialGDK/Source/SpatialGDKTests/SpatialGDK/LoadBalancing/GridBasedLBStrategy/GridBasedLBStrategyTest.cpp
  SpatialGDK/Source/SpatialGDKTests/SpatialGDK/LoadBalancing/ReferenceCountedLockingPolicy/ReferenceCountedLockingPolicyTest.cpp
Labels: jira/UNR, size/XL

#1611 Update release date in CHANGELOG
  CHANGELOG.md
Labels: jira/no-ticket, size/XS

#1570 UNR-2129 Removed the Sender from the Enforcer
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialLoadBalanceEnforcer.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialVirtualWorkerTranslator.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialStaticComponentView.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialLoadBalanceEnforcer.h
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialVirtualWorkerTranslator.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialStaticComponentView.h
Labels: jira/UNR, size/M

#1617 Update LocalDeploymentManager.cpp
  SpatialGDK/Source/SpatialGDKServices/Private/LocalDeploymentManager.cpp
Labels: jira/no-ticket, size/XS

#1616 Update premerge.steps.yaml
  .buildkite/premerge.steps.yaml
Labels: jira/no-ticket, size/XS

#1614 Don't create locking policy on client
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
Labels: jira/no-ticket, size/S

#1618 Update ReferenceCountedLockingPolicy include
  SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/ReferenceCountedLockingPolicy.cpp
Labels: jira/no-ticket, size/XS

#1615 Fixing Setup.sh
  Setup.sh
  SpatialGDK/Extras/git/post-merge
Labels: jira/no-ticket, size/S

#1610 UNR-2129 SpatialWorkerCleanup
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialGameInstance.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialGameInstance.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/SpatialWorkerConnection.h
Labels: jira/UNR, size/M

#1619 Update CHANGELOG.md
  CHANGELOG.md
Labels: jira/no-ticket, size/XS

#1622 Update unreal-engine.version
  ci/unreal-engine.version
Labels: jira/no-ticket, size/XS

#1608 Only explicitly set external ip to true if not connecting to local host
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/ConnectionConfig.h
Labels: jira/no-ticket, size/XS

#1623 Move bad changelog edits to correct position
  CHANGELOG.md
Labels: jira/no-ticket, size/XS

#1624 update queue to recent version
  .buildkite/premerge.steps.yaml
Labels: jira/no-ticket, size/XS

#1625 Merge 0.8.0-preview into master
  CHANGELOG.md
  RequireSetup
  Setup.sh
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/Build/Build.cs
  SpatialGDK/Extras/git/post-merge
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorCloudLauncher.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorCloudLauncher.h
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKSimulatedPlayerDeployment.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorToolbar.h
  SpatialGDK/Source/SpatialGDKServices/Public/LocalDeploymentManager.h
  SpatialGDK/SpatialGDK.uplugin
  ci/unreal-engine.version
Labels: jira/no-ticket, size/L

#1585 Bugfix UNR-1259 fix worker flags not per worker
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialDispatcher.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialWorkerFlags.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialStatics.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialDispatcher.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialWorkerFlags.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialStatics.h
  SpatialGDK/Source/SpatialGDKTests/SpatialGDK/Interop/SpatialWorkerFlags/SpatialWorkerFlagsTest.cpp
  SpatialGDK/Source/SpatialGDKTests/SpatialGDK/Interop/SpatialWorkerFlags/WorkerFlagsTestSpyObject.cpp
  SpatialGDK/Source/SpatialGDKTests/SpatialGDK/Interop/SpatialWorkerFlags/WorkerFlagsTestSpyObject.h
Labels: jira/UNR, size/L

#1629 Adjustments for RPC Tests
  SpatialGDK/Source/SpatialGDK/Private/Tests/RPCServiceTest.cpp
Labels: jira/no-ticket, size/XL

#1631 Switch defaults to 14.3.0
  CHANGELOG.md
  RequireSetup
  SpatialGDK/Extras/core-sdk.version
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/ConnectionConfig.h
Labels: jira/no-ticket, size/S

#1635 Missed tcp fixes
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/Improbable.Unreal.Scripts.sln
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/WorkerCoordinator/CoordinatorConnection.cs
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp
Labels: jira/no-ticket, size/S

#1554 RPC Service (Ring buffers)
  RequireSetup
  SpatialGDK/Extras/schema/rpc_payload.schema
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialRPCService.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialStaticComponentView.cpp
  SpatialGDK/Source/SpatialGDK/Private/Schema/ClientEndpoint.cpp
  SpatialGDK/Source/SpatialGDK/Private/Schema/MulticastRPCs.cpp
  SpatialGDK/Source/SpatialGDK/Private/Schema/ServerEndpoint.cpp
  SpatialGDK/Source/SpatialGDK/Private/Tests/RPCServiceTest.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/InterestFactory.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/RPCRingBuffer.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialRPCService.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialSender.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialStaticComponentView.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/ClientEndpoint.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/MulticastRPCs.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/ServerEndpoint.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
  SpatialGDK/Source/SpatialGDK/Public/Tests/TestDefinitions.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/RPCRingBuffer.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SchemaGenerator.cpp
  SpatialGDK/Source/SpatialGDKTests/Examples/SpatialGDKExampleTest.cpp
  SpatialGDK/Source/SpatialGDKTests/SpatialGDK/EngineClasses/SpatialVirtualWorkerTranslator/SpatialVirtualWorkerTranslatorTest.cpp
  SpatialGDK/Source/SpatialGDKTests/SpatialGDK/LoadBalancing/GridBasedLBStrategy/GridBasedLBStrategyTest.cpp
  SpatialGDK/Source/SpatialGDKTests/SpatialGDK/Utils/Misc/SpatialActivationFlags.cpp
  SpatialGDK/Source/SpatialGDKTests/SpatialGDK/Utils/RPCContainer/RPCContainerTest.cpp
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/ExpectedSchema/rpc_endpoints.schema
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/SpatialGDKEditorSchemaGeneratorTest.cpp
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKServices/LocalDeploymentManager/LocalDeploymentManagerTest.cpp
Labels: jira/no-ticket, size/XXL

#1636 Bugfix/unr 2607 SpatialDebugger crashfix
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialDebugger.cpp
Labels: jira/UNR, size/XS

#1637 Rename origin to prevent name clash warning
  SpatialGDK/Source/SpatialGDK/Public/Schema/StandardLibrary.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SnapshotGenerator/SpatialGDKEditorSnapshotGenerator.cpp
Labels: jira/no-ticket, size/XS

#1591 [UNR-2434][MS] Removing logic from schema generator for spatial type look up
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp
Labels: jira/UNR, size/S

#1638 Switch schema database path to editor version
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditor.cpp
Labels: jira/no-ticket, size/XS
