Repository spatialos/UnrealGDK, pull requests merged in 2019-02, with the labels that each got.

#630 UNR-938 Critical with unresolved objects
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetBitWriter.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentFactory.cpp
Labels: size/S

#633 Add a troubleshooting entry for missing .NETFramework 4.5
  SpatialGDK/Documentation/content/troubleshooting.md
Labels: size/XS

#635 Bugfix/null player state
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialSender.h
Labels: size/S

#632 Added checks for actor channel validity when creating entities
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h
Labels: size/S

#634 Bugfix: Only apply actor component initial data if bReplicates = true
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SchemaGenerator.cpp
Labels: size/S

#631 Apply zero array update
  SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentFactory.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentReader.cpp
  SpatialGDK/Source/SpatialGDK/Public/Utils/ComponentReader.h
Labels: size/L

#629 Updated the text and fixed some markdown formatting problems.
  SpatialGDK/Documentation/content/ability-system.md
  SpatialGDK/Documentation/known-issues.md
  SpatialGDK/Documentation/toc.md
Labels: size/S

#644 UNR-953 Added parent index check
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
Labels: size/XS

#643 Updated template for release notes
  .github/pull-request-template.md
Labels: size/XS

#626 Refactored TypebindingManager into ClassInfoManager
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/GlobalStateManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialClassInfoManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentFactory.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentReader.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialPackageMapClient.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialClassInfoManager.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialSender.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/UnrealMetadata.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/ComponentFactory.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/ComponentReader.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SchemaGenerator.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SchemaGenerator.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SnapshotGenerator/SpatialGDKEditorSnapshotGenerator.cpp
Labels: size/XL

#640 changed type of key in TMap so linux build will not give errors
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialSender.h
Labels: size/XS

#642 Additions/changes to Get Started
  SpatialGDK/Documentation/content/directory-structure.md
  SpatialGDK/Documentation/content/get-started/build-unreal-fork.md
  SpatialGDK/Documentation/content/get-started/dependencies.md
  SpatialGDK/Documentation/content/get-started/introduction.md
  SpatialGDK/Documentation/welcome.md
Labels: size/L

#646 Add FUnrealObjRef.IsValid()
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetBitReader.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetBitWriter.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/GlobalStateManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialClassInfoManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentFactory.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentReader.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialPackageMapClient.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialClassInfoManager.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/UnrealObjectRef.cpp
  SpatialGDK/Source/SpatialGDK/Public/Schema/UnrealObjectRef.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/ComponentFactory.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/ComponentReader.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/TypeStructure.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SnapshotGenerator/SpatialGDKEditorSnapshotGenerator.cpp
Labels: size/M

#648 Switched to Raknet default
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/ConnectionConfig.h
Labels: size/XS

#556 Redirect logging in the cloud to output to the correct file
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/Build/Build.cs
Labels: size/S

#623 Startup Actors v2
  SpatialGDK/Extras/schema/global_state_manager.schema
  SpatialGDK/Extras/schema/unreal_metadata.schema
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/GlobalStateManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialDispatcher.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialStaticComponentView.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentFactory.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentReader.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialPackageMapClient.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/GlobalStateManager.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialStaticComponentView.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/Interest.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/UnrealMetadata.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/UnrealObjectRef.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/SchemaUtils.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SnapshotGenerator/SpatialGDKEditorSnapshotGenerator.cpp
Labels: size/XXL

#645 Fix USpatialGameInstance::StartPlayInEditorGameInstance() to properly call OnStart() if on Client
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialGameInstance.cpp
Labels: size/XS

#650 [UNR-911] Pass player name and login options in the login URL
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialPlayerSpawner.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialPlayerSpawner.h
Labels: size/S

#651 Better function name
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialPlayerSpawner.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialPlayerSpawner.h
Labels: size/XS

#652 Disable loopback of component updates
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp
Labels: size/XS

#653 Fix hanging on shutdown when timeed out from SpatialOS
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp
Labels: size/S

#655 UNR-982: Actor not destroyed when entity removed
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
Labels: size/XS

#647 [UNR-874] Heartbeats, player disconnection
  RequireSetup
  SpatialGDK/Extras/schema/heartbeat.schema
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetConnection.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialStaticComponentView.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetConnection.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/Heartbeat.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
Labels: size/XL

#656 Fix crash on multiserver PIE shutdown
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp
Labels: size/XS

#658 Fix the fix for the multiserver PIE shutdown
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp
Labels: size/XS

#637 UNR-925: exposing connection events
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialGameInstance.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialDispatcher.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialGameInstance.h
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/SpatialWorkerConnection.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h
Labels: size/L

#638 UNR-935: Running in editor with multiple processes causes load balancing issues
  SpatialGDK/Extras/schema/global_state_manager.schema
  SpatialGDK/Source/SpatialGDK/Private/Interop/GlobalStateManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/GlobalStateManager.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SnapshotGenerator/SpatialGDKEditorSnapshotGenerator.cpp
Labels: size/M

#662 Fix not returning in switch statement
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
Labels: size/XS

#665 Remove unused constant and reformat.
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
Labels: size/XS

#666 Wrap with null check to avoid crash bug on quit for deployments
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialGameInstance.cpp
Labels: size/XS

#664 [UNR-1003] - Docs/update engine branch instructions
  README.md
  SpatialGDK/Documentation/content/get-started/build-unreal-fork.md
Labels: size/XS

#639 Bugfix/commandlet iterative schema gen
  SpatialGDK/Source/SpatialGDKEditorCommandlet/Private/Commandlets/GenerateSchemaAndSnapshotsCommandlet.cpp
  SpatialGDK/Source/SpatialGDKEditorCommandlet/Private/Commandlets/GenerateSchemaAndSnapshotsCommandlet.h
Labels: size/L

#669 Fix delete dynamic entities check
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
Labels: size/S

#668 UNR-937 Load Default GameMode for schema generation
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditor.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSchemaGenerator.h
Labels: size/M

#674 Adjusted fork path
  README.md
  SpatialGDK/Documentation/content/get-started/build-unreal-fork.md
Labels: size/XS

#641 Turn bReplicates offset warning into an error
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SchemaGenerator.cpp
Labels: size/XS

#670 UNR-996 Handcrafted Component ids start at 9999 and decrease. dynamic start at 10000
  RequireSetup
  SpatialGDK/Extras/schema/global_state_manager.schema
  SpatialGDK/Extras/schema/heartbeat.schema
  SpatialGDK/Extras/schema/singleton.schema
  SpatialGDK/Extras/schema/spawndata.schema
  SpatialGDK/Extras/schema/spawner.schema
  SpatialGDK/Extras/schema/unreal_metadata.schema
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
Labels: size/M

#667 If schema database is manually deleted, reset internal state for schema generator
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditor.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSchemaGenerator.h
Labels: size/S

#675 [UNR-927] Better error reporting during schema generation
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SchemaGenerator.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/TypeStructure.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/TypeStructure.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/Utils/DataTypeUtilities.cpp
Labels: size/L

#676 Better logic for clearing the schema database
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditor.cpp
Labels: size/S

#663 Added new doc for Schema
  SpatialGDK/Documentation/content/dynamic-typebindings.md
  SpatialGDK/Documentation/content/generating-a-snapshot.md
  SpatialGDK/Documentation/content/get-started/tutorial.md
  SpatialGDK/Documentation/content/glossary.md
  SpatialGDK/Documentation/content/map-travel.md
  SpatialGDK/Documentation/content/schema.md
  SpatialGDK/Documentation/content/whatsnew.md
  SpatialGDK/Documentation/toc.md
Labels: size/M

#677 Bug fix - COND_InitialOnly not doing anything
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
Labels: size/XS

#678 Fixed standalone local client connection.
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialGameInstance.cpp
Labels: size/XS

#680 Add the 'cloud launch blocks local launch' bug to known issues
  SpatialGDK/Documentation/known-issues.md
Labels: size/XS

#681 [UNR-1015] Error if blueprint RPCs have by ref arguments
  SpatialGDK/Documentation/known-issues.md
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp
Labels: size/S

#683 Bugfix/external client missing class
  SpatialGDK/Source/SpatialGDK/Public/Schema/UnrealMetadata.h
Labels: size/XS

#657 Buildkite CI
  .buildkite/.gitignore
  .buildkite/premerge.definition.yaml
  .buildkite/premerge.steps.yaml
  .buildkite/trigger.sh
  SpatialGDK/Extras/core-sdk.version
  ci/build-gdk.ps1
  ci/common.ps1
  ci/get-engine.ps1
  ci/setup-and-build-gdk.ps1
  ci/setup-gdk.ps1
  ci/unreal-engine.version
Labels: size/L

#684 Generate schema for classes that only have RPCs
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp
Labels: size/XS

#688 Install UE4 prereqs and renaming CI events
  .buildkite/premerge.steps.yaml
  ci/build-gdk.ps1
  ci/get-engine.ps1
Labels: size/XS

#685 Update build kite queue to production queue
  .buildkite/premerge.steps.yaml
  ci/build-gdk.ps1
  ci/get-engine.ps1
Labels: size/S

#672 Added support for autogenerated launch configs (UNR-700)
  .buildkite/premerge.definition.yaml
  .buildkite/trigger.sh
  SpatialGDK/Documentation/assets/screen-grabs/toolbar/multi-player-options.png
  SpatialGDK/Documentation/content/generating-a-snapshot.md
  SpatialGDK/Documentation/content/toolbars.md
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/GlobalStateManager.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SnapshotGenerator/SpatialGDKEditorSnapshotGenerator.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorSettings.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorToolbar.h
  ci/setup-and-build-gdk.ps1
  ci/unreal-engine.version
Labels: size/L

#687 Don't update shadow data if we created the entity locally
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentFactory.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
Labels: size/S

#689 Bugfix/snapshot file path
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorSettings.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h
Labels: size/XS

#686 Tidy up default connection flows
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialGameInstance.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialGameInstance.h
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialPackageMapClient.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/ConnectionConfig.h
Labels: size/L

#661 Docs/template docs
  .gitignore
  SpatialGDK/Documentation/assets/set-up-template/template-multiplayer-options.png
  SpatialGDK/Documentation/assets/set-up-template/template-project-browser.png
  SpatialGDK/Documentation/assets/set-up-template/template-project-page.png
  SpatialGDK/Documentation/assets/set-up-template/template-start.png
  SpatialGDK/Documentation/assets/set-up-template/template-stop.png
  SpatialGDK/Documentation/assets/set-up-template/template-vs-toolbar.png
  SpatialGDK/Documentation/content/get-started/gdk-and-starter-project.md
  SpatialGDK/Documentation/content/get-started/gdk-template.md
  SpatialGDK/Documentation/content/get-started/porting-unreal-project-to-gdk.md
  SpatialGDK/Documentation/content/get-started/tutorial.md
  SpatialGDK/Documentation/index.md
  SpatialGDK/Documentation/toc.md
Labels: size/L

#691 Fix default port override
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
Labels: size/XS

#690 Contribution Policy
  CONTRIBUTING.md
Labels: size/S

#697 Duplicate of #694 - Remove legacy flag in generated default config to fix warning when launching SpatialOS
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
Labels: size/XS

#699 UNR-1010 Fix Spatial connection destroy on PIE and allow map name as first argument.
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/ConnectionConfig.h
Labels: size/S

#700 Change pass-by-ref args in RPCs error to warning
  SpatialGDK/Documentation/known-issues.md
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp
Labels: size/XS

#701 Fix boot segfault with packaged clients.
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/ConnectionConfig.h
Labels: size/XS

#673 UNR-1000 make sure all dirty blueprints are compiled before schema generation
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditor.cpp
Labels: size/S

#698 Duplicate of #695 - Spatial OS Toolbar now only shows one of the Start / Stop button
  SpatialGDK/Documentation/assets/screen-grabs/snapshot.png
  SpatialGDK/Documentation/assets/screen-grabs/toolbar/schema-button.png
  SpatialGDK/Documentation/assets/screen-grabs/toolbar/snapshot-button.png
  SpatialGDK/Documentation/assets/screen-grabs/toolbar/toolbar-buttons.png
  SpatialGDK/Documentation/assets/screen-grabs/toolbar/toolbars-basic.png
  SpatialGDK/Documentation/assets/screen-grabs/toolbar/toolbars.png
  SpatialGDK/Documentation/assets/screen-grabs/toolbar/window-access.png
  SpatialGDK/Documentation/assets/set-up-template/template-start.png
  SpatialGDK/Documentation/assets/set-up-template/template-stop.png
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
Labels: size/XS

#682 [UNR-1009] Use events to send Unreliable RPCs
  RequireSetup
  SpatialGDK/Extras/schema/core_types.schema
  SpatialGDK/Extras/schema/rpc_components.schema
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialClassInfoManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialClassInfoManager.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialSender.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SchemaGenerator.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SnapshotGenerator/SpatialGDKEditorSnapshotGenerator.cpp
Labels: size/XL

#679 UNR-950: make sure that editor doesn't crash when loading a class which isn't present in schema DB
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialClassInfoManager.cpp
Labels: size/S

#704 Fixed using incorrect component ID and Linux builds.
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h
Labels: size/XS

#705 Replace inline logic with call to replicate subobjects
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
Labels: size/S
