Repository spatialos/UnrealGDK, pull requests merged in 2019-10, with the labels that each got.

#1383 Look for version file in the right directory
  ci/check-version-file.ps1
Labels: jira/no-ticket, size/S

#1380 Use the modular upd networking stack
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/ConnectionConfig.h
Labels: jira/UNR, size/XS

#1386 UNR-2176 Added error message
  SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentReader.cpp
Labels: jira/UNR, size/XS

#1364 Bugfix/unr-1453 fix net dormancy
  SpatialGDK/Extras/schema/relevant.schema
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialFastArrayNetSerialize.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetConnection.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialStaticComponentView.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetConnection.h
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialSender.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/AlwaysRelevant.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/EngineVersionCheck.h
  ci/unreal-engine.version
Labels: jira/no-ticket, size/XL

#1390 Add check for null package map
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
Labels: jira/no-ticket, size/S

#1352 UNR-1708 Spatial Output Log
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialOutputDevice.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp
  SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h
  SpatialGDK/Source/SpatialGDKServices/Private/LocalDeploymentManager.cpp
  SpatialGDK/Source/SpatialGDKServices/Private/SSpatialOutputLog.cpp
  SpatialGDK/Source/SpatialGDKServices/Private/SSpatialOutputLog.h
  SpatialGDK/Source/SpatialGDKServices/Private/SpatialGDKServicesModule.cpp
  SpatialGDK/Source/SpatialGDKServices/SpatialGDKServices.Build.cs
  ci/unreal-engine.version
Labels: jira/UNR, size/XL

#1393 Bugfix - Fix inspector button
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
Labels: jira/no-ticket, size/XS

#1395 Enable downstream compression
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp
Labels: jira/no-ticket, size/XS

#1394 [UNR-2187] Bugfix Handover causing crashes in net dormancy
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
Labels: jira/UNR, size/S

#1397 Add an AuthorityIntent component
  CHANGELOG.md
  SpatialGDK/Extras/schema/authority_intent.schema
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialStaticComponentView.cpp
  SpatialGDK/Source/SpatialGDK/Public/Schema/AuthorityIntent.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
Labels: jira/UNR, size/M

#1399 UNR-2193 Dropped Multicast RPCs Fix
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
Labels: jira/GCS, jira/UNR, size/S

#1391 UNR-1979 Use the latest built engine version in CI builds
  .buildkite/premerge.steps.yaml
  ci/check-version-file.sh
  ci/get-engine.ps1
  ci/unreal-engine.version
Labels: do-not-merge/work-in-progress, jira/UNR, size/M

#1403 UNR-2194 Only use Owner's Spatial position if the owner is replicated
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
Labels: jira/UNR, size/XS

#1402 [UNR-2195] Fix component updates being dropped when waking up an actor
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h
Labels: jira/UNR, size/S

#1404 Bugfix/dormancy initial replication v2
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h
Labels: jira/no-ticket, size/XS

#1396 Update tutorial-multiserver-intro.md
  SpatialGDK/Documentation/content/tutorials/multiserver-shooter/tutorial-multiserver-intro.md
Labels: jira/no-ticket, size/XS

#1405 Increment RequireSetup sequence number
  RequireSetup
Labels: jira/UNR, size/XS

#1407 Turn off packing by default, add compression to modular udp
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetConnection.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp
Labels: jira/UNR, size/S

#1370 Add console command to toggle SpatialMetricsDisplay. Various approac…
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialGameInstance.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialMetricsDisplay.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialMetricsDisplay.h
Labels: jira/UNR, size/M

#1387 Bugfix/UNR-1418 force spatial networking in builds
  CHANGELOG.md
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/Build/Build.cs
Labels: jira/UNR, size/S

#1410 [UNR-2220] Bugfix: Force bSpatialNetworking in CookAndGenerateSchema
  SpatialGDK/Source/SpatialGDKEditorCommandlet/Private/Commandlets/CookAndGenerateSchemaCommandlet.cpp
  SpatialGDK/Source/SpatialGDKEditorCommandlet/Private/Commandlets/CookAndGenerateSchemaCommandlet.h
  SpatialGDK/Source/SpatialGDKEditorCommandlet/Private/Commandlets/GenerateSchemaAndSnapshotsCommandlet.cpp
  SpatialGDK/Source/SpatialGDKEditorCommandlet/SpatialGDKEditorCommandlet.Build.cs
Labels: jira/UNR, size/S

#1412 UNR-2186: define gcs publish bucked
  ci/get-engine.ps1
Labels: jira/UNR, size/XS

#1413 Bugfix - Deleted actor dormancy check
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
Labels: jira/no-ticket, size/XS

#1415 Replace an outdated check with a warning log
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
Labels: jira/no-ticket, size/XS

#1417 UNR-2229 Update SpatialGDKTests folder structure
  SpatialGDK/Source/SpatialGDKTests/SpatialGDK/Utils/RPCContainer/ObjectDummy.cpp
  SpatialGDK/Source/SpatialGDKTests/SpatialGDK/Utils/RPCContainer/ObjectDummy.h
  SpatialGDK/Source/SpatialGDKTests/SpatialGDK/Utils/RPCContainer/ObjectSpy.cpp
  SpatialGDK/Source/SpatialGDKTests/SpatialGDK/Utils/RPCContainer/ObjectSpy.h
  SpatialGDK/Source/SpatialGDKTests/SpatialGDK/Utils/RPCContainer/ObjectStub.cpp
  SpatialGDK/Source/SpatialGDKTests/SpatialGDK/Utils/RPCContainer/ObjectStub.h
  SpatialGDK/Source/SpatialGDKTests/SpatialGDK/Utils/RPCContainer/RPCContainerTest.cpp
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/SpatialGDKEditorSchemaGeneratorTest.cpp
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKServices/LocalDeploymentManager/LocalDeploymentManagerTest.cpp
Labels: jira/UNR, size/XS

#1418 Release 0.6.2-rc
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
Labels: jira/no-ticket, size/M

#1423 UNR-2243 Fix a crash when applying component data for deleted static subobject
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentReader.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h
Labels: jira/UNR, size/M

#1406 Spatial output worker categories
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialOutputDevice.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialStatics.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialOutputDevice.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/EngineVersionCheck.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialStatics.h
  SpatialGDK/Source/SpatialGDKServices/Private/SSpatialOutputLog.cpp
  SpatialGDK/Source/SpatialGDKServices/Public/SSpatialOutputLog.h
Labels: jira/no-ticket, size/L

#1425 Feature/unr 2198 create virtual worker mapping component
  CHANGELOG.md
  RequireSetup
  SpatialGDK/Extras/schema/virtual_worker_translation.schema
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
Labels: jira/UNR, size/S

#1428 Merge 0.7.0 preview into master
  CHANGELOG.md
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/WorkerCoordinator/WorkerCoordinator.csproj
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentReader.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h
  SpatialGDK/Source/SpatialGDKEditorCommandlet/Private/Commandlets/CookAndGenerateSchemaCommandlet.cpp
  SpatialGDK/Source/SpatialGDKEditorCommandlet/Private/Commandlets/CookAndGenerateSchemaCommandlet.h
  SpatialGDK/Source/SpatialGDKEditorCommandlet/Private/Commandlets/GenerateSchemaAndSnapshotsCommandlet.cpp
  SpatialGDK/Source/SpatialGDKEditorCommandlet/SpatialGDKEditorCommandlet.Build.cs
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
  SpatialGDK/SpatialGDK.uplugin
  ci/unreal-engine.version
Labels: jira/no-ticket, size/L

#1398 Docs - DOC-1332 - Adds VS 2019 support
  SpatialGDK/Documentation/content/get-started/dependencies.md
Labels: jira/DOC, size/XS

#1432 GCS-1548 Error instead of crash if there's an invalid field ID in a schema object
  SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentReader.cpp
  SpatialGDK/Source/SpatialGDK/Public/Utils/ComponentReader.h
Labels: jira/GCS, size/S

#1433 Ignore ops for components in the spatial reserved range (<100)
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
Labels: jira/no-ticket, size/XS

#1434 Fix wrong offset used in unresolved reference map for fast array serialization
  SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentReader.cpp
Labels: jira/no-ticket, size/XS

#1369 UNR-1067 expose client server worker ping
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/Components/SpatialPingComponent.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/Components/SpatialPingComponent.h
Labels: jira/UNR, size/L

#1436 Docs - Unlist and deprecate the deployment-manager based tutorial
  SpatialGDK/Documentation/content/tutorials/deployment-manager/tutorial-deploymentmgr-intro.md
  SpatialGDK/Documentation/index.md
  SpatialGDK/Documentation/toc.md
Labels: jira/no-ticket, size/S

#1367 Bugfix/UNR-1869 allow runtime ip exposure
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorSettings.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorToolbar.h
  SpatialGDK/Source/SpatialGDKServices/Private/LocalDeploymentManager.cpp
  SpatialGDK/Source/SpatialGDKServices/Public/LocalDeploymentManager.h
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKServices/LocalDeploymentManager/LocalDeploymentManagerTest.cpp
Labels: jira/UNR, size/M

#1429 Feature/unr 2199 create virtual worker translator
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialVirtualWorkerTranslator.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialVirtualWorkerTranslator.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h
  SpatialGDK/Source/SpatialGDKTests/SpatialGDK/EngineClasses/SpatialVirtualWorkerTranslator/SpatialVirtualWorkerTranslatorTest.cpp
Labels: jira/UNR, size/L

#1439 Removed remaining references to deprecated tutorial
  SpatialGDK/Documentation/content/get-started/example-project/exampleproject-play.md
  SpatialGDK/Documentation/content/get-started/introduction.md
  SpatialGDK/Documentation/content/tutorials/deployment-manager/tutorial-deploymentmgr-authentication.md
  SpatialGDK/Documentation/content/tutorials/deployment-manager/tutorial-deploymentmgr-clone.md
  SpatialGDK/Documentation/content/tutorials/deployment-manager/tutorial-deploymentmgr-configure.md
  SpatialGDK/Documentation/content/tutorials/deployment-manager/tutorial-deploymentmgr-launch.md
  SpatialGDK/Documentation/content/tutorials/deployment-manager/tutorial-deploymentmgr-play.md
  SpatialGDK/Documentation/content/tutorials/deployment-manager/tutorial-deploymentmgr-workers.md
  SpatialGDK/Documentation/content/tutorials/porting-guide/tutorial-portingguide-logs.md
  SpatialGDK/Documentation/index.md
Labels: jira/no-ticket, size/S

#1442 give deployment more time to start
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKServices/LocalDeploymentManager/LocalDeploymentManagerTest.cpp
Labels: jira/UNR, size/XS

#1422 [UNR-2083 & UNR-1543] Trigger unit tests from CI and use Setup.bat in CI
  .buildkite/hooks/pre-exit.bat
  .buildkite/premerge.steps.yaml
  Setup.bat
  SpatialGDK/Build/Scripts/FindMSBuild.bat
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKServices/LocalDeploymentManager/LocalDeploymentManagerTest.cpp
  ci/build-gdk.ps1
  ci/cleanup.ps1
  ci/get-engine.ps1
  ci/report-tests.ps1
  ci/run-tests.ps1
  ci/setup-and-build-gdk.ps1
  ci/setup-build-test-gdk.ps1
  ci/setup-gdk.ps1
  ci/setup-tests.ps1
Labels: jira/UNR, size/XL

#1435 Buildkite: Permit use of fastbuild cache/distribution
  .buildkite/premerge.steps.yaml
Labels: jira/no-ticket, size/XS

#1416 UNR-1912 Feature/handle orphaned runtime
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDKServices/Private/LocalDeploymentManager.cpp
  SpatialGDK/Source/SpatialGDKServices/Public/LocalDeploymentManager.h
  SpatialGDK/Source/SpatialGDKServices/SpatialGDKServices.Build.cs
Labels: jira/UNR, size/M

#1446 Fix unit test CI
  ci/report-tests.ps1
  ci/run-tests.ps1
  ci/setup-tests.ps1
Labels: jira/no-ticket, size/M

#1419 UNR-2008 SpatialGDKEditorSchemaGenerator tests
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditor.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSchemaGenerator.h
  SpatialGDK/Source/SpatialGDKEditorCommandlet/Private/Commandlets/CookAndGenerateSchemaCommandlet.cpp
  SpatialGDK/Source/SpatialGDKEditorCommandlet/Private/Commandlets/GenerateSchemaCommandlet.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/ExpectedGeneratedSchemaFileContents.h
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/SchemaGenObjectStub.cpp
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/SchemaGenObjectStub.h
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/SpatialGDKEditorSchemaGeneratorTest.cpp
Labels: jira/UNR, size/XXL

#1414 [UNR-2180] Bugfix: Sublevel component names can collide. Downgrade Collision Warnings
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSchemaGenerator.h
  SpatialGDK/Source/SpatialGDKEditorCommandlet/Private/Commandlets/CookAndGenerateSchemaCommandlet.cpp
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/SpatialGDKEditorSchemaGeneratorTest.cpp
Labels: jira/UNR, size/M

#1408 UNR-2209 Bugfix/show invalid deploy config in console
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorSettings.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKSimulatedPlayerDeployment.cpp
Labels: jira/UNR, size/M

#1456 Don't attach new subobject if it's a static subobject that got deleted
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h
Labels: jira/no-ticket, size/S

#1460 UNR-2311 Fix static initialization in SchemaGen tests
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/SpatialGDKEditorSchemaGeneratorTest.cpp
Labels: jira/UNR, size/M

#1459 Add MSVC install workaround to `docs-preview`
  SpatialGDK/Documentation/content/get-started/dependencies.md
  SpatialGDK/Documentation/content/tutorials/multiserver-shooter/tutorial-multiserver-intro.md
Labels: jira/UNR, size/XS

#1458 Add MSVC install workaround to CHANGELOG
  CHANGELOG.md
Labels: jira/UNR, size/S

#1457 Add MSVC install workaround to CHANGELOG
  CHANGELOG.md
Labels: jira/UNR, size/S

#1449 Call ReserveEntityIdsDelegate unconditionally.
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
Labels: jira/no-ticket, size/S

#1461 Quote paths when copying worker coordinator
  CHANGELOG.md
  RequireSetup
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/Build/Build.cs
Labels: jira/no-ticket, size/XS

#1464 Docs - add replicated blueprint timelines to the features support page
  SpatialGDK/Documentation/unreal-features-support.md
Labels: jira/no-ticket, size/S

#1465 UNR-2008 Minor fixes for Schema Generation tests.
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/SpatialGDKEditorSchemaGeneratorTest.cpp
Labels: jira/UNR, size/XS
