Repository spatialos/UnrealGDK, pull requests merged in 2019-08, with the labels that each got.

#1273 Add XBox DLL step to release process
  SpatialGDK/Extras/internal-documentation/release-process.md
Labels: jira/no-ticket, size/XS

#1140 UNR-1338 Automated Test Framework
  SpatialGDK/Source/SpatialGDK/Public/Utils/RPCContainer.h
  SpatialGDK/Source/SpatialGDKTests/Private/RPCContainer/ObjectDummy.cpp
  SpatialGDK/Source/SpatialGDKTests/Private/RPCContainer/ObjectDummy.h
  SpatialGDK/Source/SpatialGDKTests/Private/RPCContainer/ObjectSpy.cpp
  SpatialGDK/Source/SpatialGDKTests/Private/RPCContainer/ObjectSpy.h
  SpatialGDK/Source/SpatialGDKTests/Private/RPCContainer/RPCContainerTest.cpp
  SpatialGDK/Source/SpatialGDKTests/Private/SpatialGDKTestsModule.cpp
  SpatialGDK/Source/SpatialGDKTests/Private/SpatialGDKTestsPrivate.h
  SpatialGDK/Source/SpatialGDKTests/Public/SpatialGDKTestsModule.h
  SpatialGDK/Source/SpatialGDKTests/Public/TestDefinitions.h
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKTests.Build.cs
  SpatialGDK/SpatialGDK.uplugin
Labels: jira/UNR, size/XL

#1272 Feature/vs 2019
  CHANGELOG.md
  SpatialGDK/Build/Scripts/FindMSBuild.bat
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialPlayerSpawner.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/InterestFactory.cpp
Labels: jira/no-ticket, size/M

#1275 Remove step that is no longer needed
  SpatialGDK/Documentation/content/get-started/example-project/exampleproject-local-deployment.md
  SpatialGDK/Documentation/content/get-started/starter-template/get-started-template-local.md
Labels: jira/no-ticket, size/S

#1271 Feature/bifrost/playercontroller rework
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialPlayerSpawner.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
Labels: jira/no-ticket, size/L

#1283 iOS mobile devleopment
  SpatialGDK/Documentation/assets/ios/dev-login-tag.png
  SpatialGDK/Documentation/assets/ios/identify-file-not-accessible.png
  SpatialGDK/Documentation/assets/ios/ip-address.png
  SpatialGDK/Documentation/content/mobile/ios/zh/0-ios-intro.md
  SpatialGDK/Documentation/content/mobile/ios/zh/1-get-started.md
  SpatialGDK/Documentation/content/mobile/ios/zh/2-set-up-ios-support.md
  SpatialGDK/Documentation/content/mobile/ios/zh/3-set-up-macos-environment.md
  SpatialGDK/Documentation/content/mobile/ios/zh/3-set-up-windows-environment.md
  SpatialGDK/Documentation/content/mobile/ios/zh/4-connect-to-local-deployment.md
  SpatialGDK/Documentation/content/mobile/ios/zh/5-connect-to-cloud-deployment.md
Labels: jira/no-ticket, size/XL

#1282 Added change branch for multiserver zoning shooter tutorial
  SpatialGDK/Documentation/content/get-started/example-project/exampleproject-manual-setup.md
  SpatialGDK/Documentation/content/get-started/example-project/exampleproject-setup.md
  SpatialGDK/Documentation/content/tutorials/multiserver-shooter/tutorial-multiserver-cloudtest.md
  SpatialGDK/Documentation/content/tutorials/multiserver-shooter/tutorial-multiserver-healthchanges.md
  SpatialGDK/Documentation/content/tutorials/multiserver-shooter/tutorial-multiserver-intro.md
  SpatialGDK/Documentation/content/tutorials/multiserver-shooter/tutorial-multiserver-localtest.md
  SpatialGDK/Documentation/toc.md
Labels: jira/no-ticket, size/M

#1277 UNR-1857 Unresolved RPC parameters can cause permanent queue blocking
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/RPCContainer.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/RPCContainer.h
Labels: jira/UNR, size/S

#1284 IsListening and ownership fix (#1246)
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialStaticComponentView.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/ClientRPCEndpoint.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/ServerRPCEndpoint.h
Labels: jira/no-ticket, size/M

#1278 UNR-1864 Use GetPlugin helper method to resolve sim player launch config
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorSettings.cpp
Labels: jira/UNR, size/XS

#1286 Docs/doc 1266
  SpatialGDK/Documentation/content/get-started/build-unreal-fork.md
  SpatialGDK/Documentation/content/get-started/dependencies.md
Labels: jira/no-ticket, size/S

#1285 DOC-1256 clarify status of zoning and offloading
  SpatialGDK/Documentation/content/actor-handover.md
  SpatialGDK/Documentation/content/authority.md
  SpatialGDK/Documentation/content/cross-server-rpcs.md
  SpatialGDK/Documentation/content/get-started/introduction.md
  SpatialGDK/Documentation/content/glossary.md
  SpatialGDK/Documentation/content/spatialos-concepts/schema-and-snapshots.md
  SpatialGDK/Documentation/content/technical-overview/gdk-concepts.md
  SpatialGDK/Documentation/content/technical-overview/gdk-principles.md
  SpatialGDK/Documentation/content/tutorials/multiserver-shooter/tutorial-multiserver-intro.md
  SpatialGDK/Documentation/content/tutorials/offloading-tutorial/offloading-gameplay-changes.md
  SpatialGDK/Documentation/content/tutorials/porting-guide/tutorial-portingguide-logs.md
  SpatialGDK/Documentation/content/workers/offloading-concept.md
  SpatialGDK/Documentation/index.md
  SpatialGDK/Documentation/unreal-features-support.md
Labels: jira/DOC, size/L

#1280 DOC-1255 Update GDK and plugin terminology
  README.md
  SpatialGDK/Documentation/assets/screen-grabs/networking-switch.jpg
  SpatialGDK/Documentation/assets/shooting-across-boundaries.png
  SpatialGDK/Documentation/assets/tech-overview/architecture-of-spatialos-gdk-for-unreal-game.jpg
  SpatialGDK/Documentation/assets/tech-overview/networking-switch.png
  SpatialGDK/Documentation/content/get-started/build-unreal-fork.md
  SpatialGDK/Documentation/content/get-started/dependencies.md
  SpatialGDK/Documentation/content/get-started/example-project/exampleproject-intro.md
  SpatialGDK/Documentation/content/get-started/example-project/exampleproject-manual-setup.md
  SpatialGDK/Documentation/content/get-started/example-project/exampleproject-setup.md
  SpatialGDK/Documentation/content/get-started/gdk-template.md
  SpatialGDK/Documentation/content/get-started/introduction.md
  SpatialGDK/Documentation/content/get-started/starter-template/get-started-template-intro.md
  SpatialGDK/Documentation/content/get-started/starter-template/get-started-template-setup-manual.md
  SpatialGDK/Documentation/content/get-started/starter-template/get-started-template-setup.md
  SpatialGDK/Documentation/content/manual-engine-build.md
  SpatialGDK/Documentation/content/pricing-and-support/versioning-scheme.md
  SpatialGDK/Documentation/content/project-setup.md
  SpatialGDK/Documentation/content/technical-overview/gdk-concepts.md
  SpatialGDK/Documentation/content/technical-overview/gdk-principles.md
  SpatialGDK/Documentation/content/technical-overview/how-the-gdk-fits-in.md
  SpatialGDK/Documentation/content/tutorials/dbsync/tutorial-dbsync-intro.md
  SpatialGDK/Documentation/content/tutorials/dbsync/tutorial-dbsync-setup.md
  SpatialGDK/Documentation/content/tutorials/porting-guide/tutorial-portingguide-build.md
  SpatialGDK/Documentation/content/tutorials/tutorial-porting-guide.md
  SpatialGDK/Documentation/toc.md
Labels: jira/DOC, size/M

#1287 DOC-1255 Clarify elements of the GDK in readme
  README.md
Labels: jira/DOC, size/S

#1288 Docs/update game client interest docs
  SpatialGDK/Documentation/content/game-client-interest-management.md
Labels: jira/no-ticket, size/XS

#1279 Feature/refactor spatialos project settings merge
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorCloudLauncher.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorSettings.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKSimulatedPlayerDeployment.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKSimulatedPlayerDeployment.h
  SpatialGDK/Source/SpatialGDKServices/Private/LocalDeploymentManager.cpp
  SpatialGDK/Source/SpatialGDKServices/Private/SpatialGDKServicesModule.cpp
  SpatialGDK/Source/SpatialGDKServices/Public/LocalDeploymentManager.h
  SpatialGDK/Source/SpatialGDKServices/Public/SpatialGDKServicesModule.h
Labels: jira/no-ticket, size/L

#1289 Docs - DOC-1221
  SpatialGDK/Documentation/content/tutorials/deployment-manager/tutorial-deploymentmgr-authentication.md
  SpatialGDK/Documentation/content/tutorials/deployment-manager/tutorial-deploymentmgr-clone.md
  SpatialGDK/Documentation/content/tutorials/deployment-manager/tutorial-deploymentmgr-configure.md
  SpatialGDK/Documentation/content/tutorials/deployment-manager/tutorial-deploymentmgr-intro.md
  SpatialGDK/Documentation/content/tutorials/deployment-manager/tutorial-deploymentmgr-launch.md
  SpatialGDK/Documentation/content/tutorials/deployment-manager/tutorial-deploymentmgr-workers.md
Labels: docs, jira/DOC, size/M

#1281 UNR-1456 Use class path to refer to singleton actors
  SpatialGDK/Extras/schema/core_types.schema
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetBitReader.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetBitWriter.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentFactory.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentReader.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetBitWriter.h
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialPackageMapClient.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialSender.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/UnrealObjectRef.cpp
  SpatialGDK/Source/SpatialGDK/Public/Schema/UnrealObjectRef.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/ComponentFactory.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/SchemaUtils.h
Labels: jira/UNR, size/XXL

#1297 Increment RequireSetup
  RequireSetup
Labels: jira/no-ticket, size/XS

#1298 Adding SPATIALGDK_API declaration to UnrealObjectRef.
  SpatialGDK/Source/SpatialGDK/Public/Schema/UnrealObjectRef.h
Labels: jira/no-ticket, size/XS

#1299 Feature/unr 1936 move generators to spatialgdkeditor
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKDefaultLaunchConfigGenerator.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKDefaultWorkerJsonGenerator.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKDefaultLaunchConfigGenerator.h
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKDefaultWorkerJsonGenerator.h
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorToolbar.h
Labels: jira/no-ticket, size/XL

#1300 UNR-1942 - Switch validity checks to use whats defaulted
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorSettings.cpp
Labels: jira/UNR, size/XS

#1293 UNR-1644: Schema compiler failure should fail schema generation
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp
Labels: jira/UNR, size/XS

#1304 0.6.1 hotfix
  CHANGELOG.md
  README.md
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialStaticComponentView.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/RPCContainer.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/ClientRPCEndpoint.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/ServerRPCEndpoint.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/RPCContainer.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorSettings.cpp
Labels: jira/no-ticket, size/L

#1306 0.6.1 hotfix
  CHANGELOG.md
  README.md
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialStaticComponentView.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/RPCContainer.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/ClientRPCEndpoint.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/ServerRPCEndpoint.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/RPCContainer.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorSettings.cpp
Labels: jira/no-ticket, size/L

#1301 UNR-1957: Generate schema commandlet crashes because editor is missing
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDKEditorCommandlet/Private/Commandlets/GenerateSchemaCommandlet.cpp
Labels: jira/UNR, size/XS

#1308 UNR-1878: Generate Schema Crashes if SchemaDatabase is locked by another process
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp
Labels: jira/UNR, size/XS

#1313 UNR-1908 Release branch merge
  CHANGELOG.md
  README.md
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorSettings.cpp
Labels: jira/UNR, size/M

#1305 UNR-1960 Updated logging for RPC processing
  SpatialGDK/Source/SpatialGDK/Private/Utils/RPCContainer.cpp
  SpatialGDK/Source/SpatialGDK/Public/Utils/RPCContainer.h
  SpatialGDK/Source/SpatialGDKTests/Private/RPCContainer/RPCContainerTest.cpp
Labels: jira/UNR, size/M

#1152 Update release-process.md
  SpatialGDK/Extras/internal-documentation/release-process.md
Labels: docs, jira/no-ticket, size/M

#1310 Feature/unr 1961 disable serverqbi in offloading
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/InterestFactory.cpp
  SpatialGDK/Source/SpatialGDK/Public/Utils/InterestFactory.h
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
Labels: jira/UNR, size/M

#1294 Docs - Add VS 2019 support
  SpatialGDK/Documentation/content/get-started/dependencies.md
Labels: docs, jira/no-ticket, size/XS

#1295 UNR-1402: Crash when attempting to replicate a non supported type
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentFactory.cpp
  SpatialGDK/Source/SpatialGDK/Public/Utils/ComponentFactory.h
Labels: jira/UNR, size/S

#1296 Docs - Typo in the porting guide
  SpatialGDK/Documentation/content/tutorials/porting-guide/tutorial-portingguide-build.md
Labels: docs, jira/no-ticket, size/XS

#1315 Check for entity in view before erroring in create response
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h
Labels: jira/UNR, size/S

#1319 remove old owner
  OWNERS
Labels: jira/no-ticket, size/XS

#1311 UNR-1870 Local Deployment Test
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKDefaultLaunchConfigGenerator.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKDefaultWorkerJsonGenerator.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKDefaultLaunchConfigGenerator.h
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKDefaultWorkerJsonGenerator.h
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
  SpatialGDK/Source/SpatialGDKTests/Private/LocalDeploymentManager/LocalDeploymentManagerTest.cpp
  SpatialGDK/Source/SpatialGDKTests/Private/RPCContainer/RPCContainerTest.cpp
  SpatialGDK/Source/SpatialGDKTests/Public/TestDefinitions.h
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKTests.Build.cs
Labels: jira/UNR, size/XL

#1321 Docs/docs reformat
  SpatialGDK/Documentation/assets/tutorial/deployment-overview-screen.png
  SpatialGDK/Documentation/content/get-started/example-project/exampleproject-play.md
  SpatialGDK/Documentation/content/get-started/starter-template/get-started-template-play.md
Labels: jira/no-ticket, size/M

#1291 UNR-1852 Use spot service health-check instead of spatial service status
  RequireSetup
  SpatialGDK/Extras/spot.version
  SpatialGDK/Source/SpatialGDKServices/Private/LocalDeploymentManager.cpp
  SpatialGDK/Source/SpatialGDKServices/Public/LocalDeploymentManager.h
Labels: jira/UNR, size/M

#1303 UNR-1858 - Added pre run check to local deployment manager
  SpatialGDK/Source/SpatialGDKServices/Private/LocalDeploymentManager.cpp
  SpatialGDK/Source/SpatialGDKServices/Private/SpatialGDKServicesModule.cpp
  SpatialGDK/Source/SpatialGDKServices/Public/LocalDeploymentManager.h
  SpatialGDK/Source/SpatialGDKServices/Public/SpatialGDKServicesModule.h
Labels: jira/UNR, size/M

#1312 UNR-1771: Initial schema generation isn't triggered if you delete SchemaDatabase
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialClassInfoManager.cpp
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditor.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSchemaGenerator.h
Labels: jira/UNR, size/S

#1317 Docs - Unreal features support page cleanup + push out gameplay debugger support
  SpatialGDK/Documentation/unreal-features-support.md
Labels: docs, jira/no-ticket, size/M

#1322 UNR-1796: MacOS fixes since 0.6.0
  Setup.sh
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/Build/Build.csproj
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/CodeGenerator/CodeGenerator.csproj
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/Common/Common.csproj
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/DeploymentLauncher/DeploymentLauncher.csproj
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/Linter/Linter.csproj
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/Mac/Build/Build.csproj
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/Mac/Common/Common.csproj
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/Mac/Improbable.Unreal.Scripts.sln
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/Mac/Linter/Linter.csproj
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/WorkerCoordinator/WorkerCoordinator.csproj
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/WriteLinuxScript/WriteLinuxScript.csproj
  SpatialGDK/SpatialGDK.uplugin
Labels: jira/UNR, size/XL
