Repository spatialos/UnrealGDK, pull requests merged in 2019-09, with the labels that each got.

#1328 No longer register actors which are singletons and also stably named
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
Labels: jira/no-ticket, size/XS

#1330 UNR-1937 - BuildProject.bat filepaths for engine and project plugin
  SpatialGDK/Documentation/content/cloud-deployment-workflow.md
  SpatialGDK/Documentation/content/get-started/example-project/exampleproject-cloud-deployment.md
  SpatialGDK/Documentation/content/get-started/example-project/exampleproject-local-deployment.md
  SpatialGDK/Documentation/content/get-started/starter-template/get-started-template-cloud.md
Labels: docs, jira/UNR, size/M

#1329 Tell users to check out the latest tag, rather than the repo's `master`
  .buildkite/premerge.steps.yaml
  SpatialGDK/Documentation/content/tutorials/dbsync/tutorial-dbsync-setup.md
Labels: jira/no-ticket, size/XS

#1332 Use a proper ScalerV2 queue for docs-release
  .buildkite/premerge.steps.yaml
Labels: jira/no-ticket, size/XS

#1336 Docs - Auto install as first option
  SpatialGDK/Documentation/content/get-started/build-unreal-fork.md
Labels: jira/no-ticket, size/XS

#1331 Zoning tutorial fixes: UNR-1938, UNR-1914
  SpatialGDK/Documentation/content/tutorials/multiserver-shooter/tutorial-multiserver-cloudtest.md
  SpatialGDK/Documentation/content/tutorials/multiserver-shooter/tutorial-multiserver-intro.md
Labels: jira/UNR, size/M

#1327 [GSE-531] Add more stats annotations
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
Labels: jira/GSE, size/S

#1333 Don't ResolveIncomingOperations for objects that have been torn off
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
Labels: jira/no-ticket, size/S

#1324 UNR-1404 Schema / snapshot missing check before local deployment start.
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorSettings.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSchemaGenerator.h
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorToolbar.h
  SpatialGDK/Source/SpatialGDKServices/Private/LocalDeploymentManager.cpp
  SpatialGDK/Source/SpatialGDKServices/Public/LocalDeploymentManager.h
  SpatialGDK/Source/SpatialGDKTests/Private/LocalDeploymentManager/LocalDeploymentManagerTest.cpp
Labels: jira/UNR, size/M

#1341 Docs - remove duplicate linux cross compilation instruction
  SpatialGDK/Documentation/content/get-started/manual-engine-build.md
Labels: docs, jira/no-ticket, size/S

#1307 UNR-954: Expose a simple means to "clear the schema database".
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSchemaGenerator.h
  SpatialGDK/Source/SpatialGDKEditorCommandlet/Private/Commandlets/GenerateSchemaAndSnapshotsCommandlet.cpp
  SpatialGDK/Source/SpatialGDKEditorCommandlet/Private/Commandlets/GenerateSchemaAndSnapshotsCommandlet.h
  SpatialGDK/Source/SpatialGDKEditorCommandlet/Private/Commandlets/GenerateSchemaCommandlet.cpp
  SpatialGDK/Source/SpatialGDKEditorCommandlet/Private/Commandlets/GenerateSchemaCommandlet.h
  SpatialGDK/Source/SpatialGDKEditorCommandlet/SpatialGDKEditorCommandlet.Build.cs
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbarCommands.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorToolbar.h
  SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorToolbarCommands.h
  SpatialGDK/Source/SpatialGDKServices/Private/SpatialGDKServicesModule.cpp
Labels: jira/UNR, size/M

#1338 UNR-1645-Refactor SpatialGDKEditorSettings
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h
Labels: jira/UNR, size/S

#1334 UNR-1993 Worker Metrics Delegate
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialDispatcher.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialMetrics.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialDispatcher.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialMetrics.h
Labels: jira/UNR, size/S

#1345 Remove unused code in schema generator
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SchemaGenerator.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SchemaGenerator.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/TypeStructure.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/TypeStructure.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/Utils/DataTypeUtilities.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/Utils/DataTypeUtilities.h
Labels: jira/no-ticket, size/XL

#1343 Fix missing conversion from UTF8
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
Labels: jira/no-ticket, size/XS

#1349 UNR-2094 Remove shootergame reference (it's on 4.20)
  SpatialGDK/Documentation/content/tutorials/tutorial-porting-guide.md
Labels: jira/UNR, size/XS

#1348 Actor Replication Net Relevancy
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp
  SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h
Labels: jira/no-ticket, size/M

#1339 Feature/unr 1498 snapshot reloading ue interface
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Public/Utils/EngineVersionCheck.h
  ci/unreal-engine.version
Labels: jira/UNR, size/XS

#1359 Fix initial player control in a multi-worker (zoned) deployment.
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
Labels: jira/no-ticket, size/S

#1358 Destroy SpatialWorkerConnection when destroying the NetDriver to be able to disconnect from SpatialOS
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialGameInstance.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialGameInstance.h
Labels: jira/no-ticket, size/S

#1353 UNR-2010: Streaming levels causes error messages with QBI
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
Labels: jira/UNR, size/XS

#1318 DOC-1259: Update Database Integration Guide Docs
  SpatialGDK/Documentation/content/tutorials/dbsync/tutorial-dbsync-syncing.md
Labels: do-not-merge/invalid-owners-file, docs, jira/DOC, size/S

#1363 Remove 420 support
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetConnection.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/GlobalStateManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialClassInfoManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentReader.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetConnection.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditor.cpp
Labels: jira/UNR, size/L

#1365 Check for world before dereferencing
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
Labels: jira/UNR, size/XS

#1342 [UNR-2003] Create CookAndGenerateSchemaCommandlet
  CHANGELOG.md
  RequireSetup
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialClassInfoManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/InterestFactory.cpp
  SpatialGDK/Source/SpatialGDK/Public/Utils/EngineVersionCheck.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SchemaGenerator.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/TypeStructure.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/TypeStructure.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/Utils/CodeWriter.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditor.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSchemaGenerator.h
  SpatialGDK/Source/SpatialGDKEditorCommandlet/Private/Commandlets/CookAndGenerateSchemaCommandlet.cpp
  SpatialGDK/Source/SpatialGDKEditorCommandlet/Private/Commandlets/CookAndGenerateSchemaCommandlet.h
  SpatialGDK/Source/SpatialGDKEditorCommandlet/Private/Commandlets/GenerateSchemaCommandlet.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
  ci/unreal-engine.version
Labels: jira/UNR, size/XL

#1360 UNR-2019: Example Project CI
  .buildkite/premerge.steps.yaml
  ci/build-gdk.ps1
  ci/get-engine.ps1
  ci/setup-and-build-gdk.ps1
  ci/setup-gdk.ps1
Labels: jira/UNR, size/M

#1371 CI: correct triggered pipeline name
  .buildkite/premerge.steps.yaml
Labels: jira/no-ticket, size/XS

#1372 Docs - fix the manual install flow
  SpatialGDK/Documentation/content/get-started/build-unreal-fork.md
  SpatialGDK/Documentation/content/get-started/manual-engine-build.md
  SpatialGDK/Documentation/content/get-started/starter-template/get-started-template-local.md
Labels: docs, jira/no-ticket, size/M

#1373 Add breaking change entry for replicated subobjects
  CHANGELOG.md
Labels: jira/no-ticket, size/XS

#1357 Feature/unr 1488 track deleted startup actors
  CHANGELOG.md
  SpatialGDK/Extras/schema/tombstone.schema
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialSender.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/Tombstone.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
Labels: jira/UNR, size/L

#1350 UNR-2009: Fix spatiald starting with spatial networking disabled
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDKServices/Private/LocalDeploymentManager.cpp
Labels: jira/UNR, size/XS

#1375 UNR-2154: Queued RPCs with unresolved references are never processed in some cases
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h
Labels: jira/UNR, size/S

#1378 Bugfix/UNR-2164 GSM Reception Fix
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
Labels: jira/UNR, size/M

#1366 [UNR-2093] Upgrade to SpatialOS 14.1.0
  CHANGELOG.md
  RequireSetup
  Setup.bat
  Setup.sh
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/WorkerCoordinator/CoordinatorConnection.cs
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/WorkerCoordinator/WorkerCoordinator.csproj
  SpatialGDK/Extras/core-sdk.version
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetConnection.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/OutgoingMessages.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/GlobalStateManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SnapshotManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialDispatcher.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialPlayerSpawner.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialWorkerFlags.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentFactory.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/OpUtils.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialMetrics.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/SpatialWorkerConnection.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialSender.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialWorkerFlags.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/AlwaysRelevant.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/ClientRPCEndpoint.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/Heartbeat.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/Interest.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/RPCPayload.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/ServerRPCEndpoint.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/Singleton.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/SpawnData.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/StandardLibrary.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/Tombstone.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/UnrealMetadata.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/UnrealObjectRef.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialCommonTypes.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialGDKLoader.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/SchemaUtils.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialMetrics.h
  SpatialGDK/Source/SpatialGDK/SpatialGDK.Build.cs
  SpatialGDK/Source/SpatialGDKEditor/Private/SnapshotGenerator/SpatialGDKEditorSnapshotGenerator.cpp
  ci/setup-gdk.ps1
Labels: jira/UNR, size/XL

#1381 Fix schema generation with SpatialOS 14
  SpatialGDK/Extras/schema/spawndata.schema
Labels: size/XS

#1376 Bugfix: Reset SchemaGeneratedClasses before doing in-editor generation
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp
Labels: jira/no-ticket, size/S

#1377 [UNR-1876] Add support for OverrideSpatialOffloading command line argument
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp
  SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h
Labels: jira/UNR, size/S

#1382 Ensure that ActorInterestQueries specify a result type
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/Components/ActorInterestComponent.cpp
Labels: jira/no-ticket, size/XS

#1379 UNR 2168: Remove QBI toggle
  CHANGELOG.md
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/WorkerCoordinator/SpatialConfig/spatialos.SimulatedPlayerCoordinator.worker.json
  SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/InterestFactory.cpp
  SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKDefaultLaunchConfigGenerator.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
Labels: jira/UNR, size/M
