Repository spatialos/UnrealGDK, pull requests merged in 2020-05, with the labels that each got.

#2065 Remove PIE prefix when setting DeploymentMap in GSM
  SpatialGDK/Source/SpatialGDK/Private/Interop/GlobalStateManager.cpp
Labels: jira/no-ticket, size/XS

#2067 Fixed a bug where RPCs called before the CreateEntityRequest were not…
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
Labels: jira/UNR, size/XS

#2062 UNR-3382 Set some runtime settings when we choose different flow in new UI.
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorToolbar.h
Labels: jira/UNR, size/M

#2069 [UNR-3411] Print a better error and don't attempt to connect if dev auth flow deployment not found
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialConnectionManager.cpp
Labels: jira/UNR, size/XS

#2070 Save arguments passed to Setup.bat when creating git hooks
  Setup.bat
Labels: jira/no-ticket, size/XS

#2071 Slow GDK tests will only run nightly
  SpatialGDK/Source/SpatialGDK/Public/Tests/TestDefinitions.h
  SpatialGDK/Source/SpatialGDKTests/SpatialGDK/Utils/Misc/SpatialActivationFlagsTest.cpp
  ci/setup-build-test-gdk.ps1
Labels: jira/no-ticket, size/S

#1922 [UNR-3078] Launch Configuration settings refactorisation + UX improvements
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp
  SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h
  SpatialGDK/Source/SpatialGDKEditor/Private/EditorExtension/GridLBStrategyEditorExtension.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/EditorExtension/GridLBStrategyEditorExtension.h
  SpatialGDK/Source/SpatialGDKEditor/Private/EditorExtension/LBStrategyEditorExtension.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKDefaultLaunchConfigGenerator.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKDefaultWorkerJsonGenerator.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorLayoutDetails.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorModule.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorSettings.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialLaunchConfigCustomization.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialRuntimeLoadBalancingStrategies.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/Utils/LaunchConfigEditor.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/Utils/LaunchConfigEditorLayoutDetails.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/Utils/LaunchConfigEditorLayoutDetails.h
  SpatialGDK/Source/SpatialGDKEditor/Private/Utils/TransientUObjectEditor.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/EditorExtension/LBStrategyEditorExtension.h
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKDefaultLaunchConfigGenerator.h
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorLayoutDetails.h
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialLaunchConfigCustomization.h
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialRuntimeLoadBalancingStrategies.h
  SpatialGDK/Source/SpatialGDKEditor/Public/Utils/LaunchConfigEditor.h
  SpatialGDK/Source/SpatialGDKEditor/Public/Utils/TransientUObjectEditor.h
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKSimulatedPlayerDeployment.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorToolbar.h
  SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKSimulatedPlayerDeployment.h
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/LoadBalancingEditorExtension/SpatialGDKEditorLBExtensionTest.cpp
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/LoadBalancingEditorExtension/TestLoadBalancingStrategyEditorExtension.h
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKServices/LocalDeploymentManager/LocalDeploymentManagerUtilities.cpp
Labels: jira/UNR, size/XXL

#2074 UNR-3407 Async Package Load fix
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
Labels: jira/UNR, size/XS

#2078 [UNR-3078] Launch config files fixups
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKSimulatedPlayerDeployment.cpp
Labels: jira/UNR, size/S

#1998 [UNR-3128] Fix startup actors receiving empty lists
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialClassInfoManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentReader.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialClassInfoManager.h
Labels: jira/UNR, size/M

#2084 Revert "[UNR-3128] Fix startup actors receiving empty lists (#1998)"
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialClassInfoManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentReader.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialClassInfoManager.h
Labels: jira/UNR, size/M

#2068 Worker load can be supplied by the game
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialMetrics.cpp
  SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialMetrics.h
Labels: jira/no-ticket, size/S

#2085 Fix up 0.9.0 CHANGELOG
  CHANGELOG.md
Labels: jira/no-ticket, size/L

#2087 Fix linking unique actors
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Schema/UnrealObjectRef.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialPackageMapClient.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/UnrealObjectRef.h
Labels: jira/no-ticket, size/M

#2088 Add deployment tags field to Cloud Deployment window
  CHANGELOG.md
  RequireSetup
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/DeploymentLauncher/DeploymentLauncher.cs
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorCloudLauncher.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorSettings.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKSimulatedPlayerDeployment.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKSimulatedPlayerDeployment.h
Labels: jira/no-ticket, size/M

#2090 Final Changelog proofread before translation
  CHANGELOG.md
Labels: jira/no-ticket, size/S

#2094 Fix release CI
  ci/setup-build-test-gdk.ps1
Labels: jira/no-ticket, size/XS

#2089 Tidy up cloud deployment clusters
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorCloudLauncher.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKSimulatedPlayerDeployment.cpp
Labels: jira/no-ticket, size/S

#2082 Add connection flow setting and expose local runtime IP and dev auth params to engine
  SpatialGDK/Source/SpatialGDK/Public/Utils/EngineVersionCheck.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorModule.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorSettings.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorModule.h
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
Labels: jira/no-ticket, size/M

#2093 Remove Unreal 4.22 support
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentFactory.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentReader.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialFastArrayNetSerialize.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialConditionMapFilter.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/RepLayoutUtils.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/TypeStructure.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditor.cpp
  SpatialGDK/Source/SpatialGDKEditorCommandlet/Private/Commandlets/CookAndGenerateSchemaCommandlet.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKSimulatedPlayerDeployment.cpp
  SpatialGDK/Source/SpatialGDKServices/Private/LocalDeploymentManager.cpp
Labels: jira/no-ticket, size/L

#2100 Bugfix/nullrhi with spatial debugger
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialDebugger.cpp
Labels: jira/no-ticket, size/XS

#2102 Add a button to open console page
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKSimulatedPlayerDeployment.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKSimulatedPlayerDeployment.h
Labels: jira/UNR, size/M

#2107 Fix creating deployment with empty tags
  RequireSetup
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/DeploymentLauncher/DeploymentLauncher.cs
Labels: jira/no-ticket, size/XS

#2075 RPCs can now be called on UINTERFACE
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Public/Utils/RepLayoutUtils.h
Labels: jira/UNR, size/XS

#2109 0.9.0 master merge
  CHANGELOG.md
  SpatialGDK/SpatialGDK.uplugin
Labels: jira/no-ticket, size/L

#2101 Fix using event instead of sleep in non-flushing cases
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/SpatialWorkerConnection.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/WorkerConnectionCoordinator.h
Labels: jira/no-ticket, size/XS

#2103 UNR-3423
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h
Labels: jira/UNR, size/XS

#2104 UNR-3422 Remove Win32 Platform Option
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorPackageAssembly.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorSettings.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorPackageAssembly.h
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKSimulatedPlayerDeployment.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKSimulatedPlayerDeployment.h
Labels: jira/UNR, size/M

#2058 Fix typo
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
Labels: jira/no-ticket, size/XS

#2112 UNR-3429 When starting local deployment, grey out the start button.
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
Labels: jira/UNR, size/XS

#2117 Adjustments / suggestions
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKSimulatedPlayerDeployment.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKSimulatedPlayerDeployment.h
Labels: jira/UNR, size/M

#2060 Bugfix/unr 3072 commandline configuration
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialConnectionManager.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/ConnectionConfig.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
  SpatialGDK/Source/SpatialGDKTests/SpatialGDK/Interop/Connection/SpatialConnectionManagerTest.cpp
  SpatialGDK/Source/SpatialGDKTests/SpatialGDK/Interop/Connection/SpatialWorkerConnectionTest.cpp
Labels: jira/UNR, size/XL

#2108 Process auth gained before actor creation
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
Labels: jira/no-ticket, size/XS

#2072 Enable zoning automated tests in CI
  ci/run-tests.ps1
  ci/setup-build-test-gdk.ps1
Labels: jira/no-ticket, size/M

#2105 UNR-3421 Swap the toolbar button actions for deployment
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbarCommands.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbarStyle.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorToolbar.h
  SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorToolbarCommands.h
Labels: jira/UNR, size/S

#2116 UNR-3425 Add regex checking on text committed for deployment and assembly name.
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKSimulatedPlayerDeployment.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKSimulatedPlayerDeployment.h
Labels: jira/UNR, size/M

#2121 URN-2570 Make the Cloud Deployment Settings Window unique
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorToolbar.h
Labels: jira/URN, size/M

#2086 Add a setting to auto start PIE clients when launching on device
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorModule.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorSettings.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorModule.h
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h
Labels: jira/no-ticket, size/XS

#2114 UNR-3427 Prevent users from specifying invalid IP or deployment name in the dropdown menu.
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
Labels: jira/UNR, size/S

#2046 UNR-3066: Only apply OwnerOnly components when gaining authority
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/InterestFactory.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/InterestFactory.h
Labels: jira/UNR, size/M

#2118 Bugfix/sim player auth issue
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/Common/LinuxScripts.cs
Labels: jira/no-ticket, size/XS

#2098 UNR-2988 Remove schema generation test hack
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/ExpectedSchema/NonSpatialTypeActor.schema
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/ExpectedSchema/SpatialTypeActor.schema
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/ExpectedSchema/SpatialTypeActorWithActorComponent.schema
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/ExpectedSchema/SpatialTypeActorWithMultipleActorComponents.schema
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/ExpectedSchema/SpatialTypeActorWithMultipleObjectComponents.schema
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/ExpectedSchema_4.24/NonSpatialTypeActor.schema
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/ExpectedSchema_4.24/SpatialTypeActor.schema
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/ExpectedSchema_4.24/SpatialTypeActorComponent.schema
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/ExpectedSchema_4.24/SpatialTypeActorWithActorComponent.schema
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/ExpectedSchema_4.24/SpatialTypeActorWithMultipleActorComponents.schema
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/ExpectedSchema_4.24/SpatialTypeActorWithMultipleObjectComponents.schema
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/ExpectedSchema_4.24/rpc_endpoints.schema
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/SpatialGDKEditorSchemaGeneratorTest.cpp
Labels: jira/UNR, size/XL

#2095 [UNR-2908] Add access to CookAndGenerateSchema to the GDK toolbar.
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Public/Utils/EngineVersionCheck.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditor.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorSettings.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditor.h
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h
  SpatialGDK/Source/SpatialGDKEditorCommandlet/Private/Commandlets/CookAndGenerateSchemaCommandlet.cpp
  SpatialGDK/Source/SpatialGDKEditorCommandlet/Private/Commandlets/GenerateSchemaAndSnapshotsCommandlet.cpp
  SpatialGDK/Source/SpatialGDKEditorCommandlet/Private/Commandlets/GenerateSchemaCommandlet.cpp
  SpatialGDK/Source/SpatialGDKEditorCommandlet/SpatialGDKEditorCommandlet.Build.cs
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/SpatialGDKEditorToolbar.Build.cs
  ci/run-tests.ps1
  ci/run-tests.sh
Labels: jira/UNR, size/L

#2125 Display the Notification about cloud deployment.
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
Labels: jira/no-ticket, size/XS

#2113 UNR-3420 - Dev Auth Token Generation performed Asynchronously
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKDevAuthTokenGenerator.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditor.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKDevAuthTokenGenerator.h
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditor.h
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
Labels: jira/UNR, size/L

#2073 Cleanup network initialized actors only after connection to SpatialOS.
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialGameInstance.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialGameInstance.h
Labels: jira/UNR, size/M

#2127 Don't infer useExternalIpForBridge from the presence of an external r…
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/ConnectionConfig.h
  SpatialGDK/Source/SpatialGDKTests/SpatialGDK/Interop/Connection/SpatialConnectionManagerTest.cpp
Labels: jira/no-ticket, size/S

#2122 Package assembly from the Editor
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
  SpatialGDK/Source/SpatialGDKEditor/Private/CloudDeploymentConfiguration.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SnapshotGenerator/SpatialGDKEditorSnapshotGenerator.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditor.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorCloudLauncher.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorPackageAssembly.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorSettings.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/CloudDeploymentConfiguration.h
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditor.h
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorCloudLauncher.h
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorPackageAssembly.h
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSnapshotGenerator.h
  SpatialGDK/Source/SpatialGDKEditor/SpatialGDKEditor.Build.cs
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbarCommands.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbarStyle.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKSimulatedPlayerDeployment.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorToolbar.h
  SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorToolbarCommands.h
  SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKSimulatedPlayerDeployment.h
  SpatialGDK/Source/SpatialGDKServices/Private/SpatialCommandUtils.cpp
  SpatialGDK/Source/SpatialGDKServices/Public/SpatialGDKServicesConstants.h
Labels: jira/UNR, size/XXL

#2128 Add missing '#pragma once'
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorModule.h
  SpatialGDK/Source/SpatialGDKEditorCommandlet/Public/SpatialGDKEditorCommandletModule.h
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKServices/LocalDeploymentManager/LocalDeploymentManagerUtilities.h
Labels: jira/no-ticket, size/XS

#2015 [UNR-3201] Fix multiple dynamic subobjects being created in the same tick
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/InterestFactory.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/InterestFactory.h
Labels: jira/UNR, size/M

#2129 Move build client and simplayer checkboxes
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorToolbar.h
Labels: jira/UNR, size/S

#2132 UNR-3408 Automatically remove UE4Commandline.txt when the launcher session ended.
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKDevAuthTokenGenerator.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorCommandLineArgsManager.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorLayoutDetails.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorModule.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorCommandLineArgsManager.h
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorLayoutDetails.h
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorModule.h
  SpatialGDK/Source/SpatialGDKServices/Private/SpatialCommandUtils.cpp
  SpatialGDK/Source/SpatialGDKServices/Public/SpatialCommandUtils.h
Labels: jira/UNR, size/XXL

#2133 UNR-3390 - On Mac do not support launch cloud deployment
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
Labels: jira/UNR, size/XS

#2137 UNR-3408 Automatically remove UE4Commandline.txt when the launcher session ended.
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKDevAuthTokenGenerator.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorCommandLineArgsManager.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorLayoutDetails.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorModule.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorCommandLineArgsManager.h
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorLayoutDetails.h
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorModule.h
  SpatialGDK/Source/SpatialGDKEditor/SpatialGDKEditor.Build.cs
  SpatialGDK/Source/SpatialGDKServices/Private/SpatialCommandUtils.cpp
  SpatialGDK/Source/SpatialGDKServices/Public/SpatialCommandUtils.h
Labels: jira/UNR, size/XXL

#2110 Update release-process.md
  SpatialGDK/Extras/internal-documentation/release-process.md
Labels: jira/no-ticket, size/S

#2141 Fix nightly CI
  ci/run-tests.ps1
  ci/run-tests.sh
Labels: jira/no-ticket, size/XS

#2026 Added user-level op logging
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialConnectionManager.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/ConnectionConfig.h
Labels: jira/no-ticket, size/M

#2139 UNR-3481 Failed schema generation aborts quick deploy
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorToolbar.h
Labels: jira/UNR, size/M

#2147 Add NetOwningClient worker to enforcer worker query
  SpatialGDK/Source/SpatialGDK/Private/Utils/InterestFactory.cpp
Labels: jira/no-ticket, size/XS

#2136 Change spammy logs to Verbose
  SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/OwnershipLockingPolicy.cpp
Labels: jira/no-ticket, size/XS

#2123 Feature/user supplied metrics
  SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialMetrics.cpp
  SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialMetrics.h
Labels: jira/no-ticket, size/M

#2126 Reserve server worker entity
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/EntityPool.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialPackageMapClient.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialSender.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/EntityPool.h
Labels: jira/no-ticket, size/M

#2144 New icons for the toolbar
  CHANGELOG.md
  SpatialGDK/Resources/Cloud.png
  SpatialGDK/Resources/Cloud@0.5x.png
  SpatialGDK/Resources/Inspector.png
  SpatialGDK/Resources/Inspector@0.5x.png
  SpatialGDK/Resources/Launch.png
  SpatialGDK/Resources/Launch@0.5x.png
  SpatialGDK/Resources/None.png
  SpatialGDK/Resources/None@0.5x.png
  SpatialGDK/Resources/Schema.png
  SpatialGDK/Resources/Schema@0.5x.png
  SpatialGDK/Resources/Snapshot.png
  SpatialGDK/Resources/Snapshot@0.5x.png
  SpatialGDK/Resources/StartCloud.png
  SpatialGDK/Resources/StartCloud@0.5x.png
  SpatialGDK/Resources/StartLocal.png
  SpatialGDK/Resources/StartLocal@0.5x.png
  SpatialGDK/Resources/Stop.png
  SpatialGDK/Resources/Stop@0.5x.png
  SpatialGDK/Resources/StopCloud.png
  SpatialGDK/Resources/StopCloud@0.5x.png
  SpatialGDK/Resources/StopLocal.png
  SpatialGDK/Resources/StopLocal@0.5x.png
  SpatialGDK/Resources/Upload.png
  SpatialGDK/Resources/Upload@0.5x .png
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbarCommands.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbarStyle.cpp
Labels: jira/no-ticket, size/S

#2152 Prevent new actor channels for dying actors
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
Labels: jira/no-ticket, size/S

#2143 [UNR-3503] Check that AutomationTool is up to date when running Schema generation from the editor
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditor.cpp
Labels: jira/UNR, size/M

#2155 Re-enable linux build for the EngineNetTest repo
  ci/generate-and-upload-build-steps.sh
Labels: jira/no-ticket, size/XS

#2135 New connection flow UI
  CHANGELOG.md
  SpatialGDK/Resources/Cloud.png
  SpatialGDK/Resources/Cloud@0.5x.png
  SpatialGDK/Resources/Inspector.png
  SpatialGDK/Resources/Inspector@0.5x.png
  SpatialGDK/Resources/Launch.png
  SpatialGDK/Resources/Launch@0.5x.png
  SpatialGDK/Resources/None.png
  SpatialGDK/Resources/None@0.5x.png
  SpatialGDK/Resources/Schema.png
  SpatialGDK/Resources/Schema@0.5x.png
  SpatialGDK/Resources/Snapshot.png
  SpatialGDK/Resources/Snapshot@0.5x.png
  SpatialGDK/Resources/StartCloud.png
  SpatialGDK/Resources/StartCloud@0.5x.png
  SpatialGDK/Resources/StartLocal.png
  SpatialGDK/Resources/StartLocal@0.5x.png
  SpatialGDK/Resources/Stop.png
  SpatialGDK/Resources/Stop@0.5x.png
  SpatialGDK/Resources/StopCloud.png
  SpatialGDK/Resources/StopCloud@0.5x.png
  SpatialGDK/Resources/StopLocal.png
  SpatialGDK/Resources/StopLocal@0.5x.png
  SpatialGDK/Resources/Upload.png
  SpatialGDK/Resources/Upload@0.5x .png
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialConnectionManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKDevAuthTokenGenerator.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditor.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorLayoutDetails.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorSettings.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKDevAuthTokenGenerator.h
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditor.h
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbarCommands.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbarStyle.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKSimulatedPlayerDeployment.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorToolbar.h
  SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorToolbarCommands.h
  SpatialGDK/Source/SpatialGDKServices/Private/SpatialCommandUtils.cpp
  SpatialGDK/Source/SpatialGDKServices/Public/SpatialCommandUtils.h
Labels: jira/no-ticket, size/XXL

#2148 Delay actor migration till after entity created
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/EntityFactory.cpp
Labels: jira/no-ticket, size/S

#2157 Bugfix/worker flush
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/ConnectionConfig.h
Labels: jira/no-ticket, size/XS

#2149 [UNR-3395] Fix crash on subobject attachment when channel is closed
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h
Labels: jira/UNR, size/S

#2142 Bugfix/wait zero doesnt sleep
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/WorkerConnectionCoordinator.h
Labels: jira/no-ticket, size/S

#2134 Add Layered LB Strategy
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialVirtualWorkerTranslationManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/GridBasedLBStrategy.cpp
  SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/LayeredLBStrategy.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialVirtualWorkerTranslationManager.h
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialWorldSettings.h
  SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/AbstractLBStrategy.h
  SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/GridBasedLBStrategy.h
  SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/LayeredLBStrategy.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/LayerInfo.h
  SpatialGDK/Source/SpatialGDKTests/SpatialGDK/EngineClasses/SpatialVirtualWorkerTranslationManager/SpatialVirtualWorkerTranslationManagerTest.cpp
  SpatialGDK/Source/SpatialGDKTests/SpatialGDK/LoadBalancing/GridBasedLBStrategy/GridBasedLBStrategyTest.cpp
Labels: jira/UNR, size/XL

#2163 Failure notification in package assembly when schema or snapshot fails
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorToolbar.h
Labels: jira/UNR, size/M

#2131 [UNR-3472] New runtime settings
  SpatialGDK/Source/SpatialGDKEditor/Private/CloudDeploymentConfiguration.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorLayoutDetails.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorModule.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorSettings.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialRuntimeVersionCustomization.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialRuntimeVersionCustomization.h
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKSimulatedPlayerDeployment.cpp
  SpatialGDK/Source/SpatialGDKServices/Private/LocalDeploymentManager.cpp
  SpatialGDK/Source/SpatialGDKServices/Public/SpatialGDKServicesConstants.h
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKServices/LocalDeploymentManager/LocalDeploymentManagerUtilities.cpp
Labels: jira/UNR, size/XXL

#2164 Push/remove command line args for mobile
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorCommandLineArgsManager.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorLayoutDetails.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorModule.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorCommandLineArgsManager.h
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorLayoutDetails.h
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorModule.h
  SpatialGDK/Source/SpatialGDKEditor/SpatialGDKEditor.Build.cs
Labels: jira/UNR, size/XL

#2160 UNR-3485 Friendly dev auth error message
  SpatialGDK/Source/SpatialGDKServices/Private/SpatialCommandUtils.cpp
Labels: jira/UNR, size/XS

#2158 UNR-3486 Popup message box for user actionable errors
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorPackageAssembly.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorPackageAssembly.h
Labels: jira/UNR, size/S

#2153 UNR-3528 Remove last usage of dynamic worker flags
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/DeploymentLauncher/DeploymentLauncher.cs
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/WorkerCoordinator/ManagedWorkerCoordinator.cs
Labels: jira/UNR, size/M

#2162 Bugfix/fix case
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/WorkerConnectionCoordinator.h
Labels: jira/no-ticket, size/XS

#2151 [UNR-3526] Allow specifying port from `open ip:port`
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialConnectionManager.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/ConnectionConfig.h
  SpatialGDK/Source/SpatialGDKTests/SpatialGDK/Interop/Connection/SpatialConnectionManagerTest.cpp
Labels: jira/UNR, size/M

#2161 UNR-3482 Copy cloud deployment name from the cloud deployment window to the Start dropdown
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
Labels: jira/UNR, size/XS

#2170 Save config when selecting connection flow
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorSettings.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
Labels: jira/no-ticket, size/XS

#2171 Fix connecting to local deployment from 'Push settings to device'
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorCommandLineArgsManager.cpp
Labels: jira/no-ticket, size/XS

#2156 [UNR-3532] Better platform selection for cook and generate schema
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorSettings.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h
Labels: jira/UNR, size/S
