Repository spatialos/UnrealGDK, pull requests merged in 2020-12, with the labels that each got.

#2707 Feature/unr 4536 property update traces
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialGDKSpanId.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialTraceEventBuilder.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialTraceUniqueId.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/RPCs/SpatialRPCService.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentReader.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/SpatialTraceEventBuilder.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/SpatialTraceUniqueId.h
Labels: jira/UNR, size/L

#2719 UNR-3519 Fix multiple client travel
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
Labels: jira/UNR, size/XS

#2723 Remove "." from key string
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialTraceEventBuilder.cpp
Labels: jira/no-ticket, size/XS

#2721 Fix scope for FSpatialNetBitReader lifecycle
  SpatialGDK/Source/SpatialGDK/Private/Interop/RPCs/SpatialRPCService.cpp
Labels: jira/UNR, size/XS

#2713 V15 Standalone
  CHANGELOG.md
  Setup.bat
  Setup.sh
  SpatialGDK/Extras/spot.version
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/SpatialOSWorkerInterface.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/EntityFactory.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKDefaultLaunchConfigGenerator.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditor.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorModule.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorSettings.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/Utils/LaunchConfigurationEditor.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKDefaultLaunchConfigGenerator.h
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h
  SpatialGDK/Source/SpatialGDKEditor/Public/Utils/LaunchConfigurationEditor.h
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKCloudDeploymentConfiguration.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorToolbar.h
  SpatialGDK/Source/SpatialGDKServices/Private/LocalDeploymentManager.cpp
  SpatialGDK/Source/SpatialGDKServices/Private/SSpatialOutputLog.cpp
  SpatialGDK/Source/SpatialGDKServices/Private/SpatialCommandUtils.cpp
  SpatialGDK/Source/SpatialGDKServices/Private/SpatialGDKServicesModule.cpp
  SpatialGDK/Source/SpatialGDKServices/Public/LocalDeploymentManager.h
  SpatialGDK/Source/SpatialGDKServices/Public/SSpatialOutputLog.h
  SpatialGDK/Source/SpatialGDKServices/Public/SpatialCommandUtils.h
  SpatialGDK/Source/SpatialGDKServices/Public/SpatialGDKServicesConstants.h
  SpatialGDK/Source/SpatialGDKServices/Public/SpatialGDKServicesModule.h
  SpatialGDK/Source/SpatialGDKTests/SpatialGDK/Interop/Connection/SpatialWorkerConnectionTest.cpp
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKServices/LocalDeploymentManager/LocalDeploymentManagerUtilities.cpp
Labels: jira/no-ticket, size/XXL

#2724 Bugfix/et crash fix
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
Labels: jira/no-ticket, size/XS

#2715 Feature/add player disconnect command
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialOSDispatcherInterface.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
Labels: jira/no-ticket, size/M

#2718 Feature/unr 4576 spatial view 15 - Part 1
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialConnectionManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialView/ViewCoordinator.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialView/ViewDelta.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialView/WorkerView.cpp
  SpatialGDK/Source/SpatialGDK/Private/Tests/SpatialView/CommandRetryHandlerTest.cpp
  SpatialGDK/Source/SpatialGDK/Private/Tests/SpatialView/DispatcherTest.cpp
  SpatialGDK/Source/SpatialGDK/Private/Tests/SpatialView/SubViewTest.cpp
  SpatialGDK/Source/SpatialGDK/Private/Tests/SpatialView/ViewCoordinatorTest.cpp
  SpatialGDK/Source/SpatialGDK/Private/Tests/SpatialView/ViewDeltaTest.cpp
  SpatialGDK/Source/SpatialGDK/Private/Tests/SpatialView/WorkerViewTest.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/SpatialWorkerConnection.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialView/ComponentSetData.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialView/ViewCoordinator.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialView/ViewDelta.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialView/WorkerView.h
  SpatialGDK/Source/SpatialGDK/Public/Tests/SpatialView/SpatialViewUtils.h
Labels: jira/UNR, size/XXL

#2726 Bugfix/fix debug interface not updating
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriverDebugContext.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialVirtualWorkerTranslationManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialStaticComponentView.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/EntityFactory.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/InterestFactory.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialSender.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialStaticComponentView.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/EntityFactory.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/InterestFactory.h
Labels: jira/no-ticket, size/M

#2727 Update worker flag api
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialDispatcher.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialWorkerFlags.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialWorkerFlags.h
  SpatialGDK/Source/SpatialGDKTests/SpatialGDK/Interop/SpatialWorkerFlags/SpatialWorkerFlagsTest.cpp
Labels: jira/no-ticket, size/L

#2730 Update taskkill plugin
  .buildkite/premerge.steps.yaml
  ci/gdk_build.template.steps.yaml
Labels: jira/no-ticket, size/XS

#2732 Feature/unr 4491 add server only always relevant interest
  RequireSetup
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialClassInfoManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/EntityFactory.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/InterestFactory.cpp
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/InterestFactory.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/RelevancyTest/RelevancyTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/RelevancyTest/RelevancyTest.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/TestActors/RelevancyTestActors.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/TestActors/RelevancyTestActors.h
Labels: jira/UNR, size/L

#2734 fix Setup.sh
  Setup.sh
Labels: jira/no-ticket, size/S

#2737 Support downloading runtime bundles in China
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
  SpatialGDK/Source/SpatialGDKServices/Private/SpatialCommandUtils.cpp
  SpatialGDK/Source/SpatialGDKServices/Public/SpatialCommandUtils.h
  SpatialGDK/Source/SpatialGDKServices/Public/SpatialGDKServicesConstants.h
Labels: jira/no-ticket, size/M

#2741 Event tracing tests fix up
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/EventTracingTests/EventTracingTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/EventTracingTests/EventTracingTest.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/EventTracingTests/ProcessRPCEventTracingTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/EventTracingTests/ProcessRPCEventTracingTest.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/EventTracingTests/UserSendPropertyEventTracingTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/EventTracingTests/UserSendRPCEventTracingTest.cpp
Labels: jira/no-ticket, size/M

#2674 Feature/unr 4416 cross worker migration diagnostics
  CHANGELOG.md
  SpatialGDK/Extras/schema/migration_diagnostic.schema
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/EntityFactory.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialLoadBalancingHandler.cpp
  SpatialGDK/Source/SpatialGDK/Public/Schema/MigrationDiagnostic.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialLoadBalancingHandler.h
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/SpatialGDKEditorSchemaGeneratorTest.cpp
Labels: jira/UNR, size/XL

#2745 Bugfix/add serveronlyalwaysrelevant schema
  CHANGELOG.md
  RequireSetup
  SpatialGDK/Extras/schema/relevant.schema
Labels: jira/no-ticket, size/XS

#2735 Feature/unr 4576 fix the tests
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialView/OpList/EntityComponentOpList.cpp
  SpatialGDK/Source/SpatialGDK/Private/Tests/SpatialView/CommandRetryHandlerTest.cpp
  SpatialGDK/Source/SpatialGDK/Private/Tests/SpatialView/DispatcherTest.cpp
  SpatialGDK/Source/SpatialGDK/Private/Tests/SpatialView/ExpectedViewDelta.cpp
  SpatialGDK/Source/SpatialGDK/Private/Tests/SpatialView/SubViewTest.cpp
  SpatialGDK/Source/SpatialGDK/Private/Tests/SpatialView/ViewCoordinatorTest.cpp
  SpatialGDK/Source/SpatialGDK/Private/Tests/SpatialView/ViewDeltaTest.cpp
  SpatialGDK/Source/SpatialGDK/Private/Tests/SpatialView/WorkerViewTest.cpp
  SpatialGDK/Source/SpatialGDK/Public/SpatialView/OpList/EntityComponentOpList.h
  SpatialGDK/Source/SpatialGDK/Public/Tests/SpatialView/SpatialViewUtils.h
Labels: jira/UNR, size/XXL

#2743 Fix GDK CI
  ci/setup-build-test-gdk.ps1
Labels: jira/no-ticket, size/XS

#2746 fix: remove unused option
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorSettings.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h
Labels: jira/no-ticket, size/XS

#2740 Update to v15-preview-5
  SetupIncTraceLibs.bat
  SpatialGDK/Extras/core-sdk.version
  SpatialGDK/Source/SpatialGDKServices/Public/SpatialGDKServicesConstants.h
Labels: jira/no-ticket, size/XS

#2731 Add partition component and track on controllers
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialStaticComponentView.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialStaticComponentView.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/Restricted.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
Labels: jira/UNR, size/M

#2728 UNR-4609 fix: ensure automation tests start from clean slate
  SpatialGDK/Source/SpatialGDKTests/Public/GDKAutomationTestBase.h
  SpatialGDK/Source/SpatialGDKTests/SpatialGDK/EngineClasses/SpatialVirtualWorkerTranslator/SpatialVirtualWorkerTranslatorTest.cpp
  SpatialGDK/Source/SpatialGDKTests/SpatialGDK/Interop/Connection/SpatialConnectionManagerTest.cpp
  SpatialGDK/Source/SpatialGDKTests/SpatialGDK/Interop/Connection/SpatialWorkerConnectionTest.cpp
  SpatialGDK/Source/SpatialGDKTests/SpatialGDK/Interop/SpatialWorkerFlags/SpatialWorkerFlagsTest.cpp
  SpatialGDK/Source/SpatialGDKTests/SpatialGDK/LoadBalancing/GridBasedLBStrategy/GridBasedLBStrategyTest.cpp
  SpatialGDK/Source/SpatialGDKTests/SpatialGDK/LoadBalancing/LayeredLBStrategy/LayeredLBStrategyTest.cpp
  SpatialGDK/Source/SpatialGDKTests/SpatialGDK/LoadBalancing/OwnershipLockingPolicy/OwnershipLockingPolicyTest.cpp
  SpatialGDK/Source/SpatialGDKTests/SpatialGDK/Schema/UnrealObjectRef/UnrealObjectRefTests.cpp
  SpatialGDK/Source/SpatialGDKTests/SpatialGDK/Utils/CheckoutRadiusConstraintUtils/NetCullDistanceInterestTest.cpp
  SpatialGDK/Source/SpatialGDKTests/SpatialGDK/Utils/RPCContainer/RPCContainerTest.cpp
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKServices/LocalDeploymentManager/LocalDeploymentManagerUtilities.cpp
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKServices/LocalDeploymentManager/LocalDeploymentManagerUtilities.h
Labels: jira/UNR, size/L

#2705 [UNR-4342] 4.26 Support
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialClassInfoManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReplicationGraphLoadBalancingHandler.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReplicationGraphLoadBalancingHandler.h
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/EntityFactory.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h
  SpatialGDK/Source/SpatialGDK/Public/Tests/TestActor.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/SpatialFunctionalTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Public/SpatialFunctionalTest.h
  SpatialGDK/Source/SpatialGDKServices/Private/LocalDeploymentManager.cpp
  SpatialGDK/Source/SpatialGDKTests/Examples/SpatialGDKExampleTest.cpp
  SpatialGDK/Source/SpatialGDKTests/SpatialGDK/Utils/CheckoutRadiusConstraintUtils/NetCullDistanceInterestTest.cpp
Labels: jira/UNR, size/M

#2739 [UNR-4482] Change how bCanSpawnActorWithAuthority is set after an update
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/Interop/GlobalStateManager.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialSnapshotTest/SpatialSnapshotTest.cpp
Labels: jira/UNR, size/M

#2671 UNR-4318 fix: server workers use TCP by default
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/ConnectionConfig.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/ConnectionConfig.h
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKServices/LocalDeploymentManager/LocalDeploymentManagerUtilities.cpp
Labels: jira/UNR, size/M

#2744 Unr 4441 - Handover dynamically set bReplicates
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestHandoverReplication/DynamicReplicationHandoverCube.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestHandoverReplication/DynamicReplicationHandoverCube.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestHandoverReplication/SpatialTestHandoverReplication.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestHandoverReplication/SpatialTestHandoverReplication.h
Labels: jira/no-ticket, size/L

#2753 Early out from replication if UpdateChangelistMgr fails
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
Labels: jira/no-ticket, size/S

#2750 UNR-1628/Remove runtime library build workaround
  SpatialGDK/Source/SpatialGDK/SpatialGDK.Build.cs
Labels: jira/UNR, size/XS

#2729 UNR-4611 Speculative crash fix
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Public/SpatialCommonTypes.h
Labels: jira/UNR, size/M

#2756 Update to preview-6
  SpatialGDK/Extras/core-sdk.version
  SpatialGDK/Source/SpatialGDKServices/Public/SpatialGDKServicesConstants.h
Labels: jira/no-ticket, size/XS

#2759 Fix build
  SpatialGDK/Source/SpatialGDK/Public/SpatialCommonTypes.h
Labels: jira/no-ticket, size/XS

#2758 UNR-3880 - Set focus to output log on Cloud Deployment
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
Labels: jira/UNR, size/XS

#2760 Bugfix/unr 4619 remove legacy rpcs
  SpatialGDK/Extras/schema/rpc_components.schema
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialStaticComponentView.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/EntityFactory.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialLatencyTracer.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialSender.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/ClientRPCEndpointLegacy.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/RPCPayload.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/ServerRPCEndpointLegacy.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/EntityFactory.h
Labels: jira/UNR, size/XL

#2761 Switch to 4.26 in CI
  ci/generate-and-upload-build-steps.sh
  ci/unreal-engine.version
Labels: jira/no-ticket, size/XS

#2717 [UNR-4474] Remote ability activation (changelog message)
  CHANGELOG.md
Labels: jira/UNR, size/XS

#2755 Fix race condition in Spatial Test framework that would cause tests t…
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/SpatialFunctionalTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/SpatialFunctionalTestFlowController.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Public/SpatialFunctionalTestFlowController.h
Labels: jira/UNR, size/S

#2764 NFR build fix
  SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialLatencyTracer.h
Labels: jira/no-ticket, size/XS

#2765 [UNR-4687] Fix deprecation warning for InvokeTab in 4.26
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
Labels: jira/UNR, size/XS

#2766 Example Project Android CI Fix
  SpatialGDK/Source/SpatialGDK/SpatialGDK.Build.cs
Labels: jira/no-ticket, size/XS

#2752 UNR-811 Spatial Switch Has Authority
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialStatics.cpp
  SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialStatics.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialAuthorityTest/SpatialAuthorityTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialAuthorityTest/SpatialAuthorityTest.h
Labels: jira/UNR, size/L

#2767 Fix for android
  SpatialGDK/Source/SpatialGDK/SpatialGDK.Build.cs
Labels: jira/no-ticket, size/XS

#2768 Fix for 4.26
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
Labels: jira/no-ticket, size/XS

#2769 Update Engine versions for RC CI
  ci/unreal-engine.version
Labels: jira/no-ticket, size/XS

#2720 Cross Server RPC Handler and Sender
  RequireSetup
  SpatialGDK/Extras/schema/rpc_payload.schema
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/CrossServerRPCHandler.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/CrossServerRPCSender.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/RPCExecutor.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialDispatcher.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialView/OpList/EntityComponentOpList.cpp
  SpatialGDK/Source/SpatialGDK/Private/Tests/CrossServerRPCHandlerTest.cpp
  SpatialGDK/Source/SpatialGDK/Private/Tests/RPCServiceTest.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/CrossServerRPCHandler.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/CrossServerRPCParams.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/CrossServerRPCSender.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/RPCExecutor.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/RPCExecutorInterface.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialSender.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/RPCPayload.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialView/OpList/EntityComponentOpList.h
  SpatialGDK/Source/SpatialGDKTests/SpatialGDK/Utils/RPCContainer/RPCContainerTest.cpp
Labels: jira/no-ticket, size/XXL

#2771 Check existence of the output log
  SpatialGDK/Source/SpatialGDKServices/Private/LocalDeploymentManager.cpp
Labels: jira/UNR, size/XS

#2772 Check existance of spatial output log
  SpatialGDK/Source/SpatialGDKServices/Private/LocalDeploymentManager.cpp
Labels: jira/UNR, size/XS

#2774 Fix functional test race in RC
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/SpatialFunctionalTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/SpatialFunctionalTestFlowController.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Public/SpatialFunctionalTestFlowController.h
Labels: jira/no-ticket, size/S

#2751 UNR-4617 Fix Async loading of sublevels
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp
Labels: jira/UNR, size/S

#2775 Sanitize schema database
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSchemaGenerator.h
  SpatialGDK/Source/SpatialGDKEditorCommandlet/Private/Commandlets/CookAndGenerateSchemaCommandlet.cpp
Labels: jira/no-ticket, size/M

#2782 Add system entity reference
  SpatialGDK/Extras/schema/server_worker.schema
Labels: jira/no-ticket, size/XS

#2770 [UNR-4603] When async loading, avoid queuing components that are handled through static component view
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
Labels: jira/UNR, size/S

#2736 Bug/unr 4245 actors switching workers
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialAuthorityTest/SpatialAuthorityTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialAuthorityTest/SpatialAuthorityTest.h
Labels: jira/UNR, size/XL

#2783 Set delegation index fix
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/SpatialFunctionalTest.cpp
Labels: jira/no-ticket, size/XS

#2778 Feature/unr-4665-run-onactor-ready-on-nonauth-servers
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Public/Utils/EngineVersionCheck.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialAuthorityTest/SpatialAuthorityTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialAuthorityTest/SpatialAuthorityTest.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialAuthorityTest/SpatialAuthorityTestActorComponent.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialAuthorityTest/SpatialAuthorityTestActorComponent.h
Labels: jira/UNR, size/M

#2781 make inspector exe executable on mac
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
  SpatialGDK/Source/SpatialGDKServices/Private/SpatialCommandUtils.cpp
  SpatialGDK/Source/SpatialGDKServices/Public/SpatialGDKServicesConstants.h
Labels: jira/no-ticket, size/S
