Repository spatialos/UnrealGDK, pull requests merged in 2020-03, with the labels that each got.

#1847 UNR-3014 Moved some flags to RPCContainter
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/RPCContainer.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialSender.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/RPCContainer.h
  SpatialGDK/Source/SpatialGDKTests/SpatialGDK/Utils/RPCContainer/ObjectDummy.cpp
  SpatialGDK/Source/SpatialGDKTests/SpatialGDK/Utils/RPCContainer/ObjectSpy.cpp
  SpatialGDK/Source/SpatialGDKTests/SpatialGDK/Utils/RPCContainer/ObjectStub.cpp
  SpatialGDK/Source/SpatialGDKTests/SpatialGDK/Utils/RPCContainer/RPCContainerTest.cpp
Labels: jira/UNR, size/M

#1848 Fix int8 -> bool compile error in VS2019
  SpatialGDK/Source/SpatialGDK/Public/Schema/SpatialDebugging.h
Labels: jira/no-ticket, size/XS

#1839 Update release-process.md
  SpatialGDK/Extras/internal-documentation/release-process.md
Labels: jira/no-ticket, size/M

#1851 Restored a check for if the connection should be used from the game t…
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialConnectionManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/SpatialWorkerConnection.h
Labels: jira/no-ticket, size/XS

#1856 UNR-2888 Added proper error output for new RPC errors
  SpatialGDK/Source/SpatialGDK/Private/Utils/RPCContainer.cpp
Labels: jira/UNR, size/XS

#1849 Merge of MBL-13 and MBL-18
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/SpatialWorkerConnection.h
Labels: jira/MBL, size/M

#1807 robust actor and not actor receiving
  .buildkite/premerge.steps.yaml
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialLoadBalanceEnforcer.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialStaticComponentView.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/EntityFactory.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialLoadBalanceEnforcer.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialSender.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
  SpatialGDK/Source/SpatialGDKTests/SpatialGDK/LoadBalanceEnforcer/SpatialLoadBalanceEnforcerTest.cpp
  ci/gdk_build.template.steps.yaml
Labels: jira/UNR, size/XXL

#1833 server qbi that CAN'T be turned off
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/GridBasedLBStrategy.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/InterestFactory.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialSender.h
  SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/AbstractLBStrategy.h
  SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/GridBasedLBStrategy.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/StandardLibrary.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/InterestFactory.h
  SpatialGDK/Source/SpatialGDKTests/SpatialGDK/LoadBalancing/GridBasedLBStrategy/GridBasedLBStrategyTest.cpp
  SpatialGDK/Source/SpatialGDKTests/SpatialGDK/LoadBalancing/GridBasedLBStrategy/TestGridBasedLBStrategy.cpp
  SpatialGDK/Source/SpatialGDKTests/SpatialGDK/LoadBalancing/GridBasedLBStrategy/TestGridBasedLBStrategy.h
Labels: jira/UNR, size/XL

#1860 indentation
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
Labels: jira/no-ticket, size/L

#1845 Improvements to worker regions
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/WorkerRegion.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialDebugger.cpp
  SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/WorkerRegion.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialDebugger.h
Labels: jira/no-ticket, size/M

#1850 Remove parallel tracking sets
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp
Labels: jira/no-ticket, size/S

#1859 Maybe fix slack hooks?
  ci/common.ps1
Labels: jira/no-ticket, size/XS

#1864 [CHINF-886][MS] Fixing a crash caused by the merge into release related to the jira issue.
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/SpatialWorkerConnection.h
Labels: jira/CHINF, size/S

#1863 Create log directory if it doesn't exist for the spatial output
  SpatialGDK/Source/SpatialGDKServices/Private/SSpatialOutputLog.cpp
Labels: jira/no-ticket, size/XS

#1855 Added custom warning timeouts per RPC failure condition
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/RPCContainer.cpp
  SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/RPCContainer.h
  SpatialGDK/Source/SpatialGDKTests/SpatialGDK/Utils/RPCContainer/RPCContainerTest.cpp
Labels: jira/UNR, size/M

#1869 Removing the netdriver from the spatial worker connection.
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/SpatialWorkerConnection.h
Labels: jira/CHINF, size/M

#1862 [UNR-2763] Add avg/min/max ping measurements
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/Components/SpatialPingComponent.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/Components/SpatialPingComponent.h
Labels: jira/UNR, size/M

#1870 Remove 0.6.5 from CHANGELOG
  CHANGELOG.md
Labels: jira/no-ticket, size/XS

#1846 [UNR-2964][MS] Ensure spatial commands are run with correct environment arg.
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
  SpatialGDK/Source/SpatialGDKServices/Private/Interop/Connection/EditorWorkerController.cpp
  SpatialGDK/Source/SpatialGDKServices/Private/LocalDeploymentManager.cpp
  SpatialGDK/Source/SpatialGDKServices/Private/SpatialCommandUtils.cpp
  SpatialGDK/Source/SpatialGDKServices/Private/SpatialGDKServicesModule.cpp
  SpatialGDK/Source/SpatialGDKServices/Public/LocalDeploymentManager.h
  SpatialGDK/Source/SpatialGDKServices/Public/SpatialCommandUtils.h
  SpatialGDK/Source/SpatialGDKServices/Public/SpatialGDKServicesModule.h
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKServices/LocalDeploymentManager/LocalDeploymentManagerTest.cpp
Labels: jira/UNR, size/M

#1858 [UNR-3011][MS] Checking bPreventAutoConnectWithLocator before first spatial connection logic.
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialGameInstance.h
Labels: jira/UNR, size/XS

#1844 [UNR-1954] Use System entity for connection cleanup
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetConnection.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialStaticComponentView.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/InterestFactory.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetConnection.h
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/StandardLibrary.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
Labels: jira/UNR, size/L

#1854 Fixed crash caused by state persisting across a transition from one d…
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialGameInstance.cpp
Labels: jira/UNR, size/S

#1866 user query Result type additions and some refactoring +comments
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/Components/ActorInterestComponent.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/InterestFactory.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/Components/ActorInterestComponent.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialInterestConstraints.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/Interest.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialCommonTypes.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/InterestFactory.h
Labels: jira/UNR, size/L

#1871 schrodinger's channel A
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h
Labels: jira/UNR, size/M

#1872 Fixes for bugs encountered in during test gyms playthroughs
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/EntityFactory.cpp
Labels: jira/no-ticket, size/S

#1867 [UNR-3041][MS] Addin 14.3 into release
  CHANGELOG.md
  RequireSetup
  SpatialGDK/Extras/core-sdk.version
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/ConnectionConfig.h
Labels: jira/UNR, size/S

#1873 [UNR-2989] Fix the Start deployment button being greyed out after auth timeout
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDKServices/Private/LocalDeploymentManager.cpp
Labels: jira/UNR, size/XS

#1875 UNR-3000 Spatial Output shows startup errors
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDKServices/Private/LocalDeploymentManager.cpp
  SpatialGDK/Source/SpatialGDKServices/Private/SSpatialOutputLog.cpp
  SpatialGDK/Source/SpatialGDKServices/Public/SSpatialOutputLog.h
Labels: jira/UNR, size/M

#1874 supa set
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/InterestFactory.cpp
  SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/InterestFactory.h
Labels: jira/UNR, size/XL

#1877 [UNR-2184] Copy Portal part of Urls so you can specify the spawn poin…
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialPlayerSpawner.cpp
Labels: jira/UNR, size/XS

#1879 flip result types
  SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp
Labels: jira/no-ticket, size/XS

#1878 single interest factory per net driver
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentFactory.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/EntityFactory.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/InterestFactory.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/Interest.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/InterestFactory.h
Labels: jira/UNR, size/L

#1885 [UNR-3064][MS] Catching exception where resources run out in AWS
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/DeploymentLauncher/DeploymentLauncher.cs
Labels: jira/UNR, size/XS

#1891 [UNR-3062][MS] Fixing spatial auth to west when in china in local deployment
  SpatialGDK/Source/SpatialGDKServices/Private/LocalDeploymentManager.cpp
  SpatialGDK/Source/SpatialGDKServices/Public/LocalDeploymentManager.h
Labels: jira/UNR, size/XS

#1892 [UNR-3064][MS] Adding extra logging for unhandled exceptions
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/DeploymentLauncher/DeploymentLauncher.cs
Labels: jira/UNR, size/XS

#1887 Bugfix/unr 3065 spatial output device crash
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
Labels: jira/UNR, size/XS

#1829 [UNR-838][MS] Adding connection saturation
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentFactory.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/EntityFactory.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialSender.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/ComponentFactory.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/EngineVersionCheck.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/EntityFactory.h
  ci/unreal-engine.version
Labels: jira/UNR, size/L

#1883 [UNR-2809] Add a dedicated editor tool to create and edit SpatialOS launch configuration Json files.
  SpatialGDK/Source/SpatialGDKEditor/Private/Utils/LaunchConfigEditor.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/Utils/TransientUObjectEditor.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/Utils/LaunchConfigEditor.h
  SpatialGDK/Source/SpatialGDKEditor/Public/Utils/TransientUObjectEditor.h
  SpatialGDK/Source/SpatialGDKEditor/SpatialGDKEditor.Build.cs
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbarCommands.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorToolbar.h
  SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorToolbarCommands.h
Labels: jira/UNR, size/L

#1888 interest refactoring
  SpatialGDK/Source/SpatialGDK/Private/Utils/CheckoutRadiusConstraintUtils.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/Interest/NetCullDistanceInterest.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/InterestFactory.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/Components/ActorInterestComponent.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/Interest.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialCommonTypes.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/CheckoutRadiusConstraintUtils.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/Interest/NetCullDistanceInterest.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/InterestFactory.h
  SpatialGDK/Source/SpatialGDKTests/SpatialGDK/Utils/CheckoutRadiusConstraintUtils/NetCullDistanceInterestTest.cpp
Labels: jira/UNR, size/XXL

#1899 Add missing category
  SpatialGDK/Source/SpatialGDKEditor/Private/Utils/LaunchConfigEditor.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/Utils/LaunchConfigEditor.h
Labels: jira/UNR, size/XS

#1886 [UNR-3055][MS] Simplayer connection now knows about region to choose locator.
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/DeploymentLauncher/DeploymentLauncher.cs
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/WorkerCoordinator/Authentication.cs
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/WorkerCoordinator/ManagedWorkerCoordinator.cs
Labels: jira/UNR, size/S

#1896 [UNR-3071][MS] Update Worker SDK version
  CHANGELOG.md
  Setup.bat
  SpatialGDK/Extras/core-sdk.version
Labels: jira/UNR, size/XS

#1900 SpatialD update + Engine Plugin include fixes
  SpatialGDK/Source/SpatialGDKEditor/Private/Utils/LaunchConfigEditor.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/Utils/TransientUObjectEditor.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/Utils/TransientUObjectEditor.h
  SpatialGDK/Source/SpatialGDKServices/Private/LocalDeploymentManager.cpp
Labels: jira/no-ticket, size/S

#1884 fixing smaller mobile bugs
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorLayoutDetails.cpp
  SpatialGDK/Source/SpatialGDKServices/Private/SpatialCommandUtils.cpp
Labels: jira/no-ticket, size/XS

#1889 Prevent overflow when computing grid based interest
  SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/GridBasedLBStrategy.cpp
Labels: jira/no-ticket, size/XS

#1906 Release date for 0.8.1 in CHANGELOG.md
  CHANGELOG.md
Labels: jira/no-ticket, size/XS

#1905 UNR-2813 - Default enable ncd interest
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp
Labels: jira/UNR, size/XS

#1880 New Docs Website + Readme Cleanup
  CONTRIBUTING.md
  README.md
  SpatialGDK/Documentation/README.md
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKSimulatedPlayerDeployment.cpp
  SpatialGDK/SpatialGDK.uplugin
Labels: jira/no-ticket, size/S

#1890 Added log warning when AddPendingRPC fails due to ControllerChannelNo…
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
Labels: jira/UNR, size/XS

#1908 Create log directory if it doesn't exist for the spatial output (#1863)
  SpatialGDK/Source/SpatialGDKServices/Private/SSpatialOutputLog.cpp
Labels: jira/UNR, size/XS

#1909 Update SpatialGDK.uplugin
  SpatialGDK/SpatialGDK.uplugin
Labels: jira/no-ticket, size/XS

#1910 Update CHANGELOG.md
  CHANGELOG.md
Labels: jira/no-ticket, size/XS

#1762 [UNR-2600] Offloading & Authority & Startup actor fixes
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialGameInstance.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/GlobalStateManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/EntityFactory.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialStatics.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialGameInstance.h
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/EngineVersionCheck.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/EntityFactory.h
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
  ci/unreal-engine.version
Labels: jira/UNR, size/L

#1907 0.8.1-preview-rc > preview
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  RequireSetup
  Setup.bat
  Setup.sh
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/DeploymentLauncher/DeploymentLauncher.cs
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/WorkerCoordinator/Authentication.cs
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/WorkerCoordinator/ManagedWorkerCoordinator.cs
  SpatialGDK/Documentation/README.md
  SpatialGDK/Extras/core-sdk.version
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialGameInstance.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialClassInfoManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialGameInstance.h
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialPackageMapClient.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/ConnectionConfig.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/SpatialWorkerConnection.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialClassInfoManager.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialSender.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/UnrealObjectRef.cpp
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditor.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorCloudLauncher.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorSettings.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSchemaGenerator.h
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKSimulatedPlayerDeployment.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKSimulatedPlayerDeployment.h
  SpatialGDK/Source/SpatialGDKServices/Private/Interop/Connection/EditorWorkerController.cpp
  SpatialGDK/Source/SpatialGDKServices/Private/LocalDeploymentManager.cpp
  SpatialGDK/Source/SpatialGDKServices/Private/SSpatialOutputLog.cpp
  SpatialGDK/Source/SpatialGDKServices/Private/SpatialCommandUtils.cpp
  SpatialGDK/Source/SpatialGDKServices/Private/SpatialGDKServicesModule.cpp
  SpatialGDK/Source/SpatialGDKServices/Public/LocalDeploymentManager.h
  SpatialGDK/Source/SpatialGDKServices/Public/SpatialCommandUtils.h
  SpatialGDK/Source/SpatialGDKServices/Public/SpatialGDKServicesModule.h
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/SpatialGDKEditorSchemaGeneratorTest.cpp
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKServices/LocalDeploymentManager/LocalDeploymentManagerTest.cpp
  SpatialGDK/SpatialGDK.uplugin
Labels: jira/no-ticket, size/XXL

#1882 [UNR-2809] Add editor extension to get the number of workers to launch from a load balancing strategy
  SpatialGDK/Source/SpatialGDKEditor/Private/EditorExtension/GridLBStrategyEditorExtension.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/EditorExtension/GridLBStrategyEditorExtension.h
  SpatialGDK/Source/SpatialGDKEditor/Private/EditorExtension/LBStrategyEditorExtension.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorModule.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/EditorExtension/LBStrategyEditorExtension.h
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorModule.h
Labels: jira/UNR, size/L

#1914 Update CHANGELOG.md
  CHANGELOG.md
Labels: jira/no-ticket, size/S

#1865 Feature/enable replication graph
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialReplicationGraph.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialConnectionManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialReplicationGraph.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/EngineVersionCheck.h
  SpatialGDK/Source/SpatialGDK/SpatialGDK.Build.cs
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SnapshotGenerator/SpatialGDKEditorSnapshotGenerator.cpp
  SpatialGDK/Source/SpatialGDKEditor/SpatialGDKEditor.Build.cs
  SpatialGDK/SpatialGDK.uplugin
Labels: jira/no-ticket, size/M

#1902 Fixed crash caused by uninitialised shadow data
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
Labels: jira/no-ticket, size/XS

#1898 [UNR-2809] Use map's load balancing strategy when starting local deployment
  SpatialGDK/Source/SpatialGDKEditor/Private/EditorExtension/LBStrategyEditorExtension.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKDefaultLaunchConfigGenerator.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorSettings.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/EditorExtension/LBStrategyEditorExtension.h
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKDefaultLaunchConfigGenerator.h
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorToolbar.h
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKServices/LocalDeploymentManager/LocalDeploymentManagerUtilities.cpp
Labels: jira/UNR, size/XL

#1876 UNR-3008 Spawn players Actors based on PlayerStart authortitative server
  RequireSetup
  SpatialGDK/Extras/schema/server_worker.schema
  SpatialGDK/Extras/schema/virtual_worker_translation.schema
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialVirtualWorkerTranslationManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialVirtualWorkerTranslator.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/GlobalStateManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialDispatcher.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialPlayerSpawner.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialDebugger.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialPackageMapClient.h
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialVirtualWorkerTranslationManager.h
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialVirtualWorkerTranslator.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialPlayerSpawner.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/PlayerSpawner.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/ServerWorker.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/EngineVersionCheck.h
Labels: jira/UNR, size/XXL

#1916 Add function to get entity ID from actor
  SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialStatics.cpp
  SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialStatics.h
Labels: jira/no-ticket, size/S

#1919 Move FindPlayerStart call with nullptr to only occur with load-balanc…
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialPlayerSpawner.cpp
Labels: jira/no-ticket, size/XS

#1881 [UNR-2859] Multi-worker dynamic components using component presence
  SpatialGDK/Extras/schema/component_presence.schema
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialLoadBalanceEnforcer.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialStaticComponentView.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/EntityFactory.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/InterestFactory.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialDebugger.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialLoadBalanceEnforcer.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialSender.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/ComponentPresence.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/EntityFactory.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SnapshotGenerator/SpatialGDKEditorSnapshotGenerator.cpp
  SpatialGDK/Source/SpatialGDKTests/SpatialGDK/LoadBalanceEnforcer/SpatialLoadBalanceEnforcerTest.cpp
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/SpatialGDKEditorSchemaGeneratorTest.cpp
Labels: jira/UNR, size/XL

#1918 UNR-2811 Custom Locator URL
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialConnectionManager.cpp
Labels: jira/UNR, size/M

#1920 Fix trace lib snapshots
  SpatialGDK/Source/SpatialGDKEditor/Private/SnapshotGenerator/SpatialGDKEditorSnapshotGenerator.cpp
Labels: jira/no-ticket, size/S

#1926 Add ComponentPresence to non-auth server interest
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
Labels: jira/no-ticket, size/XS

#1828 WIP UNR-2927 Initial SpatialView vertical slice
  SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialView/ViewCoordinator.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialView/ViewDelta.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialView/WorkerView.cpp
  SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialView/CommandMessages.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialView/ConnectionHandlers/AbstractConnectionHandler.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialView/ConnectionHandlers/QueuedOpListConnectionHandler.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialView/MessagesToSend.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialView/OpList/AbstractOpList.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialView/OpList/ViewDeltaLegacyOpList.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialView/OpList/WorkerConnectionOpList.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialView/ViewCoordinator.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialView/ViewDelta.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialView/WorkerView.h
Labels: do-not-merge/work-in-progress, jira/UNR, size/XL

#1923 Release 0.8.1 master merge
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  Setup.bat
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/DeploymentLauncher/DeploymentLauncher.cs
  SpatialGDK/Documentation/README.md
  SpatialGDK/Extras/core-sdk.version
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditor.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSchemaGenerator.h
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKSimulatedPlayerDeployment.cpp
  SpatialGDK/Source/SpatialGDKServices/Private/Interop/Connection/EditorWorkerController.cpp
  SpatialGDK/Source/SpatialGDKServices/Private/LocalDeploymentManager.cpp
  SpatialGDK/Source/SpatialGDKServices/Private/SpatialCommandUtils.cpp
  SpatialGDK/Source/SpatialGDKServices/Private/SpatialGDKServicesModule.cpp
  SpatialGDK/Source/SpatialGDKServices/Public/LocalDeploymentManager.h
  SpatialGDK/Source/SpatialGDKServices/Public/SpatialCommandUtils.h
  SpatialGDK/Source/SpatialGDKServices/Public/SpatialGDKServicesModule.h
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/SpatialGDKEditorSchemaGeneratorTest.cpp
  SpatialGDK/SpatialGDK.uplugin
Labels: jira/no-ticket, size/L

#1928 Made headers explicit.
  SpatialGDK/Source/SpatialGDK/Private/SpatialView/ViewDelta.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialView/WorkerView.cpp
  SpatialGDK/Source/SpatialGDK/Public/SpatialView/ConnectionHandlers/AbstractConnectionHandler.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialView/ConnectionHandlers/QueuedOpListConnectionHandler.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialView/MessagesToSend.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialView/OpList/ViewDeltaLegacyOpList.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialView/OpList/WorkerConnectionOpList.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialView/ViewCoordinator.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialView/ViewDelta.h
Labels: jira/no-ticket, size/S

#1930 Virtual destructor
  SpatialGDK/Source/SpatialGDKEditor/Public/EditorExtension/LBStrategyEditorExtension.h
Labels: jira/no-ticket, size/XS

#1929 Broadcast OnDeploymentStart from game thread
  SpatialGDK/Source/SpatialGDKServices/Private/LocalDeploymentManager.cpp
Labels: jira/no-ticket, size/XS

#1927 Default to 4.24 engine
  ci/unreal-engine.version
Labels: jira/DEFAULT, size/XS

#1935 Update WorkerJsonTemplate
  SpatialGDK/Extras/templates/WorkerJsonTemplate.json
Labels: jira/no-ticket, size/S

#1893 Feature/unr 3001 spatial view authority
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialRPCService.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialView/AuthorityRecord.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialView/ViewCoordinator.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialView/ViewDelta.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialView/WorkerView.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialRPCService.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialView/AuthorityRecord.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialView/EntityComponentId.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialView/ViewCoordinator.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialView/ViewDelta.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialView/WorkerView.h
Labels: jira/UNR, size/L

#1921 [UNR-3067][UNR-3068] Fix dormancy and tombstones
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
Labels: jira/UNR, size/XS

#1934 Check weak pointer in SpatialConnectionManager after connecting
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialConnectionManager.cpp
Labels: jira/no-ticket, size/XS

#1936 Fix erroneous include path
  SpatialGDK/Source/SpatialGDK/Public/SpatialView/EntityComponentId.h
Labels: jira/no-ticket, size/XS

#1941 Switch back to 4.23 default until NFR pipeline is sorted
  ci/unreal-engine.version
Labels: jira/no-ticket, size/XS

#1943 Early exit processing a server RPC if the Actor role has changed to SimulatedProxy
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
Labels: jira/no-ticket, size/S

#1894 UNR-2927 Test for WorkerView and ViewDelta
  SpatialGDK/Source/SpatialGDK/Private/SpatialView/ViewDelta.cpp
  SpatialGDK/Source/SpatialGDK/Private/Tests/SpatialView/ViewDeltaTest.cpp
  SpatialGDK/Source/SpatialGDK/Private/Tests/SpatialView/WorkerViewTest.cpp
Labels: jira/UNR, size/L

#1895 UNR-3001 AuthorityRecord Tests
  SpatialGDK/Source/SpatialGDK/Private/Tests/SpatialView/AuthorityRecordTest.cpp
  SpatialGDK/Source/SpatialGDK/Private/Tests/SpatialView/ViewDeltaTest.cpp
  SpatialGDK/Source/SpatialGDK/Private/Tests/SpatialView/WorkerViewTest.cpp
Labels: jira/UNR, size/M

#1945 Disable legacy include
  SpatialGDK/Source/SpatialGDK/Private/Tests/SpatialView/WorkerViewTest.cpp
  SpatialGDK/Source/SpatialGDK/SpatialGDK.Build.cs
  SpatialGDK/Source/SpatialGDKEditor/SpatialGDKEditor.Build.cs
  SpatialGDK/Source/SpatialGDKEditorCommandlet/SpatialGDKEditorCommandlet.Build.cs
  SpatialGDK/Source/SpatialGDKEditorToolbar/SpatialGDKEditorToolbar.Build.cs
  SpatialGDK/Source/SpatialGDKServices/SpatialGDKServices.Build.cs
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKTests.Build.cs
Labels: jira/no-ticket, size/XS

#1942 Update to 2019 queue
  .buildkite/premerge.steps.yaml
  ci/gdk_build.template.steps.yaml
  ci/setup-build-test-gdk.ps1
Labels: jira/no-ticket, size/XS

#1948 Revert "Update to 2019 queue"
  .buildkite/premerge.steps.yaml
  ci/gdk_build.template.steps.yaml
  ci/setup-build-test-gdk.ps1
Labels: jira/no-ticket, size/XS

#1917 Client possession (/ net ownership) works with zoning
  SpatialGDK/Extras/schema/component_presence.schema
  SpatialGDK/Extras/schema/net_owning_client_worker.schema
  SpatialGDK/Extras/schema/unreal_metadata.schema
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialLoadBalanceEnforcer.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetConnection.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialStaticComponentView.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/EntityFactory.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialDebugger.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetConnection.h
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialSender.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/ComponentPresence.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/NetOwningClientWorker.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/UnrealMetadata.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialActorUtils.h
  SpatialGDK/Source/SpatialGDKTests/SpatialGDK/LoadBalanceEnforcer/SpatialLoadBalanceEnforcerTest.cpp
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/SpatialGDKEditorSchemaGeneratorTest.cpp
Labels: jira/no-ticket, size/XL

#1940 Call OnAuthorityLost callback when sending auth intent
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
Labels: jira/no-ticket, size/XS

#1946 Locking policy simplification, smarter role exchanging, deleting Ally's code
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/OwnershipLockingPolicy.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/AbstractSpatialPackageMapClient.h
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/AbstractVirtualWorkerTranslator.h
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialPackageMapClient.h
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialVirtualWorkerTranslator.h
  SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/AbstractLockingPolicy.h
  SpatialGDK/Source/SpatialGDKTests/SpatialGDK/LoadBalancing/OwnershipLockingPolicy/OwnershipLockingPolicyTest.cpp
  SpatialGDK/Source/SpatialGDKTests/SpatialGDK/LoadBalancing/OwnershipLockingPolicy/SpatialPackageMapClientMock.cpp
  SpatialGDK/Source/SpatialGDKTests/SpatialGDK/LoadBalancing/OwnershipLockingPolicy/SpatialPackageMapClientMock.h
  SpatialGDK/Source/SpatialGDKTests/SpatialGDK/LoadBalancing/OwnershipLockingPolicy/SpatialStaticComponentViewMock.cpp
  SpatialGDK/Source/SpatialGDKTests/SpatialGDK/LoadBalancing/OwnershipLockingPolicy/SpatialStaticComponentViewMock.h
  SpatialGDK/Source/SpatialGDKTests/SpatialGDK/LoadBalancing/OwnershipLockingPolicy/SpatialVirtualWorkerTranslatorMock.cpp
  SpatialGDK/Source/SpatialGDKTests/SpatialGDK/LoadBalancing/OwnershipLockingPolicy/SpatialVirtualWorkerTranslatorMock.h
Labels: jira/no-ticket, size/XL

#1897 MacOS CI
  .buildkite/hooks/pre-command
  .buildkite/hooks/pre-exit.bat
  .buildkite/premerge.steps.yaml
  Setup.sh
  ci/build-project.sh
  ci/cleanup.sh
  ci/gdk_build.template.steps.yaml
  ci/generate-and-upload-build-steps.sh
  ci/get-engine.sh
  ci/run-tests.sh
  ci/setup-build-test-gdk.sh
Labels: jira/no-ticket, size/XL

#1947 Reduce unnecessary logspam for handling server RPCs when simulated proxy
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
Labels: jira/no-ticket, size/S

#1932 Bugfix/log entity
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetConnection.cpp
Labels: jira/no-ticket, size/XS

#1949 Add tracePrefix command line argument
  SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialLatencyTracer.cpp
Labels: jira/GV, size/XS

#1951 [UNR-3178]Pin 14.5.0 as the runtime version
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDKServices/Public/SpatialGDKServicesConstants.h
Labels: jira/UNR, size/XS

#1950 Update GridBasedLBStrategy.cpp
  SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/GridBasedLBStrategy.cpp
Labels: jira/no-ticket, size/XS

#1953 my boolean defaults to true question mark?
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialPlayerSpawner.cpp
Labels: jira/no-ticket, size/XS

#1952 Revert "Revert "Default engine to 424 (#1927)" (#1941)"
  ci/unreal-engine.version
Labels: jira/no-ticket, size/XS

#1944 Feature/unr 3076 latency tracer single root
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialGameInstance.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentFactory.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialLatencyTracer.cpp
  SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialLatencyPayload.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialLatencyTracer.h
Labels: jira/UNR, size/XL

#1924 Update CHANGELOG.md
  CHANGELOG.md
Labels: do-not-merge/work-in-progress, jira/no-ticket, size/M

#1955 VS2019 CI Support V2
  .buildkite/premerge.steps.yaml
  ci/gdk_build.template.steps.yaml
  ci/setup-build-test-gdk.ps1
  ci/setup-gdk.ps1
Labels: jira/no-ticket, size/XS
