Repository spatialos/UnrealGDK, pull requests merged in 2020-04, with the labels that each got.

#1960 Explicit bool
  SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialLatencyTracer.cpp
Labels: jira/no-ticket, size/XS

#1962 Rename unreal_path to unreal_engine_symlink_dir for consistency
  ci/gdk_build.template.steps.yaml
  ci/setup-build-test-gdk.ps1
Labels: jira/no-ticket, size/XS

#1964 Increase the default ring buffer size
  SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp
Labels: jira/no-ticket, size/XS

#1956 [UNR-3010][MS] Modifying SpatialCommandUtils so that it better wraps up spatial cli commands.
  SpatialGDK/Source/SpatialGDKServices/Private/Interop/Connection/EditorWorkerController.cpp
  SpatialGDK/Source/SpatialGDKServices/Private/LocalDeploymentManager.cpp
  SpatialGDK/Source/SpatialGDKServices/Private/SpatialCommandUtils.cpp
  SpatialGDK/Source/SpatialGDKServices/Private/SpatialGDKServicesModule.cpp
  SpatialGDK/Source/SpatialGDKServices/Public/SpatialCommandUtils.h
Labels: jira/UNR, size/L

#1961 UNR-3199 Remove obsolete code about exposing local deployment IP.
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorSettings.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
Labels: jira/UNR, size/S

#1933 [UNR-3142] [MS] bPreventAutoConnectWithLocator now only relevant to clients
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialGameInstance.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialGameInstance.h
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h
Labels: jira/UNR, size/M

#1966 Explicitly set Actors as non-authoritative before calling BeginPlay a…
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
Labels: jira/no-ticket, size/S

#1963 Split up actor entity ID functions
  SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialStatics.cpp
  SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialStatics.h
Labels: jira/no-ticket, size/M

#1971 Avoid crash trying to update non-auth pawn
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
Labels: jira/no-ticket, size/XS

#1973 Fix log message for docs
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
Labels: jira/no-ticket, size/XS

#1977 Ported mw changes and requests
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialMetrics.cpp
  SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialMetrics.h
Labels: jira/no-ticket, size/S

#1974 Bugfix/unr 3232 component rpcs on creation
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h
Labels: jira/UNR, size/S

#1978 [UNR-3230] Fix external process connections
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialConnectionManager.cpp
Labels: jira/UNR, size/XS

#1972 Revert #1961 + Override exposed runtime IP
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorSettings.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
Labels: jira/no-ticket, size/S

#1975 Feature/GV-329 New NFR parameter and new span name format
  SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialLatencyTracer.cpp
  SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialLatencyTracer.h
Labels: jira/GV, size/S

#1980 UNR-3056 - 0.9 - Update defaults, remove rpc packing
  CHANGELOG.md
  RequireSetup
  SpatialGDK/Extras/schema/rpc_components.schema
  SpatialGDK/Extras/schema/rpc_payload.schema
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialSender.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h
Labels: jira/UNR, size/L

#1981 Flush ring buffer RPCs after call
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
Labels: jira/no-ticket, size/XS

#1984 UNR-3252: Remove shadowing variables
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Private/Tests/RPCServiceTest.cpp
Labels: jira/UNR, size/S

#1985 UNR-3244: Fixing dev auth token generation
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorLayoutDetails.cpp
Labels: jira/UNR, size/XS

#1957 Call BroadcastNetworkFailure when the PlayerController gets deleted by the server.
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
Labels: jira/no-ticket, size/XS

#1987 Update QueuedOutgoingRPCWaitTime to 30s
  SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp
Labels: jira/no-ticket, size/XS

#1990 Ensuring empty runtime versions are not used when deploying.
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorSettings.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKSimulatedPlayerDeployment.cpp
Labels: jira/no-ticket, size/XS

#1991 Missed commit
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKSimulatedPlayerDeployment.cpp
Labels: jira/no-ticket, size/XS

#1986 Remove and Add component ops processed in the wrong order.
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
Labels: jira/no-ticket, size/XS

#1992 Don't prematurely set channel authority on entity checkout
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
Labels: jira/no-ticket, size/XS

#1965 [UNR-3187] Add settings to CI, re-enable weekly builds
  .buildkite/premerge.steps.yaml
  ci/build-and-send-slack-notification.ps1
  ci/build-project.ps1
  ci/gdk_build.template.steps.yaml
  ci/generate-and-upload-build-steps.sh
  ci/run-tests.ps1
  ci/setup-build-test-gdk.ps1
Labels: jira/UNR, size/L

#1954 Added ClientOwnershipGained and ClientOwnershipLost events when the client-worker's authority over the ClientRPCEndpoint has changed.
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDK/Public/Utils/EngineVersionCheck.h
Labels: jira/no-ticket, size/S

#1983 Update runtime pin to 14.5.1
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDKServices/Public/SpatialGDKServicesConstants.h
Labels: jira/no-ticket, size/XS

#1994 Revert "Call BroadcastNetworkFailure when the PlayerController gets deleted by the server."
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
Labels: jira/no-ticket, size/XS

#1925 Update CHANGELOG.md
  CHANGELOG.md
Labels: jira/IQA, size/XS

#1996 [UNR-3313][MS] Giving users the option to cancel SimPlayer deployments if built Simplayers can not be found.
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKSimulatedPlayerDeployment.cpp
Labels: jira/UNR, size/XS

#1993 Schema names for unreal names with leading digits are prepended with ZZ
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/Utils/DataTypeUtilities.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/Utils/DataTypeUtilities.h
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSchemaGenerator.h
Labels: jira/UNR, size/M

#2000 [UNR-3230][MS] Fixing assert on server travel by clearing client GSM singleton map.
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/GlobalStateManager.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/GlobalStateManager.h
Labels: jira/UNR, size/XS

#1988 Force-enable handover properties when required for load balancing.
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialClassInfoManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialClassInfoManager.h
  SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/AbstractLBStrategy.h
  SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/GridBasedLBStrategy.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKDefaultLaunchConfigGenerator.cpp
  SpatialGDK/Source/SpatialGDKTests/SpatialGDK/LoadBalancing/GridBasedLBStrategy/GridBasedLBStrategyTest.cpp
Labels: jira/no-ticket, size/M

#2001 [UNR-3230][MS] Clearing the singleton map on the GSM on client when loading map
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/GlobalStateManager.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/GlobalStateManager.h
Labels: jira/UNR, size/XS

#1999 [UNR-3318] Log deployment name when using dev auth flow
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialConnectionManager.cpp
Labels: jira/UNR, size/XS

#2002 UNR-3304 Cloud Deployment Window: make project name field editable.
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKSimulatedPlayerDeployment.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKSimulatedPlayerDeployment.h
  SpatialGDK/Source/SpatialGDKServices/Private/SpatialGDKServicesModule.cpp
  SpatialGDK/Source/SpatialGDKServices/Public/SpatialGDKServicesConstants.h
  SpatialGDK/Source/SpatialGDKServices/Public/SpatialGDKServicesModule.h
Labels: jira/UNR, size/M

#2004 Add TestGyms rc to release docs
  SpatialGDK/Extras/internal-documentation/release-process.md
Labels: jira/no-ticket, size/S

#1931 [UNR-683] Package Assembly from Editor
  CHANGELOG.md
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/DeploymentLauncher/DeploymentLauncher.cs
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditor.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorCloudLauncher.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorPackageAssembly.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorSettings.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditor.h
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorPackageAssembly.h
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKSimulatedPlayerDeployment.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKSimulatedPlayerDeployment.h
Labels: jira/MBL, jira/UNR, size/XXL

#1995 [UNR-2987] Actor hierarchy migration
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h
Labels: jira/UNR, size/M

#2008 Track handover properties on clients to avoid failed lookups
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialClassInfoManager.cpp
Labels: jira/no-ticket, size/XS

#2009 Fix problem where load balanced cloud deploys could fail to start whi…
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/GlobalStateManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
Labels: jira/UNR, size/M

#2013 Added OnPlayerSpawnFailed delegate to SpatialGameInstance
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialGameInstance.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialPlayerSpawner.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialGameInstance.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialPlayerSpawner.h
Labels: jira/UNR, size/M

#2011 Update change log file.
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDKServices/Private/SpatialGDKServicesModule.cpp
Labels: jira/no-ticket, size/XS

#2014 [UNR-2770] Actually enable locking immediate after spawning
  SpatialGDK/Source/SpatialGDK/Private/Utils/EntityFactory.cpp
  SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/AbstractLBStrategy.h
Labels: jira/UNR, size/S

#2003 Handle duplicate add remove component ops a bit better
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialStaticComponentView.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SnapshotGenerator/SpatialGDKEditorSnapshotGenerator.cpp
Labels: jira/no-ticket, size/M

#2005 Made gsm failure warning more verbose
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
Labels: jira/no-ticket, size/XS

#2020 [UNR-3326] EntityFactory include warning fix
  SpatialGDK/Source/SpatialGDK/Private/Utils/EntityFactory.cpp
Labels: jira/UNR, size/XS

#2017 Disable stdout register unless we're actually outputting
  SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialLatencyTracer.cpp
Labels: jira/no-ticket, size/XS

#1997 Feature/upstream interval improvements
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/Components/SpatialPingComponent.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/Components/SpatialPingComponent.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/ConnectionConfig.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/SpatialWorkerConnection.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/WorkerConnectionCoordinator.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h
Labels: jira/no-ticket, size/M

#2025 my bad
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h
Labels: jira/no-ticket, size/XS

#2018 Update to 14.6
  CHANGELOG.md
  RequireSetup
  Setup.bat
  Setup.sh
  SpatialGDK/Extras/core-sdk.version
Labels: jira/no-ticket, size/S

#2016 UNR-3295 Add Remove UE4CommandLine.txt from Device
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorLayoutDetails.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorLayoutDetails.h
Labels: jira/UNR, size/L

#2022 Feature/unr 3311 open console page
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKSimulatedPlayerDeployment.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKSimulatedPlayerDeployment.h
Labels: jira/UNR, size/M

#2019 UNR-3290 Create dropdown for choosing connection flow in the Start toolbar button
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorModule.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorSettings.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorModule.h
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbarCommands.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorToolbar.h
  SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorToolbarCommands.h
  SpatialGDK/Source/SpatialGDKServices/Private/SpatialCommandUtils.cpp
  SpatialGDK/Source/SpatialGDKServices/Public/SpatialCommandUtils.h
Labels: jira/UNR, size/XL

#2030 Fix include order
  SpatialGDK/Source/SpatialGDKServices/Private/SpatialCommandUtils.cpp
Labels: jira/no-ticket, size/XS

#2032 Rename result types
  SpatialGDK/Source/SpatialGDK/Private/Utils/InterestFactory.cpp
  SpatialGDK/Source/SpatialGDK/Public/Schema/Interest.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/InterestFactory.h
Labels: jira/no-ticket, size/M

#2033 update changelog
  CHANGELOG.md
Labels: jira/UNR, size/XS

#2023 [UNR-3160][MS] Targeting specific cluster when deploying using the unreal engine
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/DeploymentLauncher/DeploymentLauncher.cs
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorCloudLauncher.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorSettings.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKSimulatedPlayerDeployment.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKSimulatedPlayerDeployment.h
Labels: jira/UNR, size/L

#1958 [UNR-3159] Make singletons work with zoning
  CHANGELOG.md
  SpatialGDK/Extras/schema/core_types.schema
  SpatialGDK/Extras/schema/global_state_manager.schema
  SpatialGDK/Extras/schema/singleton.schema
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetBitReader.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetBitWriter.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/GlobalStateManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSnapshotManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialStaticComponentView.cpp
  SpatialGDK/Source/SpatialGDK/Private/Schema/UnrealObjectRef.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/EntityFactory.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/InterestFactory.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialDebugger.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialPackageMapClient.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/GlobalStateManager.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/Singleton.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/UnrealObjectRef.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/SchemaUtils.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialDebugger.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialMetricsDisplay.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SnapshotGenerator/SpatialGDKEditorSnapshotGenerator.cpp
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/SpatialGDKEditorSchemaGeneratorTest.cpp
Labels: jira/UNR, size/XXL

#2031 Rename functions and variables for UNR-3290.
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbarCommands.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorToolbar.h
  SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorToolbarCommands.h
Labels: jira/UNR, size/M

#2029 Update CHANGELOG.md for UNR-3290
  CHANGELOG.md
Labels: jira/UNR, size/XS

#2035 Write bytes when clearing fields
  SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentFactory.cpp
Labels: jira/no-ticket, size/XS

#2043 [UNR-3320] Avoid using packages being async loaded
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
Labels: jira/UNR, size/S

#2044 UNR-3365 ResolveObjectReferences fix
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
Labels: jira/UNR, size/XS

#2047 Changing Stream to UStream
  SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialLatencyTracer.cpp
Labels: jira/no-ticket, size/XS

#2040 removed singleton tag
  SpatialGDK/Content/SpatialDebugger/BP_SpatialDebugger.uasset
Labels: jira/no-ticket, size/XS

#2045 Ring buffer latency support
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialRPCService.cpp
  SpatialGDK/Source/SpatialGDK/Private/Tests/RPCServiceTest.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentFactory.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialLatencyTracer.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialRPCService.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialLatencyTracer.h
Labels: jira/UNR, size/L

#2036 UNR-3300 Automatically pass in dev auth token when using mobile PIE flow to connect to spatial cloud deployment.(GDK part)
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorModule.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorModule.h
Labels: jira/UNR, size/S

#2034 Feature/UNR-3301-quick-deploy-button
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbarCommands.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbarStyle.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKSimulatedPlayerDeployment.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorToolbar.h
  SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorToolbarCommands.h
  SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKSimulatedPlayerDeployment.h
Labels: jira/UNR, size/XL

#2028 Set histogram buckets array to right size
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp
Labels: jira/no-ticket, size/XS

#2049 Changed Log to Error for
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
Labels: jira/UNR, size/XS

#2038 Fix release notes for SpatialGameInstance breaking changes
  CHANGELOG.md
Labels: jira/UNR, size/XS

#2024 Fix nightly native tests in CI
  ci/gdk_build.template.steps.yaml
  ci/generate-and-upload-build-steps.sh
  ci/setup-build-test-gdk.ps1
Labels: jira/no-ticket, size/XS

#2006 [UNR-3325] Fix editor load balancing extension selection
  SpatialGDK/Source/SpatialGDKEditor/Private/EditorExtension/LBStrategyEditorExtension.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/EditorExtension/LBStrategyEditorExtension.h
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorModule.h
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/LoadBalancingEditorExtension/SpatialGDKEditorLBExtensionTest.cpp
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/LoadBalancingEditorExtension/TestLoadBalancingStrategy.h
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/LoadBalancingEditorExtension/TestLoadBalancingStrategyEditorExtension.h
Labels: jira/UNR, size/L

#2048 Fix Mac GDK CI
  Setup.bat
  Setup.sh
Labels: jira/no-ticket, size/S

#2042 Try to fix CI getting stuck on timeout
  ci/cleanup.ps1
  ci/common.ps1
  ci/run-tests.ps1
Labels: jira/no-ticket, size/S

#2050 Actor channel respects locking better
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
Labels: jira/no-ticket, size/S

#2057 Ignore server worker component id
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
Labels: jira/no-ticket, size/XS

#2052 Unbind launch delegate when we're not in local deployment mode.
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorToolbar.h
Labels: jira/UNR, size/S

#1976 Bugfix/setup sometimes fails
  CHANGELOG.md
  Setup.bat
  SetupIncTraceLibs.bat
Labels: jira/no-ticket, size/XS

#2051 UNR-3294 Hook up cloud connection flow in new UI(GDK part)
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorModule.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorModule.h
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
Labels: jira/UNR, size/S

#2054 Fixing conflict with singleton-esque stably-named object behaviour
  SpatialGDK/Source/SpatialGDK/Private/Schema/UnrealObjectRef.cpp
Labels: jira/no-ticket, size/XS

#2059 [UNR-3383][MS] More verbose logging in DeploymentLauncher
  RequireSetup
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/DeploymentLauncher/DeploymentLauncher.cs
Labels: jira/UNR, size/XS

#2061 Allow smaller master builds in CI
  .buildkite/premerge.steps.yaml
  ci/generate-and-upload-build-steps.sh
Labels: jira/no-ticket, size/XS

#2039 Feature/UNR-3291
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbarCommands.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbarStyle.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorToolbar.h
  SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorToolbarCommands.h
Labels: jira/UNR, size/M

#1967 Feature/unr 3090 spatial view components
  SpatialGDK/Source/SpatialGDK/Private/SpatialView/ComponentData.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialView/ComponentUpdate.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialView/EntityComponentRecord.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialView/EntityComponentUpdateRecord.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialView/ViewCoordinator.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialView/ViewDelta.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialView/WorkerView.cpp
  SpatialGDK/Source/SpatialGDK/Public/SpatialView/CommandMessages.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialView/ComponentData.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialView/ComponentUpdate.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialView/ConnectionHandlers/AbstractConnectionHandler.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialView/ConnectionHandlers/QueuedOpListConnectionHandler.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialView/EntityComponentRecord.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialView/EntityComponentTypes.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialView/EntityComponentUpdateRecord.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialView/MessagesToSend.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialView/OpList/AbstractOpList.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialView/OpList/ViewDeltaLegacyOpList.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialView/OpList/WorkerConnectionOpList.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialView/OutgoingComponentMessage.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialView/ViewCoordinator.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialView/ViewDelta.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialView/WorkerView.h
Labels: jira/UNR, size/XXL

#2063 Feature/unr 3090 spatial view components tests
  SpatialGDK/Source/SpatialGDK/Private/Tests/SpatialView/EntityComponentRecordTest.cpp
  SpatialGDK/Source/SpatialGDK/Private/Tests/SpatialView/EntityComponentTestUtils.h
  SpatialGDK/Source/SpatialGDK/Private/Tests/SpatialView/EntityComponentUpdateRecordTest.cpp
Labels: jira/UNR, size/XL
