Repository spatialos/UnrealGDK, pull requests merged in 2021-12, with the labels that each got.

#3347 Default disable session log recording
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorSettings.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h
Labels: size/XS, jira/no-ticket

#3348 Correct cond custom replication
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestReplicationConditions/SpatialTestReplicationConditions.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestReplicationConditions/TestReplicationConditionsActor.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestReplicationConditions/TestReplicationConditionsActor.h
Labels: size/S, jira/no-ticket

#3349 Fix ensure hit for non-GDK projects in Spatial subsystems
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialPartitionSystem.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialServerWorkerSystem.cpp
Labels: size/XS, jira/no-ticket

#3350 Better checking of actor's shadow data
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriverAuthorityDebugger.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialShadowActor.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriverAuthorityDebugger.h
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialShadowActor.h
Labels: size/M, jira/no-ticket

#3352 Fix deletion of initally dormant actors. Fixes DestroyStartupActorGym
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/TestMaps/SpatialInitialDormancyDeletionMap.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Public/TestMaps/SpatialInitialDormancyDeletionMap.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/DormancyTests/InitiallyDormantMapActorDeletionTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/DormancyTests/InitiallyDormantMapActorDeletionTest.h
Labels: size/M, jira/no-ticket

#3351 INT-126: Fixed server workers launched via multiple processes PIE not receiving the shutdown command
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/Interop/GlobalStateManager.cpp
Labels: size/XS, jira/INT

#3353 INT-133: Fixed VirtualWorkerIds getting mismatched with workers on a …
  CHANGELOG.md
  SpatialGDK/Content/SpatialDebugger/BP_SpatialDebugger.uasset
  SpatialGDK/Source/SpatialGDK/Private/Interop/Startup/PartitionCreationStartupSteps.cpp
  SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialDebugger.h
Labels: size/XS, jira/INT
