Repository spatialos/UnrealGDK, pull requests merged in 2021-09, with the labels that each got.

#3294 Spiking new interest API
  SpatialGDK/Extras/core-sdk.version
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/ActorSystem.cpp
  SpatialGDK/Source/SpatialGDK/Private/Schema/ChangeInterest.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/InterestFactory.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetConnection.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/ActorSystem.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/ChangeInterest.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/InterestFactory.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/WorkerVersionCheck.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKDefaultLaunchConfigGenerator.cpp
Labels: size/XL, jira/no-ticket

#3298 [UNR-5632] Implement the test debug interface in the strategy worker
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriverDebugContext.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialStrategySystem.cpp
  SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/DebugLBStrategy.cpp
  SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/GridBasedLBStrategy.cpp
  SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/LBDataStorage.cpp
  SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/LegacyLoadBalancingStrategy.cpp
  SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/LegacyServerWorkerSystem.cpp
  SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/PartitionManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/Schema/StaticSymbols.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriverDebugContext.h
  SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/AbstractLBStrategy.h
  SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/DebugLBStrategy.h
  SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/LegacyLoadBalancingStrategy.h
  SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/LegacyLoadbalancingComponents.h
  SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/LoadBalancingStrategy.h
  SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/LoadBalancingTypes.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/SchemaOption.h
Labels: size/XL, jira/UNR

#3308 [UNR-5875] upgrade to worker sdk 15.3.1
  CHANGELOG.md
  RequireSetup
  SpatialGDK/Extras/core-sdk.version
  SpatialGDK/Source/SpatialGDK/Public/Utils/WorkerVersionCheck.h
Labels: size/XS, jira/UNR

#3307 [UNR-5780] Handle races on interest for routing worker
  SpatialGDK/Source/SpatialGDK/Private/Interop/RPCs/CrossServerRPCService.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/RPCs/SpatialRPCService.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialRoutingSystem.cpp
  SpatialGDK/Source/SpatialGDK/Private/Tests/TestRoutingWorker.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/RPCs/CrossServerRPCService.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/RPCs/RPCStore.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/RPCs/SpatialRPCService.h
Labels: size/L, jira/UNR

#3309 [UNR-5875] Update worker sdk to 15.1.1
  CHANGELOG.md
  RequireSetup
  SpatialGDK/Extras/core-sdk.version
  SpatialGDK/Source/SpatialGDK/Public/Utils/WorkerVersionCheck.h
Labels: size/XS, jira/UNR

#3302 [UNR-5891] Allow tests to be their own maps
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/SpatialFunctionalTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/TestMapGeneration.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/TestMaps/GeneratedTestMap.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Public/GeneratableTestMap.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/Public/SpatialFunctionalTest.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/Public/TestMaps/GeneratedTestMap.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPossession/CrossServerMultiPossessionTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPossession/CrossServerMultiPossessionTest.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPossession/CrossServerPossessionLockTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPossession/CrossServerPossessionLockTest.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPossession/CrossServerPossessionMap.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPossession/CrossServerPossessionMap.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPossession/CrossServerPossessionTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPossession/CrossServerPossessionTest.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPossession/NoneCrossServerPossessionTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPossession/NoneCrossServerPossessionTest.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPossession/SpatialTestRemotePossession.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPossession/SpatialTestRemotePossession.h
Labels: size/XL, jira/UNR

#3311 Improve schema determinism
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp
Labels: size/S, jira/no-ticket

#3312 UNR-5896 - Test Timeouts
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSchemaGenerator.h
Labels: size/S, jira/UNR

#3303 [UNR-5651] 4.27 support
  .buildkite/premerge.steps.yaml
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialInterestConstraints.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/TypeStructure.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/Utils/CodeWriter.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditor.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPossession/SpatialTestRemotePossession.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/UNR-3761/SpatialTestWorldComposition/SpatialTestWorldComposition.h
Labels: size/M, jira/UNR

#3313 Bugfix/UNR-5930
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriverRPC.cpp
Labels: size/S, jira/UNR
