Repository spatialos/UnrealGDK, pull requests merged in 2021-05, with the labels that each got.

#3077 Fix bad tombstone creations
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/ActorSystem.cpp
Labels: jira/UNR, size/M

#3063 RepGraph Test Actor when there is no PC
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/DebugInterface/SpatialDebugInterfaceTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/TestActors/ReplicatedTestActorBase_RepGraphAlwaysReplicate.h
Labels: jira/UNR, size/M

#3080 Fix Always Interested tests in rep graph
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/TestActors/AlwaysInterestedTestActors.h
Labels: jira/no-ticket, size/XS

#3076 Add more envvar overrides, slow tests
  .buildkite/premerge.steps.yaml
Labels: jira/no-ticket, size/M

#3082 Bugfix/unr 5454 trace span duplication
  SpatialGDK/Source/SpatialGDK/Private/Interop/ActorSystem.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/RPCs/SpatialRPCService.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialPlayerSpawner.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentFactory.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/EntityFactory.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/OutgoingMessages.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/RPCs/SpatialRPCService.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialView/CommandRetryHandler.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/ComponentFactory.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialLatencyTracer.h
Labels: jira/UNR, size/S

#3078 Update CHANGELOG.md
  CHANGELOG.md
Labels: jira/no-ticket, size/XS

#3084 Cherry-pick - Feature/unr 5296 extend test setting overrides for groups of maps
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialWorldSettings.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialTestSettings.cpp
Labels: jira/no-ticket, size/M

#3065 [UNR-5148] Test Crash In CrossServerMultiPossessionMap
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Public/Schema/MigrationDiagnostic.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPossession/CrossServerPossessionGameMode.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/TestActors/TestPawnBase_RepGraphAlwaysReplicate.h
Labels: jira/UNR, size/S

#3083 Add PlayerControllerEntity to NetConnection on ownership change
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetConnection.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/ActorSystem.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetConnection.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialActorUtils.h
Labels: jira/UNR, size/M

#3088 Fix graceful shutdown spam crashing the editor
  SpatialGDK/Source/SpatialGDKServices/Private/LocalDeploymentManager.cpp
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKServices/LocalDeploymentManager/LocalDeploymentManagerUtilities.cpp
Labels: jira/no-ticket, size/XS

#3090 Hierarchy migrations only ever update the SpatialOS position of the r…
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
Labels: jira/no-ticket, size/XS

#2987 Feature/unr 4890 better spatial view test utils
  SpatialGDK/Source/SpatialGDK/Private/SpatialView/OpList/EntityComponentOpList.cpp
  SpatialGDK/Source/SpatialGDK/Private/Tests/SpatialView/TargetView.cpp
  SpatialGDK/Source/SpatialGDK/Private/Tests/TestRoutingWorker.cpp
  SpatialGDK/Source/SpatialGDK/Public/SpatialView/OpList/EntityComponentOpList.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialView/OpList/StringStorage.h
  SpatialGDK/Source/SpatialGDK/Public/Tests/SpatialView/TargetView.h
  SpatialGDK/Source/SpatialGDK/Public/Tests/SpatialView/TestConnectionHandler.h
  SpatialGDK/Source/SpatialGDK/Public/Tests/SpatialView/TestWorker.h
Labels: jira/UNR, size/XL

#3093 Fix test override base
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialTestSettings.cpp
Labels: jira/no-ticket, size/XS

#3095 [UNR-5424]Work around fix for spatial debugger crashing after client travelling
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialDebugger.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/SpatialWorkerConnection.h
Labels: jira/UNR, size/XS

#3094 Removing bad check
  SpatialGDK/Source/SpatialGDK/Private/Interop/RPCs/ClientServerRPCService.cpp
Labels: jira/UNR, size/XS

#3091 Copy tools to spatial dir
  RequireSetup
  Setup.bat
Labels: jira/no-ticket, size/S

#3097 [UNR-5242] Branch matching
  .buildkite/premerge.steps.yaml
Labels: jira/UNR, size/XS

#3099 Fix package map crash
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp
Labels: jira/UNR, size/XS

#3081 UNR-5421 Fix gc object creation during GC
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialConnectionManager.cpp
Labels: jira/UNR, size/M

#3102 [UNR-5223] Clean up references to bUseNetOwnerActorGroup
  CHANGELOG.md
Labels: jira/UNR, size/XS

#3089 [UNR-4765] remove entity id expiry
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/EntityPool.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialPackageMapClient.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/EntityPool.h
Labels: jira/UNR, size/M

#3096 Downgrade aggressive GDK checks
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetConnection.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriverDebugContext.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialVirtualWorkerTranslationManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/ActorSetWriter.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/ActorSystem.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialClassInfoManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialDispatcher.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/GridBasedLBStrategy.cpp
  SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/LayeredLBStrategy.cpp
  SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/OwnershipLockingPolicy.cpp
  SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/SpatialMultiWorkerSettings.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/EntityFactory.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/EntityPool.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/Interest/NetCullDistanceInterest.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/InterestFactory.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/RPCContainer.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialDebugger.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialDebuggerSystem.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialMetricsDisplay.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialStatics.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/CreateEntityHandler.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/RPCs/RPCTypes.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/MigrationDiagnostic.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialActorUtils.h
Labels: jira/no-ticket, size/XXL

#3109 [UNR-5497] RelevancyTest is flaky
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/RelevancyTest/RelevancyTest.cpp
Labels: jira/UNR, size/M

#3111 Adding override settings to the event trace test
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/EventTracingTests/EventTracingTest.h
Labels: jira/UNR, size/XS

#3110 Tombstone logging for destroyed actors before BeginPlay triggering errors during map load
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
Labels: jira/UNR, size/S

#3112 UNR-5318 Fix (Invalid schema state if schema fails to generate)
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditor.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbarCommands.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorToolbar.h
  SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorToolbarCommands.h
Labels: jira/UNR, size/M

#3117 Update CHANGELOG.md
  CHANGELOG.md
Labels: jira/no-ticket, size/S

#3120 Add how to control sim players' lifetime feature logs.
  CHANGELOG.md
Labels: jira/no-ticket, size/XS

#3060 [UNR-5415] Fix RPC parameter timeout around objects that can be locally loaded.
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriverRPC.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/RPCs/SpatialRPCService.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/EntityFactory.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriverRPC.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/UnrealObjectRef.h
Labels: jira/UNR, size/M

#3123 Fix/fix changelog max lifetime feature
  CHANGELOG.md
Labels: jira/no-ticket, size/XS

#3122 Downgrade check to error log in ApplyProperty
  SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentReader.cpp
Labels: jira/no-ticket, size/XS

#3115 Demote Warning to Log
  SpatialGDK/Source/SpatialGDKTests/Public/GDKAutomationTestBase.h
Labels: jira/UNR, size/XS

#3126 Update premerge.steps.yaml
  .buildkite/premerge.steps.yaml
Labels: jira/no-ticket, size/XS

#3125 [UNR-5544] Calculate and cache worker id as hash in game instance
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialGameInstance.cpp
  SpatialGDK/Source/SpatialGDK/Public/Utils/EngineVersionCheck.h
Labels: jira/UNR, size/XS

#3128 UNR-5551 - Use GetSpatialWorkerId in Tracelib Enabled Code
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialGameInstance.cpp
Labels: jira/UNR, size/XS

#3114 UNR-5429: Fixed test flake
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDKTests/SpatialGDK/LoadBalancing/OwnershipLockingPolicy/OwnershipLockingPolicyTest.cpp
Labels: jira/UNR, size/S

#3118 [UNR-5324] SpatialTestLoadBalancingData is flaky
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestLoadBalancingData/SpatialTestLoadBalancingData.cpp
Labels: jira/UNR, size/M

#3098 Add path to FUnrealObjectRef::ToString
  SpatialGDK/Source/SpatialGDK/Public/Schema/UnrealObjectRef.h
Labels: jira/no-ticket, size/XS

#3129 Hiding Test GridStrategy and MultiWorkerSettings classes from the Editor
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDKFunctionalTests/Public/TestWorkerSettings.h
Labels: jira/UNR, size/S

#3135 [UNR-5557] Initialize pointer in tracing callback
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriverRPC.cpp
Labels: jira/UNR, size/XS

#3138 Updating to new CI version 1.3
  .buildkite/premerge.steps.yaml
Labels: jira/no-ticket, size/XS

#3101 Disconnect clients in test framework
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/SpatialFunctionalTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/SpatialFunctionalTestFlowController.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/TestMaps/SpatialPlayerDisconnectMap.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Public/SpatialFunctionalTest.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/Public/SpatialFunctionalTestFlowController.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/Public/TestMaps/SpatialPlayerDisconnectMap.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/PlayerDisconnect/PlayerDisconnectController.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/PlayerDisconnect/PlayerDisconnectController.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/PlayerDisconnect/SpatialPlayerDisconnectGameMode.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/PlayerDisconnect/SpatialPlayerDisconnectGameMode.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/PlayerDisconnect/SpatialTestPlayerDisconnect.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/PlayerDisconnect/SpatialTestPlayerDisconnect.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDKFunctionalTests.Build.cs
Labels: jira/UNR, size/L

#3131 [UNR-5468] Add nop4 flag to ziputils call in build.cs
  RequireSetup
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/Build/Build.cs
Labels: jira/UNR, size/M

#3133 [UNR-5209] RPC Container Test Flakes on Windows and Mac
  SpatialGDK/Source/SpatialGDKTests/SpatialGDK/Utils/RPCContainer/RPCContainerTest.cpp
Labels: jira/UNR, size/XS

#3141 Fix settings override path
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialWorldSettings.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialTestSettings.cpp
Labels: jira/UNR, size/XS

#3144 [UNR-5594] Updated CHANGELOG.md with Visual Logger Improvements
  CHANGELOG.md
Labels: jira/UNR, size/XS

#3139 [UNR-5524] make ending deployment during PIE thread safe
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDKServices/Private/LocalDeploymentManager.cpp
  SpatialGDK/Source/SpatialGDKServices/Public/LocalDeploymentManager.h
Labels: jira/UNR, size/S

#3146 Revert "Cherry pick Insights work UNR-5207 (#3044)"
  SpatialGDK/Extras/insights-proxy/InsightsProxy.py
  SpatialGDK/Extras/insights-proxy/README.md
Labels: jira/UNR, size/M

#3145 Update premerge.steps.yaml
  .buildkite/premerge.steps.yaml
Labels: jira/no-ticket, size/XS

#3142 [UNR-5438] Change UNetDriver GetActorEntityId to not lazy construct
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/EngineVersionCheck.h
Labels: jira/UNR, size/S

#3147 UNR-4843: Added a changelog entry
  CHANGELOG.md
Labels: jira/UNR, size/XS

#3134 Add remote insights enabling
  CHANGELOG.md
  RequireSetup
  SpatialGDK/Extras/schema/debug_metrics.schema
  SpatialGDK/Extras/schema/server_worker.schema
  SpatialGDK/Source/SpatialGDK/Private/Interop/DebugMetricsSystem.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialMetrics.cpp
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialMetrics.h
Labels: jira/no-ticket, size/L

#3149 Fix timestamps of updated worker libs
  CHANGELOG.md
  Setup.bat
Labels: jira/UNR, size/S

#3152 Cherry pick "UNR-5290: Optimizing event tracing to reduce overheads"
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriverRPC.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/ActorSystem.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialEventTracer.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialEventTracerUserInterface.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialTraceEventBuilder.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialTraceEventDataBuilder.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/CrossServerRPCHandler.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/CrossServerRPCSender.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/DebugMetricsSystem.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/GlobalStateManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/MigrationDiagnosticsSystem.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/RPCExecutor.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/RPCs/SpatialRPCService.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialPlayerSpawner.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialView/ReceivedOpEventHandler.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialView/ViewDelta.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentReader.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/SpatialEventTracer.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/SpatialEventTracerUserInterface.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/SpatialTraceEvent.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/SpatialTraceEventBuilder.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/SpatialTraceEventDataBuilder.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/SpatialTraceUniqueId.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SnapshotGenerator/SpatialGDKEditorSnapshotGenerator.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/RelevancyTest/RelevancyTest.cpp
  SpatialGDK/Source/SpatialGDKTests/SpatialGDK/Interop/Connection/SpatialEventTracingTest.cpp
Labels: jira/UNR, size/XXL

#3151 Update CHANGELOG.md
  CHANGELOG.md
Labels: jira/no-ticket, size/XS

#3155 Rename test requirenotequal expected param to notexpected
  SpatialGDK/Source/SpatialGDKFunctionalTests/Public/SpatialFunctionalTest.h
Labels: jira/no-ticket, size/XS

#3143 ET debugger V2 (0.13.1)
  CHANGELOG.md
  SetupIncTraceLibs.bat
  SpatialGDK/Extras/core-sdk.version
  SpatialGDK/Source/SpatialGDK/Private/Interop/ActorSystem.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialEventTracer.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialEventTracerUserInterface.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialTraceEventDataBuilder.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/DebugMetricsSystem.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/MigrationDiagnosticsSystem.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/RPCExecutor.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentReader.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/SpatialEventTracer.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/SpatialTraceEventDataBuilder.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/WorkerVersionCheck.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKDefaultLaunchConfigGenerator.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/EventTracingTests/EventTracingTest.cpp
  SpatialGDK/Source/SpatialGDKServices/Private/LocalDeploymentManager.cpp
  SpatialGDK/Source/SpatialGDKServices/Public/SpatialGDKServicesConstants.h
Labels: jira/UNR, size/XL

#3148 [UNR-5430] Gracefully shutdown runtime on windows via process signal
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDKServices/Private/LocalDeploymentManager.cpp
  SpatialGDK/Source/SpatialGDKServices/Private/SpatialCommandUtils.cpp
  SpatialGDK/Source/SpatialGDKServices/Public/LocalDeploymentManager.h
  SpatialGDK/Source/SpatialGDKServices/Public/SpatialCommandUtils.h
Labels: jira/UNR, size/L

#3156 Fix/downgrade stale object warning
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp
Labels: jira/no-ticket, size/XS

#3153 Client crash schema hash mismatch
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
Labels: jira/UNR, size/M
