Repository spatialos/UnrealGDK, pull requests merged in 2021-08, with the labels that each got.

#3268 [UNR-5819] pre/post net receive match native
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/ActorSystem.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentReader.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/ActorSystem.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/TestMaps/SpatialNetworkingMap.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestNetReceive/SpatialTestNetReceive.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestNetReceive/SpatialTestNetReceive.h
Labels: jira/UNR, size/XL

#3266 Startup straightening - pass 1
  CHANGELOG.md
  SpatialGDK/Extras/schema/query_tags.schema
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialVirtualWorkerTranslationManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialVirtualWorkerTranslator.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/GlobalStateManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SkeletonEntities.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/Startup/DefaultServerWorkerStartupHandler.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/Startup/DefaultServerWorkerStartupHandler.h
  SpatialGDK/Source/SpatialGDK/Private/Interop/Startup/SpatialClientWorkerStartupHandler.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/Startup/SpatialClientWorkerStartupHandler.h
  SpatialGDK/Source/SpatialGDK/Private/Interop/WellKnownEntitySystem.cpp
  SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/LegacyLoadBalancingStrategy.cpp
  SpatialGDK/Source/SpatialGDK/Private/Tests/LoadBalanceEnforcerTest.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/EntityFactory.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialVirtualWorkerTranslationManager.h
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialVirtualWorkerTranslator.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/ClaimPartitionHandler.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/SpatialWorkerConnection.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/GlobalStateManager.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/WellKnownEntitySystem.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SnapshotGenerator/SpatialGDKEditorSnapshotGenerator.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKLogParser.cpp
  SpatialGDK/Source/SpatialGDKTests/SpatialGDK/EngineClasses/SpatialVirtualWorkerTranslator/SpatialVirtualWorkerTranslatorTest.cpp
Labels: jira/UNR, size/XXL

#3277 [UNR-5812] Fix nightly test failures - UnresolvedRefTest in Native (v2)
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/StaticSubobjectsTest/StaticSubobjectsTest.cpp
Labels: jira/UNR, size/XS

#3275 [UNR-5848] Add test helpers
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/SpatialFunctionalTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/SpatialFunctionalTestRequireHandler.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Public/SpatialFunctionalTest.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/Public/SpatialFunctionalTestRequireHandler.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/DynamicSubobjectsTest/DynamicSubobjectsTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestNetReceive/SpatialTestNetReceive.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/StaticSubobjectsTest/StaticSubobjectsTest.cpp
Labels: jira/UNR, size/L

#3272 Add player spawning queuing
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialPlayerSpawner.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/Startup/DefaultServerWorkerStartupHandler.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialPlayerSpawner.h
Labels: jira/no-ticket, size/M

#3278 Move tear off channels after rep notifies
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/Interop/ActorSystem.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/ActorSystem.h
Labels: jira/no-ticket, size/S

#3279 [UNR-5790] fix actor going from dormant to awake
  CHANGELOG.md
  RequireSetup
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/ActorSystem.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/TestMaps/SpatialNetworkingMap.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Public/SpatialFunctionalTest.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/AlwaysInterestedTest/AlwaysInterestedTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/DormancyTests/DormancyTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/DormancyTests/DormancyTest.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/DormancyTests/DynamicActorAwakeAfterDormantChangePropertyTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/DormancyTests/DynamicActorAwakeAfterDormantChangePropertyTest.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/DormancyTests/DynamicActorAwakeChangePropertyTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/DormancyTests/DynamicActorDormantAllChangePropertyTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/DormancyTests/DynamicActorSetToAwakeTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/DormancyTests/InitiallyDormantDynamicActorTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/DormancyTests/InitiallyDormantMapActorTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/RelevancyTest/RelevancyTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/UnresolvedReferenceTest/UnresolvedReferenceTest.cpp
Labels: jira/UNR, size/L

#3282 Cleanup NCD values
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/TestActors/AlwaysInterestedTestActors.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/TestActors/RelevancyTestActors.cpp
Labels: jira/no-ticket, size/XS

#3284 Revert "Cleanup NCD values"
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/TestActors/AlwaysInterestedTestActors.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/TestActors/RelevancyTestActors.cpp
Labels: size/XS, jira/no-ticket

#3283 [UNR-5861]Fix/called is actor group owner for class before notify begin play
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialStatics.cpp
Labels: size/S, jira/UNR

#3259 [UNR-5632] Add partition metadata subsystem
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialGameInstance.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialHandoverManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialPartitionSystem.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialPartitionSystemImpl.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialPartitionSystemImpl.h
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialStrategySystem.cpp
  SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/LBDataStorage.cpp
  SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/LegacyLoadBalancingPartitionSystem.cpp
  SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/LegacyLoadBalancingStrategy.cpp
  SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/PartitionManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/Schema/StaticSymbols.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/InterestFactory.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialGameInstance.h
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialHandoverManager.h
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialPartitionSystem.h
  SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/LBDataStorage.h
  SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/LegacyLoadBalancingCommon.h
  SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/LegacyLoadBalancingPartitionSystem.h
  SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/LegacyLoadbalancingComponents.h
  SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/LoadBalancingTypes.h
  SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/PartitionManager.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/InterestFactory.h
Labels: size/XXL, jira/UNR

#3281 Startup straightening - pass 2
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/Startup/AssignedPartitionStartupSteps.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/Startup/AssignedPartitionStartupSteps.h
  SpatialGDK/Source/SpatialGDK/Private/Interop/Startup/DefaultServerWorkerStartupHandler.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/Startup/DefaultServerWorkerStartupHandler.h
  SpatialGDK/Source/SpatialGDK/Private/Interop/Startup/ElectGsmAuthWorkerStep.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/Startup/ElectGsmAuthWorkerStep.h
  SpatialGDK/Source/SpatialGDK/Private/Interop/Startup/HandleSkeletonEntityCreationStep.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/Startup/HandleSkeletonEntityCreationStep.h
  SpatialGDK/Source/SpatialGDK/Private/Interop/Startup/PartitionCreationStartupSteps.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/Startup/PartitionCreationStartupSteps.h
  SpatialGDK/Source/SpatialGDK/Private/Interop/Startup/ServerWorkerCreationStartupSteps.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/Startup/ServerWorkerCreationStartupSteps.h
  SpatialGDK/Source/SpatialGDK/Private/Interop/Startup/ServerWorkerStartupCommon.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/Startup/ServerWorkerStartupCommon.h
  SpatialGDK/Source/SpatialGDK/Private/Interop/Startup/SpatialClientWorkerStartupHandler.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/Startup/SpatialClientWorkerStartupHandler.h
  SpatialGDK/Source/SpatialGDK/Private/Interop/Startup/SpatialStartupCommon.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/Startup/SpatialStartupCommon.h
  SpatialGDK/Source/SpatialGDK/Private/Interop/Startup/StartPlayStartupSteps.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/Startup/StartPlayStartupSteps.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/SpatialWorkerConnection.h
Labels: size/XXL, jira/UNR

#3285 Cleanup NCD values (#3282)
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/TestActors/AlwaysInterestedTestActors.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/TestActors/RelevancyTestActors.cpp
Labels: size/XS, jira/no-ticket

#3243 [UNR-5632] Have the strategy worker build the actor sets
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialHandoverManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialStrategySystem.cpp
  SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/ActorSetSystem.cpp
  SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/LegacyLoadBalancingStrategy.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/EntityFactory.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialHandoverManager.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialStrategySystem.h
  SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/ActorSetSystem.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/ActorSetMember.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestLoadBalancingData/SpatialTestLoadBalancingData.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestLoadBalancingData/SpatialTestLoadBalancingData.h
Labels: size/XXL, jira/UNR

#3290 Updating 0.14.0 docs links to new website
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  SpatialGDK/Documentation/README.md
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKCloudDeploymentConfiguration.cpp
  ci/ReleaseTool/ReleaseCommand.cs
Labels: size/S, jira/no-ticket

#3292 [UNR-5131] Remove the authoritative destruction switch
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/ActorSystem.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/ActorSystem.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestCharacterMigration/SpatialTestCharacterMigration.cpp
Labels: size/M, jira/UNR

#3276 [UNR-5437] Allocate entityid during begin play
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/ActorSystem.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/GlobalStateManager.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/ActorSystem.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/TestMaps/SpatialNetworkingMap.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/DormancyTests/RefreshActorDormancyTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/DormancyTests/RefreshActorDormancyTest.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/DormancyTests/RefreshActorDormancyTestActor.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/DormancyTests/RefreshActorDormancyTestActor.h
Labels: size/L, jira/UNR

#3253 Add a debug mode to detect non-auth modification of data
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriverAuthorityDebugger.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialShadowActor.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/ActorSystem.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriverAuthorityDebugger.h
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialShadowActor.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/TestMaps/SpatialDataDebugMap.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Public/TestMaps/SpatialDataDebugMap.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPropertyReplication/ReplicatedTestActorBasic.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPropertyReplication/ReplicatedTestActorBasic.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPropertyReplication/ReplicatedTestActorSubobject.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPropertyReplication/ReplicatedTestActorSubobject.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPropertyReplication/SpatialTestPropertyReplicationMultiworker.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPropertyReplication/SpatialTestPropertyReplicationMultiworker.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPropertyReplication/SpatialTestPropertyReplicationSubobject.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPropertyReplication/SpatialTestPropertyReplicationSubobject.h
Labels: size/XXL, jira/UNR

#3296 [UNR-5873] Upgrade Worker SDK and Runtime versions to 15.3.0
  RequireSetup
  SpatialGDK/Extras/core-sdk.version
  SpatialGDK/Source/SpatialGDK/Public/Utils/WorkerVersionCheck.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKDefaultLaunchConfigGenerator.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h
  SpatialGDK/Source/SpatialGDKServices/Public/SpatialGDKServicesConstants.h
Labels: size/S, jira/UNR

#3291 [UNR-5632] Add ServerWorker System
  SpatialGDK/Extras/schema/server_worker.schema
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialServerWorkerSystem.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialServerWorkerSystemImpl.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialServerWorkerSystemImpl.h
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialStrategySystem.cpp
  SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/ActorSetSystem.cpp
  SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/LBDataStorage.cpp
  SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/LegacyLoadBalancingStrategy.cpp
  SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/LegacyServerWorkerSystem.cpp
  SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/PartitionManager.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialServerWorkerSystem.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialStrategySystem.h
  SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/ActorSetSystem.h
  SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/LBDataStorage.h
  SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/LegacyLoadBalancingStrategy.h
  SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/LegacyServerWorkerSystem.h
  SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/LoadBalancingStrategy.h
  SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/PartitionManager.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSchemaGenerator.h
  SpatialGDK/Source/SpatialGDKEditorCommandlet/Private/Commandlets/CookAndGenerateSchemaCommandlet.cpp
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/SpatialGDKEditorSchemaGeneratorTest.cpp
Labels: size/XL, jira/UNR

#3297 [UNR-5849] Make subobject test about actor component, instead of a spawned actor.
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPropertyReplication/ReplicatedTestActorSubobject.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPropertyReplication/ReplicatedTestActorSubobject.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPropertyReplication/SpatialTestPropertyReplicationSubobject.cpp
Labels: size/M, jira/UNR

#3300 Fix cast warning in shadow actor
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialShadowActor.cpp
Labels: size/XS, jira/no-ticket

#3301 Fix player controllers being deleted incorrectly
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/Interop/ActorSystem.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/ClientConnectionManager.cpp
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.cxx
Labels: size/S, jira/no-ticket
