Repository spatialos/UnrealGDK, pull requests merged in 2021-06, with the labels that each got.

#3136 [UNR-5447] Replace Handover with ServerOnly replication condition
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/Components/RemotePossessionComponent.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/ActorSystem.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialClassInfoManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentFactory.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentReader.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/EntityFactory.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/Components/RemotePossessionComponent.h
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/ActorSystem.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialClassInfoManager.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialConditionMapFilter.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.cxx
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/ComponentFactory.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/ComponentReader.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/EngineVersionCheck.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/RepDataUtils.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/SchemaDatabase.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SchemaGenerator.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SchemaGenerator.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/TypeStructure.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/TypeStructure.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/Utils/DataTypeUtilities.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/Utils/DataTypeUtilities.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestHandoverReplication/SpatialTestHandoverActorComponentReplication.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestHandoverReplication/SpatialTestHandoverActorComponentReplication.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestMultiServerUnrealComponents/TestUnrealComponents.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestMultiServerUnrealComponents/TestUnrealComponents.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPossession/SpatialTestRemotePossession.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPossession/SpatialTestRemotePossession.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPossession/TestPossessionPlayerController.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPossession/TestPossessionPlayerController.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestReplicationConditions/SpatialTestReplicationConditions.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestReplicationConditions/SpatialTestReplicationConditions.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestReplicationConditions/TestReplicationConditionsActor.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestReplicationConditions/TestReplicationConditionsActor.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestSingleServerDynamicComponents/TestDynamicComponent.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestSingleServerDynamicComponents/TestDynamicComponent.h
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/SchemaGenObjectStub.cpp
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/SchemaGenObjectStub.h
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/SpatialGDKEditorSchemaGeneratorTest.cpp
Labels: jira/UNR, size/XXL

#3107 [UNR-4297] always remove dynamic components from clientnetload actors
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/ActorSystem.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/ClientNetLoadActorHelper.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialPackageMapClient.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/ActorSystem.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/ClientNetLoadActorHelper.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/UnrealObjectRef.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialActorUtils.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/SpatialFunctionalTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/TestMaps/SpatialNetworkingMap.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Public/SpatialFunctionalTest.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/DynamicSubobjectsTest/DynamicSubObjectsTest.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/DynamicSubobjectsTest/DynamicSubobjectTestActor.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/DynamicSubobjectsTest/DynamicSubobjectTestActor.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/DynamicSubobjectsTest/DynamicSubobjectsTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/DynamicSubobjectsTest/ReplicatedGASTestActor.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/DynamicSubobjectsTest/ReplicatedGASTestActor.h
  SpatialGDK/Source/SpatialGDKServices/Private/SpatialCommandUtils.cpp
Labels: jira/UNR, size/XXL

#3158 Fixing flaky RPCQueueWarningDefaultTimeout test.... kinda
  SpatialGDK/Source/SpatialGDK/Private/Utils/RPCContainer.cpp
  SpatialGDK/Source/SpatialGDKTests/SpatialGDK/Utils/RPCContainer/RPCContainerTest.cpp
Labels: jira/UNR, size/XS

#3159 Disable TestDebugInterface because of flakyness.
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/DebugInterface/SpatialDebugInterfaceTest.cpp
Labels: jira/no-ticket, size/XS

#3161 [UNR-4146] Solve replicated Actor with disabled collision
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/ExpectedSchema/NonSpatialTypeActor.schema
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/ExpectedSchema/SpatialTypeActor.schema
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/ExpectedSchema/SpatialTypeActorWithActorComponent.schema
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/ExpectedSchema/SpatialTypeActorWithMultipleActorComponents.schema
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/ExpectedSchema/SpatialTypeActorWithMultipleObjectComponents.schema
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/ExpectedSchema_425/NonSpatialTypeActor.schema
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/ExpectedSchema_425/SpatialTypeActor.schema
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/ExpectedSchema_425/SpatialTypeActorWithActorComponent.schema
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/ExpectedSchema_425/SpatialTypeActorWithMultipleActorComponents.schema
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/ExpectedSchema_425/SpatialTypeActorWithMultipleObjectComponents.schema
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/SpatialGDKEditorSchemaGeneratorTest.cpp
Labels: jira/no-ticket, size/XL

#3163 Fixes UNR-5610 - UnrealGDK/Setup.sh throws `sed: can't read : No such file or directory`
  CHANGELOG.md
  RequireSetup
  Setup.sh
Labels: jira/UNR, size/XS

#3165 UNR-5530 Gameplay debugger interest setup
  SpatialGDK/Source/SpatialGDK/Private/Utils/InterestFactory.cpp
  SpatialGDK/Source/SpatialGDK/Public/Utils/InterestFactory.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialActorUtils.h
Labels: jira/UNR, size/M

#3171 add missing gameplay debugger define to SpatialGDK Build.cs
  SpatialGDK/Source/SpatialGDK/SpatialGDK.Build.cs
Labels: jira/no-ticket, size/XS

#3174 Fix server only schema include
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.cxx
Labels: jira/no-ticket, size/XS

#3164 merge 0.13.1 into master
  CHANGELOG.md
  RequireSetup
  SetupIncTraceLibs.bat
  SpatialGDK/Extras/core-sdk.version
  SpatialGDK/Extras/insights-proxy/InsightsProxy.py
  SpatialGDK/Extras/insights-proxy/README.md
  SpatialGDK/Extras/schema/debug_metrics.schema
  SpatialGDK/Extras/schema/server_worker.schema
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/ActorSystem.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialEventTracer.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialEventTracerUserInterface.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialTraceEventDataBuilder.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/DebugMetricsSystem.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/MigrationDiagnosticsSystem.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/RPCExecutor.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentReader.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialMetrics.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/SpatialEventTracer.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/SpatialTraceEventDataBuilder.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialMetrics.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/WorkerVersionCheck.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKDefaultLaunchConfigGenerator.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/EventTracingTests/EventTracingTest.cpp
  SpatialGDK/Source/SpatialGDKServices/Private/LocalDeploymentManager.cpp
  SpatialGDK/Source/SpatialGDKServices/Public/SpatialGDKServicesConstants.h
  SpatialGDK/SpatialGDK.uplugin
Labels: jira/no-ticket, size/XXL

#3172 Disable server only components when handover is disabled
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialClassInfoManager.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialClassInfoManager.h
Labels: jira/no-ticket, size/S

#3170 Fix multicast rpc overwrite bug
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/Interop/RPCs/MulticastRPCService.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/RPCs/MulticastRPCService.h
Labels: jira/UNR, size/M

#3169 De-duplicate setup steps
  SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialLatencyTracer.h
Labels: jira/UNR, size/S

#3023 unr-5322 view coordinator interface
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialGameInstance.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/CrossServerRPCSender.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialView/ViewCoordinator.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/SpatialWorkerConnection.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialView/SpatialOSWorker.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialView/ViewCoordinator.h
Labels: jira/UNR, size/L

#3175 Fix spatial flow controller registration
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/SpatialFunctionalTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/SpatialFunctionalTestFlowController.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/SpatialFunctionalTestFlowControllerSpawner.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Public/SpatialFunctionalTestFlowController.h
Labels: jira/UNR, size/M

#3181 Revert "Fix spatial flow controller registration"
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/SpatialFunctionalTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/SpatialFunctionalTestFlowController.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/SpatialFunctionalTestFlowControllerSpawner.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Public/SpatialFunctionalTestFlowController.h
Labels: jira/no-ticket, size/M

#3157 Clean up legacy tracer
  SetupIncTraceLibs.bat
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialGameInstance.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/RPCExecutor.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/RPCs/SpatialRPCService.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentFactory.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialLatencyTracer.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialLatencyTracerMinimal.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/SpatialWorkerConnection.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/RPCs/SpatialRPCService.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/RPCPayload.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialCommonTypes.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialGDKLoader.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/ComponentFactory.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialLatencyTracer.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialLatencyTracerMinimal.h
  SpatialGDK/Source/SpatialGDK/SpatialGDK.Build.cs
  SpatialGDK/Source/SpatialGDKEditor/Private/SnapshotGenerator/SpatialGDKEditorSnapshotGenerator.cpp
Labels: jira/UNR, size/XL

#3167 Update release-process.md
  SpatialGDK/Extras/internal-documentation/release-process.md
Labels: jira/UNR, size/XS

#3178 [UNR-5531] Gameplay Debugger replicator LB strategy and server selection
  SpatialGDK/Extras/schema/gameplay_debugger_component.schema
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriverGameplayDebuggerContext.cpp
  SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/GameplayDebuggerLBStrategy.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/EntityFactory.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/InterestFactory.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriverGameplayDebuggerContext.h
  SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/GameplayDebuggerLBStrategy.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/GameplayDebuggerComponent.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.cxx
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/InterestFactory.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialActorUtils.h
  SpatialGDK/Source/SpatialGDK/SpatialGDK.Build.cs
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/SpatialFunctionalTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestHandoverReplication/SpatialTestHandoverDynamicReplication.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/UNR-3761/SpatialTestHandover/SpatialTestHandover.cpp
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/SpatialGDKEditorSchemaGeneratorTest.cpp
Labels: jira/UNR, size/XXL

#3186 Clang format .cxx files
  SpatialGDK/Extras/git/pre-commit
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.cxx
Labels: jira/no-ticket, size/XL

#3183 Expose info for grid LB strategy
  SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/GridBasedLBStrategy.h
Labels: jira/no-ticket, size/XS

#3188 Fixed "Test" and "Shipping" builds due to missing gameplay debugger defines
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriverGameplayDebuggerContext.cpp
  SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/GameplayDebuggerLBStrategy.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriverGameplayDebuggerContext.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialActorUtils.h
Labels: jira/no-ticket, size/S

#3177 Add Insights stopping via SpatialCommand
  CHANGELOG.md
  RequireSetup
  SpatialGDK/Extras/schema/debug_metrics.schema
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialMetrics.cpp
  SpatialGDK/Source/SpatialGDK/Public/Utils/EngineVersionCheck.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialMetrics.h
Labels: jira/no-ticket, size/XL

#3168 [UNR-5609] Client correctly remove replicated static subobjects on bNetLoadOnClient actor that have been removed by server
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/ActorSystem.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/ClientNetLoadActorHelper.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialClassInfoManager.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialPackageMapClient.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/ActorSystem.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/ClientNetLoadActorHelper.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialClassInfoManager.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialActorUtils.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/TestMaps/SpatialNetworkingMap.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/StaticSubobjectsTest/StaticSubobjectTestActor.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/StaticSubobjectsTest/StaticSubobjectTestActor.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/StaticSubobjectsTest/StaticSubobjectsTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/StaticSubobjectsTest/StaticSubobjectsTest.h
Labels: jira/UNR, size/XXL

#3191 Added missing 'ActorReady' check to SpatialCleanupConnectionTest
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialCleanupConnectionTest/SpatialCleanupConnectionTest.cpp
Labels: jira/no-ticket, size/XS

#3193 fix static subobjects test not passing in native
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/StaticSubobjectsTest/StaticSubobjectsTest.cpp
Labels: jira/no-ticket, size/XS

#3192 [UNR-5579] Re-fix too many spatial flow controllers
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/SpatialFunctionalTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/SpatialFunctionalTestFlowController.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/SpatialFunctionalTestFlowControllerSpawner.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Public/SpatialFunctionalTestFlowController.h
Labels: jira/UNR, size/M

#3176 Makes `dry-run/*`, `skip-ci/`, `doc/*` & `docs/*` branches exempt from premerge
  .buildkite/premerge.definition.yaml
Labels: jira/UNR, size/XS

#3194 Revert [UNR-5579] (again)
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/SpatialFunctionalTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/SpatialFunctionalTestFlowController.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/SpatialFunctionalTestFlowControllerSpawner.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Public/SpatialFunctionalTestFlowController.h
Labels: jira/UNR, size/M

#3198 Update default template displayname
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h
Labels: jira/no-ticket, size/XS

#3195 [UNR-5559] Fix: create snapshot folder at start of deployment, delete if empty for interop with squid snapshot endpoint
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDKServices/Private/LocalDeploymentManager.cpp
  SpatialGDK/Source/SpatialGDKServices/Public/LocalDeploymentManager.h
Labels: jira/UNR, size/S

#3199 Make a 0.14.0-rc section in Changelog
  CHANGELOG.md
Labels: jira/no-ticket, size/XS

#3201 Update default branches to 0.14.0-rc
  .buildkite/premerge.steps.yaml
Labels: jira/no-ticket, size/XS

#3202 Revert CompleteEntity recalculation
  SpatialGDK/Source/SpatialGDK/Private/Interop/ActorSystem.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialView/SubView.cpp
  SpatialGDK/Source/SpatialGDK/Public/SpatialView/SubView.h
Labels: jira/no-ticket, size/S

#3185 UNR-4849: Removed initial op reordering
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/ActorSystem.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialView/ConnectionHandler/InitialOpListConnectionHandler.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/SpatialWorkerConnection.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialView/ConnectionHandler/InitialOpListConnectionHandler.h
Labels: jira/UNR, size/XL

#3205 UNR-4849: Fixed changelog
  CHANGELOG.md
Labels: jira/UNR, size/XS

#3180 [UNR-5467] Bugfix: Do not generate worker jsons for unused worker types
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKDefaultWorkerJsonGenerator.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKServices/LocalDeploymentManager/LocalDeploymentManagerUtilities.cpp
Labels: jira/UNR, size/M

#3206 Add Ownership Completeness advance
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/OwnershipCompletenessHandler.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/OwnershipCompletenessHandler.h
Labels: jira/no-ticket, size/S

#3182 Bugfix/unr 5214
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/ActorSystem.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentReader.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialConditionMapFilter.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestReplicationConditions/SpatialTestReplicationConditions.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestReplicationConditions/TestReplicationConditionsActor.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestReplicationConditions/TestReplicationConditionsActor.h
Labels: jira/UNR, size/M

#3137 [UNR-5489] Spike centralized load balancer
  SpatialGDK/Extras/schema/authority_intent.schema
  SpatialGDK/Extras/schema/known_entity_auth_component_set.schema
  SpatialGDK/Extras/schema/partition_auth_component_set.schema
  SpatialGDK/Extras/schema/query_tags.schema
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialHandoverManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialLoadBalanceEnforcer.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialVirtualWorkerTranslationManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialVirtualWorkerTranslator.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialStrategySystem.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/WellKnownEntitySystem.cpp
  SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/GridBasedLBStrategy.cpp
  SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/LBDataStorage.cpp
  SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/LayeredLBStrategy.cpp
  SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/LegacyLoadBalancingStrategy.cpp
  SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/PartitionManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp
  SpatialGDK/Source/SpatialGDK/Private/Tests/LoadBalanceEnforcerTest.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/EntityFactory.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/InterestFactory.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialStatics.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialHandoverManager.h
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialVirtualWorkerTranslationManager.h
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialVirtualWorkerTranslator.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialStrategySystem.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/WellKnownEntitySystem.h
  SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/AbstractLBStrategy.h
  SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/GridBasedLBStrategy.h
  SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/LBDataStorage.h
  SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/LayeredLBStrategy.h
  SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/LegacyLoadBalancingStrategy.h
  SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/LoadBalancingStrategy.h
  SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/LoadBalancingTypes.h
  SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/PartitionManager.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/AuthorityIntent.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/ServerWorker.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.cxx
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/EntityFactory.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/InterestFactory.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialStatics.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SnapshotGenerator/SpatialGDKEditorSnapshotGenerator.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/SpatialFunctionalTestRequireHandler.cpp
  SpatialGDK/Source/SpatialGDKTests/SpatialGDK/EngineClasses/SpatialVirtualWorkerTranslator/SpatialVirtualWorkerTranslatorTest.cpp
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/SpatialGDKEditorSchemaGeneratorTest.cpp
Labels: jira/UNR, size/XXL

#3208 Fixed dormancy unresolved ref checking
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h
Labels: jira/no-ticket, size/XS

#3210 Fixed dormancy unresolved ref checking (#3208)
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h
Labels: jira/no-ticket, size/XS

#3207 Fix spatial flow controller registration
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/SpatialFunctionalTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/SpatialFunctionalTestFlowController.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Public/SpatialFunctionalTest.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/Public/SpatialFunctionalTestFlowController.h
Labels: jira/UNR, size/M

#3212 Correctly handle sampling of spans
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/SpatialEventTracer.h
Labels: jira/UNR, size/XS

#3214 [UNR-5171] Fix a functional test is already running error
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/SpatialFunctionalTest.cpp
Labels: jira/UNR, size/XS

#3220 Fix ASpatialTestReplicationConditions COND_Custom test
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestReplicationConditions/SpatialTestReplicationConditions.cpp
Labels: jira/no-ticket, size/S

#3217 Fixing ET Settings Warnings
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialEventTracer.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/SpatialEventTracer.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKDefaultLaunchConfigGenerator.cpp
Labels: jira/no-ticket, size/M

#3211 Additional facilities for getting LB data and cleanup of the systems using them
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialStrategySystem.cpp
  SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/LBDataStorage.cpp
  SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/LegacyLoadBalancingStrategy.cpp
  SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/PartitionManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/Schema/ActorOwnership.h
  SpatialGDK/Source/SpatialGDK/Private/Schema/StaticSymbols.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialStrategySystem.h
  SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/LBDataStorage.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/ActorGroupMember.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/ActorSetMember.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/AuthorityIntent.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/DebugComponent.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/GameplayDebuggerComponent.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/Interest.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/MigrationDiagnostic.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/NetOwningClientWorker.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/PlayerSpawner.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/Restricted.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/ServerWorker.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/SnapshotVersionComponent.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/SpatialDebugging.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/SpawnData.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/StandardLibrary.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/Tombstone.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/UnrealMetadata.h
Labels: jira/no-ticket, size/XXL

#3219 Small tweaks
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/Interest/NetCullDistanceInterest.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h
Labels: jira/no-ticket, size/M

#3213 [UNR-5750] Add track player mode to gameplay debugger
  RequireSetup
  SpatialGDK/Extras/schema/gameplay_debugger_component.schema
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriverGameplayDebuggerContext.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriverGameplayDebuggerContext.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/GameplayDebuggerComponent.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/EngineVersionCheck.h
Labels: jira/UNR, size/L

#3224 [UNR-5773] Add Gameplay Debugger to changelog
  CHANGELOG.md
Labels: jira/UNR, size/XS

#3225 UNR-5777 gameplay debugger backports
  CHANGELOG.md
  RequireSetup
  SpatialGDK/Extras/schema/gameplay_debugger_component.schema
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriverGameplayDebuggerContext.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriverGameplayDebuggerContext.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/GameplayDebuggerComponent.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/EngineVersionCheck.h
Labels: jira/UNR, size/L

#3226 [UNR-5726] Fix visibility test flake
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/UNR-3761/SpatialTestMultipleOwnership/SpatialTestMultipleOwnership.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/UNR-3761/SpatialTestMultipleOwnership/SpatialTestMultipleOwnership.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/VisibilityTest/VisibilityTest.cpp
Labels: jira/UNR, size/S

#3227 [UNR-5762] Avoid a crash in the routing worker in case of interest races on the receiver
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialRoutingSystem.cpp
  SpatialGDK/Source/SpatialGDK/Private/Tests/TestRoutingWorker.cpp
  SpatialGDK/Source/SpatialGDK/Public/Utils/CrossServerUtils.h
Labels: jira/UNR, size/M

#3222 UNR-5752: Fixed an error caused by destroying an actor between entity creation and confirmation thereof
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/Interop/ActorSystem.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/TestMaps/Spatial2WorkerMap.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialActorResolutionTest/SpatialActorResolutionTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialActorResolutionTest/SpatialActorResolutionTest.h
Labels: jira/UNR, size/M
