Repository spatialos/UnrealGDK, pull requests merged in 2021-03, with the labels that each got.

#2912 [UNR-5020] Custom configs for generated maps
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorModule.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialTestSettings.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorModule.h
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialTestSettings.h
  SpatialGDK/Source/SpatialGDKEditor/SpatialGDKEditor.Build.cs
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/GenerateTestMapsCommandlet.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/SpatialGDKFunctionalTestsModule.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/TestMapGeneration.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/TestMaps/GeneratedTestMap.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/TestMaps/SpatialAuthorityMap.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Public/SpatialGDKFunctionalTestsModule.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/Public/TestMapGeneration.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/Public/TestMaps/GeneratedTestMap.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialAuthorityTest/SpatialAuthoritySettingsOverride.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialComponentTest/SpatialComponentSettingsOverride.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDKFunctionalTests.Build.cs
Labels: jira/UNR, size/XL

#2928 Fix snapshot reloading tests
  SpatialGDK/Source/SpatialGDK/Private/Utils/EntityFactory.cpp
Labels: jira/no-ticket, size/XS

#2901 Override test settings
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialEventTracer.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialWorldSettings.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorModule.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorSettings.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialTestSettings.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorModule.h
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialTestSettings.h
  SpatialGDK/Source/SpatialGDKEditor/SpatialGDKEditor.Build.cs
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/GenerateTestMapsCommandlet.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/SpatialFunctionalTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/SpatialGDKFunctionalTestsModule.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/TestMapGeneration.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/TestMaps/GeneratedTestMap.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/TestMaps/SpatialAuthorityMap.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/TestMaps/SpatialComponentMap.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Public/SpatialFunctionalTest.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/Public/SpatialGDKFunctionalTestsModule.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/Public/TestMapGeneration.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/Public/TestMaps/GeneratedTestMap.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/EventTracingTests/EventTracingSettingsOverride.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/EventTracingTests/EventTracingSettingsOverride.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/EventTracingTests/EventTracingTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialAuthorityTest/SpatialAuthoritySettingsOverride.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialAuthorityTest/SpatialAuthoritySettingsOverride.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialCleanupConnectionTest/SpatialCleanupConnectionTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialComponentTest/SpatialComponentSettingsOverride.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialComponentTest/SpatialComponentSettingsOverride.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialSnapshotTest/SpatialSnapshotDummyTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialSnapshotTest/SpatialSnapshotTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialSnapshotTest/SpatialSnapshotTestPart1SettingsOverride.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialSnapshotTest/SpatialSnapshotTestPart1SettingsOverride.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialSnapshotTest/SpatialSnapshotTestPart2SettingsOverride.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialSnapshotTest/SpatialSnapshotTestPart2SettingsOverride.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/UNR-3761/SpatialTestNetReference/SpatialTestNetReference.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/UNR-3761/SpatialTestNetReference/SpatialTestNetReference.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/UNR-3761/SpatialTestNetReference/SpatialTestNetReferenceSettingsOverride.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/UNR-3761/SpatialTestNetReference/SpatialTestNetReferenceSettingsOverride.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/UNR-3761/SpatialTestWorldComposition/SpatialTestWorldComposition.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDKFunctionalTests.Build.cs
Labels: jira/UNR, size/XXL

#2930 Cleanup legacy client-quit message
  SpatialGDK/Extras/schema/player_controller.schema
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetConnection.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/EntityFactory.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetConnection.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/PlayerController.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
Labels: jira/UNR, size/M

#2594 Property replication test
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/SpatialFunctionalTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/TestMaps/SpatialPropertyReplicationMap.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Public/TestMaps/SpatialPropertyReplicationMap.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPropertyReplication/ReplicatedTestActor.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPropertyReplication/ReplicatedTestActor.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPropertyReplication/SpatialTestPropertyReplication.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPropertyReplication/SpatialTestPropertyReplication.h
Labels: jira/UNR, size/L

#2922 [UNR-5035] Add base infrastructure for modularised RPC service
  SpatialGDK/Source/SpatialGDK/Private/Interop/RPCs/RPCService.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/RPCs/RPCTypes.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/RPCs/RPCService.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/RPCs/RPCTypes.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/RPCPayload.h
Labels: jira/UNR, size/XXL

#2932 Correctly state the number of clients in my test.
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPropertyReplication/SpatialTestPropertyReplication.cpp
Labels: jira/UNR, size/XS

#2908 [UNR-5019] Generate test maps from editor
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbarCommands.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorToolbar.h
  SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorToolbarCommands.h
  SpatialGDK/Source/SpatialGDKEditorToolbar/SpatialGDKEditorToolbar.Build.cs
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/TestMapGeneration.cpp
Labels: jira/UNR, size/S

#2931 UNR 4980 entities not deleted
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/ActorSystem.cpp
Labels: jira/UNR, size/XS

#2936 Tidying up some bits and pieces for ET Sampling
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialEventTracer.cpp
  SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h
Labels: jira/UNR, size/XS

#2929 Unr 4845 move sender
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetConnection.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriverDebugContext.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/ActorSystem.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/WellKnownEntitySystem.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialView/ViewCoordinator.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialDebuggerSystem.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/ActorSystem.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialSender.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/WellKnownEntitySystem.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialView/ViewCoordinator.h
Labels: jira/no-ticket, size/XXL

#2899 Shutting runtime down gracefully
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorSettings.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
  SpatialGDK/Source/SpatialGDKServices/Private/LocalDeploymentManager.cpp
  SpatialGDK/Source/SpatialGDKServices/Public/LocalDeploymentManager.h
Labels: jira/UNR, size/M

#2938 Feature/unr 3774 detect out of date snapshots
  .github/pull-request-template.md
  CHANGELOG.md
  RequireSetup
  SpatialGDK/Extras/schema/global_state_manager.schema
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/GlobalStateManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/WellKnownEntitySystem.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/GlobalStateManager.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/SnapshotVersionComponent.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SnapshotGenerator/SpatialGDKEditorSnapshotGenerator.cpp
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/SpatialGDKEditorSchemaGeneratorTest.cpp
Labels: jira/UNR, size/L

#2942 UNR-4915 fix auto generated launch config for clients.
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKDefaultLaunchConfigGenerator.cpp
Labels: jira/UNR, size/XS

#2945 World settings fix
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/Interop/GlobalStateManager.cpp
Labels: jira/UNR, size/XS

#2926 Feature/initial only support
  CHANGELOG.md
  SpatialGDK/Extras/schema/initial_only_presence.schema
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/ActorSystem.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/InitialOnlyFilter.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialClassInfoManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialView/EntityQuery.cpp
  SpatialGDK/Source/SpatialGDK/Private/Tests/SpatialView/CommandRetryHandlerTest.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentFactory.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/EntityFactory.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/InterestFactory.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/RPCContainer.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/ActorSystem.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/InitialOnlyFilter.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/RPCs/SpatialRPCService.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialClassInfoManager.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialConditionMapFilter.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialView/EntityQuery.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/ComponentFactory.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/RPCContainer.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/SchemaDatabase.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SchemaGenerator.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/TypeStructure.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/TypeStructure.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/TestMaps/SpatialInitialOnlyMap.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Public/TestMaps/SpatialInitialOnlyMap.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/GameModeReplicationTest/GameModeReplicationTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestHandoverReplication/SpatialTestHandoverDynamicReplication.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestInitialOnly/SpatialTestInitialOnlyForInterestActor.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestInitialOnly/SpatialTestInitialOnlyForInterestActor.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestInitialOnly/SpatialTestInitialOnlyForInterestActorWithUpdatedValue.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestInitialOnly/SpatialTestInitialOnlyForInterestActorWithUpdatedValue.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestInitialOnly/SpatialTestInitialOnlyForSpawnActor.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestInitialOnly/SpatialTestInitialOnlyForSpawnActor.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestInitialOnly/SpatialTestInitialOnlyForSpawnComponents.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestInitialOnly/SpatialTestInitialOnlyForSpawnComponents.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestInitialOnly/TestClasses/SpatialTestInitialOnlySpawnActor.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestInitialOnly/TestClasses/SpatialTestInitialOnlySpawnActor.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestInitialOnly/TestClasses/SpatialTestInitialOnlySpawnActorWithComponent.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestInitialOnly/TestClasses/SpatialTestInitialOnlySpawnActorWithComponent.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestInitialOnly/TestClasses/SpatialTestInitialOnlySpawnComponent.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestInitialOnly/TestClasses/SpatialTestInitialOnlySpawnComponent.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestSingleServerDynamicComponents/SpatialTestSingleServerDynamicComponents.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestSingleServerDynamicComponents/SpatialTestSingleServerDynamicComponents.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestSingleServerDynamicComponents/TestDynamicComponent.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestSingleServerDynamicComponents/TestDynamicComponent.h
  SpatialGDK/Source/SpatialGDKTests/SpatialGDK/Utils/RPCContainer/RPCContainerTest.cpp
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/SchemaGenObjectStub.cpp
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/SchemaGenObjectStub.h
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/SpatialGDKEditorSchemaGeneratorTest.cpp
Labels: jira/no-ticket, size/XXL

#2934 Additional logging which can sometimes be user error
  SpatialGDK/Source/SpatialGDK/Private/Interop/ActorSystem.cpp
Labels: jira/no-ticket, size/XS

#2947 Fix shipping builds
  SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp
Labels: jira/no-ticket, size/XS

#2940 [UNR-4657] Convert functional tests to use C++ generated maps
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/SpatialTest1x2GridSmallInterestStrategy.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/SpatialTest1x2GridSmallInterestWorkerSettings.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/Test1x2GridStrategy.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/Test1x2WorkerSettings.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/Test2x2GridStrategy.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/Test2x2WorkerSettings.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/TestMaps/GeneratedTestMap.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/TestMaps/Spatial2WorkerMap.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/TestMaps/Spatial2WorkerSmallInterestMap.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/TestMaps/Spatial4WorkerMap.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/TestMaps/SpatialAuthorityMap.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/TestMaps/SpatialComponentMap.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/TestMaps/SpatialHandoverMap.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Public/SpatialTest1x2GridSmallInterestStrategy.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/Public/SpatialTest1x2GridSmallInterestWorkerSettings.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/Public/Test1x2GridStrategy.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/Public/Test1x2WorkerSettings.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/Public/Test2x2GridStrategy.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/Public/Test2x2WorkerSettings.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/Public/TestMaps/GeneratedTestMap.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/Public/TestWorkerSettings.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/DebugInterface/SpatialDebugInterfaceTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/DebugInterface/SpatialDebugInterfaceTest.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestCharacterMigration/SpatialTestCharacterMigration.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestCharacterMigration/SpatialTestCharacterMigration.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPlayerControllerMigration/SpatialTestPlayerControllerHandover.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPlayerControllerMigration/SpatialTestPlayerControllerHandover.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPossession/CrossServerPossessionMap.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPossession/CrossServerPossessionMap.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestTearOff/SpatialTestTearOff.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestTearOff/SpatialTestTearOff.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/UNR-3761/SpatialTestClientNetOwnership/SpatialTestNetOwnership.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/UNR-3761/SpatialTestClientNetOwnership/SpatialTestNetOwnership.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/UNR-3761/SpatialTestNetReference/SpatialTestNetReference.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/UNR-3761/SpatialTestNetReference/SpatialTestNetReference.h
Labels: jira/UNR, size/XXL

#2948 [UNR-5136] Made test snapshot hash platform agnostic, and fixed error log
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/SpatialGDKEditorSchemaGeneratorTest.cpp
Labels: jira/UNR, size/XS

#2949 UNR-5126 fix WellKnownEntity server crash
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
Labels: jira/UNR, size/XS

#2950 [UNR-5119] Fix crash in CrossServerAndClientOrchestrationTest
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/SpatialFunctionalTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/CrossServerAndClientOrchestrationTest/CrossServerAndClientOrchestrationTest.cpp
Labels: jira/UNR, size/S

#2954 [UNR-5108] Fixed regex used to search for IDs during schema generator tests
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/SpatialGDKEditorSchemaGeneratorTest.cpp
Labels: jira/UNR, size/XS

#2943 Move RPC logic from sender into RPC service
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/ActorSystem.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/RPCs/SpatialRPCService.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/RPCs/SpatialRPCService.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialSender.h
Labels: jira/no-ticket, size/XL

#2955 Bugfix/unr 5126 nfr fix
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
Labels: jira/UNR, size/XS

#2935 UNR-4933: Modify worker coordinator to support lifetime management.
  CHANGELOG.md
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/Build/Build.cs
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/Common/LinuxScripts.cs
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/WorkerCoordinator/AbstractWorkerCoordinator.cs
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/WorkerCoordinator/LifetimeComponent.cs
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/WorkerCoordinator/ManagedWorkerCoordinator.cs
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/WorkerCoordinator/RegisseurWorkerCoordinator.cs
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/WorkerCoordinator/WorkerCoordinator.csproj
Labels: jira/UNR, size/XL

#2961 [UNR-5078] Fix for cross server RPC intermittent test failure
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/UNR-3761/SpatialTestCrossServerRPC/SpatialTestCrossServerRPC.cpp
Labels: jira/UNR, size/XS

#2956 SpatialTestCharacterMovement fix
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestCharacterMovement/SpatialTestCharacterMovement.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestCharacterMovement/SpatialTestCharacterMovement.h
Labels: jira/UNR, size/M

#2958 [UNR-5160][UNR-5161] Fix nightly tests and other things
  SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/TestMaps/SpatialInitialOnlyMap.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestInitialOnly/SpatialTestInitialOnlyForInterestActor.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestInitialOnly/SpatialTestInitialOnlyForInterestActor.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestInitialOnly/SpatialTestInitialOnlyForInterestActorWithUpdatedValue.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestInitialOnly/SpatialTestInitialOnlyForInterestActorWithUpdatedValue.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestInitialOnly/SpatialTestInitialOnlyForSpawnActor.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestInitialOnly/SpatialTestInitialOnlyForSpawnActor.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestInitialOnly/SpatialTestInitialOnlyForSpawnComponents.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestInitialOnly/SpatialTestInitialOnlyForSpawnComponents.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestInitialOnly/TestClasses/SpatialTestInitialOnlySpawnActor.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPossession/CrossServerMultiPossessionTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPossession/CrossServerPossessionLockTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPossession/CrossServerPossessionTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPossession/NoneCrossServerPossessionTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPossession/SpatialTestPossession.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPossession/SpatialTestRemotePossession.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPossession/SpatialTestRepossession.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestSingleServerDynamicComponents/SpatialTestSingleServerDynamicComponents.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestSingleServerDynamicComponents/SpatialTestSingleServerDynamicComponents.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/TestActors/TestPossessionPawn.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/TestActors/TestPossessionPawn.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/UNR-3157/RPCInInterfaceActor.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/UNR-3157/RPCInInterfaceTest.cpp
Labels: jira/UNR, size/L

#2962 Add replication tests for unreal components
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/TestMaps/Spatial2WorkerMap.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestMultiServerUnrealComponents/SpatialTestMultiServerUnrealComponents.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestMultiServerUnrealComponents/SpatialTestMultiServerUnrealComponents.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestMultiServerUnrealComponents/TestUnrealComponents.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestMultiServerUnrealComponents/TestUnrealComponents.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestMultiServerUnrealComponents/TestUnrealComponentsActor.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestMultiServerUnrealComponents/TestUnrealComponentsActor.h
Labels: jira/UNR, size/XL

#2963 Fix clients not starting in NFRs
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/WorkerCoordinator/LifetimeComponent.cs
Labels: jira/UNR, size/M

#2965 Enable Forward declaration for types used in unique ptrs in USpatialNetDriver
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetConnection.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/ActorSystem.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/GlobalStateManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/RPCs/ClientServerRPCService.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/RPCs/CrossServerRPCService.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/RPCs/MulticastRPCService.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/RPCs/SpatialRPCService.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialPlayerSpawner.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialDebugger.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialDebuggerSystem.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/MigrationDiagnostic.h
Labels: jira/no-ticket, size/M

#2964 [UNR-2626] Add spec handle changelog note
  CHANGELOG.md
Labels: jira/UNR, size/XS

#2968 Remove complex type instantation from SpatialConstants.h
  SpatialGDK/Source/SpatialGDK/Private/SpatialGDKModule.cpp
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.cxx
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorModule.cpp
  SpatialGDK/Source/SpatialGDKEditorCommandlet/Private/SpatialGDKEditorCommandletModule.cpp
  SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/SpatialGDKFunctionalTestsModule.cpp
  SpatialGDK/Source/SpatialGDKTests/Private/SpatialGDKTestsModule.cpp
Labels: jira/no-ticket, size/XL

#2970 Fix static initialization fiasco
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp
Labels: jira/no-ticket, size/S

#2969 Made default viewport nicer on generated maps
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/TestMaps/GeneratedTestMap.cpp
Labels: jira/no-ticket, size/XS

#2967 UNR-5169: Fix clients not starting in NFRs.
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/WorkerCoordinator/LifetimeComponent.cs
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/WorkerCoordinator/LifetimeComponentTest.cs
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/WorkerCoordinator/Logger.cs
  SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/WorkerCoordinator/WorkerCoordinator.csproj
Labels: jira/UNR, size/L

#2933 [UNR-5036] Additional facilities to handle event tracing with the modularied RPC system.
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriverRPC.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialTraceUniqueId.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/RPCs/RPCService.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/RPCs/RPCTypes.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriverRPC.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/SpatialTraceUniqueId.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/RPCs/RPCQueues.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/RPCs/RPCService.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/RPCs/RPCTypes.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/ObjectAllocUtils.h
Labels: jira/UNR, size/XXL

#2972 Downgrade check send authority update
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
Labels: jira/UNR, size/XS

#2975 Unr 4922/update delete dynamic entities flag usage
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorSettings.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h
Labels: jira/UNR, size/S

#2971 [UNR-4548] Run tests using the replication graph nightly
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialComponentTest/SpatialComponentTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestInitialOnly/SpatialTestInitialOnlyForInterestActor.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestInitialOnly/SpatialTestInitialOnlyForSpawnActor.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestInitialOnly/SpatialTestInitialOnlyForSpawnComponents.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPlayerControllerMigration/SpatialTestPlayerControllerHandover.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestSingleServerDynamicComponents/SpatialTestSingleServerDynamicComponents.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestTearOff/ReplicatedTearOffActor.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestTearOff/ReplicatedTearOffActor.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestTearOff/SpatialTestTearOff.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/UNR-3761/SpatialTestClientNetOwnership/SpatialTestNetOwnership.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/UNR-3761/SpatialTestClientNetOwnership/SpatialTestNetOwnership.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/VisibilityTest/VisibilityTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/VisibilityTest/VisibilityTest.h
  ci/gdk_build.template.steps.yaml
  ci/setup-build-test-gdk.ps1
Labels: jira/UNR, size/L

#2882 Exposing the transport window buffer sizes
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialConnectionManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/ConnectionConfig.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h
Labels: jira/no-ticket, size/M

#2925 UNR-4885: Defined LB components
  SpatialGDK/Extras/schema/actor_group_member.schema
  SpatialGDK/Extras/schema/actor_set_member.schema
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/ActorGroupWriter.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/ActorSetWriter.cpp
  SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/DebugLBStrategy.cpp
  SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/GridBasedLBStrategy.cpp
  SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/LayeredLBStrategy.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/EntityFactory.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialPackageMapClient.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/ActorGroupWriter.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/ActorSetWriter.h
  SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/AbstractLBStrategy.h
  SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/DebugLBStrategy.h
  SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/GridBasedLBStrategy.h
  SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/LayeredLBStrategy.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/ActorGroupMember.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/ActorSetMember.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.cxx
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialView/ComponentData.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/SchemaUtils.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestLoadBalancingData/SpatialTestLoadBalancingData.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestLoadBalancingData/SpatialTestLoadBalancingData.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDKFunctionalTests.Build.cs
  SpatialGDK/Source/SpatialGDKTests/SpatialGDK/LoadBalancing/GridBasedLBStrategy/GridBasedLBStrategyTest.cpp
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/SpatialGDKEditorSchemaGeneratorTest.cpp
Labels: jira/UNR, size/XXL

#2941 UNR-4848: Moved commands from SpatialReceiver to their respective systems
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialVirtualWorkerTranslationManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/ActorSystem.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/ClaimPartitionHandler.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/ClientConnectionManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialConnectionManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/DebugMetricsSystem.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/GlobalStateManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/InitialOnlyFilter.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/MigrationDiagnosticsSystem.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialDispatcher.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialPlayerSpawner.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSnapshotManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/WellKnownEntitySystem.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/EntityPool.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialPackageMapClient.h
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialVirtualWorkerTranslationManager.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/ActorSystem.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/ClaimPartitionHandler.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/ClientConnectionManager.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/SpatialWorkerConnection.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/CreateEntityHandler.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/DebugMetricsSystem.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/EntityCommandHandler.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/EntityQueryHandler.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/GlobalStateManager.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/InitialOnlyFilter.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/MigrationDiagnosticsSystem.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/ReserveEntityIdsHandler.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialDispatcher.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialOSDispatcherInterface.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialPlayerSpawner.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialSender.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialSnapshotManager.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/WellKnownEntitySystem.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/EntityPool.h
  SpatialGDK/Source/SpatialGDKTests/SpatialGDK/Interop/SpatialOSDispatcherInterface/SpatialOSDispatcherSpy.cpp
  SpatialGDK/Source/SpatialGDKTests/SpatialGDK/Interop/SpatialOSDispatcherInterface/SpatialOSDispatcherSpy.h
Labels: jira/UNR, size/XXL

#2984 Run new CI in parallel
  .buildkite/premerge.steps.yaml
Labels: jira/no-ticket, size/S

#2944 Ability to start strategy worker
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialStrategySystem.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialStrategySystem.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.cxx
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SnapshotGenerator/SpatialGDKEditorSnapshotGenerator.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKDefaultLaunchConfigGenerator.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKDefaultWorkerJsonGenerator.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorModule.cpp
Labels: jira/UNR, size/L

#2980 [UNR-4415] Put routing worker partition in the initial snapshot
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialRoutingSystem.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/EntityFactory.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialRoutingSystem.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SnapshotGenerator/SpatialGDKEditorSnapshotGenerator.cpp
Labels: jira/UNR, size/L

#2979 Adding retry attempts to start runtime
  SpatialGDK/Source/SpatialGDKServices/Private/LocalDeploymentManager.cpp
  SpatialGDK/Source/SpatialGDKServices/Public/LocalDeploymentManager.h
Labels: jira/UNR, size/M

#2974 [UNR-4714] Fix level reload crash
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/ActorSystem.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/ActorSystem.h
Labels: jira/UNR, size/L

#2977 UNR-4844: Removed StaticComponentView
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialGameInstance.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/ActorSystem.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/GlobalStateManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/RPCs/ClientServerRPCService.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/RPCs/SpatialRPCService.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialDispatcher.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialStaticComponentView.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/WellKnownEntitySystem.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialView/SubView.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialView/ViewCoordinator.cpp
  SpatialGDK/Source/SpatialGDK/Private/Tests/LoadBalanceEnforcerTest.cpp
  SpatialGDK/Source/SpatialGDK/Private/Tests/TestRoutingWorker.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialDebuggerSystem.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialLoadBalancingHandler.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialGameInstance.h
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/GlobalStateManager.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/RPCs/ClientServerRPCService.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/RPCs/CrossServerRPCService.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/RPCs/MulticastRPCService.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/RPCs/SpatialRPCService.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialDispatcher.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialSender.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialStaticComponentView.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialView/SubView.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialView/ViewCoordinator.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialDebuggerSystem.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialLoadBalancingHandler.h
Labels: jira/UNR, size/XL

#2985 [UNR-5225] Fix build issue
  SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialLatencyTracerMinimal.cpp
  SpatialGDK/Source/SpatialGDK/Public/Schema/RPCPayload.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialLatencyTracerMinimal.h
Labels: jira/UNR, size/M

#2988 [UNR-5233] Stopped callbacks marked as "pending remove" from being invoked
  SpatialGDK/Source/SpatialGDK/Private/Tests/SpatialView/CallbacksTest.cpp
  SpatialGDK/Source/SpatialGDK/Public/SpatialView/Callbacks.h
Labels: jira/UNR, size/XS

#2978 Added property replication tests
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/SpatialFunctionalTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/TestMaps/Spatial2WorkerMap.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Public/SpatialFunctionalTest.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestReplicationConditions/SpatialTestReplicationConditions.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestReplicationConditions/SpatialTestReplicationConditions.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestReplicationConditions/TestReplicationConditionsActor.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestReplicationConditions/TestReplicationConditionsActor.h
Labels: jira/UNR, size/XXL

#2989 [UNR-5234] Removing Dispatcher callbacks includes value callbacks
  SpatialGDK/Source/SpatialGDK/Private/SpatialView/Dispatcher.cpp
  SpatialGDK/Source/SpatialGDK/Private/Tests/SpatialView/DispatcherTest.cpp
Labels: jira/UNR, size/M

#2982 [UNR-4415] Add a dedicated authority component set for Server Worker Entities
  RequireSetup
  SpatialGDK/Extras/schema/known_entity_auth_component_set.schema
  SpatialGDK/Extras/schema/server_worker.schema
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialVirtualWorkerTranslationManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/InterestFactory.cpp
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.cxx
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/SpatialGDKEditorSchemaGeneratorTest.cpp
Labels: jira/UNR, size/M

#2994 Use new CI in parallel (FIXED)
  .buildkite/premerge.steps.yaml
Labels: jira/no-ticket, size/XS

#2993 Handle tombstones correctly
  SpatialGDK/Extras/schema/query_tags.schema
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/ActorSystem.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/EntityFactory.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/ActorSystem.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.cxx
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/EntityFactory.h
Labels: jira/no-ticket, size/M

#2990 UNR-5232: Fixed RPCs crashing workers when called on incomplete entities
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/Interop/RPCs/SpatialRPCService.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialView/SubView.cpp
  SpatialGDK/Source/SpatialGDK/Public/SpatialView/SubView.h
Labels: jira/UNR, size/XS
