Repository spatialos/UnrealGDK, pull requests merged in 2021-04, with the labels that each got.

#2992 [UNR-5246] Add missing copyright messages
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriverDebugContext.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/ConnectionConfig.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialRoutingSystem.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialStrategySystem.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialView/AuthorityRecord.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialView/CommandRequest.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialView/CommandResponse.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialView/EntityPresenceRecord.cpp
  SpatialGDK/Source/SpatialGDK/Public/SpatialView/AuthorityRecord.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialView/Callbacks.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialView/Dispatcher.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialView/EntityComponentId.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/CrossServerUtils.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/SpatialFunctionalTestFlowControllerSpawner.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Public/SpatialFunctionalTestFlowControllerSpawner.h
  SpatialGDK/Source/SpatialGDKTests/Examples/SpatialGDKTestGuidelines.h
Labels: jira/UNR, size/M

#2999 Changed ApplyUpdate to also resize the component.
  SpatialGDK/Source/SpatialGDK/Private/SpatialView/ComponentData.cpp
  SpatialGDK/Source/SpatialGDK/Public/SpatialView/ComponentData.h
Labels: jira/UNR, size/XS

#2998 [UNR-5141] Fix races in the DebugInterface test
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/DebugInterface/SpatialDebugInterfaceTest.cpp
Labels: jira/UNR, size/S

#3000 Explicitly include standard library schema
  RequireSetup
  SpatialGDK/Extras/schema/server_worker.schema
Labels: jira/UNR, size/XS

#3002 [UNR-4369] Disable FastBuild for now, due to issues with the cache
  ci/gdk_build.template.steps.yaml
Labels: jira/UNR, size/XS

#2991 [UNR-4232] Subviews remove registered dispatcher callbacks on shutdown
  SpatialGDK/Source/SpatialGDK/Private/SpatialView/Dispatcher.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialView/ScopedDispatcherCallback.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialView/SubView.cpp
  SpatialGDK/Source/SpatialGDK/Private/Tests/SpatialView/CallbacksTest.cpp
  SpatialGDK/Source/SpatialGDK/Private/Tests/SpatialView/ScopedDispatcherCallbackTest.cpp
  SpatialGDK/Source/SpatialGDK/Private/Tests/SpatialView/SubViewTest.cpp
  SpatialGDK/Source/SpatialGDK/Public/SpatialView/Callbacks.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialView/Dispatcher.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialView/DispatcherInterface.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialView/ScopedDispatcherCallback.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialView/SubView.h
  SpatialGDK/Source/SpatialGDK/Public/Tests/SpatialView/DispatcherSpy.h
Labels: jira/UNR, size/XL

#3004 [UNR-5141] Fix the debug sub view not getting the locally authoritative components
  RequireSetup
  SpatialGDK/Extras/schema/debug_component.schema
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriverDebugContext.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/EntityFactory.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/InterestFactory.cpp
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/DebugInterface/SpatialDebugInterfaceTest.cpp
Labels: jira/UNR, size/M

#3008 Update CHANGELOG.md
  CHANGELOG.md
Labels: jira/UNR, size/XS

#3009 Only use new CI
  .buildkite/premerge.steps.yaml
Labels: jira/no-ticket, size/M

#3010 Remove UnrealGDK slack notify as this is now in UnrealGDKBuild
  .buildkite/premerge.steps.yaml
Labels: jira/no-ticket, size/XS

#3012 Change UGeneratedTestMap::AddActorToLevel to return a ref
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/TestMaps/GeneratedTestMap.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/TestMaps/SpatialAuthorityMap.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/TestMaps/SpatialComponentMap.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Public/TestMaps/GeneratedTestMap.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestAttachedComponentReplication/SpatialTestAttachedComponentReplication.cpp
Labels: jira/UNR, size/M

#2092 [UNR-3128] Fix startup actors receiving empty lists v2
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialClassInfoManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentReader.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialClassInfoManager.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/SchemaDatabase.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSchemaGenerator.h
  SpatialGDK/Source/SpatialGDKEditorCommandlet/Private/Commandlets/CookAndGenerateSchemaCommandlet.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestReplicationConditions/SpatialTestReplicationConditions.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/UNR-3761/SpatialTestReplicatedStartupActor/SpatialTestReplicatedStartupActor.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/UNR-3761/SpatialTestReplicatedStartupActor/SpatialTestReplicatedStartupActor.h
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/SpatialGDKEditorSchemaGeneratorTest.cpp
Labels: jira/UNR, size/L

#3011 [UNR-4522] Support replicating references to stably named dynamic subobjects of dynamic actors
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp
  SpatialGDK/Source/SpatialGDK/Private/Schema/UnrealObjectRef.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/PartiallyStablePathTest/PartiallyStablePathActor.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/PartiallyStablePathTest/PartiallyStablePathActor.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/PartiallyStablePathTest/PartiallyStablePathGameMode.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/PartiallyStablePathTest/PartiallyStablePathGameMode.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/PartiallyStablePathTest/PartiallyStablePathPawn.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/PartiallyStablePathTest/PartiallyStablePathPawn.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/PartiallyStablePathTest/PartiallyStablePathTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/PartiallyStablePathTest/PartiallyStablePathTest.h
Labels: jira/UNR, size/XL

#3014 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: jira/UNR, size/XS

#3015 [UNR-5150] Update premerge.steps.yaml
  .buildkite/premerge.steps.yaml
Labels: jira/UNR, size/XS

#3001 Feature/unr 5043 improve player disconnect reliability
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialGameInstance.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialGameInstance.h
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
Labels: jira/UNR, size/M

#3016 Add bOnlyRelevantToOwner support + relevancy tests
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialClassInfoManager.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/RelevancyTest/RelevancyTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/RelevancyTest/RelevancyTest.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/TestActors/RelevancyTestActors.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/TestActors/RelevancyTestActors.h
Labels: jira/no-ticket, size/M

#3018 Fix labels and messages. Make new ci required.
  .buildkite/premerge.steps.yaml
Labels: jira/no-ticket, size/XS

#3021 Revert dbghelp fix and apply patch from UE master
  CHANGELOG.md
Labels: jira/UNR, size/XS

#3027 Update release-process.md
  SpatialGDK/Extras/internal-documentation/release-process.md
Labels: jira/no-ticket, size/XS

#3028 Fix a race condition in PartiallyStablePathTest
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/PartiallyStablePathTest/PartiallyStablePathTest.cpp
Labels: jira/UNR, size/XS

#3029 Update premerge.steps.yaml
  .buildkite/premerge.steps.yaml
Labels: jira/no-ticket, size/XS

#3025 [UNR-5121] Cross server possession tests can't be placed in the same map
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPossession/CrossServerMultiPossessionTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPossession/CrossServerPossessionLockTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPossession/CrossServerPossessionLockTest.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPossession/CrossServerPossessionMap.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPossession/CrossServerPossessionMap.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPossession/CrossServerPossessionTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPossession/NoneCrossServerPossessionTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPossession/SpatialTestRemotePossession.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPossession/SpatialTestRemotePossession.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPossession/TestPossessionPlayerController.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPossession/TestPossessionPlayerController.h
Labels: jira/UNR, size/L

#3036 [UNR-5326] Fix StartupActorTest and make Requires return bools
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/SpatialFunctionalTestRequireHandler.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Public/SpatialFunctionalTest.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/Public/SpatialFunctionalTestRequireHandler.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/UNR-3761/SpatialTestReplicatedStartupActor/SpatialTestReplicatedStartupActor.cpp
Labels: jira/UNR, size/L

#3033 Remove unused arrays from schema db
  SpatialGDK/Source/SpatialGDK/Public/Utils/SchemaDatabase.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SchemaGenerator.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SchemaGenerator.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp
Labels: jira/no-ticket, size/S

#3026 [UNR-5365] Add SpatialNetDriver implementation of GetActorEntityId()
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/EngineVersionCheck.h
Labels: jira/UNR, size/S

#3039 Re-add partition shadow component
  SpatialGDK/Source/SpatialGDK/Private/Utils/EntityFactory.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/SnapshotGenerator/SpatialGDKEditorSnapshotGenerator.cpp
Labels: jira/no-ticket, size/XS

#3040 Update release-process.md
  SpatialGDK/Extras/internal-documentation/release-process.md
Labels: jira/no-ticket, size/XS

#3031 Proxy for Unreal Insights data streamed from server workers
  SpatialGDK/Extras/insights-proxy/InsightsProxy.py
  SpatialGDK/Extras/insights-proxy/README.md
Labels: jira/UNR, size/M

#3043 Update premerge.steps.yaml
  .buildkite/premerge.steps.yaml
Labels: jira/no-ticket, size/XS

#3017 [UNR-5037] Modular client server rpcs
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriverRPC.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/RPCs/ClientServerRPCService.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/RPCs/SpatialRPCService.cpp
  SpatialGDK/Source/SpatialGDK/Private/Tests/RPCServiceTest.cpp
  SpatialGDK/Source/SpatialGDK/Private/Tests/RPCs/RPCRingBufferTest.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/EntityFactory.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriverRPC.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/RPCs/RPCQueues.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/RPCs/RPCTypes.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/RPCs/RPC_RingBufferSerializer.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/RPCs/RPC_RingBufferWithACK_Receiver.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/RPCs/RPC_RingBufferWithACK_Sender.h
Labels: jira/UNR, size/XXL

#3045 [UNR-5046] Duplicate authority intent update bugfix
  SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialLoadBalancingHandler.cpp
Labels: jira/UNR, size/XS

#3042 [UNR-5051] Make Addstep default timeout non-infinite, include expected values in successful requires, add test step time logging
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/SpatialFunctionalTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/SpatialFunctionalTestRequireHandler.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Public/SpatialFunctionalTest.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/Public/SpatialFunctionalTestRequireHandler.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/Public/SpatialFunctionalTestStep.h
Labels: jira/UNR, size/L

#3044 Cherry pick Insights work UNR-5207
  CHANGELOG.md
  SpatialGDK/Extras/insights-proxy/InsightsProxy.py
  SpatialGDK/Extras/insights-proxy/README.md
Labels: jira/UNR, size/M

#3047 Update pull-request-template.md
  .github/pull-request-template.md
Labels: jira/no-ticket, size/XS

#3050 Fixed an issue with migration diagnostic logging failing.
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.cxx
Labels: jira/UNR, size/XS

#3030 UNR-4853: Added multiple actor system subviews
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/ActorSubviews.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/ActorSubviews.h
  SpatialGDK/Source/SpatialGDK/Private/Interop/ActorSystem.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialView/SubView.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/ActorSystem.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialView/SubView.h
Labels: jira/UNR, size/XL

#3052 [UNR-5021] Use GDK heartbeat configurations for worker timeout
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialConnectionManager.cpp
Labels: jira/UNR, size/S

#3038 Feature/unr 5296 extend test setting overrides for groups of maps
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialWorldSettings.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialTestSettings.cpp
Labels: jira/UNR, size/M

#3055 Update CHANGELOG.md
  CHANGELOG.md
Labels: jira/UNR, size/XS

#3054 [UNR-5021] Use GDK heartbeat configurations for worker timeout
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialConnectionManager.cpp
Labels: jira/UNR, size/S

#3064 Update SpatialFunctionalTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/SpatialFunctionalTest.cpp
Labels: jira/no-ticket, size/XS

#3066 Fix asset load causing stall during shutdown
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp
Labels: jira/UNR, size/XS

#3069 Actually use env var for project branch
  .buildkite/premerge.steps.yaml
Labels: jira/no-ticket, size/XS

#3070 Remove engine branch override from RC
  .buildkite/premerge.steps.yaml
Labels: jira/no-ticket, size/XS

#3046 UNR-5290: Optimizing event tracing to reduce overheads
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriverRPC.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/ActorSystem.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialEventTracer.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialEventTracerUserInterface.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialTraceEventBuilder.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialTraceEventDataBuilder.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/CrossServerRPCHandler.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/CrossServerRPCSender.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/DebugMetricsSystem.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/GlobalStateManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/MigrationDiagnosticsSystem.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/RPCExecutor.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/RPCs/SpatialRPCService.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialPlayerSpawner.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialView/ReceivedOpEventHandler.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialView/ViewDelta.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentReader.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/SpatialEventTracer.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/SpatialEventTracerUserInterface.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/SpatialTraceEvent.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/SpatialTraceEventBuilder.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/SpatialTraceEventDataBuilder.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/SpatialTraceUniqueId.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SnapshotGenerator/SpatialGDKEditorSnapshotGenerator.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/RelevancyTest/RelevancyTest.cpp
  SpatialGDK/Source/SpatialGDKTests/SpatialGDK/Interop/Connection/SpatialEventTracingTest.cpp
Labels: jira/UNR, size/XXL

#3071 Fix RPC queue moving incorrect number of items
  SpatialGDK/Source/SpatialGDK/Private/Tests/RPCs/RPCRingBufferTest.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/RPCs/RPCTypes.h
Labels: jira/no-ticket, size/S

#3068 [UNR-5438] Change UNetDriver GetActorEntityId to not lazy construct
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/EngineVersionCheck.h
Labels: jira/UNR, size/S

#3072 Move SendComponentUpdates early out to avoid memory leak
  SpatialGDK/Source/SpatialGDK/Private/Interop/ActorSystem.cpp
Labels: jira/no-ticket, size/S

#3073 UNR-5442: Removed unnecessary ActorSystem assert
  SpatialGDK/Source/SpatialGDK/Private/Interop/ActorSystem.cpp
Labels: jira/UNR, size/XS

#3061 Feature/5052 extend always interested
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentFactory.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/InterestFactory.cpp
  SpatialGDK/Source/SpatialGDK/Public/Utils/InterestFactory.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/TestMaps/Spatial2WorkerSmallInterestMap.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Public/SpatialFunctionalTest.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/AlwaysInterestedTest/AlwaysInterestedTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/AlwaysInterestedTest/AlwaysInterestedTest.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/RelevancyTest/RelevancyTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/TestActors/AlwaysInterestedTestActors.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/TestActors/AlwaysInterestedTestActors.h
Labels: jira/no-ticket, size/XXL

#2973 [UNR-4415] Add support for NetWriteFence and Unordered
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/RPCs/CrossServerRPCService.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/RPCs/SpatialRPCService.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialClassInfoManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialRoutingSystem.cpp
  SpatialGDK/Source/SpatialGDK/Private/Tests/RPCServiceTest.cpp
  SpatialGDK/Source/SpatialGDK/Private/Tests/TestRoutingWorker.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/EntityFactory.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/InterestFactory.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/RPCRingBuffer.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/RPCs/CrossServerRPCService.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/RPCs/SpatialRPCService.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.cxx
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/EngineVersionCheck.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/RepLayoutUtils.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SchemaGenerator.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/TestMaps/SpatialRoutingWorkerMap.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Public/TestMaps/SpatialRoutingWorkerMap.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestEntityInteration/EntityInteractionTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestEntityInteration/EntityInteractionTest.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestEntityInteration/EntityInteractionTestActor.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestEntityInteration/EntityInteractionTestActor.h
Labels: jira/UNR, size/XXL

#3075 [UNR-5443] Add missing flag initialization
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriverRPC.cpp
Labels: jira/UNR, size/XS

#3067 [UNR-5404] Fix error with flattened handover structs
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/TestMaps/SpatialComponentMap.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestHandoverReplication/SpatialTestHandoverActorComponentReplication.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestHandoverReplication/SpatialTestHandoverActorComponentReplication.h
Labels: jira/UNR, size/M
