Repository spatialos/UnrealGDK, pull requests merged in 2021-07, with the labels that each got.

#3216 Refactor command handlers
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialVirtualWorkerTranslationManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/ActorSystem.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/ClaimPartitionHandler.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/GlobalStateManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/InitialOnlyFilter.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialPlayerSpawner.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSnapshotManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/EntityPool.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialVirtualWorkerTranslationManager.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/ActorSystem.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/ClaimPartitionHandler.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/SpatialWorkerConnection.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/CreateEntityHandler.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/EntityQueryHandler.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/GlobalStateManager.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/InitialOnlyFilter.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/ReserveEntityIdsHandler.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialCommandsHandler.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialOSDispatcherInterface.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialPlayerSpawner.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialSnapshotManager.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/EntityPool.h
Labels: jira/no-ticket, size/XL

#3229 Reverts PR #3176
  .buildkite/premerge.definition.yaml
Labels: jira/no-ticket, size/XS

#3228 [UNR-5783] Fix test reruns
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/SpatialFunctionalTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/SpatialFunctionalTestFlowController.cpp
Labels: jira/UNR, size/S

#3184 [UNR-2304] Match native RepNotify ordering
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/ActorSystem.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentReader.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/ActorSystem.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/ComponentReader.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestRepNotify/SpatialTestRepNotify.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestRepNotify/SpatialTestRepNotify.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestRepNotify/SpatialTestRepNotifyActor.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestRepNotify/SpatialTestRepNotifyActor.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestRepNotify/SpatialTestRepNotifySubobject.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestRepNotify/SpatialTestRepNotifySubobject.h
Labels: jira/UNR, size/XXL

#3235 [UNR-5791] Gameplay Debugger tracks focused actor across interest boundaries
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriverGameplayDebuggerContext.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/InterestFactory.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriverGameplayDebuggerContext.h
Labels: jira/UNR, size/M

#3231 Spatialguidmap has an objectref->netguid mapping that should have been deleted
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialPackageMapClient.h
Labels: jira/no-ticket, size/M

#3237 [UNR-5726] Fix visibility test flake - cherry pick for RC
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/UNR-3761/SpatialTestMultipleOwnership/SpatialTestMultipleOwnership.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/UNR-3761/SpatialTestMultipleOwnership/SpatialTestMultipleOwnership.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/VisibilityTest/VisibilityTest.cpp
Labels: jira/UNR, size/S

#3238 Update SpatialSwitchHasAuthority to check NetDriver via World
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialStatics.cpp
Labels: jira/no-ticket, size/XS

#3241 Update default CI branch to 0.14.0-rc
  .buildkite/premerge.steps.yaml
Labels: jira/no-ticket, size/XS

#3240 Use new CI versioned against main
  .buildkite/premerge.steps.yaml
  SpatialGDK/Extras/internal-documentation/release-process.md
  ci/ReleaseTool/Common.cs
  ci/ReleaseTool/PrepCommand.cs
  ci/ReleaseTool/ReleaseCommand.cs
  ci/prepare-full-release.sh
  ci/prepare-release.sh
  ci/release.sh
Labels: jira/no-ticket, size/M

#3239 [UNR-5632] Generate partition auth data set
  SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/PartitionManager.cpp
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/Utils/SchemaBundleParser.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/Utils/SchemaBundleParser.h
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSchemaGenerator.h
  SpatialGDK/Source/SpatialGDKEditorCommandlet/Private/Commandlets/CookAndGenerateSchemaCommandlet.cpp
Labels: jira/UNR, size/XL

#3160 UNR-5491: Spiked out skeleton entities
  RequireSetup
  SpatialGDK/Extras/schema/query_tags.schema
  SpatialGDK/Extras/schema/skeleton_entity.schema
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriverRPC.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialVirtualWorkerTranslationManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/ActorSubviews.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/ActorSystem.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/GlobalStateManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/RPCs/RPCService.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/RPCs/SpatialRPCService.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SkeletonEntities.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SkeletonEntityCreationStep.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SkeletonEntityCreationStep.h
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialClassInfoManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/WellKnownEntitySystem.cpp
  SpatialGDK/Source/SpatialGDK/Private/Schema/SkeletonEntityManifest.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialView/WorkerView.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/EntityFactory.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/InterestFactory.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriverRPC.h
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialVirtualWorkerTranslationManager.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/ActorSystem.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/GlobalStateManager.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/RPCs/SpatialRPCService.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SkeletonEntities.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialClassInfoManager.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/WellKnownEntitySystem.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/SkeletonEntityManifest.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.cxx
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/EntityFactory.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/InterestFactory.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SnapshotGenerator/SpatialGDKEditorSnapshotGenerator.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialAuthorityTest/SpatialAuthorityTest.cpp
  SpatialGDK/Source/SpatialGDKTests/SpatialGDK/Utils/EntityFactory/EntityFactoryTest.cpp
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/SpatialGDKEditorSchemaGeneratorTest.cpp
Labels: jira/UNR, size/XXL

#3215 Adding tests regarding dormancy
  SpatialGDK/Source/SpatialGDK/Private/Interop/ActorSystem.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/TestMaps/SpatialInitialDormancyMap.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/TestMaps/SpatialNetworkingMap.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Public/TestMaps/SpatialInitialDormancyMap.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/DormancyAndTombstoneTest/DormancyAndTombstoneTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/DormancyAndTombstoneTest/DormancyAndTombstoneTest.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/DormancyTests/DormancyTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/DormancyTests/DormancyTest.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/DormancyTests/DormancyTestActor.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/DormancyTests/DormancyTestActor.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/DormancyTests/DynamicActorAwakeAfterDormantChangePropertyTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/DormancyTests/DynamicActorAwakeAfterDormantChangePropertyTest.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/DormancyTests/DynamicActorAwakeChangePropertyTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/DormancyTests/DynamicActorAwakeChangePropertyTest.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/DormancyTests/DynamicActorDormantAllChangePropertyTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/DormancyTests/DynamicActorDormantAllChangePropertyTest.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/DormancyTests/DynamicActorSetToAwakeTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/DormancyTests/DynamicActorSetToAwakeTest.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/DormancyTests/InitiallyDormantDynamicActorTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/DormancyTests/InitiallyDormantDynamicActorTest.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/DormancyTests/InitiallyDormantMapActorTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/DormancyTests/InitiallyDormantMapActorTest.h
Labels: jira/no-ticket, size/XXL

#3234 [UNR-5576] Call repnotifies in ascending RepIndex order
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/Interop/ActorSystem.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/ActorSystem.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestRepNotify/SpatialTestRepNotify.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestRepNotify/SpatialTestRepNotifyActor.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestRepNotify/SpatialTestRepNotifyActor.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestRepNotify/SpatialTestRepNotifySubobject.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestRepNotify/SpatialTestRepNotifySubobject.h
Labels: jira/UNR, size/M

#3246 [UNR-5799] fix buggy movement across servers
  SpatialGDK/Source/SpatialGDK/Private/Interop/ActorSystem.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/ActorSystem.h
Labels: jira/UNR, size/M

#3247 [UNR-5638] Add better logging for the RegisterAutoDestroyActor tests
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/SpatialFunctionalTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Public/SpatialFunctionalTest.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/RegisterAutoDestroyActorsTest/RegisterAutoDestroyActorsTest.cpp
Labels: jira/UNR, size/L

#3250 UNR-5818: Fixed a Spatial component double-add
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/TestMaps/SpatialNetworkingMap.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/DynamicSubobjectsTest/SpatialDynamicComponentsFastReadditionTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/DynamicSubobjectsTest/SpatialDynamicComponentsFastReadditionTest.h
Labels: jira/UNR, size/L

#3248 Support separately enabling Event Tracing in Editor and non-Editor bu…
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialConnectionManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp
  SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKDefaultLaunchConfigGenerator.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/EventTracingTests/EventTracingSettingsOverride.cpp
Labels: jira/UNR, size/M

#3256 [UNR-5809] Fix offloading
  SpatialGDK/Source/SpatialGDK/Private/Interop/GlobalStateManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialStatics.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/GameModeReplicationTest/GameModeReplicationTest.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestLoadBalancingData/SpatialTestLoadBalancingData.h
Labels: jira/UNR, size/S

#3257 Merge in-progress 0.14.0-rc into master
  CHANGELOG.md
  RequireSetup
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialEventTracer.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/GlobalStateManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialStatics.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/SpatialEventTracer.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKDefaultLaunchConfigGenerator.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/GameModeReplicationTest/GameModeReplicationTest.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestLoadBalancingData/SpatialTestLoadBalancingData.h
  SpatialGDK/SpatialGDK.uplugin
Labels: jira/no-ticket, size/L

#3244 Adding a migration test for no interest zoning scenario
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/TestMaps/Spatial2WorkerMigrationMaps.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Public/TestMaps/Spatial2WorkerMigrationMaps.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestCharacterMigration/SpatialTestCharacterMigration.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestCharacterMigration/SpatialTestCharacterMigration.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestCharacterMovement/CharacterMovementTestGameMode.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestCharacterMovement/CharacterMovementTestGameMode.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/TestActors/TestMovementCharacter.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/TestActors/TestMovementCharacter.h
Labels: jira/UNR, size/XL

#3255 [UNR-5212] Feature/add rep override capability
  CHANGELOG.md
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialClassInfoManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentReader.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialClassInfoManager.h
  SpatialGDK/Source/SpatialGDK/Public/Utils/SchemaDatabase.h
  SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/Utils/SchemaBundleParser.cpp
  SpatialGDK/Source/SpatialGDKEditor/Private/Utils/SchemaBundleParser.h
  SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSchemaGenerator.h
  SpatialGDK/Source/SpatialGDKEditorCommandlet/Private/Commandlets/CookAndGenerateSchemaCommandlet.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestReplicationConditions/SpatialTestReplicationConditions.cpp
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/SpatialGDKEditorSchemaGeneratorTest.cpp
Labels: jira/UNR, size/M

#3260 Cleanup the centralized load balancer by using SpatialCommandHandler
  SpatialGDK/Source/SpatialGDK/Private/Interop/ClaimPartitionHandler.cpp
  SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/LegacyLoadBalancingStrategy.cpp
  SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/PartitionManager.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/ClaimPartitionHandler.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialCommandsHandler.h
  SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/LegacyLoadBalancingStrategy.h
Labels: jira/no-ticket, size/L

#3271 [UNR-5843] Update SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
Labels: jira/UNR, size/XS

#3262 [UNR-5785] Fix SpatialPackageMap having ObjectRef->NetGUID mapping it shouldn't have
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp
Labels: jira/UNR, size/S

#3267 Adding functional tests to test ET settings
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriverRPC.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/ActorSystem.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialEventTracer.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/CrossServerRPCSender.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/RPCs/SpatialRPCService.cpp
  SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/SpatialEventTracer.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/TestMaps/EventTracingMaps/EventTracingCustomGDKFilterMap.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/TestMaps/EventTracingMaps/EventTracingEventSamplingProbabilityOverrideMap.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/TestMaps/EventTracingMaps/EventTracingMaxSamplingProbabilityFilterFalseMap.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/TestMaps/EventTracingMaps/EventTracingZeroSamplingProbabilityFilterTrueMap.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Public/TestMaps/EventTracingMaps/EventTracingCustomGDKFilterMap.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/Public/TestMaps/EventTracingMaps/EventTracingEventSamplingProbabilityOverrideMap.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/Public/TestMaps/EventTracingMaps/EventTracingMaxSamplingProbabilityFilterFalseMap.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/Public/TestMaps/EventTracingMaps/EventTracingZeroSamplingProbabilityFilterTrueMap.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/ConfigurationAssets/CustomGDKFilterSettings.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/ConfigurationAssets/EventSamplingProbabilityOverrideSettings.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/ConfigurationAssets/EventSamplingProbabilityOverrideSettings.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/ConfigurationAssets/MaxSamplingProbabilityFilterFalseSettings.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/ConfigurationAssets/ZeroSamplingProbabilityFilterTrueSettings.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/EventTracingTests/ComponentUpdateEventTracingTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/EventTracingTests/EventTracingSettingsOverride.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/EventTracingTests/EventTracingTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/EventTracingTests/EventTracingTest.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/EventTracingTests/EventTracingTestGameMode.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/EventTracingTests/EventTracingTestGameMode.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/EventTracingTests/ProcessCrossServerRPCEventTracingTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/EventTracingTests/ProcessRPCEventTracingTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/EventTracingTests/PropertyUpdateEventTracingTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/EventTracingTests/SettingsTests/CustomGDKFilterTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/EventTracingTests/SettingsTests/CustomGDKFilterTest.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/EventTracingTests/SettingsTests/EventSamplingProbabilityOverrideTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/EventTracingTests/SettingsTests/EventSamplingProbabilityOverrideTest.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/EventTracingTests/SettingsTests/MaxSamplingProbabilityFilterFalseTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/EventTracingTests/SettingsTests/MaxSamplingProbabilityFilterFalseTest.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/EventTracingTests/SettingsTests/ZeroSamplingProbabilityFilterTrueTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/EventTracingTests/SettingsTests/ZeroSamplingProbabilityFilterTrueTest.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/EventTracingTests/UserProcessCrossServerPropertyEventTracingTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/EventTracingTests/UserProcessCrossServerRPCEventTracingTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/EventTracingTests/UserProcessRPCEventTracingTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/EventTracingTests/UserReceivePropertyEventTracingTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/EventTracingTests/UserSendPropertyEventTracingTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/EventTracingTests/UserSendRPCEventTracingTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/TestActors/EventTracerComponent.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/TestActors/EventTracerComponent.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/TestActors/EventTracingCharacter.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/TestActors/EventTracingCharacter.h
Labels: jira/UNR, size/XXL

#3264 [UNR-5410] Feature/unresolved reference gym test
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/TestMaps/SpatialNetworkingMap.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/UnresolvedReferenceTest/UnresolvedReferenceTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/UnresolvedReferenceTest/UnresolvedReferenceTest.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/UnresolvedReferenceTest/UnresolvedReferenceTestActor.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/UnresolvedReferenceTest/UnresolvedReferenceTestActor.h
Labels: jira/UNR, size/M

#3273 Change packagemap warning to ensure.
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp
Labels: jira/no-ticket, size/XS

#3265 [UNR-5804] Update to 15.2.0 SDK and runtime
  CHANGELOG.md
  RequireSetup
  Setup.bat
  Setup.sh
  SpatialGDK/Extras/core-sdk.version
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialEventTracer.cpp
  SpatialGDK/Source/SpatialGDK/Public/Utils/WorkerVersionCheck.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/EventTracingTests/EventTracingTest.cpp
  SpatialGDK/Source/SpatialGDKServices/Public/SpatialGDKServicesConstants.h
Labels: jira/UNR, size/M

#3274 [UNR-5812] Fix nightly test failures - UnresolvedRefTest in Native
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/StaticSubobjectsTest/StaticSubobjectsTest.cpp
Labels: jira/UNR, size/XS
