Repository spatialos/UnrealGDK, pull requests merged in 2022-01, with the labels that each got.

#3332 [UNR-5599] Automate RPC Timeout Test Gym
  SpatialGDK/Source/SpatialGDKFunctionalTests/Private/SpatialFunctionalTest.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/Public/SpatialFunctionalTest.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestRPCTimeout/SpatialTestRPCTimeout.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestRPCTimeout/SpatialTestRPCTimeout.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestRPCTimeout/SpatialTestRPCTimeoutCharacter.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestRPCTimeout/SpatialTestRPCTimeoutCharacter.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestRPCTimeout/SpatialTestRPCTimeoutGameMode.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestRPCTimeout/SpatialTestRPCTimeoutGameMode.h
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestRPCTimeout/SpatialTestRPCTimeoutPlayerController.cpp
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestRPCTimeout/SpatialTestRPCTimeoutPlayerController.h
Labels: size/XL, jira/UNR

#3355 INT-126: Demoted the missing worker entity ensure down to a warning
  SpatialGDK/Source/SpatialGDK/Private/Interop/ClientConnectionManager.cpp
Labels: size/XS, jira/INT

#3356 Disabling run under single process doesn't work in native
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestRPCTimeout/SpatialTestRPCTimeout.cpp
Labels: size/XS, jira/no-ticket

#3343 Marker-led working sets spike
  CHANGELOG.md
  RequireSetup
  SpatialGDK/Extras/internal-documentation/working-sets/README.md
  SpatialGDK/Extras/internal-documentation/working-sets/edge-case-1.wsd
  SpatialGDK/Extras/internal-documentation/working-sets/edge-case-2.wsd
  SpatialGDK/Extras/internal-documentation/working-sets/working-sets-cross-server-creation.puml
  SpatialGDK/Extras/internal-documentation/working-sets/working-sets-different-workers.puml
  SpatialGDK/Extras/internal-documentation/working-sets/working-sets-same-worker.puml
  SpatialGDK/Extras/schema/authority_intent.schema
  SpatialGDK/Extras/schema/partition_components.schema
  SpatialGDK/Extras/schema/working_sets.schema
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialHandoverManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/ActorSubviews.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/ActorSubviews.h
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialStrategySystem.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialWorkingSetSubsystem.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/Startup/StrategyWorkerStartupSteps.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/WorkingSetsCommon.cpp
  SpatialGDK/Source/SpatialGDK/Private/Interop/WorkingSetsHandler.cpp
  SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/ActorSetSystem.cpp
  SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/LegacyLoadBalancingStrategy.cpp
  SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/PartitionManager.cpp
  SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/WorkingSetSystem.cpp
  SpatialGDK/Source/SpatialGDK/Private/Tests/WorkingSetSystemTests.cpp
  SpatialGDK/Source/SpatialGDK/Private/Tests/WorkingSetsHandlerTests.cpp
  SpatialGDK/Source/SpatialGDK/Private/Utils/EntityFactory.cpp
  SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialStrategySystem.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialWorkingSetSubsystem.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/WorkingSetsCommon.h
  SpatialGDK/Source/SpatialGDK/Public/Interop/WorkingSetsHandler.h
  SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/ActorSetSystem.h
  SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/PartitionManager.h
  SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/WorkingSetSystem.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/StandardLibrary.h
  SpatialGDK/Source/SpatialGDK/Public/Schema/WorkingSet.h
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.cxx
  SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/SpatialGDKEditorSchemaGeneratorTest.cpp
Labels: size/XXL, jira/no-ticket

#3357 Fix working set subsystem include
  SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialWorkingSetSubsystem.cpp
Labels: size/XS, jira/no-ticket

#3358 Disable spatial debugger tick when running a replay
  SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialDebugger.cpp
Labels: size/XS, jira/no-ticket

#3359 UNR-5057: Unity builds
  .buildkite/premerge.steps.yaml
  SpatialGDK/Source/SpatialGDK/SpatialGDK.Build.cs
  SpatialGDK/Source/SpatialGDKEditor/SpatialGDKEditor.Build.cs
  SpatialGDK/Source/SpatialGDKEditorCommandlet/SpatialGDKEditorCommandlet.Build.cs
  SpatialGDK/Source/SpatialGDKEditorToolbar/SpatialGDKEditorToolbar.Build.cs
  SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDKFunctionalTests.Build.cs
  SpatialGDK/Source/SpatialGDKServices/SpatialGDKServices.Build.cs
  SpatialGDK/Source/SpatialGDKTests/SpatialGDKTests.Build.cs
Labels: size/L, jira/UNR
